### ISSUE TITLE
link error in trex_vm_manual.asciidoc

### ISSUE THREAD

**Issue by digger-yu** [cisco-system-traffic-generator/trex-core#1003]
https://trex-tgn.cisco.com/trex/doc/trex_vm_manual.html

![image](https://user-images.githubusercontent.com/55081697/223970086-68c48790-0cf2-4813-909a-314cfd64b8e3.png)
The link cannot be accessed

```
[NOTE]
See http://trex-tgn.cisco.com/trex/doc/trex_book.pdf[TRex full manual] for a complete understading of the tool features and options.
```

i see the document source code ,If I know the correct link, it should be easy to fix

is this link right  https://trex-tgn.cisco.com/trex/doc/trex_manual.html  ?

**Comment by hhaim** [comment]
@digger-yu yes, you can use relative path instead of a full path
