### ISSUE TITLE
How to use trex to test RFC2544 for a Single network port

### ISSUE THREAD

**Issue by Snailfl** [cisco-system-traffic-generator/trex-core#1012]
I want to use trex streaming on two different devices. How can I test it?
/etc/trex_cfg.yaml:
- version: 2
  interfaces: ['0a:00.0', 'dummy']
  port_info:
      - src_mac: 68:ed:a4:31:ba:fa
        dest_mac: 68:ed:a4:5c:90:83

  platform:
      master_thread_id: 0
      latency_thread_id: 1
      dual_if:
        - socket: 0
          threads: [2,3]

**Comment by hhaim** [comment]
@Snailfl please use our mailer for questions
