### ISSUE TITLE
How to set rx and tx queues per port in TRex ?

### ISSUE THREAD

**Issue by pankajrodge** [cisco-system-traffic-generator/trex-core#1025]
How to set rx and tx queues per port in TRex ?

**Comment by wujiahao15** [comment]
I am new to trex and I also want to know about this problem.

**Comment by hhaim** [comment]
@pankajrodge you can't

**Comment by pankajrodge** [comment]
Hi @hhaim  what is that value and how it determines the number of tx and rx ?
