### ISSUE TITLE
Documentation page is unavaliable

### ISSUE THREAD

**Issue by wujiahao15** [cisco-system-traffic-generator/trex-core#1028]
## Problem

- A lot of pages of official documentation is unreachable.

![image](https://github.com/cisco-system-traffic-generator/trex-core/assets/22017865/f658125e-2c57-4580-8445-cdda956a1466)

## influenced pages

- api reference
- faq
- ...

**Comment by yakbay** [comment]
Same here...

**Comment by hhaim** [comment]
[this](https://trex-tgn.cisco.com/trex/doc/cp_stl_docs/index.html) 
works for me

**Comment by yakbay** [comment]
@hhaim tried your link, but still not working for me. Then I tried `Shift+F5` and got `ERR_CERT_AUTHORITY_INVALID`. Seems like the site certificate expired. You can reproduce it in incognito mode.

**Comment by yakbay** [comment]
seems like nobody cares

**Comment by wujiahao15** [comment]
> [this](https://trex-tgn.cisco.com/trex/doc/cp_stl_docs/index.html) works for me

I have tried your link and it works for me. However, the certificate of this website seems invalid? @hhaim

**Comment by hhaim** [comment]
@wujiahao15 the certificate is valid. I think you have an old CA installed on you machine.
