### ISSUE TITLE
[Question] MTU 1500 throughput less than MTU 9000 throughput 

### ISSUE THREAD

**Issue by Huxianying** [cisco-system-traffic-generator/trex-core#1056]
Recently, I've been running TRex in a Calico-VPP environment, but I've noticed a rather peculiar phenomenon: MTU 1500 throughput less than MTU 9000. For example, with 128 Bytes packet, throughput is 3.24Gbps for MTU1500 and 3.10Gbps for MTU 9000. I know that When the MTU is set to a smaller value ( MTU1500 ), each data packet carries less data, but there are more packets, so a smaller MTU means smaller data packets that can be transmitted faster. So, this is quite tricky, why MTU 1500 throughput less than MTU 9000, or may something wrong with TRex configuration error.

trex_cfg.yaml:
![image](https://github.com/cisco-system-traffic-generator/trex-core/assets/101862062/bbb3ee98-b80c-4a5b-87ee-8c0d74bbf8ff)

**Comment by hhaim** [comment]
@Huxianying this is a driver/hardware specific issue. TRex only care about PPS (CPU%) . 
In general you are right, as packet length is higher it is less PPS for the same bandwidth so it is less CPU% 
but there are more limitations in hardware/drivers. In specific drivers (CX-5) you can get to 100gbps with a few cores.

**Comment by Huxianying** [comment]
@hhaim Thank you for your answer, could you please tell me which hardware/drivers might affect the throughput? I'll investigate further.

**Comment by hhaim** [comment]
@Huxianying what is the dpdk driver that you are using? what is the setup?

**Comment by Huxianying** [comment]
@hhaim, 
Question1: dpdk driver is "vfio-pci". 
Question2: use the "dpdk-devbind.py" file to bound NIC to "vfio-pci" driver.

**Comment by hhaim** [comment]
@Huxianying what is the PF of this virtual VF?

**Comment by Huxianying** [comment]
@hhaim, PF: intel's E810-CQDA2.

**Comment by hhaim** [comment]
@Huxianying you should ask this question in E810 dpdk forum
