### ISSUE TITLE
latency type is? LILO, LIFO, FIFO

### ISSUE THREAD

**Issue by laijiq** [cisco-system-traffic-generator/trex-core#1078]
Hi, I have used the stl mode to test latency, and got the avg latency, but which type of the latency reuslt is? LILO, LIFO, FIFO or some others.

**Comment by hhaim** [comment]
it is LPF with alpha of 0.5

**Comment by laijiq** [comment]
> it is LPF with alpha of 0.5

Thanks for your reply very much. But I still have doubts what the 'LPF' means. is it means Low Pass Filter? I thought the answer should be one of 'LIFO', 'FIFO' or 'LILO' which define in appendix. I've seen the default latency is FIFO for Spirent TestCenter as you can see in https://support.spirent.com/SC_KnowledgeView?Id=FAQ12288#:~:text=LILO%20is%20the%20only%20latency%20mode%20that%20actually,choice%20for%20testing%20most%20cut-through%20devices%20than%20FIFO. I still can not connect the 'LPF' to any latency type. Looking forward to your reply very much

Appendix:
LIFO: last-in, first-out, defines in rfc 1242. For store-and-forward devices, latency is defined as the time interval starting when the last bit of the input frame reaches the input port and ending when the first bit of the output frame is seen on the output port.
FIFO: first-in, first-out, also defines in rfc 1242. For bit forwarding devices, latency is defined as the time interval starting when the end of the first bit of the input frame reaches the input port and ending when the start of the first bit of the output frame is seen on the output port.
LILO: last-in, last-out, which is called forwarding delay, defines in rfc 4689. Forwarding delay is defined as the time interval starting when the last bit of the input IP packet is offered to the input port of the DUT/SUT and ending when the last bit of the
output IP packet is received from the output port of the DUT/SUT.

**Comment by hhaim** [comment]
@laijiq we are doing low pass filter. you can use the accurate histogram and calculate the average in your script. the accurate histogram include all the data of the latency information

**Comment by laijiq** [comment]
Thanks very much
