### ISSUE TITLE
start t-rex failed due to  no Driver_str in dpdk_setup_ports.py

### ISSUE THREAD

**Issue by HouMinXi** [cisco-system-traffic-generator/trex-core#1135]
t-rex version: 3.04

trex_cfg.yaml as below:
```
# cat /etc/trex_cfg.yaml 
- version    : 2
  interfaces : ["0000:12:00.0","0000:12:00.1"]
  port_info  :
  - dest_mac : [0x00,0x00,0x00,0x00,0x00,0x02]
    src_mac  : [0x00,0x00,0x00,0x00,0x00,0x01]
  - dest_mac : [0x00,0x00,0x00,0x00,0x00,0x01]
    src_mac  : [0x00,0x00,0x00,0x00,0x00,0x02]
  platform:
    master_thread_id: 10
    latency_thread_id: 11
    dual_if:
      - socket: 0
        threads: [1,2,3,4,5,6,7,8,9]
```

Start t-rex failed with no 'Driver_str'
```
[root@32b5a1566281 v3.04]# ./t-rex-64 -i -c 9 --no-ofed-check
Traceback (most recent call last):
  File "/v3.04/./dpdk_setup_ports.py", line 1764, in main
    ret = obj.do_run()
  File "/v3.04/./dpdk_setup_ports.py", line 990, in do_run
    if 'mlx5' in self.m_devices[key]['Driver_str']:
KeyError: 'Driver_str'
```

I try use hack way to dump all of self.m_devices and find no Driver_str. 

add print code near line 990 in dpdk_setup_ports.py
```
if 'Mellanox' in self.m_devices[key]['Vendor_str']:
                Mellanox_cnt += 1
                print(json.dumps(self.m_devices))
```

Here is output.
{"0000:12:00.0": {"Slot": "0000:12:00.0", "Class": "0200", "Vendor": 5555, "Device": 4119, "SVendor": "15b3", "SDevice": "0020", "Rev": "07", "NUMANode": "0", "IOMMUGroup": "10", "ProgIf": "20", "PhySlot": "1", "Slot_str": "12:00.0", "Class_str": "Ethernet controller", "Vendor_str": "Mellanox Technologies", "Device_str": "MT27800 Family [ConnectX-5]", "SVendor_str": "Mellanox Technologies", "SDevice_str": "ConnectX-5 EN network interface card, 10/25GbE dual-port SFP28, PCIe3.0 x8, tall bracket ; MCX512A-ACAT", "PhySlot_str": "1", "NUMANode_str": "0", "IOMMUGroup_str": "10", "Interface": "ens1f0np0", "net_path": "/sys/bus/pci/devices/0000:12:00.0/net/", "Active": "", "Module_str": "igb_uio,vfio-pci,uio_pci_generic", "MAC": "04:3f:72:b0:35:32", "NUMA": 0}, "0000:12:00.1": {"Slot": "0000:12:00.1", "Class": "0200", "Vendor": 5555, "Device": 4119, "SVendor": "15b3", "SDevice": "0020", "Rev": "07", "NUMANode": "0", "IOMMUGroup": "11", "ProgIf": "20", "PhySlot": "1", "Slot_str": "12:00.1", "Class_str": "Ethernet controller", "Vendor_str": "Mellanox Technologies", "Device_str": "MT27800 Family [ConnectX-5]", "SVendor_str": "Mellanox Technologies", "SDevice_str": "ConnectX-5 EN network interface card, 10/25GbE dual-port SFP28, PCIe3.0 x8, tall bracket ; MCX512A-ACAT", "PhySlot_str": "1", "NUMANode_str": "0", "IOMMUGroup_str": "11", "Interface": "ens1f1np1", "net_path": "/sys/bus/pci/devices/0000:12:00.1/net/", "Active": "", "Module_str": "igb_uio,vfio-pci,uio_pci_generic", "MAC": "04:3f:72:b0:35:33", "NUMA": 0}, "0000:13:00.0": {"Slot": "0000:13:00.0", "Class": "0200", "Vendor": 32902, "Device": 5531, "SVendor": "8086", "SDevice": "0003", "Rev": "02", "NUMANode": "0", "IOMMUGroup": "12", "ProgIf": "20", "PhySlot": "3", "Slot_str": "13:00.0", "Class_str": "Ethernet controller", "Vendor_str": "Intel Corporation", "Device_str": "Ethernet Controller E810-XXV for SFP", "SVendor_str": "Intel Corporation", "SDevice_str": "Ethernet Network Adapter E810-XXV-2", "PhySlot_str": "3", "Rev_str": "02", "NUMANode_str": "0", "IOMMUGroup_str": "12", "Interface": "", "net_path": "/sys/bus/pci/devices/0000:13:00.0/net/", "Active": "", "Module_str": "igb_uio,vfio-pci,uio_pci_generic", "NUMA": 0}, "0000:13:00.1": {"Slot": "0000:13:00.1", "Class": "0200", "Vendor": 32902, "Device": 5531, "SVendor": "8086", "SDevice": "0003", "Rev": "02", "NUMANode": "0", "IOMMUGroup": "13", "ProgIf": "20", "PhySlot": "3", "Slot_str": "13:00.1", "Class_str": "Ethernet controller", "Vendor_str": "Intel Corporation", "Device_str": "Ethernet Controller E810-XXV for SFP", "SVendor_str": "Intel Corporation", "SDevice_str": "Ethernet Network Adapter E810-XXV-2", "PhySlot_str": "3", "Rev_str": "02", "NUMANode_str": "0", "IOMMUGroup_str": "13", "Interface": "", "net_path": "/sys/bus/pci/devices/0000:13:00.1/net/", "Active": "", "Module_str": "igb_uio,vfio-pci,uio_pci_generic", "NUMA": 0}, "0000:5d:00.0": {"Slot": "0000:5d:00.0", "Class": "0200", "Vendor": 32902, "Device": 5409, "SVendor": "103c", "SDevice": "17d1", "Rev": "01", "NUMANode": "0", "IOMMUGroup": "3", "ProgIf": "20", "PhySlot": "3", "Slot_str": "5d:00.0", "Class_str": "Ethernet controller", "Vendor_str": "Intel Corporation", "Device_str": "I350 Gigabit Network Connection", "SVendor_str": "Hewlett-Packard Company", "SDevice_str": "Ethernet 1Gb 4-port 366FLR Adapter", "Rev_str": "01", "NUMANode_str": "0", "IOMMUGroup_str": "3", "Interface": "", "net_path": "/sys/bus/pci/devices/0000:5d:00.0/net/", "Active": "", "Module_str": "igb_uio,vfio-pci,uio_pci_generic", "NUMA": 0}, "0000:5d:00.1": {"Slot": "0000:5d:00.1", "Class": "0200", "Vendor": 32902, "Device": 5409, "SVendor": "103c", "SDevice": "17d1", "Rev": "01", "NUMANode": "0", "IOMMUGroup": "4", "ProgIf": "20", "PhySlot": "3", "Slot_str": "5d:00.1", "Class_str": "Ethernet controller", "Vendor_str": "Intel Corporation", "Device_str": "I350 Gigabit Network Connection", "SVendor_str": "Hewlett-Packard Company", "SDevice_str": "Ethernet 1Gb 4-port 366FLR Adapter", "Rev_str": "01", "NUMANode_str": "0", "IOMMUGroup_str": "4", "Interface": "", "net_path": "/sys/bus/pci/devices/0000:5d:00.1/net/", "Active": "", "Module_str": "igb_uio,vfio-pci,uio_pci_generic", "NUMA": 0}, "0000:5d:00.2": {"Slot": "0000:5d:00.2", "Class": "0200", "Vendor": 32902, "Device": 5409, "SVendor": "103c", "SDevice": "17d1", "Rev": "01", "NUMANode": "0", "IOMMUGroup": "5", "ProgIf": "20", "PhySlot": "3", "Slot_str": "5d:00.2", "Class_str": "Ethernet controller", "Vendor_str": "Intel Corporation", "Device_str": "I350 Gigabit Network Connection", "SVendor_str": "Hewlett-Packard Company", "SDevice_str": "Ethernet 1Gb 4-port 366FLR Adapter", "Rev_str": "01", "NUMANode_str": "0", "IOMMUGroup_str": "5", "Interface": "", "net_path": "/sys/bus/pci/devices/0000:5d:00.2/net/", "Active": "", "Module_str": "igb_uio,vfio-pci,uio_pci_generic", "NUMA": 0}, "0000:5d:00.3": {"Slot": "0000:5d:00.3", "Class": "0200", "Vendor": 32902, "Device": 5409, "SVendor": "103c", "SDevice": "17d1", "Rev": "01", "NUMANode": "0", "IOMMUGroup": "6", "ProgIf": "20", "PhySlot": "3", "Slot_str": "5d:00.3", "Class_str": "Ethernet controller", "Vendor_str": "Intel Corporation", "Device_str": "I350 Gigabit Network Connection", "SVendor_str": "Hewlett-Packard Company", "SDevice_str": "Ethernet 1Gb 4-port 366FLR Adapter", "Rev_str": "01", "NUMANode_str": "0", "IOMMUGroup_str": "6", "Interface": "", "net_path": "/sys/bus/pci/devices/0000:5d:00.3/net/", "Active": "", "Module_str": "igb_uio,vfio-pci,uio_pci_generic", "NUMA": 0}, "0000:af:00.0": {"Slot": "0000:af:00.0", "Class": "0200", "Vendor": 32902, "Device": 5515, "SVendor": "8086", "SDevice": "0001", "Rev": "02", "NUMANode": "1", "IOMMUGroup": "17", "ProgIf": "20", "PhySlot": "4", "Slot_str": "af:00.0", "Class_str": "Ethernet controller", "Vendor_str": "Intel Corporation", "Device_str": "Ethernet Controller XXV710 for 25GbE SFP28", "SVendor_str": "Intel Corporation", "SDevice_str": "Ethernet Network Adapter XXV710-2", "PhySlot_str": "4", "Rev_str": "02", "NUMANode_str": "1", "IOMMUGroup_str": "17", "Interface": "", "net_path": "/sys/bus/pci/devices/0000:af:00.0/net/", "Active": "", "Module_str": "igb_uio,vfio-pci,uio_pci_generic", "NUMA": 1}, "0000:af:00.1": {"Slot": "0000:af:00.1", "Class": "0200", "Vendor": 32902, "Device": 5515, "SVendor": "8086", "SDevice": "0000", "Rev": "02", "NUMANode": "1", "IOMMUGroup": "18", "ProgIf": "20", "PhySlot": "4", "Slot_str": "af:00.1", "Class_str": "Ethernet controller", "Vendor_str": "Intel Corporation", "Device_str": "Ethernet Controller XXV710 for 25GbE SFP28", "SVendor_str": "Intel Corporation", "SDevice_str": "Ethernet Network Adapter XXV710", "PhySlot_str": "4", "Rev_str": "02", "NUMANode_str": "1", "IOMMUGroup_str": "18", "Interface": "", "net_path": "/sys/bus/pci/devices/0000:af:00.1/net/", "Active": "", "Module_str": "igb_uio,vfio-pci,uio_pci_generic", "NUMA": 1}}

**Comment by HouMinXi** [comment]
```
# ./dpdk_nic_bind.py --status

Network devices using DPDK-compatible driver
============================================
<none>

Network devices using kernel driver
===================================
<none>

Other network devices
=====================
0000:12:00.0 'MT27800 Family [ConnectX-5]' unused=
0000:12:00.1 'MT27800 Family [ConnectX-5]' unused=
0000:13:00.0 'Ethernet Controller E810-XXV for SFP' unused=
0000:13:00.1 'Ethernet Controller E810-XXV for SFP' unused=
0000:5d:00.0 'I350 Gigabit Network Connection' unused=
0000:5d:00.1 'I350 Gigabit Network Connection' unused=
0000:5d:00.2 'I350 Gigabit Network Connection' unused=
0000:5d:00.3 'I350 Gigabit Network Connection' unused=
0000:af:00.0 'Ethernet Controller XXV710 for 25GbE SFP28' unused=
0000:af:00.1 'Ethernet Controller XXV710 for 25GbE SFP28' unused=

# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if14: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether f2:51:81:e7:82:1c brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.88.0.2/16 brd 10.88.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::f051:81ff:fee7:821c/64 scope link 
       valid_lft forever preferred_lft forever
10: ens1f0np0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 04:3f:72:b0:35:32 brd ff:ff:ff:ff:ff:ff
    altname enp18s0f0np0
    inet6 fe80::63f:72ff:feb0:3532/64 scope link 
       valid_lft forever preferred_lft forever
12: ens1f1np1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 04:3f:72:b0:35:33 brd ff:ff:ff:ff:ff:ff
    altname enp18s0f1np1
    inet6 fe80::63f:72ff:feb0:3533/64 scope link 
       valid_lft forever preferred_lft forever


```

**Comment by surajsureshkumar** [comment]
Hey @HouMinXi How did you resolve the issue you had?
