### ISSUE TITLE
Can anyone confirm if TREX works with RHEL 8.10

### ISSUE THREAD

**Issue by gusgus71** [cisco-system-traffic-generator/trex-core#1156]
We are looking to run TREX for some testing and the server's OS will be RHEL 8.10, can only find details saying TREX will work with 7.6.

Just wanted confirmation that newer RHEL versions are ok. 8.1 to 8.10.

Also we will be using 10Gb fibre cards, are all Mellanox and Broadcom cards support?

**Comment by DTran0** [comment]
I am using TRex v3.06 on EL8.10 (Oracle Linux to be specific), so it should work on RHEL 8.10 as well. List of supported cards can be found in [manual](https://trex-tgn.cisco.com/trex/doc/trex_manual.html#_hardware_recommendations). Mellanox is [included](https://trex-tgn.cisco.com/trex/doc/trex_appendix_mellanox.html). For Mellanox cards I am currently using OFED version 23.10-0.5.5.0.
