### ISSUE TITLE
ASTF Multiple CPU sending packets on wrong port

### ISSUE THREAD

**Issue by srogers6** [cisco-system-traffic-generator/trex-core#145]
I found a problem with the way Trex ASTF is sending packets when using 2 CPU’s instead of 1.   I configured 2 sets of ports 1,2 and 3,4 and put the ports in loopback so that I could capture the packets being received via the –v 7 server option and running the debug version of the server.
I suspected that Trex was sending data on the wrong port because in non loopback I would only receive half the packets.   To prove this I captured data with ports 1,2 in loopback and 3,4 disconnected so that I could capture the data received on ports 1,2  
 
Based on the config files attached I expected trex to do the following:
 
Ports 1,2
40.125.1.1  00:00:0a:25:00:01 <-> 11.140.1.1 00:11:01:40:01:01
40.125.1.2 00:00:0a:25:00:02 <-> 11.140.1.2 00:11:01:40:01:02
 
Ports 3,4
40.125.1.3 00:00:0a:26:00:01  <-> 11.140.1.3 00:11:01:40:01:03
40.125.1.4 00:00:0a:26:00:02 <-> 11.140.1.4 00:11:01:40:01:04
 
What trex actually sent on ports 1,2
Ports 1,2
40.125.1.1  00:00:0a:25:00:01 <-> 11.140.1.1 00:11:01:40:01:01
**40.125.1.3 00:00:0a:26:00:01  <-> 11.140.1.3 00:11:01:40:01:03    #### This should have been sent on Ports 3,4 not Ports 1,2**

[trex_mcore.zip](https://github.com/cisco-system-traffic-generator/trex-core/files/2412358/trex_mcore.zip)

**Comment by hhaim** [comment]
solved in v2.46 using https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/astf/http_simple_split_per_core.py
