### ISSUE TITLE
Unicode is not accepted

### ISSUE THREAD

**Issue by zverevalexei** [cisco-system-traffic-generator/trex-core#15]
Hi @hhaim 

I sent the number of PPS to TRex over HTTP API, which happened to have been encoded in UTF-8. Unicode turned out to mess with TRex, because when the UTF-8-encoded pps string was sent to the traffic generator, it threw the error - see below:

```
Error at t_rex_stateless.py:296 - 'client.start(ports=[0, 1], mult=rate, duration=duration)'

specific error:

Argument: 'mult' invalid value: '10000pps'
```

I believe try-except block with ValueError exception must be enough to avoid this.

**Comment by imarom** [comment]
Hi @zverevalexei,

Thanks for raising this up.
We've found the issue and we will fix it.

You can except the fix for the next version.

Thanks,
Itay

**Comment by zverevalexei** [comment]
Hi @imarom 

Thanks for the reply. Sounds great!

**Comment by imarom** [comment]
fixed at:

commit 0422016ab056245449e0e5bdf0dceef2c4f06e31
Author: imarom <imarom@cisco.com>
Date:   Mon Jun 20 14:30:46 2016 +0300

    bug: multiplier can be string or unicode
