### ISSUE TITLE
dpdk_setup_ports - ERROR need at least 2 ports

### ISSUE THREAD

**Issue by grantcurell** [cisco-system-traffic-generator/trex-core#176]
When I run dpdk_setup_ports.py I get: "ERROR need at least 2 ports" when I am providing two ports.

![image](https://user-images.githubusercontent.com/35169230/48989494-1cc09300-f0f0-11e8-8d22-07a3f0753f99.png)

**Comment by hhaim** [comment]
Another thing to verify, could you remove/rename you trex_cfg.yaml and check again?
The script uses the information in this file to generate the new file

**Comment by grantcurell** [comment]
Haven't forgotten! I ended up using pktgen to get everything working, but I don't want to leave you hanging. This weekend I'll fire things back up and give you a better update.

**Comment by hhaim** [comment]
We couldn't reconstruct
