### ISSUE TITLE
duration key is not taken into account in traffic yaml files

### ISSUE THREAD

**Issue by yohanbelleguic** [cisco-system-traffic-generator/trex-core#177]
Hello,

The file cap2/dns.yaml specifies a 10 seconds test duration, but when I run t-rex in stateful mode with this file (`./t-rex-64 -f cap2/dns.yaml`), this parameter is not taken into account and the default value of 3600 seconds is used.

However, note that I can set the duration by setting the `-d` option when running t-rex (`./t-rex-64 -f cap2/dns.yaml -d 10`)

**Comment by ybrustin** [comment]
This argument is deprecated and ignored (in traffic YAML file)

**Comment by hhaim** [comment]
won't be fixed
