### ISSUE TITLE
Cannot load topology file in trex-console

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#187]
Hi,
topology file could not be loaded in trex-console as below.
trex>topo load -f my_topo.py

...
 File "/opt/trex/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py", line 971, in topo_line
    self.topo_load(opts.file[0], opts.tunables)
  File "/opt/trex/automation/trex_control_plane/interactive/trex/common/trex_api_annotators.py", line 51, in wrap2
    ret = f(*args, **kwargs)
 File "/opt/trex/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py", line 702, in topo_load
    self.topo_mngr.load(topology, **tunables)
TypeError: load() argument after ** must be a mapping, not NoneType

I patched code as below and it's working now.
Please take a look at this issue.

diff -Naur scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py.org scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py
--- scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py.org	2019-01-24 15:14:57.333129103 +0900
+++ scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py	2019-01-24 15:22:34.907270173 +0900
@@ -968,7 +968,8 @@
         opts = parser.parse_args(line.split())
 
          if opts.command == 'load':
\-            self.topo_load(opts.file[0], opts.tunables)
\+	    tunables = opts.tunables or {}
\+            self.topo_load(opts.file[0], tunables)
             return False
 
         elif opts.command == 'resolve':

**Comment by ybrustin** [comment]
Hi,

Thanks for pointing on the error.

The better solution seems to me is setting empty dict as default here:
https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/automation/trex_control_plane/interactive/trex/utils/parsing_opts.py#L517
