### ISSUE TITLE
TRex changes source mac when pushing a pcap

### ISSUE THREAD

**Issue by purifier1983** [cisco-system-traffic-generator/trex-core#192]
Hi,
I have a pcap with single frame where source_mac is '00:00:00:00:00:00'
When I push the pcap, TRex changes source mac to the MAC address of the NIC's port.
How can I avoid this?

I was trying to put the following under port_info in /etc/trex_cfg.yaml:
src_mac    : '00:00:00:00:00:00'

Still, it didn't solve the problem and source mac is still being overwritten by TRex.
How can I force TRex to use the exact source mac which appears inside the pcap frame?
I use TRex v2.35

the YAML I use looks like that (indentation may look corrupted after copy-paste):
- port_limit      : 8
  version         : 2
  interfaces      : ['0b:00.0','dummy','0b:00.1','dummy','0b:00.2','dummy','0b:00.3','dummy']
  port_info       :  # Port IPs. Change to suit your needs. In case of loopback, you can leave as is.
          - default_gw : 2.2.2.2
            src_mac    : '00:00:00:00:00:00'
          - default_gw : 1.1.1.1
            src_mac    : '00:00:00:00:00:00'
          - default_gw : 4.4.4.4
            src_mac    : '00:00:00:00:00:00'
          - default_gw : 3.3.3.3
            src_mac    : '00:00:00:00:00:00'
          - default_gw : 6.6.6.6
            src_mac    : '00:00:00:00:00:00'
          - default_gw : 5.5.5.5
            src_mac    : '00:00:00:00:00:00'
          - default_gw : 8.8.8.8
            src_mac    : '00:00:00:00:00:00'
          - default_gw : 7.7.7.7
            src_mac    : '00:00:00:00:00:00'

May you please help me?
Thanks,
Lior.

**Comment by hhaim** [comment]
How do you send the pcap? there are a few method to do the same

**Comment by purifier1983** [comment]
I use local push:
push --force -f /home/lab/64B.pcap -p 0 -i 0.001 -c 0

**Comment by hhaim** [comment]
I see
```
                profile = STLProfile.load_pcap(pcap_filename,
                                               ipg_usec,
                                               speedup,
                                               count,
                                               vm = vm,
                                               packet_hook = packet_hook,
                                               min_ipg_usec = min_ipg_usec)
```
This function converts each packet to stream **without**  the option to preserve the src address (of the pcap file)

option 1:  you can add this ability and create a PR
option 2: you can use '-r' (remote) the src_mac is not changed --only the dest MAC

**Comment by purifier1983** [comment]
I tried option #2 (remote push) but seems like the src_mac is still being overwritten just as before.
I used:
push **-r** --force -f /home/lab/64B.pcap -p 0 -i 0.001 -c 0

**Comment by hhaim** [comment]
```
    memcpy(m_mac_addr, mac_addr, 12);
    memcpy(m_slave_mac_addr, slave_mac_addr, 12);
```
This is the code, you are correct. we could add a mode to keep the src_mac
I would go with option 1. it should be a few lines in python code

**Comment by purifier1983** [comment]
Seems like modifying ./automation/trex_control_plane/interactive/trex/stl/trex_stl_streams.py solves it:
int_mac_src_override_by_pkt = **1**;

Thank you.

**Comment by hhaim** [comment]
You should add arg to this function STLProfile.load_pcap and pass it along to the stream object ( the location you found).  stream support this functionality

**Comment by bdollma** [comment]
Hello,
We implemented the fix and it will be integrated soon.
When pushing the pcap as you did:
push --force -f /home/lab/64B.pcap -p 0 -i 0.001 -c 0 **--{src,dst}_mac_pcap**
adding the bolded flag will make sure that the relevant mac address is taken from the pcap. 
Best,
Besart
