### ISSUE TITLE
latency for custom packets

### ISSUE THREAD

**Issue by purifier1983** [cisco-system-traffic-generator/trex-core#201]
Hi Hanoch,
We wish to have latency results (flow stats) for custom packets, but I see the packet must begin with Ether()/IP() bytes. Can we avoid this requirement somehow?

For example, if I have a raw packet string 'cap', I wish to use:
```
packet = TLPktBuilder(pkt_buffer=cap, vm=vm, build_raw=True)
streams.append(STLStream(name = 1,
                                         packet = packet,
                                         mode = STLTXSingleBurst(total_pkts = 1, percentage = 100),
                                         self_start = True,
                                         isg = isg + start_delay_usec,  # usec
                                         action_count = action_count,
                                         flow_stats = STLFlowLatencyStats(pg_id = 5),
                                         next = next))
```
The above will not work, as TRex throws TrexFStatEx("Failed getting payload len")

In order for it to work, I must extend the packet with Ether()/IP() before:
```
pkt = Ether()/IP(src="0.0.0.0",dst="0.0.0.0")/cap
packet = STLPktBuilder(pkt=pkt, vm=vm, build_raw=True)
```
How can we avoid this? (I understand that flow stats (latency) require modifying packet's trailer (last 16B)  and we can live with that)

Thanks,
Lior.

**Comment by hhaim** [comment]
Could you give an example for such a packet?
To achieve very accurate latency we are using hardware capability of the NIC to filter and redirect those packets to specific cores which has a capability to measure the latency with no delay. Each NIC has different capability and to have an ability to redirect every type of packet won’t work in the general case.
Software mode could potentially do that with less accuracy - but it have the same verification as the hardware case. Would it help to enable that?

**Comment by purifier1983** [comment]
We define a customized packet format, which may look to TRex as series of random bytes.
It would be helpful to enable that, so we can measure latency of raw (customized) packets (even if not so accurate due to --software).
If it's not a big change to deal with, could you please point me to the relevant part of the code? maybe I can do it myself and upload a PR.

Thanks,
Lior.

**Comment by hhaim** [comment]
Could you define the way you want to identify those custom packets as latency (in Rx side)? Is it offset/magic? other? 
Today  ipv4.id/ipv6.id. is used (using hardware filters)

**Comment by purifier1983** [comment]
Consider a case where the rate is low (1Gbps link) so we assume the CPU is not a bottleneck.
Can we somehow change the filter to ALL packets? Zero mask for example?
Also:
Does ipv4.id needs to be a specific value? Does TRex change it? Is it the only field that is used for filtering latency packets?

**Comment by hhaim** [comment]
We can do it at higher rates for multi-core software mode and in case RSS can work on those flows. 
In case of latency stream 
1. ipv4.id is changed 
2. TOS &1 is changed  
3. Meta data is added at the end of the packet (16 bytes)
see manual for more info. 

But I have a different simple proposal that now with multi-core software mode could work in scale too (again if the RSS can split the work)
Please provide your input. 

1.  Add RPC to add bpf filter latency. The packet still needs to have at least 16 bytes at the end (to add the latency magic ).
2. In case the  bpf was given ,the filter will be matched in rx side for both the old condition (ipv4.id) and bpf condition. In this case the requirement of IP header for stream will be removed.
3. In this case, It will be a user responsibility that **only** latency streams will match the bpf filter.

**Comment by hhaim** [comment]
v2.58 solves this
