### ISSUE TITLE
please update the document " https://trex-tgn.cisco.com/trex/doc/trex_cookbook/index.html#j1_21"

### ISSUE THREAD

**Issue by srikanthg10** [cisco-system-traffic-generator/trex-core#205]
please add or update the document for astf api examples
https://trex-tgn.cisco.com/trex/doc/trex_cookbook/index.html#j1_21

**Comment by hhaim** [comment]
You are welcome to update it.

See snippets for examples at the end
[astf](https://trex-tgn.cisco.com/trex/doc/cp_astf_docs/api/client_code.html)

**Comment by srikanthg10** [comment]
Thanks sure!

**Comment by hhaim** [comment]
fixed
