### ISSUE TITLE
catching polymorphic type ‘class TrexFStatEx’

### ISSUE THREAD

**Issue by raghavendrachari08** [cisco-system-traffic-generator/trex-core#209]
While building trex on rhel8 with gcc8.x am getting following error 

../../src/stx/stl/trex_stl_fs.cpp: In member function ‘int CFlowStatRuleMgr::start_stream(TrexStream*)’:
../../src/stx/stl/trex_stl_fs.cpp:823:18: error: catching polymorphic type ‘class TrexFStatEx’ by value [-Werror=catch-value=]
         } catch (TrexFStatEx) {
                  ^~~~~~~~~~~
cc1plus: all warnings being treated as errors

In function ‘pci_get_kernel_driver_by_path’,
    inlined from ‘pci_scan_one.isra.1’ at ../../src/dpdk/drivers/bus/pci/linux/pci.c:342:8:
../../src/dpdk/drivers/bus/pci/linux/pci.c:86:3: warning: ‘strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
   strncpy(dri_name, name + 1, strlen(name + 1) + 1);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../src/dpdk/drivers/bus/pci/linux/pci.c: In function ‘pci_scan_one.isra.1’:
../../src/dpdk/drivers/bus/pci/linux/pci.c:86:31: note: length computed here
   strncpy(dri_name, name + 1, strlen(name + 1) + 1);
                               ^~~~~~~~~~~~~~~~

Waf: Leaving directory `/root/trex-core/linux_dpdk/build_dpdk'
Build failed
 -> task in '_t-rex-64-debug' failed with exit status 1 (run with -v to display more information)

**Comment by ybrustin** [comment]
Hi,

Could you share gcc version?
Are you using RHEL8 beta? (AFAIK there was no official release yet)
I can't reconstruct errors you show with gcc-8.2 in Ubuntu 18.

Thanks,
Yaroslav.

**Comment by raghavendrachari08** [comment]
yeah it is working now ,
Thanks
