### ISSUE TITLE
about 2544

### ISSUE THREAD

**Issue by ghnicky** [cisco-system-traffic-generator/trex-core#216]
trex sends at port 1 and receive from port 1, the dut seems work correctly which receive 1.7Mpps and send back about 0.9Mpps.
the trex works in vm , dut works in another vm, they all use VF.
the two PF  is connected with cable, i am sure it works in loopback.

the packet is 64byte. and it's content is as follows( is it lack of some info ?)
0x7fc31a342ec0 : aabbccdd ee31aabb ccdde030 08004501
0x7fc31a342ed0 : 0038fc00 00004011 fb26c0a8 010dc0a8
0x7fc31a342ee0 : 012fc354 c3540024 7b6e0114 00120000
0x7fc31a342ef0 : 00010000 000d0000 002f0000 abcd3031
0x7fc31a342f00 : 32333435 36373839

server statistics is as follows:
-Per port stats table 
      ports |               0 |               1 
 -----------------------------------------------
   opackets |              14 |      3725314280 
     obytes |             896 |    275673257080 
   ipackets |              84 |      1954222572 
     ibytes |            5456 |    144612469628 
    ierrors |               0 |               0 
    oerrors |               0 |               0 
      Tx Bw |       0.00  bps |       1.34 Gbps 

-Global stats enabled 
 Cpu Utilization : 100.0  %  2.7 Gb/core 
 Platform_factor : 1.0  
 Total-Tx        :       1.34 Gbps  
 Total-Rx        :     687.93 Mbps  
 Total-PPS       :       2.27 Mpps

**Comment by ghnicky** [comment]
notied that the code in 
RXLatency::handle_pkt(const rte_mbuf_t *m) {
    uint8_t tmp_buf[sizeof(struct flow_stat_payload_header)];
    CFlowStatParser parser(CFlowStatParser::FLOW_STAT_PARSER_MODE_SW);
    int ret = parser.parse(rte_pktmbuf_mtod(m, uint8_t *), m->pkt_len);

    if (m_rcv_all ||  (ret == 0)) {
        uint32_t ip_id = 0;
        int ret2 = parser.get_ip_id(ip_id);
        if (m_rcv_all || ( ret2 == 0)) {
            if (m_rcv_all || is_flow_stat_id(ip_id)) {
                uint16_t hw_id;
                if (is_flow_stat_payload_id(ip_id) || ((! is_flow_stat_id(ip_id)) && m_rcv_all)) {
                    bool good_packet = true;
                    struct flow_stat_payload_header *fsp_head = (flow_stat_payload_header *)
                        utl_rte_pktmbuf_get_last_bytes(m, sizeof(struct flow_stat_payload_header), tmp_buf);
                    hw_id = fsp_head->hw_id;
                    CRFC2544Info *curr_rfc2544;

                    if (unlikely(fsp_head->magic != FLOW_STAT_PAYLOAD_MAGIC) || hw_id >= MAX_FLOW_STATS_PAYLOAD) {
                        good_packet = false;
                        if (!m_rcv_all)
                            m_err_cntrs->m_bad_header++;


the code enters to the above "unlikely branch",so the 2544 can't work.( maybe my understanding is not correctly ! please correct me!) then what's the example to construct a packet used in 2544.

**Comment by ghnicky** [comment]
the packet received is as follows:
------------------------------
0x7fc31a63e400 :  aabbccdd   e031aabb   ccddee31   08004500 
0x7fc31a63e410 :  0038a21f   00004011   5509c0a8   012fc0a8 
0x7fc31a63e420 :  010dc354   c3540024   00000114   001c0000 
0x7fc31a63e430 :  5f010000   00010000   000d0000   abcd3031 
0x7fc31a63e440 :  32333435   36373839

**Comment by ghnicky** [comment]
maybe the packet script is not good!?  then which packet script is best for test 2544? could you give some help?

**Comment by hhaim** [comment]
2544 is out of scope of TRex package.
There are many scripts that uses TRex that can help with that
