### ISSUE TITLE
VF can't Receive packet after trex  start

### ISSUE THREAD

**Issue by nicholas-chen-nj** [cisco-system-traffic-generator/trex-core#229]
Trex VM takes over VF in one PF and DUT VM takes over VFs belong to another PF. Before switching the driver to igbuio in VM, I config ip  for the port, it can ping from one vm to other VM. 
After trex starting, the DUT VM can receive the arp broadcast from trex server, but it seems that trex can't receive the arp response  packets from DUT.  And in the host, the statistics of the VF[VF10,  VF11] used in TREX vm  is as the follwoing:
     VF 10 Rx Packets: 0
     VF 10 Rx Bytes: 0
     VF 10 Tx Packets: 11
     VF 10 Tx Bytes: 660
     VF 10 MC Packets: 0
     VF 11 Rx Packets: 0
     VF 11 Rx Bytes: 0
     VF 11 Tx Packets: 11
     VF 11 Tx Bytes: 660
     VF 11 MC Packets: 0

The VF used for DUT vm is as the following:
     VF 10 Rx Packets: 0
     VF 10 Rx Bytes: 0
     VF 10 Tx Packets: 0
     VF 10 Tx Bytes: 0
     VF 10 MC Packets: 0
     VF 11 Rx Packets: 119
     VF 11 Rx Bytes: 37794
     VF 11 Tx Packets: 40
     VF 11 Tx Bytes: 1680
     VF 11 MC Packets: 11

[DUT VM receive some broadcast packet from other VFs, from the DUT capture info, it proves that arp response packet has send out and the dest mac is belongs to Trex.]

Another thing, the current CPU of the host is  avx. the nic is 82599ES.[ i have compiled the trex in this host.] 
----------------------------------------------------------------------
This test model works ok another host which is  avx-2.

could you give some help?

**Comment by nicholas-chen-nj** [comment]
this problem occurs in some hosts, maybe there's some defects in trex.
---the server output is as follwong
WARNING: hugepages config file (/sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages) does not exist!
Starting Scapy server..... Scapy server is started
Trying to bind to igb_uio ...
/usr/bin/python dpdk_nic_bind.py --bind=igb_uio 0000:06:12.1 0000:06:12.3 
The ports are bound/configured.
FLAG=avx
Starting  TRex v2.49 please wait  ... 
 set driver name net_ixgbe_vf 
 driver capability  : TCP_UDP_OFFLOAD  TSO 
 set dpdk queues mode to ONE_QUE 
 Number of ports found: 2
zmq publisher at: tcp://*:4500
 wait 1 sec .
port : 0 
------------
link         :  link : Link Up - speed 10000 Mbps - full-duplex
promiscuous  : 0 
port : 1 
------------
link         :  link : Link Up - speed 10000 Mbps - full-duplex
promiscuous  : 0 
 number of ports         : 2 
 max cores for 2 ports   : 1 
 tx queues per port      : 3 
 -------------------------------
RX core uses TX queue number 65535 on all ports
 core, c-port, c-queue, s-port, s-queue, lat-queue
 ------------------------------------------
 1        0      0       1       0      0  
 -------------------------------
trex>start -f stl/udp_for_benchmarks.py -t  packet_len=64 -m 10pps
========the tui output is following

**Comment by nicholas-chen-nj** [comment]
the tui output is as follows:
----------------------
Global Statistitcs

connection   : localhost, Port 4501                  total_tx_L2  : 0 b/sec                        
version      : STL @ v2.49                           total_tx_L1  : 0 b/sec                        
cpu_util.    : 0.0% @ 1 cores (1 per port)           total_rx     : 0 b/sec                        
rx_cpu_util. : 0.0% / 0 pkt/sec                      total_pps    : 0 pkt/sec                      
async_util.  : 0.06% / 1.23 KB/sec                   drop_rate    : 0 b/sec                        
                                                     queue_full   : 0 pkts                         

Port Statistics

   port    |         0         |         1         |       total       
-----------+-------------------+-------------------+------------------
owner      |              root |              root |                   
link       |                UP |                UP |                   
state      |      TRANSMITTING |      TRANSMITTING |                   
speed      |           10 Gb/s |           10 Gb/s |                   
CPU util.  |              0.0% |              0.0% |                   
--         |                   |                   |                   
Tx bps L2  |             0 bps |             0 bps |             0 bps 
Tx bps L1  |             0 bps |             0 bps |             0 bps 
Tx pps     |             0 pps |             0 pps |             0 pps 
Line Util. |               0 % |               0 % |                   
---        |                   |                   |                   
Rx bps     |             0 bps |             0 bps |             0 bps 
Rx pps     |             0 pps |             0 pps |             0 pps 
----       |                   |                   |                   
opackets   |                 0 |                 0 |                 0 
ipackets   |                 0 |                 0 |                 0 
obytes     |                 0 |                 0 |                 0 
ibytes     |                 0 |                 0 |                 0 
tx-pkts    |            0 pkts |            0 pkts |            0 pkts 
rx-pkts    |            0 pkts |            0 pkts |            0 pkts 
tx-bytes   |               0 B |               0 B |               0 B 
rx-bytes   |               0 B |               0 B |               0 B 
-----      |                   |                   |                   
oerrors    |                 0 |                 0 |                 0 
ierrors    |                 0 |                 0 |                 0 

status:  \
--------------
the trex_cfg.yaml  is as follows:
------------------------------------------------
- version: 2
  interfaces: ['06:12.1', '06:12.3']
  port_info:
      - dest_mac: aa:bb:cc:dd:10:09
        src_mac:  aa:bb:cc:dd:10:08 
      - dest_mac: aa:bb:cc:dd:10:08 
        src_mac:  aa:bb:cc:dd:10:09
  platform:
      master_thread_id: 1 
      latency_thread_id: 2 
      dual_if:
        - socket: 0 
          threads: [3]

**Comment by nicholas-chen-nj** [comment]
the problem is the intel driver not work as expect.

**Comment by cansintartici** [comment]
> the problem is the intel driver not work as expect.

Hi, I am having similar problem with net_ixgbe_vf  
Can you give more information about what is wrong with the intel driver and if you find a solution for it.
Thanks
BR
