### ISSUE TITLE
Use the trex DPDK model test 10 g flow anomalies 

### ISSUE THREAD

**Issue by numbhonker** [cisco-system-traffic-generator/trex-core#23]
I installed two pieces x520 - D2 NIC on the server of DELL-R730, and compile good linux_dpdk model code.
1、Using dpdk_setup_ports. py can view the information card.
Network devices using DPDK-compatible driver
============================================
0000:05:00.0 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=
0000:05:00.1 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=
0000:06:00.0 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=
0000:06:00.1 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=

2、Create a configuration file: /etc/trex_cfg.yaml.
[root@bogon etc]# vim trex_cfg.yaml 
- port_limit      : 4  
  version         : 2
  interfaces    : ["05:00.0","05:00.1","06:00.0","06:00.1"]
 c    : 4
port_bandwidth_gb    : 10
port_info       :  
          - dest_mac        :   [0x00,0x1b,0x21,0x98,0x0c,0xe1] 
            src_mac         :   [0x00,0x1b,0x21,0x96,0x7a,0x50] 
          - dest_mac        :   [0x00,0x1b,0x21,0x96,0x7a,0x50] 
            src_mac         :   [0x00,0x1b,0x21,0x98,0x0c,0xe1] 
          - dest_mac        :   [0x00,0x1b,0x21,0x98,0x0c,0xe0] 
            src_mac         :   [0x00,0x1b,0x21,0x96,0x7a,0x51]  
          - dest_mac        :   [0x00,0x1b,0x21,0x96,0x7a,0x51] 
            src_mac         :   [0x00,0x1b,0x21,0x98,0x0c,0xe0] 

3、Run TRex
[root@bogon scripts]# ./t-rex-64 -f cap2/dns.yaml -c 4 -m 1 -d 100  -l 1000
-Per port stats table 
      ports |               0 |               1 |               2 |               3 
 -----------------------------------------------------------------------------------------
   opackets |            8564 |            8564 |            8564 |            8564 
     obytes |          565268 |          565332 |          565268 |          565332 
   ipackets |               0 |               0 |               0 |            8564 
     ibytes |               0 |               0 |               0 |          565268 
    ierrors |               0 |               0 |               0 |               0 
    oerrors |               0 |               0 |               0 |               0 
      Tx Bw |     524.56 Kbps |     524.56 Kbps |     524.56 Kbps |     524.56 Kbps 

-Global stats enabled 
 Cpu Utilization : 0.0  %  5.3 Gb/core 
 Platform_factor : 1.0  
 Total-Tx        :       2.10 Mbps  
 Total-Rx        :     524.56 Kbps  
 Total-PPS       :       3.97 Kpps  
 Total-CPS       :       0.00  cps  
 Expected-PPS    :       2.00  pps  
 Expected-CPS    :       1.00  cps  
 Expected-BPS    :       1.30 Kbps  
 Active-flows    :        0  Clients :      504   Socket-util : 0.0000 %    
 Open-flows      :        8  Servers :      248   Socket :        8 Socket/Clients :  0.0 
 drop-rate       :       1.57 Mbps   
 current time    : 11.7 sec  
 test duration   : 88.3 sec  

-Latency stats enabled 
 Cpu Utilization : 0.2 %  
 if|   tx_ok , rx_ok  , rx check ,error,       latency (usec) ,    Jitter          max window 
   |         ,        ,          ,     ,   average   ,   max  ,    (usec)                     
 ---------------------------------------------------------------------------------------------------------------- 
 0 |     8560,       0,         0,    0,          0  ,       0,       0      |  0  0  0  0  0  0  0  0  0  0  0  0  0 
 1 |     8560,       0,         0,    0,          0  ,       0,       0      |  0  0  0  0  0  0  0  0  0  0  0  0  0 
 2 |     8560,       0,         0,    0,          0  ,       0,       0      |  0  0  0  0  0  0  0  0  0  0  0  0  0 
 3 |     8560,    8560,         0,    0,          3  ,      16,       0      |  7  5  5  5  4  4  4  4  5  4  4  4  4 

I don't know why appear this kind of phenomenon, can you  help me to solve this problem?

Finally, thank you very much can see trex project in GitHub, I'm looking forward to it can help me to solve some practical application problems,  forward to your reply!

**Comment by hhaim** [comment]
You configuration looks good.

1)      Please send questions in the google forum

2)      CentsOs 7.0 wasn’t tested by us

3)      You might not loopback the right ports – try to remove the interface section from trex_cfg.yaml in this case all the ports will have the same MAC (0.1.0) and you will get packets back

Thanks,
Hanoh

**Comment by numbhonker** [comment]
Hanoh,
    I'm very sorry,may be I did not describe my question clearly!
    If step 1 and step 2 is correct, according to the document, in the third step, I should be able to see the value Total-Tx and Total-Rx are the same, drop-rate should be 0, but you can see I posted the print information, The value of the Tx and Rx is not the same. And then only one channel can receive the data.
 In normal circumstances I should see four channel can send and receive data. So I want to know the reason why appear this phenomenon caused. How should I adjust my configuration? Or How do I can normal use!

Thanks,
Barnett

**Comment by hhaim** [comment]
Understood. I think the phy loopback does not match your config file.
If you are not connect to a switch try to set all the MAC to the *same* value or just remove it from cfg file.

Hanoh
Sent from my iPhone

On 17 ????? 2016, at 9:48, numbhonker <notifications@github.com<mailto:notifications@github.com>> wrote:


Hanoh,
I'm very sorry,may be I did not describe my question clearly!
If step 1 and step 2 is correct, according to the document, in the third step, I should be able to see the value Total-Tx and Total-Rx are the same, drop-rate should be 0, but you can see I posted the print information, The value of the Tx and Rx is not the same. And then only one channel can receive the data.
In normal circumstances I should see four channel can send and receive data. So I want to know the reason why appear this phenomenon caused. How should I adjust my configuration? Or How do I can normal use!

Thanks,
Barnett

-

**Comment by numbhonker** [comment]
Hanoh,
   I have a questions about NIC connection. Document description mentioned in the two pieces of direct connection problem. Figure identified in 0-0, 1-1, means the port 1 of the NIC 1 must be connected the port 1 of the NIC 2, or means the port 1 of NIC 1 can be connected  any port of NIC 2. Whether are each NIC on the two ports  independent of each other? If it is, why can not be  connected itself. If it isn't, what is that each port's MAC address in the configuration which exist in the relationship?
   
Barnett

**Comment by hhaim** [comment]
Hi Barnett, 

We have revisited the documentation and with the new 16.07 DPDK (2.07) it is possible to loop-back the same NIC ports to each other (82599). Your config file assumes that each NIC with dual ports is loopback

port0<->port1 (NIC0)
port2<->port3 (NIC1)

With this NIC (82599) it is possible to set the MAC addr to the same value (there is no internal switch).
Did you get packets in case you set all the MAC to the same value?
The general case to identifying the NIC is to assign them to Linux and using ethertool get the NIC info (which is which)


thanks,
Hanoh

**Comment by numbhonker** [comment]
Hi Hanoh,
    Two days ago because I configuration problem, with your help, and reviewing the document details, I have been able to successfully run the example, thank you very much!
   I want to  use the trex playback of pcap file, it was used to test the  my application of processing capacity.I found that after the call the script, ifconfig will not be able to see the card information again, Use tcpdump also will not be able to see traffic information network card, So  my application  have no direct traffic information from the network card.  I see the trex use DPDK, whether trex recompiling the nic driver,When invoked use the new driver. If I want to test my application ,Could you give me an idea to solve the problem?
   Sincerely look forward to your reply!
thanks,
Barnett

**Comment by hhaim** [comment]
Hi,  I suggest to move this discussion to our forum.

On 19 ????? 2016, at 5:35, Barnett <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Hanoh,
Two days ago because I configuration problem, with your help, and reviewing the document details, I have been able to successfully run the example, thank you very much!
I want to use the trex playback of pcap file, it was used to test the my application of processing capacity.I found that after the call the script, ifconfig will not be able to see the card information again, Use tcpdump also will not be able to see traffic information network card, So my application have no direct traffic information from the network card. I see the trex use DPDK, whether trex recompiling the nic driver,When invoked use the new driver. If I want to test my application ,Could you give me an idea to solve the problem?
Sincerely look forward to your reply!
thanks,
Barnett

-
