### ISSUE TITLE
trex on CentOS 7.6

### ISSUE THREAD

**Issue by trexuser** [cisco-system-traffic-generator/trex-core#231]
Has anyone had success building trex core on CentOS 7.6?

It says in the documentation that only CentOS 7.4 is supported but we need to install this on a CentOS 7.6 machine with Mellenox drivers.

Unable to do so, encountering errors  at various states of the build starting with mlx5-64-debug "failed with exit status 1".  We have the latest version of the Mellenox drivers installed.

Any advise?

**Comment by hhaim** [comment]
You should follow the Mellanox appendix in the documentation

**Comment by trexuser** [comment]
We are following the Mellanox documentation.  

Still not able to complete the install.   

Does anyone have success with CentOS 7.6?

Is there any option for further support?

**Comment by hhaim** [comment]
This issue is likely to be related to OFED version and the way you install it.

**Comment by tmonjalo** [comment]
Wouldn't it be easier to use the rdma-core package from the distribution, instead of OFED?
https://centos.pkgs.org/7/centos-x86_64/rdma-core-22.1-3.el7.x86_64.rpm.html
