### ISSUE TITLE
pushing pcaps in cluster topology

### ISSUE THREAD

**Issue by purifier1983** [cisco-system-traffic-generator/trex-core#274]
Hi,
I have a lab topology of 3 PCs (named pc1, pc2, pc3) , each PC is installed with 2 Intel I350 NICs 4x1G ports. (total 8x1G ports per PC, named eth0 to eth7 for example, with respectively PCI addresses [01:00.0, 01:00.1, 01:00.2, 01:00.3, 05:00.0, 05:00.1, 05:00.2, 05:00.3]).
All ports on all PCs are connected to the same switch, and target is to configure TRex on each PC such that I'll be able to push pcaps from any NIC port to any NIC port in this 24-ports system.

I was looking in TRex manual and I saw generator yaml block definitions, and corresponding ip routing commands, but I'm a little confused.
 
I hope it's not a too big request, but can you please write down example generator yaml blocks for each of the 3 PCs, together with corresponding ip route commands for each PC?

Another question, say I want to push a pcap from pc1 eth0 to pc2 eth5.
What should be the value for '-p' flag in pc1 command ```push -f example.pcap --force -c 0 -p <?>```  ?

Thanks,
Lior.

**Comment by hhaim** [comment]
You can do it using STL mode. You just need to change the dest_mac or the IP of the TRex port to match eth5
