### ISSUE TITLE
TRex with non-standard EtherType

### ISSUE THREAD

**Issue by purifier1983** [cisco-system-traffic-generator/trex-core#276]
Hi,
Regarding EtherType, quoting from: https://en.wikipedia.org/wiki/EtherType#Overview
“Thus, values of 1500 and below for this field indicate that the field is used as the size of the payload of the Ethernet frame while values of 1536 and above indicate that the field is used to represent an EtherType. The interpretation of values 1501–1535, inclusive, is undefined.[1]”

How can we configure TREX to accept EthType/Size with values smaller than 1500?
For now, if we choose smaller values (which represent size, but actual packet size is different), TRex doesn't receive the packet and doesn't inform about it in ierrors either.

Thanks.

**Comment by hhaim** [comment]
Which NIC and what is the CLI?

**Comment by purifier1983** [comment]
Intel I350 4x1G
CLI is by pushing pcap file. (with --force)

**Comment by hhaim** [comment]
I mean the server command. 
try adding ```--software``` to server CLI

**Comment by purifier1983** [comment]
I already do so. This is my CLI:
./t-rex-64 --stl -c 1 --iom 1 -i --software --mbuf-factor 0.2

**Comment by hhaim** [comment]
Have a look into Console
>stats -zx
