### ISSUE TITLE
Can't stop push -r

### ISSUE THREAD

**Issue by ybrustin** [cisco-system-traffic-generator/trex-core#285]
In stateless mode:
\> push -r -f \<params\>
![image](https://user-images.githubusercontent.com/16772883/59683392-c7a9b300-91e0-11e9-8511-5377f0f72b3a.png)
\> stop
![image](https://user-images.githubusercontent.com/16772883/59683460-e445eb00-91e0-11e9-8388-e93286177b6c.png)

I guess it's related to new multi-profile support and port state.

**Comment by hhaim** [comment]
@jsmoon can you look into this?

**Comment by ybrustin** [comment]
I think this is the root cause:

>         # find the relevant ports
>         port_id_list = parse_ports_from_profiles(ports)
>         active_ports = list_intersect(ports, self.get_profiles_with_state("active"))       <-----
>         if not active_ports:
>             if not ports:
>                 msg = 'no active ports'

And also, all the usages of get_profiles_with_state (there are several places)

**Comment by jsmoon** [comment]
This issue came from multi-profile support in client side.
There is missing aware of PCAP_TX which is remained as per port operation.
JunsubHan4rmEricsson will fix this issue.

**Comment by hhaim** [comment]
@JunsubHan4rmEricsson and @jsmoon thanks for looking into it

**Comment by JunsubHan4rmEricsson** [comment]
Please check #286

**Comment by hhaim** [comment]
fixed #286
