### ISSUE TITLE
ASTF multi-profile regression tests

### ISSUE THREAD

**Issue by hhaim** [cisco-system-traffic-generator/trex-core#294]
Add test to verify multi-profile
1. Up to 1000 profiles in parallel  
2. Read the counters 
3. Random Add/Remove

**Comment by hhaim** [comment]
@JunsubHan4rmEricsson is your tests cover all of the above?

**Comment by JunsubHan4rmEricsson** [comment]
2 and 3 are covered
Can you be more specific with 1's scenario?

**Comment by hhaim** [comment]
Verify that your #3 test can work with up to ~1000 active profiles. this meant to verify the scale. 
I would verify the limitation and see what breaks when you take it to 10,000 is it only memory?

**Comment by JunsubHan4rmEricsson** [comment]
So you want me to add 1000 profiles and see if they can run together?
Do you have a specific protocol in mind?

**Comment by hhaim** [comment]
Yes,  would be good to start with http_simple.py

**Comment by hhaim** [comment]
Was done.
