### ISSUE TITLE
Crash issues from wrong API usage in ASTF mode

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#305]
Hi,
I found following 5 issues in ASTF mode.
These are caused from wrong API usage from user, but, I think it needs some defense code to report proper error messages instead of crashing TRex server.

We have 2 options to fix it.
Option#1. Defense from trex server : Complex to fix, more robust and promising approach
Option#2. Defense from Python/Java API : Simpler to fix, reduce burden of trex server
Which approach would be preferred option in trex point of view?

Issue#1. TRex server crash when user used same client/server IP in ASTF mode
Reproduction>
ip_gen_c = ASTFIPGenDist(ip_range=["16.0.0.2", "16.0.0.2"], distributionn
="seq")
ip_gen_s = ASTFIPGenDist(ip_range=["16.0.0.2", "16.0.0.2"], distributionn
="seq")

Issue#2. TRex server crash when user used big set_var in ASTF UDP mode
If user used over than 88000 loops in UDP, then, trex server was crashed.
Reproduction>
loop = 88000
prog_c.set_var("var1",loop); #
prog_c.set_label("a:");
prog_c.send_msg('*')
prog_c.jmp_nz("var1","a:")

Issue#3. TRex server crash when same port used in the multiple template group in ASTF mode
If user used same port number in the multiple template group in ASTF mode, TRex server was crashed.
Reproduction>
temp_c1 = ASTFTCPClientTemplate(port=80, program=prog_c,ip_gen=ip_gen, cc
ps = 1)
temp_c2 = ASTFTCPClientTemplate(port=80, program=prog_c, ip_gen=ip_gen, 
cps = 2)
temp_s1 = ASTFTCPServerTemplate(program=prog_s, assoc=ASTFAssociationRull
e(80)) # using default association
temp_s2 = ASTFTCPServerTemplate(program=prog_s, assoc=ASTFAssociationRull
e(80)) # using default association

Issue#4. TRex server crash when user used get_stats(pid_input='*') in ASTF mode
Reproduction>
stats = c.get_stats(pid_input='*')

Issue#5. Not possible to find exact error reason when same port used between multiple profiles
If user used same port number in the different profile, then, TRex reports 'Unknown error' when starting TRex. It's not easy to find user fault(same port used) in the user point of view.
Reproduction>
Run 2 profiles with same port number.

Best Regards
Gwangmoon

**Comment by hhaim** [comment]
It should be solved both in the server and in the client
Server should not crash due to wrong JSON.
This issues are legacy due to the movement from batch to interactive and I think there are more issues like that

**Comment by egwakim** [comment]
All listed 4 issues are cleared and merged now.
Closing ticket.
