### ISSUE TITLE
TRex logging facility suggestion

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#306]
Hi,
Currently, logs in TRex differ by each type.
It's not easy to trace issue.
How about changing them into unified way?

1. Current TRex logs
1) TRex server log, console log of trex server(no time stamp): /tmp/trex.txt (verbose_level == 7 )
   - Displayed on console, used by regression test
   - save log on /tmp/trex.txt if verbose_level == 7 without time stamp
2) DPDK log
   - saved on syslog with 'xx' prefix(/var/log/messages)
   used SET_ARGS((char *)"xx") in main_dpdk.cpp
3) RPC log, enable when --rpc-log option specified : specified path in --rpc-log option
4) Daemon log, daemon log if trex daemon used : /var/log/trex/trex-server.log

2. Suggested logging
Unify TRex server related logs into /var/log/messages with time stamp
-> We can trace server logs with timed order in single file including DPDK logs

3. Suggested change
- No change on 3) RPC log 4) Daemon log 
1) Change DPDK log 'xx' prefix to 'TRex' to figure-out log origination
2) Use RTE_LOG() with trex server messages which are not logged with RTE_LOG()
   - No impact on regression test
   - All trex server log including DPDK log will be saved on /var/log/messages with 'TRex' prefix in timed-order(if verbose_level meets)

Best Regards
Gwangmoon

**Comment by egwakim** [comment]
Hi Hanoh,
Do you have any opinion about it?
If it's acceptable, we can contribute as I suggested.

**Comment by hhaim** [comment]
I don't see an issue.
One comment, I would create a trex API that map to RTE_LOG this way create a separation betwean DPDK and TRex. 
Our regression scripts are using the log messages  @ybrustin 
Do you see an issue to change it?

**Comment by hhaim** [comment]
I've talked to @ybrustin the regression code that reads the logfiles (to identify core backtrace) is in the daemon code.  You should change it in the same  PR

**Comment by egwakim** [comment]
- Added backtrace for fault.
https://github.com/cisco-system-traffic-generator/trex-core/commit/e3845f22b5eff4f34bc2d6b90099cd3d72c45ac8

- Fixed stdout buffer to capture outside trex
https://github.com/cisco-system-traffic-generator/trex-core/commit/c37a855d89fe5e11d8e9a80665650e346f53e033
