### ISSUE TITLE
jsonrpc server responds with a batch response to a non-batch request

### ISSUE THREAD

**Issue by CtrlZvi** [cisco-system-traffic-generator/trex-core#322]
The JSON-RPC server will reply with a batch response (an array of result objects) instead of a single response (a single result object not in an array) even when presented with a non-batch request. (See [JSON-RPC 2.0 Response Object](https://www.jsonrpc.org/specification#response_object): "The Response is expressed as **a single JSON Object**" emphasis mine.)
This is causing issues for the JSON-RPC 2.0 library I'm using.
Minimal repro case in Golang:
```go
package main

import (
	"fmt"

	"github.com/pebbe/zmq4"
)

func main() {
	context, err := zmq4.NewContext()
	if err != nil {
		panic(err)
	}
	defer context.Term()

	socket, err := context.NewSocket(zmq4.REQ)
	if err != nil {
		panic(err)
	}
	defer socket.Close()

	if err := socket.Connect("tcp://localhost:4501"); err != nil {
		panic(err)
	}

	if _, err := socket.Send(`
		{
			"id": "1",
			"jsonrpc": "2.0",
			"method": "api_sync",
			"params": {
				"api_vers": [
					{
						"type": "core",
						"major": 4,
						"minor": 1
					}
				]
			}
		}`, 0); err != nil {
		panic(err)
	}
	reply, err := socket.Recv(0)
	if err != nil {
		panic(err)
	}
	fmt.Println(reply)

	if _, err := socket.Send(`
		{
			"id": "2",
			"jsonrpc": "2.0",
			"method": "ping",
			"params": null
		}`, 0); err != nil {
		panic(err)
	}
	reply, err = socket.Recv(0)
	if err != nil {
		panic(err)
	}
	fmt.Println(reply)

}
```
Tested against v2.60 in docker.

**Comment by CtrlZvi** [comment]
I managed to trace this one to https://github.com/cisco-system-traffic-generator/trex-core/blob/master/src/rpc-server/trex_rpc_req_resp_server.cpp#L268. The check of `response.size()` seems incorrect. `response` is a string passed in from the caller designed to hold the stringized JSON response. I think the intended behavior was to check if `response_json.size()` was equal to 1, to check if there was only one response to send out.
While this would resolve my current use-case, it would not be the best solution, as it's possible to submit a batch call with only one request object. According to the spec, the response should be a batch response with one response object. The ideal thing to do is track whether or not the request was a batch request and return a batch response accordingly.

**Comment by hhaim** [comment]
@CtrlZvi are you planning to write a Golang client?

**Comment by CtrlZvi** [comment]
@hhaim A client, yes, but not an SDK (at least, not yet). I'm looking into getting our current Golang load test runner to support TRex as a backend.

**Comment by CtrlZvi** [comment]
Thanks for fixing so quickly!
