### ISSUE TITLE
Trex incorrectly recognized Fortpark x722 as Fortville x710 and failed to launch due firmware version.

### ISSUE THREAD

**Issue by selinaxue0** [cisco-system-traffic-generator/trex-core#325]
Test systems had PCH integrated X722 10G Ethernet and discrete Intel XXV710 25G Ethernet as below.  The X722 firmware information is the latest v4.10. 

Met error when Trex tried to launch with x722.

[root@localhost ~]# lspci |grep Ethe
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (3) I219-LM (rev 04)
17:00.0 Ethernet controller: Intel Corporation Ethernet Controller XXV710 for 25GbE SFP28 (rev 02)
17:00.1 Ethernet controller: Intel Corporation Ethernet Controller XXV710 for 25GbE SFP28 (rev 02)
b5:00.0 Ethernet controller: Intel Corporation Ethernet Connection X722 for 10GbE SFP+ (rev 04)
b5:00.1 Ethernet controller: Intel Corporation Ethernet Connection X722 for 10GbE SFP+ (rev 04)
b5:00.2 Ethernet controller: Intel Corporation Ethernet Connection X722 for 10GbE SFP+ (rev 04)
b5:00.3 Ethernet controller: Intel Corporation Ethernet Connection X722 for 10GbE SFP+ (rev 04)
[root@localhost ~]# ethtool -i enp181s0f0
driver: i40e
version: 2.7.29
firmware-version: 4.10 0x80001a37 1.2154.0
expansion-rom-version:
bus-info: 0000:b5:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes
[root@localhost ~]#./t-rex-64 -i -c 13
Killing Scapy server... Scapy server is killed
Starting Scapy server.... Scapy server is started
The ports are bound/configured.
Starting  TRex v2.60 please wait  ...
	set driver name net_i40e
	driver capability  : TCP_UDP_OFFLOAD  TSO
	set dpdk queues mode to DROP_QUE_FILTER
	Number of ports found: 2
Error: In this TRex version, X710 firmware must be at least 05.00.04
Please refer to https://trex-tgn.cisco.com/trex/doc/trex_manual.html#_firmware_update_to_xl710_x710 for upgrade instructions

**Comment by hhaim** [comment]
Could you send the output of server run with “-v 7 “ added to the CLI

**Comment by selinaxue0** [comment]
[output with -v 7.txt](https://github.com/cisco-system-traffic-generator/trex-core/files/3500010/output.with.-v.7.txt)

**Comment by selinaxue0** [comment]
Added the CLI output with "-v 7" just now.
