### ISSUE TITLE
Garbage info in multiple ASTFProfile()

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#328]
Current Python API accumulate ASTFIPGen info when creating multiple profiles.
If we create large number of profiles, then, it'll create huge amount of garbage info in every RPC command.
User can call ASTFProfile.clear_cache() before creating new ASTFProfile().
But, it's usage is not the graceful approach.

We have 2 options,
Option#1. Let user use ASTFProfile.clear_cache() before creating new ASTFProfile() and update document about it.
Option#2. Change ASTFProfile API to clear_cache automatically

Do you have any opinion about these options?

Best Regards
Gwangmoon

**Comment by hhaim** [comment]
Maybe it is a better to use a LRU with limited size. there is a Python LRU library that we already using

**Comment by egwakim** [comment]
It's not possible to define the size of the cache because we cannot expect the buffer_list().
Instead, it's reasonable to clear inside load_profile() after convert to json because it'll be not used anymore. 
See line 475 below.
The only possible issue is that ASTFProfile() object usage after load_profile() call.
But, I cannot find such usage in current ASTFProfile().

`scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py

 449     @client_api('command', True)
 450     def load_profile(self, profile, tunables = {}, pid_input = DEFAULT_PROFILE_ID):
 451         """ Upload ASTF profile to server
 452 
 453             :parameters:
 454                 profile: string or ASTFProfile
 455                     Path to profile filename or profile object
 456 
 457                 tunables: dict
 458                     forward those key-value pairs to the profile file 
 459 
 460                 pid_input: string
 461                     Input profile ID
 462 
 463             :raises:
 464                 + :exc:`TRexError`
 465 
 466         """
 467 
 468         if not isinstance(profile, ASTFProfile):
 469             try:
 470                 profile = ASTFProfile.load(profile, **tunables)
 471             except Exception as e:
 472                 self.astf_profile_state.pop(pid_input, None)
 473                 raise TRexError('Could not load profile: %s' % e)
 474         profile_json = profile.to_json_str(pretty = False, sort_keys = True)
 **475 +       profile.clear_cache()**
 476 
 477         self.ctx.logger.pre_cmd('Loading traffic at acquired ports.')
 478         rc = self._upload_fragmented('profile_fragment', profile_json, pid_input = pid_input)
 `

**Comment by hhaim** [comment]
Agreed

**Comment by egwakim** [comment]
Hi,
We analyzed current structure.
The problem to make ASTFprofile object is that existing static/classmethod APIs and regression tests.
These APIs are already available in https://trex-tgn.cisco.com/trex/doc/cp_astf_docs/api/profile_code.html

classmethod load_py(python_file, **kwargs)
static load_json(json_file)
classmethod load(filename, **kwargs)

There is no suitable way to cover both "backward compatibility" and "isolated instantiation of ASTFProfile object"

Then, user need to aware of,
If user use load_profile(profile=object) with ASTFProfile objects, then, user need to explicitly  call profile.clear_cache() before creating ASTFProfile.
If user use load_profile(profile=filepath), then, no action required. load_profile() API calls profile.clear_cache() internally.

**Comment by hhaim** [comment]
We should fix this issue
