### ISSUE TITLE
ignore drop rate when `drop_rate < 0.1*total_tx`

### ISSUE THREAD

**Issue by RaminNietzsche** [cisco-system-traffic-generator/trex-core#332]
```c
if ( (drop_rate<0.0)  || (drop_rate < 0.1*total_tx ) )  {
        drop_rate=0.0;
}
```

why up to 10% drop in Rx bps considered a zero drop?

**Comment by hhaim** [comment]
See the forum for answer to this one

**Comment by RaminNietzsche** [comment]
I can't find answer to that ;)

https://groups.google.com/forum/#!searchin/trex-tgn/0.1*total_tx%7Csort:date/trex-tgn/Q7tO37il_Y4/Eg-BB6F9BAAJ

**Comment by hhaim** [comment]
read this thread
[STL] RX/TX/DroP bps counter
