### ISSUE TITLE
trex-console --tui does not update state properly during the state is updated by another client.

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#336]
Hi,
When I start and stop a profile by ASTFClient API, I found that `trex-console --tui` does not update the state change properly.
I found the reason is that the state update ignored by epoch value mismatch.
```
    def _on_astf_state_chg(self, ctx_state, error, epoch):
        if ctx_state < 0 or ctx_state >= len(astf_states):
            raise TRexError('Unhandled ASTF state: %s' % ctx_state)

        if epoch is None or epoch != self.epoch:
            return

        ....
```
Since ASTFClient.start and ASTFClient.stop block parameter's default values are True, _transmit_async will be used internally and it requests "inc_epoch" to server everytime.
Other clients that already synched by previous epoch value won't update the new state by the above code.

I'd like to know what is the purpose of the **epoch** value and how I handle this issue properly.

**Comment by hhaim** [comment]
There was an assumption that there is only one active profile. The epoch helps to identify that the **async** messages  match to the current active profile and only then it is safe to process it (else it is an old message)
If you change the epoc only when moving from zero profiles to 1 (CP) and not in each start it will solve the issue.

**Comment by hhaim** [comment]
@jsmoon I've discussed this with @ybrustin 
The objective of the epoch is to verify that the async events are valid and new and not relates to the past.  

There should be two types of epochs

1. per profile 
2. global - when moving from 0->1 profile need to inc it

**Comment by jsmoon** [comment]
@hhaim @ybrustin I understood the epoch value is used to figure out the received async event message is valid or not. But I'm still confusing how I could handle the value properly. So I have several questions from your comments.

1. At first, this issue is that the old connected client does not update the changed state by the async event messages **when the epoch value is changed**. What do you think of that? Should it be updated by the new one? or keep the old one?

2. How could I know the epoch value from an async event is not related to the past? I know that the client got the epoch value already by `sync` request when it began.
3. Who should have the responsibility for the epoch value handling? Currently, the server keeps the value but it is handled by the client's `inc_epoch` request.
4. `when moving from 0 -> 1 profile`: I'm not sure `0 -> 1` means. It could be the first profile loaded. It could be the first profile `start` request and more situation.
5. `per profile`: I cannot understand the reason why the `per profile` handling is needed. Could you explain it in detail?
If I understood correctly, the epoch value is used to keep the client's data consistency from the server. So, I cannot think the case that `per profile` value is needed.

**Comment by hhaim** [comment]
Have a discussion with @ybrustin 

There are two  channels of communication between the Client and CP. 

1. sync
2. async

There are two ways to sync the two channels 

1. barrier - a client API. After calling this API the async and sync chan are in sync
2. epoch - used only when starting a profile to make sure all the async event relates to the new profile.

if for any state change the client would call barrier there would be no need for the epoch as it seems that epoch just protect only for small aspect
The problem you have with **1** that the epoch is global and not per profile so old async messages that are valid for a profile A will be discarded. 

My suggestion is to remove the need of the epoch as barrier could be enough to sync the state.

so for your questions

1. because the epoch is global 
2. because there is an RPC to increment it by sync command
3. I think we can remove it and add barrier if needed 
4. no need
5. no need

**Comment by jsmoon** [comment]
Hi,

According to my investigation, the API **barrier** uses "publish_now", but it is for statistics and not for states.

So, I tried to change the epoch usage only.
I changed to update the global state and profiles state at the async events regardless of epoch value changes.
But, I've met the situation that **some async event burst messages (PUB->SUB) were lost** even when a monitoring client was busy(```./trex-console --tui```).

Do you know how to protect the event message lost?

**Comment by hhaim** [comment]
@jsmoon the barrier sync the sync (REQ/RES) and the (SUB/PUB) channels. There is no need to sync specific data. 

In regards to this
```some async event burst messages (PUB->SUB) were lost ```, "In theory this PUB/SUB channel does not have re transmission  not protected a slow subscriber  but it is unlikely with the rate we have.

Did you prove the message lost?( by writing to file in the server side and client side and compare them?)

How many profiles are we talking about?

**Comment by jsmoon** [comment]
I tested **4000** profiles **under issue #338 was solved by #342**.

Here is the reproduction step:
1. loaded 4000 profiles using by ASTFClient API.
2. started the loaded 4000 profiles in short time without blocking mode: ```c.start(block=False, duration=50, ...)```
3. During TRANSMITTING state, executed ```./trex-console --tui``` in one terminal and ```./trex-console -r``` in another terminal.
4. After duration passed, ```profiles``` should show all profiles are STATE_ASTF_LOADED but it won't.
If you execute ```./trex-console -r``` again, ```profiles``` will show the expected result.

Without ```./trex-console --tui```, the event message lost did not occur.

**Comment by hhaim** [comment]
@jsmoon you overloaded the SUB/PUB channel and it make sense that some messages will be lost
It was design for very low events rate (link down/up, one profile stop etc) . 
Need to look again into ZMQ to see if there is a reliable sub/pub. if not the sync of mulit-profile state should be move to polling

**Comment by hhaim** [comment]
I've looked into ZMQ, there is no way to have a reliable transport for SUB/PUB. Important events like profile change state can't be sent using this channel and should be move to the REQ/RES.  I would add a RPC (only for the none read-only client) for events. 
Important events would be added to a CP queue and the client would need to read those periodically (like every 100msec). This thread will be part of the Python Client and not TUI and would be protected by the same lock.

BTW I've played with TRex on MS Azure and this happen a lot when traffic rate is high without the multi-profile.  

Any better idea? 

SUB/PUB was a mistake

**Comment by jsmoon** [comment]
> I would add a RPC (only for the none read-only client) for events.

I think the ```"sync"``` RPC command can be used for this purpose.

> Important events would be added to a CP queue and the client would need to read those periodically (like every 100msec). This thread will be part of the Python Client and not TUI and would be protected by the same lock.

If I understood your idea correctly, I should add a new channel to deliver important event messages from the server(CP) to the client through the CP queue. Right?
In addition, I think this REQ/RES event channel needs to handle multiple clients.

> Any better idea?

1. 
Since the important event message is for update state change, I think the periodic request of ```"sync"``` RPC command in the client can solve this issue.
In addition, using a sequence number for the messages, I think the client can detect a message lost and trigger the sync up process.

2.
In general ways, we may tune the ZMQ socket options(HWM, BUF, ...) to endure the burst messages or move from PUB/SUB to pipe-line(PUSH/PULL) pattern.

P.S.
> BTW I've played with TRex on MS Azure and this happen a lot when traffic rate is high without the multi-profile.

What do you think of the reason? I think that the traffic rate will not drive the PUB/SUB channel overload.

**Comment by hhaim** [comment]
@jsmoon, I think you didn't understand. 
SUB/PUB was a mistake from the first place and complicated the code (sync API for example).
I'm suggesting to keep SUB/PUB for non important messages and keep all the reliable communication in the REQ/RES. 

**How**:

1. CP: All the important messages to the clients would be saved into a CP queue  and would **not** be sent in the SUB/PUB
2. Add a **new** RPC command to get the queue events  -- only the R/W client (single) will know the state. The read-only client will **not** support it and it will have the wrong information  
3. The new RPC will be called by client in another thread every 100msec to sync the events (only for R/W client)

this way the the R/W Client will poll for the important events instead of SUB/PUB

we will need to change the Java and Major version

**Comment by jsmoon** [comment]
@hhaim, I think the current ```"sync"``` RPC command can be enough for the global and profiles state updates. (i.e. the new RPC command is not needed.)

Since the current important messages to the clients are state update messages, the new RPC command will get the state update events only.
But, the server is keeping the lastest global and profiles state. There is no use of the queuing mechanism for this behavior (client gets states from the server).

All clients can REQUEST the ```"sync"``` RPC command and the server does REPLY the request with the latest global and profiles states.

**Comment by hhaim** [comment]
In your proposal the current client API won't work (get_events). 
The current client code has an assumption that the events mechanism is a reliable 
This test, for example won't work (with heavy drops of SUB/PUB) without fixing the ASYNC code as I proposed 
```def test_random_dynamic_add_remove (self):```

I've just talked with Yaroslav and he is proposing event better idea to keep an index per client this way keep all the clients (Read only and R/W) in sync. 
using this we would be able to remove the SUB/PUB completely

**Comment by jsmoon** [comment]
I meant that there is no need to get_events for the ASTF global and profiles state. ```"sync"``` RPC command can get the latest states from the server and any clients can use it for REQ/REP.
I thought about the removal of the usage of the PUB/SUB model for state change events.

If you said to general usage cases, I agree that the ZeroMQ SUB/PUB model is not reliable for that purpose. Also, I agree that a new reliable way is needed to get important events.

Anyway, I raised a pull request #347 by keeping the usage of the ASYNC events and ```"sync"``` RPC command.

**Comment by hhaim** [comment]
Ok, let's keep this issue until we will remove the SUB/PUB. The ``test_random_dynamic_add_remove``` won't work under heavy drop rate of SUB/PUB without fixing the issue
