### ISSUE TITLE
How to get correct xstats on "async" measurement

### ISSUE THREAD

**Issue by vrpolakatcisco** [cisco-system-traffic-generator/trex-core#341]
In FD.io CSIT project, we are using TRex as the traffic generator for performance tests. The main test driver (called Robot from now on, as it is a robotframework process) is started by Jenkins in a container, but TRex is running on a different physical box (called Testbed from now on). The interaction between Robot and Testbed consists of copying some scripts to Testbed and running bash commands on Testbed, initiated by SSH from Robot.

Let me first describe the "sync" measurement. Such a measurement is done by a single invocation of a Python script, and the Python script basically does:
1. client = STLClient()
2. client.connect()
3. Bunch of commands setting up the intended streams.
4. client.clear_stats()
5. client.start(...)
6. client.wait_on_traffic(...)
7. stats = client.get_stats()
8. Parse and print the measurement results.
9. client.disconnect()

The important feature is that Robot patiently waits for the SSH command to finish.
But in some new tests we want Robot to do something else while the traffic is on. Instead of putting the SSH command to background, and interacting with it when needed, we first tried to split the measurement logic to two scripts. The "start" script does steps 1-5 and then disconnects with stop_traffic=False. The "stop" script re-connects when Robot is done with those other things, and proceeds with steps 7-9.

At first, we discovered that client.connect() automatically performs an analogue of clear_stats(), but we also discovered there is also "xstats" that are not cleared on connect, so we used that.
But then we discovered xstats are tracking reference_stats on client side, and as the "stop" script is a different client, the results were as if "start" script did not clear the xstats (resulting in sum of all measurements).

Finally, we implemented a workaround. The stop start script does:
6. snapshot0 = client.ports[0].get_xstats().reference_stats
then serializes snapshot0. The serialized data is, stored on Robot side, then passed to stop script. The stop script deserializes snapshot0 object and does:
6. client.ports[0].get_xstats().reference_stats = snapshot0
(and the same also for ports[1]) and proceeding with step 7 analogue.

We realize that this last solution only works because Python does not really support information hiding, and it probably is not the recommended way to get correct results for "async" measurements.

So what is the correct way? Is there a way to store the "snapshots" on server? Is there an official API to serialize client state to restore later? Or are there good reasons to keep a single client (in a single long-lived, interactive script) for the duration of measurement?

**Comment by hhaim** [comment]
@vrpolakatcisco 
You should use the client API from your remote (Robot) directly and not **throw** ssh.

**Comment by vrpolakatcisco** [comment]
@hhaim Just to confirm: We should install trex_client on the Robot machine, and create a Python library for robotframework which creates a client object; still on Robot side, but pointing at the remote server by setting address and ports for [1]?

We will have to double-check the ports are accessible, but looks doable, thanks.
Will we need also async_port=4500? This [2] section only mentions 4501.

[1] https://github.com/cisco-system-traffic-generator/trex-core/blob/v2.61/scripts/automation/trex_control_plane/interactive/trex/stl/trex_stl_client.py#L77-L79
[2] https://trex-tgn.cisco.com/trex/doc/trex_rpc_server_spec.html#_transport_layer

**Comment by hhaim** [comment]
Correct. This is the right way to use it.

**Comment by MitchellMahan** [comment]
> @hhaim Just to confirm: We should install trex_client on the Robot machine, and create a Python library for robotframework which creates a client object; still on Robot side, but pointing at the remote server by setting address and ports for [1]?
> 
> We will have to double-check the ports are accessible, but looks doable, thanks.
> Will we need also async_port=4500? This [2] section only mentions 4501.
> 
> [1] https://github.com/cisco-system-traffic-generator/trex-core/blob/v2.61/scripts/automation/trex_control_plane/interactive/trex/stl/trex_stl_client.py#L77-L79
> [2] https://trex-tgn.cisco.com/trex/doc/trex_rpc_server_spec.html#_transport_layer

Have you created a RobotFramework library to interact with TREX? If so, I would be very interested in shamelessly reusing your work :)

**Comment by hhaim** [comment]
@MitchellMahan try asking CSIT guys for example @vrpolakatcisco. 
This is the project source code [csit](https://github.com/FDio/csit)
trex project just maintain the python client side library and not the framework

**Comment by vrpolakatcisco** [comment]
@MitchellMahan Kind of.
For license reasons (we specify traffic profiles using scapy, which brings in GPLv2, so we want that to stay in a process separate from most of CSIT Apache2.0 licensed code), there is now an additional layer [3] between TRex code and main CSIT code. Python scripts to be executed on the testbed. The Python library in the main Robot process that launches those scripts is this [4] mess. (I started a refactor a while ago, I could hurry it up if there is an interest.)

There was another issue with the step 6 "client.wait_on_traffic(...)" sometimes waiting way too long (when we want way more traffic than TRex workers are able to squeeze out due to CPU); so the current layer uses a "sleep + stop" approach instead, which has its own drawbacks.

Anyway, here is an example how the current code executes [5] in the "sync" mode, and for "async" mode here is an example of a separated start [6] and stop [7] using xstats serialization, as mentioned in the issue description.

[3] https://github.com/FDio/csit/tree/3a443e358985f9d90e0ce1a5e9295a28349f26de/GPL/tools/trex
[4] https://github.com/FDio/csit/blob/3a443e358985f9d90e0ce1a5e9295a28349f26de/resources/libraries/python/TrafficGenerator.py
[5] https://s3-logs.fd.io/vex-yul-rot-jenkins-1/csit-vpp-perf-verify-master-2n-skx/3635/log.html.gz#s1-s1-s1-s1-s1-t1-k2-k9-k7-k13-k1-k2
[6] https://s3-logs.fd.io/vex-yul-rot-jenkins-1/csit-vpp-perf-report-iterative-2110-2n-skx/109/log.html.gz#s1-s1-s1-s1-s1-s1-s2-t1-k2-k14-k10
[7] https://s3-logs.fd.io/vex-yul-rot-jenkins-1/csit-vpp-perf-report-iterative-2110-2n-skx/109/log.html.gz#s1-s1-s1-s1-s1-s1-s2-t1-k2-k18-k1

**Comment by MitchellMahan** [comment]
@vrpolakatcisco Any consideration to using the ZMQ transport instead of bash commands?

It looks a bit convoluted to work with but I'm thinking it may be preferable to bash/remote ssh commands.

**Comment by vrpolakatcisco** [comment]
(Not sure what is wrong with my github settings. Looking at it, I should have been notified about new comment, but I see no e-mail, not even in spam folder.)

I guess ZMQ would make the communication faster, but we do not have a pressing need for that right now. Our bash/ssh library also has good logging. Finally, I guess the way to specify traffic profile would be somewhat different over ZMQ (and we would have to re-investigate the license considerations).

Overall, while I think it is definitely possible, CSIT has no plans to migrate away from bash/ssh.
