### ISSUE TITLE
Precise min_latency value in STL mode

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#354]
In STL mode,
We can get max/average latency with flowlatency stats.
We also can assume min_latency via histogram.
But, assuming min_latency from histogram is not exact value,

Will it acceptable to add min_latency field in 'get_pgid_stats' command?
Some change needed in trex-server like max_latency and trex-console also need to display min_latency in 'stats -l' option.

**Comment by egwakim** [comment]
Hi @hhaim ,
It's needed in our side, if we add this feature in trex-core, will it acceptable in trex-core?
I want to get answer from you before start design.

Best Regards
Gwangmoon

**Comment by hhaim** [comment]
Sorry for the delay. Usually the important metric is the maximum.
The histogram has two implementation one has the exact minimums (the default does not). Anyhow I think it is better to add it - if you can contribute that it would be good

**Comment by egwakim** [comment]
Thanks for comment.
We also considered HDR option, but, in high delayed network environment, the resolution of histogram was too low. 
For example, if histogram shows 1000, 2000, ..., 10000, then, the worst case difference will be 1ms (2000 - 1000)
