### ISSUE TITLE
Specific ip pair support instead of ip range

### ISSUE THREAD

**Issue by zhongziyun1993** [cisco-system-traffic-generator/trex-core#356]
Wondering if TRex is able to support generate traffic between specific ip pair, for example, an src ip list and dst ip list, instead of using ip range and ip offset.

**Comment by hhaim** [comment]
It is possible.

**Comment by zhongziyun1993** [comment]
Hi, hhaim, sorry to disturb you, could you give me some lead about how to accomplish this? 
`        with open(src_file_path) as src_file, open(dst_file_path) as dst_file:
                for src_ip, dst_ip in zip(src_file, dst_file):
                        src_ip = src_ip.strip()
                        dst_ip = dst_ip.strip()
                        ip_gen = self.ip_gen(src_ip, dst_ip)
                        cnt += 1
                        caplist.append(ASTFCapInfo(file="../cap2/http_get.pcap", ip_gen=ip_gen, port=80+cnt))`

I append them in caplist, but the port numbers should be different every time, could please give me some advice? Thank you so much!

**Comment by hhaim** [comment]
The question wasn’t clear. My answer was for STL. For ASTF you can create many pools with minimum range of the number of threads and associate it with the same template.
You can test it using the simulator

**Comment by zhongziyun1993** [comment]
Thank you for your reply @hhaim ! Really appreciate it.
My question is:
I got two txt files, one store src ip address, one store dst ip address (probably about 1000 of them), they were paired by line number, in the code snippet I get src, dst ip addresses from these two files.

I need to generate traffic between these ip address pairs. 

In ASTF I can obviously see how to define a range of ip but in terms of specific ip pairs, I am confused about how to do it.

**Comment by hhaim** [comment]
See this example for 2 ranges. 
https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/astf/http_simple_different_ip_range.py
Expand it to 1000

**Comment by zhongziyun1993** [comment]
Hi, @hhaim In this example, every item in the cap list should have a unique port
```python
        profile = ASTFProfile(default_ip_gen=ip_gen1, cap_list=[
            ASTFCapInfo(file="../cap2/http_get.pcap"),
            ASTFCapInfo(file="../cap2/http_get.pcap", ip_gen=ip_gen2, **port=8080**)
            ])
```

I have 1000 ip pair for now, the port number would be enough, however, the max number ports in the server is 65535, what if I have over 65535 ip pair? 
Also, base on this example, I am not able to let all ip pairs generate traffic to the same port. 

If I let them generate traffic into one port, I would get error.

**Comment by hhaim** [comment]
@zhongziyun1993 you are right, this is a limitation right now that each template (*even if it is the same*) should have a different port. Please open a different issue on that, this might be easier to solve

**Comment by zhongziyun1993** [comment]
hi @hhaim, sorry for the delay, I would definitely raise an issue and include details.

But even if TRex could support `different template uses the same port` feature, let's say if I have about 100k ip pairs (not in a continues range), if I generate 100k templates for these 100k ip pairs, the generation speed would be extremely slow (I guess just generation of the profile would already took a long time).

Do you have some suggestions? Please correct me if I am wrong, I am really new to TRex.

**Comment by hhaim** [comment]
@zhongziyun1993 we have optimization when building the profile to json and we compress it. (there would be one template). The traffic generation is not influenced by the number of templates . However the DRAM to include all the different will influence the performance (L1$/L2$ -> DRAM) and I think for that there is a need to make a specific feature in the tuple generator which will simplify it.

Do you want to load the list of 100k tuples (src,dst)? we have something similar in STL mode but not in ASTF? if yes please open another feature request for this.

**Comment by zhongziyun1993** [comment]
Hi, @hhaim Is this the way you talking about in the previous discussion that that in STL? Like support multiple pair of ip traffic that using same template and the same port? Thank you.
https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/stl/tests/many_streams.py

PS: I just submit a feature request for load large number of tuples in ASTF mode

**Comment by hhaim** [comment]
This is a better option
https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/stl/udp_1pkt_simple_list_test.py

**Comment by zhongziyun1993** [comment]
@hhaim, in the example you just gave me(https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/stl/udp_1pkt_simple_list_test.py), the situation is like 'many src pair to one dst'; but in this example (https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/stl/tests/many_streams.py), the situation is like I could just define each pair.

Is there any major difference between these two examples?
Thank you for your help @hhaim, really appreciate it!
