### ISSUE TITLE
Unable to connect to Trex in v2.18

### ISSUE THREAD

**Issue by anuragsatish** [cisco-system-traffic-generator/trex-core#36]
When trex_client had been extracted and trying to connect to the trex chassis using python interpreter, facing an issue,

Trex client do not have 32bit folder libraries included in v2.18, trex_client/external_libs/pyzmq-14.5.0/python3/ucs4/32bit

>>> import trex_stl_lib
Unable to find required module library: 'pyzmq-14.5.0'
Please provide the correct path using TREX_STL_EXT_PATH variable
current path used: '/auto/cenbu/dev-test/ATS_python/regression/Iotssg/lib/trex_client_v2.18/external_libs/pyzmq-14.5.0/python3/ucs4/32bit'
[ATS_python] bgl-xdm-112:248>

**Comment by hhaim** [comment]
Duplicate - Defect is opened in youTrack
