### ISSUE TITLE
astf_tests.astf_resilience_test.ASTFResilience_Test.test_stress_start_stop fails

### ISSUE THREAD

**Issue by hhaim** [cisco-system-traffic-generator/trex-core#361]
@jsmoon yet another issue in ASTF
![image](https://user-images.githubusercontent.com/13034429/67659595-64394a00-f965-11e9-8b99-865b3dcf3a5b.png)

**Comment by jsmoon** [comment]
I think this issue is the same as the #360 ASTF issue.
I hope #362 might solve this issue also.

**Comment by hhaim** [comment]
@jsmoon I'm testing it, will let you know shortly

**Comment by hhaim** [comment]
duplicate #360
