### ISSUE TITLE
Question about ip_offset 

### ISSUE THREAD

**Issue by zhongziyun1993** [cisco-system-traffic-generator/trex-core#364]
Hi, I change ip_offset in `ASTFIPGenGlobal` method from `1.0.0.0` to `2.0.0.0` but nothing changed. The ip pair still like 16.0.0.1 to 48.0.0.1, 16.0.0.2 to 48.0.0.2.....

```python
        ip_gen_c = ASTFIPGenDist(ip_range=["16.0.0.0", "16.0.0.255"], distribution="seq")
        ip_gen_s = ASTFIPGenDist(ip_range=["48.0.0.0", "48.0.255.255"], distribution="seq")
        ip_gen = ASTFIPGen(glob=ASTFIPGenGlobal(ip_offset="1.0.0.0"),
                           dist_client=ip_gen_c,
                           dist_server=ip_gen_s)
```

And I didn't find a very detail introduction about `ip_offset` parameters. Could you give me some help with this? ie. what is this `ip_offset` parameter for?

**Comment by hhaim** [comment]
Have a look here https://trex-tgn.cisco.com/trex/doc/trex_manual.html#_clients_servers_ip_allocation_scheme
it is ```dual_port_mask```
