### ISSUE TITLE
problem to launch t-rex-64

### ISSUE THREAD

**Issue by VictorJ76** [cisco-system-traffic-generator/trex-core#37]
Hi, 

I installed TRex with the OVA Vm in my ESXi. I added 2 interfaces to my vm and configured them. I've done the `./dpdk_setup_ports.py -s` command and I see my interfaces in Active status. Finaly I launch t-rex-64 
with this command: `./t-rex-64 -f cap2/dns.yaml -c 4 -m 1 -d 10 -l 1000`
It returns me : 
```
mapping values are not allowed here
  in "/etc/trex_cfg.yaml", line 2, column 19
mapping values are not allowed here
  in "/etc/trex_cfg.yaml", line 2, column 19

```

My trex config file (/etc/trex_cfg.yaml) just below: 

```
<none>
- port_limit      : 2
  version         : 2
#List of interfaces. Change to suit your setup. Use ./dpdk_setup_ports.py -s to see


interfaces    : ["02:03.0", "02:05.0"]
port_info       :  # Port IPs. Change to suit your needs. In case of loopback, you can

         - ip         : 1.1.1.1
           default_gw : 2.2.2.2
         - ip         : 2.2.2.2
           default_gw : 1.1.1.1
```

Best regards 

Victor

**Comment by hhaim** [comment]
you YAML is not a valid YAML file 
better to run 

$ sudo ./dpdk_setup_ports.py -i

this script will create the best config file for you

**Comment by V5ctor** [comment]
Thank you for replying but when I launch sudo ./dpdk_setup_ports.py -i , it returns me : 
`dpdk_setup_ports.py: error: unrecognized arguments: -i`

I downloaded the OVA TRex. Do you have documentations well detailed , or tutorials ?

**Comment by V5ctor** [comment]
When I do : 
```
./dpdk_setup_ports.py -h
usage:  

Examples:
---------

To unbind the interfaces using the trex configuration file 
  dpdk_set_ports.py -l

To create a default file 
  dpdk_set_ports.py -c

To show status
  dpdk_set_ports.py -s

```

And I tried : 
```
To create a default file 
  dpdk_set_ports.py -c
```

But command `./dpdk_set_ports.py -c` it returns me command not found

**Comment by hhaim** [comment]
you are using very old version, 
update to v2.20

**Comment by V5ctor** [comment]
ok thank you :)
