### ISSUE TITLE
ASTF "server" does not answer to ARP requests

### ISSUE THREAD

**Issue by tbarbette** [cisco-system-traffic-generator/trex-core#370]
Hi all,

It seems TRex ASTF does not answer to ARP requests, but only sends some gratuitious requests according to the client cluster profile at the beginning of the session, is this an expected behavior?

The problem is that our Load Balancer ignores the gratuitous requests, maybe because they have different source and destinations for the same IP:
![image](https://user-images.githubusercontent.com/248961/68478943-65a22680-0231-11ea-86b6-c353b0bc898a.png)

So later, after the SYN arrives, the LB sends the following ARP request:
![image](https://user-images.githubusercontent.com/248961/68479010-97b38880-0231-11ea-8d25-915ad3e0b159.png)

But TRex never answers.

The load-balancer has a single client, and a single server to make it simple :
http_simple.py
```
...
        # ip generator
        ip_gen_c = ASTFIPGenDist(ip_range=["10.100.0.2", "10.100.0.2"], distribution="seq")
        ip_gen_s = ASTFIPGenDist(ip_range=["10.200.0.5", "10.200.0.5"], distribution="seq")
        ip_gen = ASTFIPGen(glob=ASTFIPGenGlobal(ip_offset="0.0.0.1"),
                           dist_client=ip_gen_c,
                           dist_server=ip_gen_s)

        return ASTFProfile(default_ip_gen=ip_gen,
                            cap_list=[ASTFCapInfo(file="../avl/delay_10_http_browsing_0.pcap",
                            cps=2.776)])
...
```

cc_http_simple.yaml
```
vlan: false

groups:

-    ip_start  : 10.100.0.2
     ip_end    : 10.100.0.2
     initiator :
         src_ip   : 10.100.0.2
         next_hop : 10.100.0.1
     responder :
         src_ip : 10.200.0.5
         next_hop : 10.200.0.1
     count     : 1
```

The LB has the "10.100.0.1" IP on the "client" interface and "10.200.0.1" IP on the server interface.

Even if I forced the gratuitous requests to be taken in, I'm still not sure how to configure the cluster as any of the servers after the load balancer may answer to any of the clients. Shall I repeat the groups to simulate all possible responder "src_ips"? I read the thread at https://groups.google.com/forum/#!topic/trex-tgn/IfoWEF3vCbI but it is still unclear to me.

Maybe there is a way to force any port to respond to any ARP requests as itself? It would solve all my problems at once.

Thanks,
Tom

**Comment by hhaim** [comment]
Hi Tom,
By default for ASTF mode TRex behaves as a next hop and it has one IP defined.
This means the all the Profile pool (clients and servers) are sent with TRex src/dst MAC. 
For this to work you should configure static route in your DUT.

To make TRex answer ARP use Linux name space feature.

If you have a requirement to simulate clients on the same subnet with different MAC for each client/server you should do this:

1. Create Linux namespace nodes with the right MAC:IPv4:IPv6 for both clients/servers
2. Create topo/pool that match the node

**Comment by hhaim** [comment]
see for how to add namespace https://trex-tgn.cisco.com/trex/doc/trex_stateless.html#_linux_network_namespace

**Comment by tbarbette** [comment]
Ok, thanks ! It seems a little bit complex for my use. I'll add static ARP in my DUT. However if you have a feature list, it would be nice to simply have multiple IPs per ports, or a simple "catch all" for ARP responder.
