### ISSUE TITLE
Too big minimum lower limit of CPS

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#378]
Hi,
Current defined lower limit of CPS is 0.5(Call profile per 2 seconds).
But, sometimes user need to test long aging 24 hour test with long running profile.
In this case, it's too big lower limit.
Reasonable limit would be 1 hour(0.000278).
How about changing this value to 0.0001(minimum 1 call per 10000 seconds)?

scripts/astf_schema.json
115 
116                         "cps": {
117                              "type" : "number",
118                              "minimum" : 0.5
119                          },

**Comment by hhaim** [comment]
First aging is not related to CPS it related to the inter packet gap which could be very high (24 hours) 
CPS has a lower limit due to a reason.
The core scheduler is responsible for CPS and the maximum time could not be high (in flow timer it could be )

**Comment by egwakim** [comment]
Hi,
It's about ASTF mode.
There is no IPG in ASTF mode.

**Comment by egwakim** [comment]
Here is example problematic scenarios,
If we have single profile which takes 3 seconds to run and want to continuously run for 1 hours
If we set to
CPS=0.5
Duration=3600(1 hour)
limit=-1(Unlimited)

Profile will be called 1800 times during 3600 seconds, but, it'll be overlapped during run time.
Time 0     1     2    3   4   5    6
         --------------> (flow0)
                       ------------------> (flow1)
                                  --------------------> (flow2)

Because we do not have upper limit of maximum concurrent flow, flow will be overlapped.
Simple option is setting lower cps than flow running time, but, it's limited to 0.5.
Another solution will be adding 'upper limit' of maximum concurrent flows per template.

**Comment by hhaim** [comment]
Not sure I follow. The aging is per flow.
You can create limited number of flows with IPG of 12 hours (each flow will send a new packet every 12 hours)

**Comment by egwakim** [comment]
Hi,
In my understanding there is no IPG in ASTF mode.
IPG is only available in STL mode.

Is there any way to set IPG in ASTF mode?

**Comment by hhaim** [comment]
There is. UDP and TCP has an application timer instructions (delay) for this purpose

**Comment by egwakim** [comment]
We have been used delay() command.
But, problem is that we do not know the bandwidth of the network path.
If we sending traffic from client to server with best effort, timing will be differ by each network path.
In this case, value in delay(value) need to be adaptive by network path environment.

**Comment by hhaim** [comment]
Delay instruction is accurate in application layer. I still don’t understand what do you want to achieve, could you give simple example?

**Comment by egwakim** [comment]
Wanted traffic is
Continuous running TCP traffic with best effort in long-term in certain duration time.
|------------------------traffic------------------------|(24 hours)
Huge loop count with setvar() and "-nc 1" option can be used in this case, but, it caused mismatch in Tx/Rx counters because it close connection forcely.
As a workaround, we can use shorter traffic with cps option if it's not overlaps. But, lower limit is too big.
|---traffic---|  |---traffic---|  |---traffic---|  |---traffic---|  

Of course, we can also use double loop with jmp_nz with delay, but, it's cannot make exact duration time.
outer_loop:
inner_loop:
best effort transfer
jmp_nz
delay(delay_by_estimated_duration_time)
jmp_nz

Currently, I just calling "whole profile python code(from connect to disconnect to trex server)" multiple times from outside.
But, removing CPS limitation will be beneficial to users to solve the issue easily.

**Comment by hhaim** [comment]
Understood. So you want to generate eFlow but with constraint of duration instead of  bytes.
You can add a new instruction for that (read the ticks_sec to a variable)

**Comment by egwakim** [comment]
Yes,
That would be better option.
We'll consider that variable.

Thanks
