### ISSUE TITLE
How to set multiple RX threads in astf mode?

### ISSUE THREAD

**Issue by kogdenko** [cisco-system-traffic-generator/trex-core#391]
Hello!
I tried to configure t-rex to benchmark http server application
With two cores (-c 2) I've got 570kcps (rx: 1.7m, tx: 1.7m) with my simple pcap file
but with 3 cores it is only 340 kcps - I pretty sure that it is bounded to RX thread.
How can I explicitly set rx and dp cores - for example I want to set that cores 0,1 would be RX cores and 2,3 wold be DP cores.
In code I found that CPlatformSocketInfoConfig have variable m_rx_thread - and it seem to me that we can have only one RX core - Is it right?

**Comment by ybrustin** [comment]
DPs are doing RX in ASTF mode

**Comment by kogdenko** [comment]
In my case rte_eth_rx_burst() called only from rte_locre_id() == 4 - may be I doing something wrong?
I run t-rex from shell:
./t-rex-64 --astf -f astf/nginx_wget.py -c 3 -m 60000 -d 10 -v 6

**Comment by kogdenko** [comment]
nginx_wget.py
``` python
from trex.astf.api import *


class Prof1():
    def get_profile(self, **kwargs):
        # ip generator
        ip_gen_c = ASTFIPGenDist(ip_range = ["1.1.1.1", "1.1.1.254"], distribution="seq")
        ip_gen_s = ASTFIPGenDist(ip_range = ["1.1.2.1", "1.1.2.3"], distribution="seq")
        ip_gen = ASTFIPGen(glob = ASTFIPGenGlobal(ip_offset="1.0.0.0"),
                           dist_client = ip_gen_c,
                           dist_server = ip_gen_s)

        return ASTFProfile(default_ip_gen = ip_gen,
                            cap_list = [ASTFCapInfo(file = 'nginx-helloworld.pcap',
                            cps = 10)])


def register():
    return Prof1()

```

**Comment by kogdenko** [comment]
removed cps = 10
and run t-rex 
```bash
./t-rex-64 --astf -f astf/nginx_wget.py -c 3 -m 600000 -d 10 -v 6
```
I ve got 600k cps
