### ISSUE TITLE
Issues in stream statistics (ibytes and Rx bps) when UDP traffic generated and received with i40e network interface driver.

### ISSUE THREAD

**Issue by gourdebnath1510** [cisco-system-traffic-generator/trex-core#398]
I am using two i40e network interface one for generation and another for reception. I am generating normal UDP traffic, there has no problem in tx stats but in rx states (shows using stats -s in trex-console) it shows N/A in ibytes and 0bps in Rx bps metric as follows.

trex>stats -s
Streams Statistics
  PG ID    |         1
-----------+------------------
Tx pps     |          9.84 pps
Tx bps L2  |        19.37 Kbps
Tx bps L1  |        20.95 Kbps
---        |
Rx pps     |         11.59 pps
**Rx bps     |             0 bps**
----       |
opackets   |              1709
ipackets   |              1709
obytes     |            420414
**ibytes     |               N/A**
-----      |
opackets   |        1.71 Kpkts
ipackets   |        1.71 Kpkts
obytes     |         420.41 KB
**ibytes     |               N/A**

All the testing has been done with lates trex revision (v2.71)

**Comment by hhaim** [comment]
Read the manual
