### ISSUE TITLE
[Improvement idea] New set_time_var() command for graceful stop in ASTF

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#400]
It's already discussed in the another discussion topic.

In single session-ed long-term traffic testing, it's not easy to stop traffic gracefully.
NC + DURATION time option will make error counters.
If set_time_var() command supported, it's possible to stop traffic in graceful way.
Another possible usage is measuring exact throughput with this command.
Because set_time_var() will send traffic in exact time, we can calculate exact throughput by Rx bytes with input time.

Example) Run ftp for 1 hour and measure the throughput
prog_c.set_time_var("ftp_time",3600*1000)   # set ftp_time to 1 hour(3600 seconds)
prog_c.set_label("ftp_loop:")
prog_c.recv(buf)
prog_c.jmp_nz("ftp_time","ftp_loop:")       # jump until ftp_time is zero

/* Average throughput = (Rx_Bytes*8)/3600 bps */

**Comment by hhaim** [comment]
@egwakim we have implemented the duration instruction 
It is something like this  

```
prog_c.capture_time_var("ftp_time") #read the timer into ftp_time
prog_c.set_label("ftp_loop:")
prog_c.recv(buf)
prog_c.jmp_de("ftp_time","ftp_loop:",10.5)  #jump in case the duration is smaller than 10.5 sec 
```

**Comment by egwakim** [comment]
That's good, thanks.

**Comment by elados93** [comment]
as Hanoch said, we implemented and tested it. We encountered some errors:

-  **_send_time = 10, recv_time = 5_**
client finished receiving data while server is still transmitting, client sent FIN to server and both flows are done, but some packets still arrived caused **tcps_rcvafterclose** error.

-  _**_send_time = 5, recv_time = 10_**_
server is stop transmitting while client's still receiving data, the server stopped but client's flow is still running caused accumulating **keepalive errors** while client's flow is running waiting for reply.

**Comment by egwakim** [comment]
Using different time in client/server can be considered as wrong usage.
Does it generate errors when you used same send_time and recv_time?

**Comment by elados93** [comment]
I agree, no errors seen using the same value for send & recv time, but I'm still testing it

**Comment by hhaim** [comment]
There is no such thing as “same״ time ..
It will always be different, better to not have the keepalive issue

**Comment by egwakim** [comment]
Yes,
But, we can explicitly close it from sender side.
See suggested usage below. 

duration = 20
alpha = 0.5  # adjust timer difference, sender() need to have more time

prog_c.connect()
prog_c.capture_time_var("cli_ftp_time") #read the timer into ftp_time
prog_c.set_label("cli_ftp_loop:")
prog_c.recv(len(buf))
prog_c.jmp_de("cli_ftp_time","cli_ftp_loop:",duration)  #jump in case the duration is smaller than duration sec 
prog_c.reset()

prog_s.accept()
prog_s.capture_time_var("srv_ftp_time") #read the timer into ftp_time
prog_s.set_label("srv_ftp_loop:")
prog_s.send(buf)
prog_s.jmp_de("srv_ftp_time","srv_ftp_loop:",duration+alpha)  #jump in case the duration is smaller than duration sec
prog_s.reset()

**Comment by hhaim** [comment]
@egwakim correct. Either way you will get 
```tcps_rcvafterclose``` or ```keepalive errors``` (per flow)

**Comment by egwakim** [comment]
@hhaim 
I tested similar scenarios(un-matched loop count by timing), but, could not found any errors.
See example below.

        prog_c.connect()
        prog_c.set_var("var1",loop+10);  /* run 10 more unmatched loops in recv side */
        prog_c.set_label("a:");
        prog_c.recv(len(ftp_data),True)
        prog_c.jmp_nz("var1","a:")
        prog_c.reset()   
     
        prog_s = ASTFProgram()
        prog_s.accept()
        prog_s.set_var("var2",loop); 
        prog_s.set_label("b:");
        prog_s.send(ftp_data)
        prog_s.jmp_nz("var2","b:") 
        prog_s.reset() /* send explicit close to peer */

See result below.

                  TCP |                   |                   |                         
                      - |                   |                   |                         
       tcps_connattempt |                 1 |                 0 | connections initiated   
           tcps_accepts |                 0 |                 1 | connections accepted    
          tcps_connects |                 1 |                 1 | connections established 
            tcps_closed |                 1 |                 1 | conn. closed (includes drops) 
         tcps_segstimed |                 1 |             18002 | segs where we tried to get rtt 
        tcps_rttupdated |                 1 |             18002 | times we succeeded      
          tcps_sndtotal |            720002 |            720002 | total packets sent      
           tcps_sndpack |                 0 |            720000 | data packets sent       
           tcps_sndbyte |                 0 |        1048576000 | data bytes sent by application 
        tcps_sndbyte_ok |                 0 |        1048576000 | data bytes sent by tcp  
           tcps_sndctrl |                 1 |                 1 | control (SYN|FIN|RST) packets sent 
           tcps_sndacks |            720001 |                 1 | ack-only packets sent   
           tcps_rcvpack |            720000 |                 0 | packets received in sequence 
           tcps_rcvbyte |        1048576000 |                 0 | bytes received in sequence 
        tcps_rcvackpack |                 0 |            720001 | rcvd ack packets        
        tcps_rcvackbyte |                 0 |        1048576000 | tx bytes acked by rcvd acks  
     tcps_rcvackbyte_of |                 0 |                 1 | tx bytes acked by rcvd acks - overflow acked 
           tcps_preddat |            720000 |                 0 | times hdr predict ok for data pkts  
             tcps_drops |                 1 |                 1 | connections dropped     
           tcps_predack |                 0 |            719966 | times hdr predict ok for acks 
                      - |                   |                   |                         
                    UDP |                   |                   |                         
                      - |                   |                   |                         
                      - |                   |                   |                         
             Flow Table |                   |                   |                         
                      - |                   |                   |

**Comment by hhaim** [comment]
@egwakim understood. In this case you will have ```tcps_drops``` due to the explicit reset. This might be better than the errors counters. My point was that there is no way to sync the time betwean the client and the server.

**Comment by egwakim** [comment]
Yes, I agree. We cannot sync time.
Instead, we send explicit reset() from long running receiver side. And we can ignore tcps_drops because it's dropped by explicit reset().
