### ISSUE TITLE
[Improvement idea] New send_dummy(size) API to reduce JSON RPC and client overhead

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#401]
send(buf)/sendmsg(buf) API requires real allocated buffer with data payload.
It'll be sent over JSON RPC, but, it's overhead will be quite big when sending many types of traffic.
And memory allocation issue will happen in client side.

Most of case, payload itself is not meaningful in traffic generation.
Instead of sending allocated data payload, just send dummy size will be better in that case.

Example> 
/* Current usage */
buf = alloc(size)
send(buf)         # Send real payload

/* Suggested new additional API */
send_dummy(size)   # Send dummy data with specified size : Send size info over JSON RPC

How about adding this new API?

**Comment by hhaim** [comment]
Good idea

**Comment by egwakim** [comment]
Merged. Closing it.
