### ISSUE TITLE
[Improvement idea] New option to limit the maximum concurrent active flows

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#402]
Current ASTF template will be called by CPS ratio whatever DUT can process or not.
If user want to measure the performance of maximum processible number of traffic sessions of DUT, then, it's not possible in current TRex.
For example>
If single user(client) want to measure the possible number of vistited www pages in certain time period, next flow should be started immediately after previous flow closed by keeping concurrent active flows to one.
If TRex have new option to limit the maximum concurrent active flows, then, we can set this value to 1.

ASTFTemplate(temp_c,temp_s, cps=100, limit=1000, climit=1 )
cps = connection per seconds
limit = total number of active flows
(New)climit = maximum concurrent active flows, do not activate new flows if climit reached

/* number of processed(visited) www pages = number of open/closed connections in ASTF stats */

**Comment by hhaim** [comment]
@egwakim 
The common case is to increase the active flows not to limit it. 
Something similar to this:
https://trex-tgn.cisco.com/trex/doc/trex_appendix_active_flows.html
The way to do it is to change the duration of the flows dynamically using a feedback mechanism 

Do you want in this case to limit the active flow per template? per client? please explain

**Comment by egwakim** [comment]
It's quite different scenarios.
If we want to simulate one UE's behavior.
Single UE will continuously visit pages by sequential order with keeping single session(flow).
The measurement point is how many pages can be visited from single UE.

Number of UE's can be more.
If DUT's capacity is 1000 UEs, then, we need to test this scenarios with climit=1000.

I also thought of other options like dynamically increasing number of flows in client side, but, it's too heavy approach because we need to poll the status of flows.

**Comment by hhaim** [comment]
@egwakim so you want to limit to climit flows per **client**? 
This option **contradicts the CPS** value so the precentage of bandwidth won't be right (e.g. 30% web vs 70% video)

**Comment by egwakim** [comment]
Yes, need to limit concurrent flow to measure performance of specified number of users.
Like 'limit' in current options, 'climit' will limit CPS value.
It's usage will be measuring performance of best effort. Different types of traffic can be mixed with different profiles.
Similar option in STL is (ISG(inter stream gap) = 0) + 'next stream'.

I have been thought of another option to allowing connect()/reset() inside ASTFProgram,
But, it'll break current concept of ASTFProgram. 
Handling it by template level would be right direction.
prog_c.set_var("no_of_pages",100)
prog_c.set_label("visit_www:")
prog_c.connect()
prog_c.recv(www_page_size)
prog_c.reset()
prog_c.delay(ISG=0)
prog_c.jmp_nz("no_of_pages","visit_www:")

**Comment by egwakim** [comment]
Hi @hhaim , Do you have any idea to cover this usage?

**Comment by egwakim** [comment]
Hi @hhaim,
I tried dynamic algorithm which tune CPS by calculated throughput dynamically, but, it's too heavy in control path because it requires polling of statistics counter to calculate throughput and not exact approach when throughput of DUT is not static.

There seems no way to cover this scenarios except adding 'climit' feature.

**Comment by hhaim** [comment]
> Yes, need to limit concurrent flow to measure performance of specified number of users.
> Like 'limit' in current options, 'climit' will limit CPS value.
> It's usage will be measuring performance of best effort. Different types of traffic can be mixed with different profiles.
> Similar option in STL is (ISG(inter stream gap) = 0) + 'next stream'.
> 
> I have been thought of another option to allowing connect()/reset() inside ASTFProgram,
> But, it'll break current concept of ASTFProgram.
> Handling it by template level would be right direction.
> prog_c.set_var("no_of_pages",100)
> prog_c.set_label("visit_www:")
> prog_c.connect()
> prog_c.recv(www_page_size)
> prog_c.reset()
> prog_c.delay(ISG=0)
> prog_c.jmp_nz("no_of_pages","visit_www:")

If it answers your need, it is the simplest solution. The problem with this approach that you will need to tune the profile to support it (in case of an engine change any profile would be able to run in this mode). Another difference is that in this case there is **one** TCP flow for many transactions while what you wanted is one new TCP flow for **each** transaction

**Comment by egwakim** [comment]
Ok,
Then, will this approach(allowing connect()/reset() inside ASTFProgram) acceptable in trex?
Some change needed in trex-core to remove restrictions and proceed more commands after reset()

**Comment by egwakim** [comment]
Hi @hhaim 
Can you comment on it?

**Comment by hhaim** [comment]
@egwakim sorry for the delay. I’m OOO this week

**Comment by egwakim** [comment]
Thanks for notification,
Please comment it after return from vacation

Regarding "connect()/reset()" support inside ASTFProgram.
Possible issues are 
1) reset() will not close flow(it'll not backward compatible) 
2) number of client flow and server flow can be differ

Original option(climit option) seems better approach, expected issue is not the big issue because it'll be provided by additional option. It'll not break backward compatibility.
I think this option is more simpler option because we just need to 'do not' invoke template if 'climit' overflow situation.

What is your opinion about it?

**Comment by hhaim** [comment]
@egwakim looking into it again, I agree connect()/reset() for the same flow does not look appealing. 
Could you elaborate what do you want to do in case of "climit?" maybe in this case there would be a need to change the way we schedule a new flow (today we first choose a template then client, maybe in this case we should do the opposite this way keeping one flow per client)

**Comment by egwakim** [comment]
Hi @hhaim ,
My assumption of 'climit(concurrent limit of flow)' feature is that new template will be invoked by CPS rate by keeping legacy way, but, new template will not be invoked if current concurrent number of flows is bigger than 'climit' and 'climit != 0(unlimited, default)'.
For example> if we have climit=2(default=0, unlimited) and CPS=10, template runs 1 second.
<---template1---> (0.0s Invoked, concurrent flows=1)
    <---template2--->(0.1s invoked, concurrent flows=2)
       <--template3---> (0.2s not invoked, since climit==2)
                             ...
                           <--template3---> (0.9s not invoked, since climit==2)
                                <---template11> (1.0s, Invoked since template1 closed)

CPS can be selected by user necessity(Higher CPS will cause higher load with higher accuracy)
Default 'climit=0' will be unlimited which will be backward compatible with old usage.
The concept of climit is just maximum upper limit, not the keeping exact number of flows.

Estimated required changes are
1. new climit option in both client API and server
2. server : if climit is not 0, check current concurrent number of flows and do not invoke new template if overflows

Best Regards
Gwangmoon

**Comment by hhaim** [comment]
@egwakim understood. The ``climit`` idea is a simple change, however, it will not guarantee that each *client* has *one* flow, didn't you want that?

**Comment by egwakim** [comment]
Yes, it cannot guarantee 100%, but, some delay(Maximum 100ms if CPS is 10) would be acceptable, small delay would be much closer to real world's UE behavior.
If we need higher accuracy(smaller delay), then, we can set higher CPS.

**Comment by hhaim** [comment]
@egwakim ok then, I would document this feature as it might be useful to other things. 
One other side effect that the throughput would be lower and can't be predicted

**Comment by hasantskn** [comment]
I need to calculate the number of active flows on Trex. Can you help me with the calculation? Is there any formula or way for the calculation?

**Comment by bdollma** [comment]
Hi @hasantskn ,
There is a counter that specifies the number of active flows, so no need for you to calculate it. If you are wondering how we calculate it, or how you to instruct your profile to tend to a specific number, you can read #718.

**Comment by hasantskn** [comment]
Hi @bdollma,
I can calculate the number of the active flows of files with `.pcap` extension. But cannot calculate files with multiple `.pcap` extensions.  Do you have any suggestions for that?

**Comment by bdollma** [comment]
I am not sure I understand you questions @hasantskn. Can you please try and be specific on the details? 
Are you running multiple dynamic profiles where each profile loads a pcap file and you want to calculate the number of active flows across all the profiles?

**Comment by hasantskn** [comment]
![screenshout](https://user-images.githubusercontent.com/82116446/131968020-e5bb93ab-95f9-4c21-be52-eb778c26a340.PNG)
You can see in the picture what I meant. How can I calculate the active flows of this system?

**Comment by bdollma** [comment]
@hasantskn ,
Have you read this [doc](https://trex-tgn.cisco.com/trex/doc/trex_manual.html#_how_to_determine_the_packet_per_second_pps_and_bit_per_second_bps)?

**Comment by hasantskn** [comment]
@bdollma 
Yeah, I read but there's a big difference between calculation and result.

**Comment by hasantskn** [comment]
@bdollma ,
I need to calculate the exact number of active flows. Do you have any suggestions to calculate active flow. Not PPS. Just active flows.
