### ISSUE TITLE
setting bitrate in stateful

### ISSUE THREAD

**Issue by daratitus** [cisco-system-traffic-generator/trex-core#412]
Hi,

What's the difference between using the muliplier option (-m) and editing the cps (in yaml file) for changing bitrate, and what is the best way to use for changing bitrate If I want to generate a similar traffic to XNetwork generator ( 300 bytes UDP packets ) ?

PS : I edited the dns.yaml, and used 300 bytes UDP packets similar to the dns.pcap (one flow 2 pakets)

Thanks !

**Comment by hhaim** [comment]
Please use the mailer https://groups.google.com/forum/#!forum/trex-tgn for questions
