### ISSUE TITLE
trex requires 4 ports

### ISSUE THREAD

**Issue by prujan** [cisco-system-traffic-generator/trex-core#413]
Hi,
I want to use trex with 2 nics, my yaml configuration :
## Config file generated by dpdk_setup_ports.py ###

- version: 2
  interfaces: ['04:00.1', '04:00.2']
  port_bandwidth_gb: 40
  port_info:
      - dest_mac: 3c:fd:fe:a8:c9:72 # MAC OF LOOPBACK TO IT'S DUAL INTERFACE
        src_mac:  3c:fd:fe:a8:c9:71
      - dest_mac: 3c:fd:fe:a8:c9:71 # MAC OF LOOPBACK TO IT'S DUAL INTERFACE
        src_mac:  3c:fd:fe:a8:c9:72

  platform:
      master_thread_id: 0
      latency_thread_id: 1
      dual_if:
        - socket: 0
          threads: [2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46]

Howevr when i run 
./t-rex-64 -i --astf
ERROR: i40e interface 0000:04:00.3 is under Linux and will interfere with TRex interface 0000:04:00.2
See following link for more information: https://trex-tgn.cisco.com/youtrack/issue/trex-528
Unbind the interface from Linux with following command:
    sudo ./dpdk_nic_bind.py -u 0000:04:00.3

ERROR encountered while configuring TRex system
thanks in advance,
Michael

**Comment by hhaim** [comment]
This is not a bug

**Comment by aleheux-tc** [comment]
> This is not a bug

Then what is it?

**Comment by hhaim** [comment]
@aleheux-Tc I see that our old defect manager is down. Will explain the issue. There is a hardware issue that all the ports from the same NIC should be mapped to DPDK. 
try to unlink all the ports from the same NIC to DPDK and you won't see this issue
