### ISSUE TITLE
No way to set delayed ack to ack every N bytes

### ISSUE THREAD

**Issue by micgolde** [cisco-system-traffic-generator/trex-core#417]
Currently trex has implemented delayed ack with only a timer causing acks to be sent.

The RFC (5681) states that it SHOULD also send out an ack at least for every second full size segment:

"Specifically, an ACK SHOULD be generated for at least every second full-sized segment, and MUST be generated within 500 ms of the arrival of the first unacknowledged packet."

I'm trying to emulate a Spirent Avalanche test and it has a configuration setting to allow the user to delayed ack every N bytes.

**Comment by hhaim** [comment]
@micgolde , thanks for raising this issue.

**Comment by hhaim** [comment]
solved in 
https://github.com/cisco-system-traffic-generator/trex-core/commit/ea394b812dfe6069f60faaf40a5b2e59f42e361e

see ```no_delay_counter``` tunable. You can set it to 2

**Comment by micgolde** [comment]
This doesn't quite get to what I'm after.

The RFC has semi-ambiguous phrasing of "every second **full size** segment"

If you're counting just raw segments, it won't take this into account.

This is why I specified that the avalanche has a setting for every "N" bytes, which makes sure they're full segments.

The current issue I'm running into is at the end of my Avalanche test I'm replicating there is a segment, a 200OK, and then a FINACK, all of which are ACKed by the client's FIN ACK because the 200OK isn't a full size segment.

**Comment by hhaim** [comment]
@micgolde good point. We could change the tunable to N bytes instead of segments (which is not always full)
Will it help?

**Comment by micgolde** [comment]
Yes, that is exactly what I'm after.  Thanks!
