### ISSUE TITLE
Create vagrant box

### ISSUE THREAD

**Issue by itsuugo** [cisco-system-traffic-generator/trex-core#42]
Currently there is an ova with trex that is great to explore the tool, also it would be awesome to have a vagrant box so you can use the image to setup different scenarios and tests the scripts before use them in production.

I can help in the automation process of the image creation and publishing in atlas

**Comment by hhaim** [comment]
This would be great. 
I suggest to update the Tutorial doc for how to use this.
https://github.com/cisco-system-traffic-generator/trex-core/blob/master/doc/trex_vm_manual.asciidoc
another option is to write blog on this here

https://communities.cisco.com/community/developer/trex/blog

for how to use it

**Comment by itsuugo** [comment]
I can explain the process to create the vagrant box and how to use it, will work on that.

My point in this issue is to publish the box, the same way you are doing with the OVA VM, but don't know if this is an internal process.

**Comment by itsuugo** [comment]
Didn't know you were using youtrack instead github, anyway your answer is fine with me

**Comment by imehrdad2012** [comment]
Does anyone know where I can grab the vagrant box of trex-core?

**Comment by imarom** [comment]
I don't think nothing was eventually added on the vagrant box side.

But we have a docker init file you can use to setup TRex development environment.
