### ISSUE TITLE
Trex package download link is broken

### ISSUE THREAD

**Issue by asimbutt77** [cisco-system-traffic-generator/trex-core#420]
I am trying to download the latest trex package with trex-client at the following link:

http://trex-tgn.cisco.com/trex/release/latest

However the link is broken for some time now.

**Comment by rm631** [comment]
You need to use HTTPS instead: https://trex-tgn.cisco.com/trex/release/latest 
A number of the links in the TRex docs appear to still be HTTP links that don't work, another notable one is the TRex VM download link.

**Comment by asimbutt77** [comment]
Thanks for the information
