### ISSUE TITLE
ASTF Keepalive limit seems artificially low

### ISSUE THREAD

**Issue by micgolde** [cisco-system-traffic-generator/trex-core#425]
The tcp.keepinit setting has a max of 253 seconds and a default of 10 seconds.  This seems very low for a value that in the RFC states "MUST default to no less than two hours."

**Comment by hhaim** [comment]
@micgolde TRex objetive is stress tests. Keep in mind that 2 hours, with rates of 1MCPS will get you very fast to the limit of the flows (~50Mactive flows). This was the reason for reducing this by default

**Comment by hhaim** [comment]
Looking into the code, I've converted the timer to be uint8 instead of an int to save memory (as 255 sec is infinit in case of stress tests)
```
struct tcpcb {

    tcp_socket m_socket; 

    /* ====== size 8 bytes  */

    uint8_t t_timer[TCPT_NTIMERS];  /* tcp timers */
```

It would be easy to convert it to uint16 (more 5 bytes to the flow, but it is not too bad)

**Comment by micgolde** [comment]
> @micgolde TRex objetive is stress tests. Keep in mind that 2 hours, with rates of 1MCPS will get you very fast to the limit of the flows (~50Mactive flows). This was the reason for reducing this by default

There are many ways to stress a box.  I'm trying to clone a test I have that opens connections and doesn't close them to stress and test the connection table limits of a DUT.  When I have millions of connections open sending keep-alives every 10 seconds for all those connections is going to cause significant traffic load on the box, which isn't what I'm trying to test.

additionally it appears the timer doesn't quite line up to what's actually happening.  I'm attaching 2 pcaps, one of which has the variable over the limit (which I assume defaults to 10) and one maxed out at 253.

The pcap with the invalid setting keep alives approximately every 5.5 seconds and the one set to 253 is every 152 seconds.

[keepalive_pcaps.zip](https://github.com/cisco-system-traffic-generator/trex-core/files/4154378/keepalive_pcaps.zip)

**Comment by micgolde** [comment]
> It would be easy to convert it to uint16 (more 5 bytes to the flow, but it is not too bad)

That would be awesome.

**Comment by hhaim** [comment]
We are working on both issues

**Comment by hhaim** [comment]
solved in https://github.com/cisco-system-traffic-generator/trex-core/commit/ea394b812dfe6069f60faaf40a5b2e59f42e361e
