### ISSUE TITLE
Support bigger pcaps

### ISSUE THREAD

**Issue by norg** [cisco-system-traffic-generator/trex-core#427]
Hi,

I'm trying to improve the traffic mix with some bigger pcaps. While I enabled hugepages and increased the memory settings in trex I even fail with pcaps that are just ~100mb and include a single flow.

I ran into this:

```
 -- loading cap file flowpcaps/1048460437579819.pcap 
assert: ../../src/bp_sim.h:1456 void CPacketDescriptorPerDir::SetPktNum(uint32_t) Assertion 'pkt_id<65000' failed.
```

And I see that in the code as well. So seems valid. But what is the reason for that limit?

If necessary I can provide those pcaps as I generated them from publicly available pcaps and just extracted single flows that I would like to add to my trex traffic mix.

**Comment by hhaim** [comment]
I would try the ASTF.

**Comment by norg** [comment]
So something like you describe in **http_eflow.py** is necessary in ASTF? I can't just have the same .yaml I'm using in STF mode with one bigger pcap run in ASTF?

**Comment by hhaim** [comment]
@norg loading huge pcap into memory is a challenge as the shared memory betwean the NIC and application is limited. A better way is to look into ASTF model and load only the first chunk of each template and create a loop (similar to  http_eflow.py )
The STL YAML model is a bit different than ASTF.  Have a look into the ASTF manual.

**Comment by norg** [comment]
I see how it works with the http_eflow.py example but this means in the end we can only simulate looped elephant flows but no realistic ones like a huge 4GB .iso download over http?

**Comment by hhaim** [comment]
Is all the 4GB are examined by the DUT in case of 4GB download? or only the start of the flow?

**Comment by norg** [comment]
The theory is that it should only look into the first parts, but we see issues with the DUT that it doesn't seem to shunt the flow. This is the reason why we want to add realistic elephant flows (at least TCP) to have the most realistic scenario to debug this issue as we currently see that the whole flow is examined.

**Comment by hhaim** [comment]
@norg I agree that simulation of eFlow is important but with ASTF you could load the first chunk  and then create a infinite loop on **another** chunk, this could be close enough in some cases. 
Another alternative is to enlarge the mbufs,  4GB should work but it is not infinite
https://trex-tgn.cisco.com/trex/doc/trex_manual.html#_memory_section_configuration

**Comment by norg** [comment]
I could try this at least yes.

I increased the mbufs and even made sure the system provides hugepages. But that's another issue I did report here https://groups.google.com/forum/#!topic/trex-tgn/mzlM3vHJwBg

**Comment by hhaim** [comment]
You should try with ASTF
