### ISSUE TITLE
Multi-port TCP profile

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#429]
Multi-port TCP profile

Feature description:
Ability to choose a profile by the l7 data provided by the TCP layer.

Suggestion:

move (reass_enabled) to true in case the flow has more than one port.

assign a EMU layer program with a new instruction that will get the mbuf and choose by the data the right template

after choosing the right template change the
3.1 reass_enabled=false
3.2 reassign the right EMU layer
3.3 update the layer with the number of bytes received from TCP to make it consistent

In this PR there should not be ANY new malloc/free in application layer. TCP provide the data as mbuf with size, you can use it.
There is only corner case that TCP will provide byte by byte and we can either have in EMU layer a constant buffer of 8 bytes or not supporting this. 

Related PR :
https://github.com/cisco-system-traffic-generator/trex-core/pull/423

Related Issues :
https://github.com/cisco-system-traffic-generator/trex-core/issues/381

**Comment by egwakim** [comment]
Hi @hhaim ,
Before implementation, we have several important design options to clarify.
Can you comment your opinion about the design options?

1. New recvcmp() instruction or re-using l7_map() API
l7_map() can map payload contents with mask and it's already merged into UDP case.
But, suggested recvcmp() have an issue when mapped payload is not located at the beginning of the payload. 
User may call recvcmp() after recv() call, it requires too complex handling logic in trex server side.
I cannot see any reason to use recvcmp() instead of l7_map() API.
Can you confirm it whether recvcmp() is needed or not?

2. Support of dynamic Enable/Disable of l7_map()
Do we need to support dynamic on/off of l7_map?
If we support it, It'll make tcpcb::m_reass_disabled dynamically at run-time.
I assume that it's not needed in general.

3. Support of smaller payload transmission for l7_map()
It's quite corner situation, 
If user send smaller packet which will not contain payload in the single packet.
It's waste of efforts to support such case.
Do we need to support such corner case?

Best Regards
Gwangmoon

**Comment by hhaim** [comment]
@egwakim very good summary. Let me refine it. 

1.  flow table (the same place you did the UDP)

```
if flow_table.lookup (SYN) != nil {
    // if the dstport has more than one possible template 
   if ( more_than_one_port_map[pkt.dst_port]  == true ) {

      flow.m_reass_disabled = true // disable reassembly to get all the data in order 
      flow.EMU = a_program_with_a_one_instruction_recvcmp_choose_template()
    }
}

```

2. EMU layer

This layer will get the data **in order** 99.99% with enough contiguous memory. 
If this is not the case, I would skip the packet and RST the flow for now 

```
// new instruction 
emu::recvcmp_choose_template( m *mbuf){

  char * p =rte_pktmbuf_mtod(m, char *)   
  chunk_size = rte_pktmbuf_data_len(m);  
  pkt_len = rte_pktmbuf_pkt_len(m)
  new_template=l7_map(p, chunk_size)
  if  !new_template {
      inc_counter()
     RST_FLOW
  }else{
  defer_set_new_template(new_template,pkt_len)  // this will save the this information into the EMU 
        object to the set the right template after this instruction finished 
  }
}

// run in the cotext outside of EMU object 
defer_set_new_template() {
  if flow.defer_cmd {
    flow.replace(template)
    flow.sappend(saved_pkt_bytes)
     flow.m_reass_disabled  = false   <<<<<<< important 
  }
}
```
So my suggestion is similar to (1)

(2) ```m_reass_disabled``` should be back to ```false``` after ```recvcmp_choose_template```
(3) There is no need to support it right now. it very not likly to happen. the DUT should have a MSS of 1 to get to this situation. It is possible to solve this but let's have one step at a time. 

NOTE: it is possible to do the same for UDP. but let's start with TCP

**Comment by egwakim** [comment]
(1) Ok, then, does it means only l7_map() will be exposed into end user API?
recvcmp() is one of internal implementation approach, right?

(2) Yes, m_reass_disabled need to be back to false.

(3) Yes.

(4) I have additional item to clarify,
When sharing same port, do we need to support mixed mode (non-l7_map and l7_map)?
I assume that it need to be supported.

**Comment by hhaim** [comment]
@egwakim 
(1) Good point. It should not be exported to the user. Only server can use it (JSON won't build it the database)
Another approach that might be simpler is to make a function in EMU class that should call associate_template_by_l7 in case it wasn't already set without an explicit instruction 

(4) What is non-l7_map? I had in mind that you have only l7_map in case of multi-port

**Comment by egwakim** [comment]
@hhaim 
(4) Non-l7_map means existing usage without using l7_map, at least one template can use same port without l7_map. It's kinds of l7_map without any rules.
In UDP case, it's already supported, I think it need to be supported in same way. What is your opinion?

(5) Where should we keep l7_map information?
 flow(flow->m_l7_map)? or EMU layer(flow->m_app.m_l7_map)?

**Comment by hhaim** [comment]
*Non-L7 should be supported as today. Only ports that have multi template should be defer to l7map

* no and no. The map is global per thread ctx. It is the same as today for UDP/TCP

**Comment by egwakim** [comment]
Close it. Further improvement will be done in different ticket.
