### ISSUE TITLE
T-rex starting issue

### ISSUE THREAD

**Issue by akaimethos** [cisco-system-traffic-generator/trex-core#43]
Hi there

I have done a new server instance for t-rex.
Installed Ubuntu 16.04 Server 64bit and CentOS 7.2 Minimal 64bit for t-rex for testing.
After the NIC bind script build successfully the configuration I tried to start t-rex. I get follwing errors on both operating systems:

[root@rcd-tlg-01 scripts]# ./t-rex-64 -c
./t-rex-64: line 47: ./_t-rex-64: No such file or directory
[root@rcd-tlg-01 scripts]# ./t-rex-64
./t-rex-64: line 47: ./_t-rex-64: No such file or directory
[root@rcd-tlg-01 scripts]# ./t-rex-64 -i
Killing Scapy server... Scapy server is killed
Starting Scapy server.... Scapy server is started
./t-rex-64: line 47: ./_t-rex-64: No such file or directory

I'm using version v2.22 of t-rex. Are there any linux packages to install for t-rex?

Cheers

Akai

**Comment by hhaim** [comment]
It seems you didn't build it.
Could you send the output of the build?

**Comment by akaimethos** [comment]
Hi hhaim

You was right.  Zlib-devel was not installed on the machine. So build went wrong. After installing zlib-devel everything worked like a charm.
Thanks for the help. Great tool by the way!

Cheers

Akai
