### ISSUE TITLE
[Suggestion] Expand the minimum limit of CPS

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#434]
It's already discussed in different thread, https://github.com/cisco-system-traffic-generator/trex-core/issues/378
But, it's needed for different traffic scenarios.
To be able to simulate UDP ping,
We need to send and wait packets, but, packets can be lost or delayed.
To resolve this issue, tuning CPS would be better option to send packets in exact time period in spite of packet delay or lost.
But, the minimum CPS value is 0.5 which means that we can ping only 2 seconds or shorter time period.
It's big limitation.
scripts/astf_schema.json
115
116 "cps": {
117 "type" : "number",
118 "minimum" : 0.5
119 },

It's not possible to use set_tick_var() because packet can be delayed quite a lot and it'll be accumulated.
The reasonable approach would be tuning CPS with reasonable number.
Reasonable minimum CPS number would be lower than 0.5, 0.01(100 seconds) would be more reasonable.
Can we tune it for the better coverage?

Best Regards
Gwangmoon

**Comment by egwakim** [comment]
Hi @hhaim ,
Any opinion about it?

**Comment by hhaim** [comment]
There are two ways to solve it:

1. Total CPS for *all* templates is higher than 1 
2. Total CPS for all templates is lower than 1- more complex,
moving those templates (with very low CPS) to the timer-wheel.

We wanted to be in the safe side so we added this limit per template. If in your use case the total CPS is higher than 1 I don’t see an issue to remove the 0.5 limit and keep a less restrictive limit (total)
