### ISSUE TITLE
No way to force server to close connection.

### ISSUE THREAD

**Issue by micgolde** [cisco-system-traffic-generator/trex-core#435]
I don't see a way to force the server to close the connection.  Only a "reset()" option.

I've added wait_for_peer_close() on the client side, but it takes 4 seconds for the connection to time out before the server closes the connection

When I run without "wait_for_peer_close()" even with a small delay on the client, the client still closes the connection.

PCAP of a delay on the client side, no "wait_for_peer_close()":
[TR1024B_SingleConnection_DAfix.zip](https://github.com/cisco-system-traffic-generator/trex-core/files/4220757/TR1024B_SingleConnection_DAfix.zip)

test profile:
    prog_c = trex.astf.trex_astf_profile.ASTFProgram()
    prog_c.connect();
    prog_c.send(http_req)
    prog_c.recv(len(http_total_response))
    prog_c.wait_for_peer_close()

    prog_s = trex.astf.trex_astf_profile.ASTFProgram()
    prog_s.recv(len(http_req))
    prog_s.send(http_total_response)

    info = trex.astf.trex_astf_profile.ASTFGlobalInfo()
    info.tcp.mss = 1460
    info.tcp.rxbufsize = 32768
    info.tcp.txbufsize = 32768
    info.tcp.initwnd = 1
    info.tcp.delay_ack_msec = 200
    info.tcp.no_delay_counter = 2
    info.tcp.do_rfc1323 = 0

**Comment by hhaim** [comment]
The “reset()” is the way to go.
The “wait_for_peer_close()” should be in client side not in the server side for this type of program.

**Comment by micgolde** [comment]
But I don't want to reset... that changes the behavior of my DUT...

**Comment by hhaim** [comment]
@micgolde ok, I see the issue, actually this is a bug not a feature. In some cases (with smaller buffers size) it works. It might be related to #436. Looking into it
