### ISSUE TITLE
Error parsing file test.yaml as YAML(generated by" ./dpdk_setup_ports.py -c 44:00.0 44:00.1 -o test.yaml ")

### ISSUE THREAD

**Issue by guiping-duan** [cisco-system-traffic-generator/trex-core#453]
i have download the latest trex-core code and build without error. and then generate a config yaml file, but when error happened when run ./t-rex-64 -f test.yaml.
[root@dell scripts]# ./dpdk_setup_ports.py -c 44:00.0 44:00.1 -o test.yaml 
Saved to test.yaml.

[root@dell scripts]# vim test.yaml 
### Config file generated by dpdk_setup_ports.py ###

- version: 2
  interfaces: ['44:00.0', '44:00.1']
  port_info:
      - ip: 1.1.1.1
        default_gw: 2.2.2.2
      - ip: 2.2.2.2
        default_gw: 1.1.1.1

  platform:
      master_thread_id: 0
      latency_thread_id: 2
      dual_if:
        - socket: 1
          threads: [1,3,5,7,9,11,13,15]

[root@dell scripts]# ./t-rex-64 -f test.yaml 
The ports are bound/configured.
Starting  TRex v2.77 please wait  ... 
 set driver name net_ixgbe 
 driver capability  : TCP_UDP_OFFLOAD  TSO 
 set dpdk queues mode to DROP_QUE_FILTER 
 Number of ports found: 2
zmq publisher at: tcp://*:4500
 wait 2 sec ..
port : 0 
------------
link         :  link : Link Up - speed 10000 Mbps - full-duplex
promiscuous  : 0 
port : 1 
------------
link         :  link : Link Up - speed 10000 Mbps - full-duplex
promiscuous  : 0 
 number of ports         : 2 
 max cores for 2 ports   : 1 
 tx queues per port      : 3 
Error parsing file test.yaml as YAML:
yaml-cpp: error at line 3, column 3: key not found: duration
RESULT=255

**Comment by hhaim** [comment]
This is not the way to use it
