### ISSUE TITLE
TRex on VM

### ISSUE THREAD

**Issue by rahendatri** [cisco-system-traffic-generator/trex-core#460]
Hello,
I have run through documentations and mailing group finding that the VM version of Trex is not available anymore.
The URL to the VM : [here](http://trex-tgn.cisco.com/trex/T_Rex_162_VM_Fedora_21.ova)

Is this on purpose ?

Regards,
rr

**Comment by hhaim** [comment]
Better to use the docker version and update to the latest image.

**Comment by hhaim** [comment]
TRex is an application.
