### ISSUE TITLE
ASTF DP core missed some burst RX packets.

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#462]
Hi,
Under the i40evf loopback environment, I observed ierrors counter in ASTF mode.

> start -f astf/udp_mix.py -m 550000

![image](https://user-images.githubusercontent.com/4134762/79936945-a74b2480-8493-11ea-8345-6f98fe496c86.png)

I think this occurs when the RX packet rate over the TCP_RX_FLUSH processing count.
Currently, 128 packets are processed per 20 usec (or 2 usec when schedule accurate is enabled).
For the 40 Gbps interface, it should process 156 packets of the 64bytes packet under 2 usec scheduling.
So, I think the number of packets needs to be increased.

@hhaim What do you think about this issue?

BR, Jeongseok

**Comment by hhaim** [comment]
@jsmoon I have a deja vu. This was discussed with @egwakim. I don't see any issue to change it to 256 packets.

**Comment by jsmoon** [comment]
At `CFlowGenListPerThread::handle_stl_pkts()`,
```
            sum+=cnt;
            /* support up to 25MPPS per core (for 20usec tick it would be 512 
               suggested by @jsmoon 
            */
            if (sum>512) {
                break;
            }
```
Did you mean this one?

**Comment by hhaim** [comment]
yes

**Comment by jsmoon** [comment]
I will raise a PR with following change.
```
@@ -201,7 +201,7 @@ uint16_t CFlowGenListPerThread::handle_rx_pkts(bool is_idle) {
                 ctx->m_ft.rx_handle_packet(ctx, m, is_idle,ports_id[dir]);
             }
             sum+=cnt;
-            if (sum>127) {
+            if (sum>256) {
                 ctx->m_ft.inc_rx_throttled_cnt();
                 break;
             }
```

**Comment by hhaim** [comment]
@jsmoon sure. now I see. It was fixed in STL and not ASTF
