### ISSUE TITLE
[Improvement idea] New simple ASTF command to measure exact throughput

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#464]
Hi @hhaim ,
Currently, we can measure throughput based on **time** via set_tick_var() or duration.
But, there is no way to measure throughput from given **transfer data size**.
If user want to measure throughput after specified data size transmitted, there is no way to measure exact throughput.
It can be done by polling TCP connection status. But, it's not exact and quite heavy method to measure throughput.

To be able to measure exact throughput in light way, how about adding new ASTF command lab_tick_var(var_id) ?
Since we already have set_tick_var(var_id), we can utilize it's implementation.

set_tick_var(var_id) : Available now
Set a flow variable used with jmp_nz command. Timer will be started when declaring tick var.
Parameters:	
var_id : string
var-id there are limited number of variables

lab_tick_var(var_id) : Newly suggested API
Lab time between set_tick_var(var_id) and lab_tick_var(var_id).
It can be retrieved from ASTF general counters.
Parameters:	
var_id : string
var-id there are limited number of variables

Example usage : It can be flexible to measure any time measurement point.
prog_c.set_tick_var("www_time")
prog_c.recv(www_page)
prog_c.lap_tick_var("www_time")

prog_c.set_tick_var("ftp_time")
prog_c.set_var("file_size",1000)
prog_c.set_label("a:")
prog_c.recv(ftp_block)
prog_c.jmp_nz("file_size","a:")
prog_c.lap_tick_var("ftp_time")

Pseudo Implementation

`   case tcSET_TICK_VAR:  `
`        {`
`            assert(cmd->u.m_tick_var.m_var_id < apVAR_NUM_SIZE);`
`            /* Save the current tick from ctx */`
`            m_tick_vars[cmd->u.m_tick_var.m_var_id] = m_pctx->m_ctx->m_tick_var->get_curr_tick();`
`            return next_cmd();`
`        }`
`        break; `

`+    case tcLAB_TICK_VAR:`
`+        {`
`+            assert(cmd->u.m_tick_var.m_var_id < apVAR_NUM_SIZE);`
`+            /* Save lab tick_var */`
`+            m_lab_tick_vars[cmd->u.m_tick_var.m_var_id] =  m_pctx->m_ctx->m_tick_var->get_curr_tick() - m_tick_vars[cmd->u.m_tick_var.m_var_id]`
`+            return next_cmd();`
`+        }`
`+        break; `

Getting lab time :  Provide as ASTF general counters per profile
Request
{
    "method": "get_total_counter_values",
    "params": {
        "profile_id": "_"
    }
}
Response:
{
    "result": {
        "client": {
            "0": 0,
			...,
            "9": ["ftp_time":1234, "www_time":5678]			
        },
}

Best Regards
Gwangmoon

**Comment by hhaim** [comment]
@egwakim I understand your proposal. What I don't understand is this:
TRex was designed to work on bulks of flows. Do you want a throughput  of **specific** flow?
If it is a specific profile, it should be done in a diff way (total profile L7/time)

**Comment by egwakim** [comment]
@hhaim I want to get throughput of specific flow and I'm assigning single flow per single profile.
To simulate dynamic real www or ftp scenarios, single flow need to be assigned to single profile.
Since ASTF statistics shows statistics of bulk flow, I suggested to get it from profile level, there is no way to get statistics per single flow. 
If we can get per flow statistics, it'll be better approach.

**Comment by egwakim** [comment]
Hi @hhaim ,
Yes, "Total profile L7/time" would be exact approach because we have per profile ASTF stats counters.
But, implementation would be complex in that case and it can be impacted to other ASTF users who do not need this feature.

Then, how about providing "total lab_tick_time per profile"?  It's just accumulated sum of lab_tick-time per profile. It'll be zero if it not used and if it's used one or more times, it'll be non-zero value.
And it'll be quite flexible API to users.

**Comment by hhaim** [comment]
@egwakim total ```lab_ticks_time``` per profile sound as a a good idea and light enough

**Comment by jsmoon** [comment]
@hhaim, @egwakim
1. I prefer adding `total_flow_time` per TGID and profile in `tcpstat_int_t`.
The `total_flow_time` can be updated when the TCP flow is closed if each TCP flow keeps its started time. I think there is no need to add a new program instruction.
2. In addition, I think the profile transmitting(STATE_TX) time can be a better solution for some users. If there are multiple flows in a profile, the accumulated time could over the profile transmitting time.

**Comment by hhaim** [comment]
@jsmoon I think we all agree that there is no need to a new instruction that works per flow for doing something per profile

**Comment by jsmoon** [comment]
![image](https://user-images.githubusercontent.com/4134762/82969186-fee82d00-a009-11ea-868a-06353e331313.png)
@hhaim I prefer (3). What do you think of it?

**Comment by hhaim** [comment]
@jsmoon first I must say that they figure is very nice.
In case the profile duration is long (e.g. 30 seconds), (3) is about the same as (4) and very close to the total duration. 
So I'm asking what do we want to achieve? Do we want to measure a profile average BW on a very short duration?

**Comment by egwakim** [comment]
The purpose of the suggestion is measuring exact throughput of traffic flow and traffic running time.
For example, If we make ftp profile(single flow per profile) on for DUT, we can measure the exact capacity of DUT. 
It can be achieved by exact time measurement since we knows total received bytes.
Currently, we are polling ASTF stats, but, it's heavy job(due to JSON RPC overhead) and not accurate approach.

**Comment by jsmoon** [comment]
@hhaim I should provide the **transfer time** for a very short sized (~kbytes) L7 data.
According to my investigation, the difference between (3) and (4) will be 110 msec at the minimum.
```
        tx_node->m_type = CGenNode::TCP_TX_FIF;
        tx_node->m_time = m_core->m_cur_time_sec + d_phase + 0.1; /* phase the transmit a bit */
```
and
```
    d_phase = 0.01 + (double)m_flow_gen->m_thread_id * d_time_flow / (double)m_flow_gen->m_max_threads;
```
So, I want to get more precise **transfer time** in that case.

**Comment by hhaim** [comment]
Understood. So you want to add start and stop time per profile for accurate BW calculation. 
Am I right? if so I'm good with it. We can capture this in the engine itself and there is no need to add an instruction for this

**Comment by jsmoon** [comment]
@hhaim I should provide the "**transfer time**" itself for the given bytes. It's my user's request.
If you agree with (3), I'll try to implement it without adding any instruction.

**Comment by hhaim** [comment]
@jsmoon I don't have a problem with (3)
