### ISSUE TITLE
Invalid certificate on trex download server

### ISSUE THREAD

**Issue by kevintraynor** [cisco-system-traffic-generator/trex-core#465]
> wget https://trex-tgn.cisco.com/trex/release/v2.80.tar.gz
--2020-04-23 12:17:58--  https://trex-tgn.cisco.com/trex/release/v2.80.tar.gz
Resolving trex-tgn.cisco.com (trex-tgn.cisco.com)... 173.36.109.208
Connecting to trex-tgn.cisco.com (trex-tgn.cisco.com)|173.36.109.208|:443... connected.
ERROR: The certificate of ‘trex-tgn.cisco.com’ is not trusted.
ERROR: The certificate of ‘trex-tgn.cisco.com’ doesn't have a known issuer.

It can be avoided with --no-check-certifcate but it would be better for ease of use and security to fix the certificate.

Thanks, Kevin.

**Comment by hhaim** [comment]
This is a bug in wget, please verify with latest browser

**Comment by hhaim** [comment]
The certificate is ok. The CA is rather new so need to update the host CA

**Comment by kevintraynor** [comment]
Thanks. I verified using a browser has no issues. wget and curl both complain.

Perhaps https://trex-tgn.cisco.com/trex/doc/trex_manual.html#_obtaining_the_trex_package could be updated, or a note added, I'm sure others will hit this issue.

**Comment by hhaim** [comment]
Yep, you are the second to report this ..
You should update root certificates in your machine

**Comment by navarrothiago** [comment]
FYI I have the same problem with curl and wget.
