### ISSUE TITLE
linker issue

### ISSUE THREAD

**Issue by spyroot** [cisco-system-traffic-generator/trex-core#470]
Hey Folks,

Did you try to compiler Trex on anything new? I've tried 3 different distro

./_t-rex-64-o
./_t-rex-64-o: so/x86_64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./_t-rex-64-o)
root@ubuntu:~/trex/trex-core/scripts# ./t-rex-64-o
The ports are bound/configured.
./_t-rex-64-o: so/x86_64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./_t-rex-64-o)

checking symbols

root@ubuntu:~/trex/trex-core/scripts# strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by spyroot** [comment]
is there a way to pass > +WERROR_FLAGS += -Wno-address-of-packed-member to all Makefiles ?

**Comment by spyroot** [comment]
I confirm it a fixed issue with gcc9 and Ubuntu 20 LTS, but not linux dir. 

../../src/stx/stl/trex_stl_stream_vm.h:324:43: error: taking address of packed member of ‘RandMemBss64’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  324 |             val = m_min_val + ( vm_rand64(&p->m_seed)  % ( (uint64_t)m_max_val - m_min_val + 1) );
      |                                           ^~~~~~~~~~
cc1plus: all warnings being treated as errors

Waf: Leaving directory `/root/test/trex-core/linux/build'
Build failed
 -> task in 'bp-sim-64-debug' failed with exit status 1 (run with -v to display more information)
 -> task in 'bp-sim-64-debug' failed with exit status 1 (run with -v to display more information)
 -> task in 'bp-sim-64-debug' failed with exit status 1 (run with -v to display more information)
 -> task in 'bp-sim-64-debug' failed with exit status 1 (run with -v to display more information)
 -> task in 'bp-sim-64-debug' failed with exit status 1 (run with -v to display more information)

**Comment by angelyouyou** [comment]
@spyroot 
How did you solve this error? I also encountered this error.
