### ISSUE TITLE
Oversized MTU size for Mellanox NIC's

### ISSUE THREAD

**Issue by vtlrazin** [cisco-system-traffic-generator/trex-core#472]
When I run TREX (t-rex-64) applications with Mellanox network cards, it changes the MTU for all network cards to a static size of **9238**. This MTU size is not supported by the switch (maximum MTU size is **9216**). This means that all outgoing traffic from my server will be dropped by switch.

Could you please describe WHY apps want to change MTU size?

Thanks,
Vitaliy

**Comment by hhaim** [comment]
@vtlrazin the driver MTU was set to maximum. this does not mean that the packets generated by TRex will be with maximum MTU, it only means that you would be able to choose to use maximum MTU .. you still can control the TCP mss/udp mtu and STL packet size

**Comment by vtlrazin** [comment]
@hhaim My question is: why does this happen during startup application?

In my opinion, this should be done at the stage of preparing the application during the launch of the script - _**dpdk_setup_ports.py**_
and the MTU size must be variable in accordance with the network topology.

Vitaliy

**Comment by hhaim** [comment]
@vtlrazin not sure I get your point. Let me start explaining how the **normal** DPDK  drivers works maybe you will get the reasoning. 

For any DPDK driver there is no interface property of MTU, you can send any packet size up to the maximum driver size. TRex API has a way to control the maximum packet size  (which is per each template or stream and not interface). 

We tried to map Mellanox to the same model so we needed to remove the MTU limit at startup

**Comment by hhaim** [comment]
@vtlrazin one more thing 

>> When I run TREX (t-rex-64) applications with Mellanox network cards, it changes the MTU for all network cards to a static size of 9238. This MTU size is not supported by the switch (maximum MTU size is 9216). This means that all outgoing traffic from my server will be dropped by switch.


this would happen only if you sent stream/template which has MTU bigger than your switch. You can control the packet size of your generated packets. We are not using MTU. the driver is just a way to move packets around

**Comment by vtlrazin** [comment]
In my opinion, as I said above, the application should work with pre-configured settings. This may work better or worse depending on the configured system settings.

**Comment by hhaim** [comment]
@vtlrazin the TRex application API does *not* expose a MTU per interface, it expose packet size per stream or mss per template. For our API to work on all the DPDK drivers (not only Mellanox) there is a need to change the Mellanox MTU to maximum size.
