### ISSUE TITLE
bad ip range in http_simple_rss.py

### ISSUE THREAD

**Issue by daratitus** [cisco-system-traffic-generator/trex-core#474]
Hello,
I got this error:

trex>start -f astf
astf-sim           astf-sim-utl       astf/              astf_schema.json
trex>start -f astf/http_simple_rss.py -m 100

start - Could not load profile:
Python Traceback follows:

  File "/home/trex-core-master/scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_profile.py", line 1801, in load_py
    profile = module.register().get_profile(**kwargs)
  File "astf/http_simple_rss.py", line 10, in get_profile
    ip_gen_c = ASTFIPGenDist(ip_range=["172.0.0.0", "16.0.0.255"], distribution="seq")
  File "/home/trex-core-master/scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_profile.py", line 906, in __init__
    ArgVerify.verify(self.__class__.__name__, ver_args)
  File "/home/trex-core-master/scripts/automation/trex_control_plane/interactive/trex/astf/arg_verify.py", line 95, in verify
    raise ASTFErrorBadIpRange(f_name, name, given_arg, ret)
ASTFErrorBadIpRange:
******

Exception stack (most recent call last):

#4     trex_astf_profile.py:21          - 'return func(*args, **kwargs)'
#3     trex_astf_profile.py:1801        - 'profile = module.register().get_profile(**kwargs)'
#2     http_simple_rss.py:10            - 'ip_gen_c = ASTFIPGenDist(ip_range=["172.0.0.0", "16.0.0.255"], distribution="seq")'
#1     trex_astf_profile.py:906         - 'ArgVerify.verify(self.__class__.__name__, ver_args)'
#0     arg_verify.py:95                 - 'raise ASTFErrorBadIpRange(f_name, name, given_arg, ret)'

Summary error message:

Bad IP range "['172.0.0.0', '16.0.0.255']" for parameter ip_range to function ASTFIPGenDist - Min IP is bigger than Max IP

Thanks

**Comment by hhaim** [comment]
not all the profile are valid, there are profile that we use for testing corner case
