### ISSUE TITLE
documentation  on multi profile on the same port

### ISSUE THREAD

**Issue by hhaim** [cisco-system-traffic-generator/trex-core#476]
@jsmoon could you point me to the documentation of this feature?

**Comment by jsmoon** [comment]
@hhaim I didn't write any documentation under doc/ contents. I just added a simple comment for l7_map usage at ASTFAssociationRule.

**Comment by hhaim** [comment]
@jsmoon thanks. Found the commit and the API doc. I see the example that you added too. 
I think it would better add an explicit example in our manual as this is not a simple mechanism

**Comment by egwakim** [comment]
How about adding document as below?
In the trex_astf.html,

2.3.26 Tutorial : Server port sharing between multiple profiles
Description of port sharing feature.
Example1. 2 profiles using different server ports without port sharing(Use two server ports)
Example2. Same as Example1, but, server port shared with l7_map API(Use single server port)
Explanation of Example2.
