### ISSUE TITLE
ConnectX-3 Two Key Same Value

### ISSUE THREAD

**Issue by shelbyt** [cisco-system-traffic-generator/trex-core#48]
Hi,

I'm using a Mellanox ConnectX-3 device which provides two ports but expose a single PCI bus address. I tried playing with the config file it seems I need to provide interfaces as a multiple of 2.

Is there any way to make this work with trex? 

Thank You

**Comment by hhaim** [comment]
Yes, see v2.24 release notes(I need to update the documentation)

https://trex-tgn.cisco.com/trex/doc/release_notes.html

Try to add this to CLI too

--mlx4-so


Keep in mind that we don't have CX3 in our lab so we didn't verified it! We would be happy if you can help

Hanoh
Sent from my iPhone

On 27 Jun 2017, at 16:01, shelbyt <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I'm using a Mellanox ConnectX-3 device which provides two ports but expose a single PCI bus address. I tried playing with the config file it seems I need to provide interfaces as a multiple of 2.

Is there any way to make this work with trex?

Thank You

-

**Comment by shelbyt** [comment]
Great thanks. I will try that

**Comment by hhaim** [comment]
For some reason all new DPDK development in on CX4/5

Hanoh
Sent from my iPhone

On 27 Jun 2017, at 17:18, shelbyt <notifications@github.com<mailto:notifications@github.com>> wrote:


Great thanks. I will try that

-

**Comment by shelbyt** [comment]
Hi Hanoh,

There are a few issues using a CX3 that I've found.

-  Since the CX3 exposes two ports(em0,em1) per PCI, using ifconfig to find and set MTU fail. `out=subprocess.check_output(['ifconfig', dev_id])` results in:  `# ifconfig em0, em1` which is an invalid command. You can find those lines below: 

https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/dpdk_setup_ports.py#L394

https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/dpdk_setup_ports.py#L408

https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/dpdk_setup_ports.py#L414

-  In the same file it looks like `dpdk_setup_port.py` only [loads the mlx5 driver](https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/dpdk_setup_ports.py#L653) which is for the  Connect-IB series of devices, not for the ConnectX series (See page 14: http://www.mellanox.com/related-docs/prod_software/Mellanox_OFED_Linux_User_Manual_v2.3-1.0.1.pdf).

- Tried to hardcorde all of these and forced loading the mlx4_core driver in the script instead of mlx5 but in the end I got an error coming from: https://github.com/cisco-system-traffic-generator/trex-core/blob/master/src/main_dpdk.cpp#L6116. 
When set_driver() is invoked, rte_eth_dev_count() returns 0 and results in a crash "Could not find interfaces"

Hope that helps

**Comment by hhaim** [comment]
Try adding --mlx4-so explicitly for the last issue

**Comment by shelbyt** [comment]
Decided to try other NICs, was unable to test if --mlx4-so would work, sorry.

**Comment by hhaim** [comment]
this command works for me 

$sudo ./t-rex-64 -i --mlx4-so

anyhow once we will have access to CX3 NICs we would be able to fix the issues you mentioned 
(I think MS Azure linux support with CX3 VF is going to be supported soon)

thanks,
Hanoh
