### ISSUE TITLE
TRex eat-up all available huge pages during startup

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#480]
During TRex startup, TRex allocates whole system huge pages for a while.
It causes memory allocation failure on other TRex process or other DPDK applications in same Linux server.

Reproduction steps
1. Monitor huge page occupation in Linux server
`# watch -n 1 ls -l /dev/hugepages`
2. Start TRex

It's known issue on DPDK library and can be fixed from DPDK 18.05.
See known DPDK issue here : https://partner-bugzilla.redhat.com/show_bug.cgi?id=1540029
See  DPDK release note and guide here : https://doc.dpdk.org/guides/rel_notes/release_18_05.html

TRex using fixed version of DPDK, but, TRex using "--legacy-mem" option, it need to be removed to solve this issue.

**Comment by egwakim** [comment]
Hi @hhaim,
What is opinion about this issue?

**Comment by hhaim** [comment]
@egwakim if it does not have side effect of performance I don't see a reason not to remove it

**Comment by egwakim** [comment]
Then, do you have plan to fix this issue?

**Comment by hhaim** [comment]
@egwakim I will check it in our regression as a side branch

**Comment by hhaim** [comment]
@egwakim it seems than the new DPDK memory subsystem requires libnuma to be installed on the system (in the target system)
```yum install libnuma-devel```
It is a new and and major dependency that I would not like to introduce now. 

```
diff --git a/src/main_dpdk.cpp b/src/main_dpdk.cpp
index fa7dcf7a..149b52f1 100644
--- a/src/main_dpdk.cpp
+++ b/src/main_dpdk.cpp
@@ -6177,8 +6177,7 @@ COLD_FUNC int  update_dpdk_args(void){
             }
         }
     }
-
-    SET_ARGS("--legacy-mem");
+    //SET_ARGS("--legacy-mem");
 
     if ( lpop->prefix.length() ) {
         SET_ARGS("--file-prefix");
diff --git a/src/pal/linux_dpdk/dpdk2002_x86_64/rte_config.h b/src/pal/linux_dpdk/dpdk2002_x86_64/rte_config.h
index 2fe05e9a..1bfc16cf 100644
--- a/src/pal/linux_dpdk/dpdk2002_x86_64/rte_config.h
+++ b/src/pal/linux_dpdk/dpdk2002_x86_64/rte_config.h
@@ -72,7 +72,7 @@
 #define RTE_MAX_VFIO_CONTAINERS 64
 #undef RTE_MALLOC_DEBUG
 #undef RTE_EAL_NUMA_AWARE_HUGEPAGES
-//#define RTE_EAL_NUMA_AWARE_HUGEPAGES 1
+#define RTE_EAL_NUMA_AWARE_HUGEPAGES 1
 #undef RTE_USE_LIBBSD
 #undef RTE_ARM_USE_WFE
 #undef RTE_ENABLE_AVX
```

**Comment by egwakim** [comment]
Hi,
In the long-term point of view, it's better to remove '--legacy-mem' to utilize memory features in the latest version of DPDK.
Additional libnuma is required for DPDK build and run.

I assume that It can be considered as external_libs and can be embedded in TRex like other external_libs.
The size of libnuma is small enough to embed.

**Comment by hhaim** [comment]
@egwakim the libnuma might have dependency on kernel header and then you **can't** attach it. 
TRex today has minimal dependncy on the kernel headers. In case it depends (Azure, mlx5, tap) users need to build TRex from source and thisis painful. I don't want to add a dependency for some not clear benefit ..
dpdk 20.02 works fine with --legacy-mem'

**Comment by egwakim** [comment]
Hi,
libnuma does not have any dependency on Linux kernel.
It's pure user space library which can run any versions of Linux.
It's officially required library to compile DPDK.
https://doc.dpdk.org/guides/linux_gsg/sys_reqs.html

**Comment by hhaim** [comment]
I see this in the code, It depends on the kernel API/version
https://github.com/numactl/numactl/blob/master/syscall.c
I would use it only if there is no choice

**Comment by egwakim** [comment]
It's not kernel API/version dependency.
It's CPU type dependency ( #if defined(__x86_64__)) and glibc version dependency(#if defined(__GLIBC__) && __GLIBC_PREREQ(2, 11))
It does not include any kernel headers.

**Comment by hhaim** [comment]
This is a system call ID 

#define __NR_sched_setaffinity    203
#define __NR_sched_getaffinity     204

**Comment by egwakim** [comment]
Hi,
These system call number did not changed since initial old Linux kernel version.
These are quite old system call numbers.
Linux System call numbers always backward compatible.

DPDK requires at least Kernel 3.16 or higher.
See system call table in Kernel 3.16 https://elixir.bootlin.com/linux/v3.16/source/arch/x86/syscalls/syscall_64.tbl#L212

Since system call numbers are differ by each CPU architecture, it'll be differ by CPU architecture.
But, it's same for all Linux kernel versions.

**Comment by hhaim** [comment]
@egwakim but it is still a dependency on another library that needs to be part of the **target** Linux (not the build system). If this library could be staticly linked against trex image I would go for it - changing only the build system. 
I would not want to change the user-experience and require more dependency 

Are you willing to verify how we could achieve this?

**Comment by egwakim** [comment]
Yes, we need to remove it.
We have other DPDK applications running in same server. But, other DPDK applications failed to allocate huge page due to TRex. Since other DPDK applications does not use "--legacy-mem", only TRex is issue in this case.
Since "--legacy-mem" option is temporary workaround for backward compatibility in DPDK side, it can be removed in the future. it'll be good to remove for the future DPDK migration.

**Comment by hhaim** [comment]
@egwakim the failure is temporary only when TRex is loaded. We can load a few TRex servers on the same server in consecutively

**Comment by egwakim** [comment]
@hhaim , If we embed this limitation, all kinds of DPDK applications(Including TRex) should be serialized, but, it's not possible to assure the serialization because we cannot know the exact timing when such memory allocation happens. 
In my server, several different DPDK applications running and only TRex have this limitation.
To avoid it, We should  make additional new application manager which serialize all kinds of DPDK applications to workaround this TRex limitation.
If you did not experience this issue, it's just lucky case, 
In my case, it always happening if multiple TRex started in short term gap with our automated CI.

**Comment by hhaim** [comment]
@egwakim agreed. Could we  remove the dependency using libnuma as shared memory? 

1. Add another TRex CLI ```--new-memory``` 
2. In this case it was requested, load libnuma **dynamically** without dependency (shared object),
2.2  In case it is not installed exit with an error msg to install it 

This gives backward compatibility

**Comment by egwakim** [comment]
That's good option for the backward compatibility

**Comment by egwakim** [comment]
Hi, Any updates on it?

**Comment by hhaim** [comment]
@egwakim no update from my side, busy with other things

**Comment by egwakim** [comment]
Hi @hhaim ,
Dynamic loading of libnuma seems not feasible option because related DPDK code written as "#ifdef".
We have 2 options,
Option#1. Let user to install DPDK dependent libnuma-dev like other DPDK applications, It's mandatory for general DPDK applications
Option#2. Embed[ libnuma-dev](https://github.com/numactl/numactl/releases/tag/v2.0.13) in external_libs and build & link statically it as a part of DPDK

Option#1 works by below change and Option#2 will need more change in the build script.
How about your opinion?

```
 --- a/src/main_dpdk.cpp
+++ b/src/main_dpdk.cpp
@@ -6177,8 +6177,7 @@ COLD_FUNC int  update_dpdk_args(void){
             }
         }
     }
-
-    SET_ARGS("--legacy-mem");
+    //SET_ARGS("--legacy-mem");
 
     if ( lpop->prefix.length() ) {
         SET_ARGS("--file-prefix");
--- a/src/pal/linux_dpdk/dpdk2002_x86_64/rte_config.h
+++ b/src/pal/linux_dpdk/dpdk2002_x86_64/rte_config.h
@@ -72,7 +72,7 @@
 #define RTE_MAX_VFIO_CONTAINERS 64
 #undef RTE_MALLOC_DEBUG
 #undef RTE_EAL_NUMA_AWARE_HUGEPAGES
-//#define RTE_EAL_NUMA_AWARE_HUGEPAGES 1
+#define RTE_EAL_NUMA_AWARE_HUGEPAGES 1
 #undef RTE_USE_LIBBSD
 #undef RTE_ARM_USE_WFE
 #undef RTE_ENABLE_AVX		 
+++ a/src/dpdk/lib/librte_eal/linux/eal/Makefile
--- b/src/dpdk/lib/librte_eal/linux/eal/Makefile
@@ -25,7 +25,6 @@
 LDLIBS += -lrte_kvargs
 ifeq ($(CONFIG_RTE_EAL_NUMA_AWARE_HUGEPAGES),y)
 LDLIBS += -lnuma
+LDLIBS += -Wl,--no-allow-shlib-undefined   # To avoid linking error in '--as-needed' option enabled linker
 endif
 
 # specific to linux exec-env
--- a/linux_dpdk/ws_main.py
+++ b/linux_dpdk/ws_main.py
@@ -1804,7 +1804,7 @@
                 includes =inc_path,
                 cxxflags = ( cxxflags + ['-std=gnu++11',]),
                 linkflags = linkflags ,
-                lib=['pthread','dl', 'z'],
+                lib=['pthread','dl', 'z','numa'],
                 use =[build_obj.get_dpdk_target(), build_obj.get_bpf_target(), 'zmq'],
                 source = bp.file_list(top) + debug_file_list,
                 rpath = rpath_linkage,
```

**Comment by hhaim** [comment]
@egwakim  option#2 won't work because the library is dependent on the kernel syscall API. 
Could we change DPDK to use as dynamic share object?

**Comment by hhaim** [comment]
@egwakim there is no guaranty that it will work!
It is compiled by server A with kernel A and will run on server B with different kernel API

Looking into how libnuma is used, there are only a few API calls to libnuma, which can be wrapped and used as share object 

This is an example 
#ifdef RTE_EAL_NUMA_AWARE_HUGEPAGES
	if (check_numa()) {
		oldmask = numa_allocate_nodemask(); <<<<
		prepare_numa(&oldpolicy, oldmask, socket); <<<<
		have_numa = true;
	}
#endif

**Comment by egwakim** [comment]
@hhaim ,
Do you have plan to add it(--new-memory) from your side?
It's not easy for us to change TRex building stuff.

**Comment by hhaim** [comment]
@egwakim, sorry for the late response, busy with other stuff. 
What about this? adding another **build** option to WAF to build with --new-memory option. this will change DPDK options and trex define. 
I agree with you that DPDK does support either of the modes and it is not easy to make it dynamic

**Comment by egwakim** [comment]
Yes, I agree.
With this new-memory option, I saw that TRex startup time reduced quite a lot.
And run-time performance of ASTF TCP also improved in my case(I did not tested many cases or different environment yet).
