### ISSUE TITLE
[Issue] FlowLatencyStat does not work when IP header changed

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#485]
In our testing network,
Original IP header changed in Rx side including IP.TOS field.
In that case, Rx packet counters were all zero in FlowLatencyStat.
From Rx captured packets, 16B FlowLatency header(at the end payload) was not changed.

I assume that it's caused by how FlowLatencyStat works.

Will it possible to fix this issue?

**Comment by hhaim** [comment]
@egwakim in case of a hardware mode, each NIC has a different hardware filter. 
There are NICS that has a ip.id hardware filter while other based on ip.ttl filter and other by IP,TOS&1 (LSB)
In case the filter does not match the latency will not forward to Rx core.
Moving to software mode (--software) will check the ipv4.Id (in SW) which is more resilient

**Comment by egwakim** [comment]
This issue was happened when "--software" option used.

**Comment by hhaim** [comment]
@egwakim 

I see the issue. We should add  ipv4.id to the software match 

```
bool CFlowStatParser::is_fs_latency(){
    uint8_t tos = 0;
    if (m_ipv4) {
        tos = m_ipv4->getTOS();
    }
    if (m_ipv6) {
        tos = m_ipv6->getTrafficClass();
    }
    return ((tos&0x01)==0x01)?true:false;
}
```
This is how we set the stream when we send it. 
```
        m_parser_pl->set_ip_id(FLOW_STAT_PAYLOAD_IP_ID);
        m_parser_pl->set_tos_to_cpu();
```

Could you add the fix by comparing both ipv4.id and tos (for ipv4) and for ipv6  ip6.label?

**Comment by jsmoon** [comment]
@hhaim, I think your suggestion is not enough to solve this issue. It is because the ipv4.id and ipv6.label could have unexpected value.
How about this? It will perform checking latency for all received IP packets when "--software" option used.
```
     uint8_t proto = m_parser->get_protocol();
     bool tcp_udp=false;
 
-    if (m_parser->is_fs_latency()) {
+    if (m_parser->is_fs_latency() || get_mode()->get_force_sw_mode()) {
         m_ports[dir].m_fs_latency.handle_pkt(m,0);
     }

```

**Comment by hhaim** [comment]
@jsmoon I do agree that we need to do better in case of a software because there is more options

```RXLatency::handle_pkt```  was written for RX which has minimal number of packets to handle.  
I can't even figure out how it the code works  .. 
I don't want to reduce the total software CPU% only because I suspect that one of the packets is latency packet. the filter should be FAST! It could be false positive, but not vice versa 

```
void RXLatency::handle_pkt(const rte_mbuf_t *m, int port) {
  uint8_t tmp_buf[sizeof(struct flow_stat_payload_header)];
  CFlowStatParser parser(CFlowStatParser::FLOW_STAT_PARSER_MODE_SW);
  parser.set_vxlan_skip(CGlobalInfo::m_options.m_ip_cfg[port].get_vxlan_fs());
  int ret = parser.parse(rte_pktmbuf_mtod(m, uint8_t *), m->pkt_len);

  if (m_rcv_all || (ret == 0)) {
    uint32_t ip_id = 0;
    int ret2 = parser.get_ip_id(ip_id);
    if (m_rcv_all || (ret2 == 0)) {
      if (m_rcv_all || is_flow_stat_id(ip_id)) {
        uint16_t hw_id = get_hw_id((uint16_t)ip_id);
        if (m_rcv_all || is_flow_stat_payload_id(ip_id)) {
          struct flow_stat_payload_header *fsp_head =
              (flow_stat_payload_header *)utl_rte_pktmbuf_get_last_bytes(
                  m, sizeof(struct flow_stat_payload_header), tmp_buf);
          if (m_rcv_all && (!is_flow_stat_id(ip_id) ||
              (fsp_head->magic == FLOW_STAT_PAYLOAD_MAGIC &&
               fsp_head->hw_id < MAX_FLOW_STATS_PAYLOAD))) {
            ip_id = FLOW_STAT_PAYLOAD_IP_ID;
          }
```

My suggestion is this:
1 . for latency we can add a test to the end of the packet ((fsp_head->magic == FLOW_STAT_PAYLOAD_MAGIC ) 
2. for flow-stats we don't have magic so we can do TOS + ip4.id/ipv6.id filter 
3. we can add a MAGIC to flow-stats packet too (if user ask for it in the stream+software) to make it more resilient 

We can't call this function for every packet

**Comment by jsmoon** [comment]
As I understood your suggestion,
1. I can add a quick filter that tests FLOW_STAT_PAYLOAD_MAGIC directly in the packet.
```
    if (m_parser->is_fs_latency() || (get_mode()->get_force_sw_mode() && is_latency_pkt(m))) {
        m_ports[dir].m_fs_latency.handle_pkt(m,0);
    }
```
2. & 3. flow-stats (without latency) improvement is another feature. So, I think this suggestion would be handled separately.
If I understood correctly, I'll prepare a PR for your suggestion 1.

**Comment by hhaim** [comment]
@jsmoon 

It is better just to improve ```is_fs_latency()``` function. No need to touch the other things. 

  if (TOS() || latency_magic() || ip4.id || ipv6.id)

This function should return true in case it is either latency or flow-stats

**Comment by jsmoon** [comment]
@hhaim, I got it. Your suggestion is better. I'll try to implement it.

**Comment by jsmoon** [comment]
@hhaim I have a question for you.
I was wondering which one is better:
1. ```(TOS() || ip_id) || latency_magic()```
2. ```(TOS() && ip_id) || latency_magic()```

Actually, 2.  is the same as ```ip_id || latency_magic()```. It is because handle_pkt() does nothing when `ip_id` is 0 although `TOS()` is true.
What do you think about it? ```ip_id || latency_magic()``` vs ```TOS() && ip_id || latency_magic()```

**Comment by hhaim** [comment]
@jsmoon you are right. 

With current ```handle_pkt``` if ip_id is not valid it won't work, so there is no added value in adding ```latency_magic()``` to the filter. 

There are two options:
1. Replace TOS with only ip_id as a filter 
2. ```filter == (ip_id) || latency_magic()``` and in case of SW mode ```handle_pkt``` to check  ```(ip_id) || latency_magic() ``` instead of ```(ip_id) && latency_magic() ```

**Comment by jsmoon** [comment]
@hhaim
After I have checked the source code more, I think the filter `(ip_id) && TOS()` is better than the `(ip_id)` only. It could secure the right packets for the flow stats without latency.
So, my change will call `handle_pkt()` if **TOS_GO_TO_CPU is set and ip_id is not 0**, else if **--software specified and FLOW_STAT_PAYLOAD_MAGIC found** in the packet.
