### ISSUE TITLE
Ubuntu 18.04.4 with Mlnx CX-5-EN Problem

### ISSUE THREAD

**Issue by somedev42** [cisco-system-traffic-generator/trex-core#490]
Hi,

i have the following problem that the TRex output is unbelievably high and this already in the IDLE state of the ports. The first few seconds after starting the server the data is still correct. Is there a known bug or already a fix for this problem? 
Below are the technical informations:
Kernel: 4.15.0-99-generic
Mlnx_OFED_EN: 4.6-1.0.1.1
Ubuntu: 18.04.4 LTS
TRex: 2.81

Following is the terminal output after the command ./t-rex-64 -i -c 7:
-Per port stats table 
      ports |               0 |               1 
 -----------------------------------------------------------------------------------------
   opackets |               1 |               1 
     obytes | 144115188075855876 | 144115188075855876 
   ipackets |               2 |               2 
     ibytes |             448 |             448 
    ierrors | 15852670688344145920 | 15852670688344145920 
    oerrors |               0 |               0 
      Tx Bw |  528863.07 Tbps |  533759.95 Tbps 

-Global stats enabled 
 Cpu Utilization : 0.0  %
 Platform_factor : 1.0  
 Total-Tx        : 1062623.01 Tbps  
 Total-Rx        :       3.30 Kbps  
 Total-PPS       :       0.92  pps  
 Total-CPS       :       0.00  cps  

 Expected-PPS    :       0.00  pps  
 Expected-CPS    :       0.00  cps  
 Expected-BPS    :       0.00  bps  

 Active-flows    :        0  Clients :        0   Socket-util : 0.0000 %    
 Open-flows      :        0  Servers :        0   Socket :        0 Socket/Clients :  -nan 
 drop-rate       : 1062623.01 Tbps   
 current time    : 8.1 sec  
 test duration   : 0.0 sec  

If you need any further information, let me now.
Kind Regards!

**Comment by hhaim** [comment]
@somedev42 
Please follow this https://trex-tgn.cisco.com/trex/doc/trex_appendix_mellanox.html
and check v2.79 too (older DPDK) 
Ubuntu is not supported with the package, you will need to build TRex from source

**Comment by somedev42** [comment]
@hhaim 
I followed this guide and all runs fine, but the statistik values seems to be unrealistic also to the fact, that i don't even send anything. I also built Trex from source and no problems occured. So are there some known fixes for this purpose to use the CX-5-EN correctly?

**Comment by hhaim** [comment]
@somedev42 It is not clear. Do you have an issue with CentOS 7.4/our recommendation OFED and our package?

**Comment by somedev42** [comment]
@hhaim I'm trying out the setup like mentioned in the first post with ubuntu but changed the TRex version to 2.79. For us it's mandatory to hold on ubuntu, so is there any known setup of version recommendations to use with CX-5-EN or is TRex to be used mainly  in connection with CentOS?

Thanks for Response!

**Comment by hhaim** [comment]
Mellanox driver is dependent on Linux kernel and OFED and has different issues in each combination of the matrix. My suggestion is to work with the latest driver (v2.81) and open bug to Mellanox DPDK team

**Comment by somedev42** [comment]
@hhaim Thanks for your response.
