### ISSUE TITLE
Randomly choosing python 2 or 3 is confusing

### ISSUE THREAD

**Issue by haggaie** [cisco-system-traffic-generator/trex-core#493]
I see that `dpdk_setup_ports.py` uses `find_python.sh` to choose the right python version, and this script uses a random number to select which one to use. I find that non-deterministic behavior a little confusing:
After noticing that the script depends on setuptools, I installed it, but only for Python 2, and then the script would randomly fail for Python 3.

**Comment by hhaim** [comment]
@haggaie You can explicitly ask for python2 or python3 using ```--python2``` or ```--python3```
In our regression, we test both, but for development, we wanted that developer will get both (randomly). it is not going to change

**Comment by haggaie** [comment]
Thanks. In that case I would recommend that you add both Python 2 and Python 3 (and all the necessary packages) to the list of dependencies in your build instructions, so that developers will not get random failures.

**Comment by bdollma** [comment]
Hi @haggaie , 
Did we at some point ask you to install Python or dependencies of a specific version? If so, please point us to where.
In case you assumed TRex would be fine running only on a specific Python version and installed that version, then simply that assumption is incorrect.
Thanks,
Bes

**Comment by haggaie** [comment]
Yes @bdollma, I couldn't find any documentation about TRex dependencies, so I had to try and run it and see what is missing as I go along. Once it started working with one version of Python, I (incorrectly) assumed that I've set it up correctly, but I was frustrated to see it was randomly failing. I've written this issue as I thought I could save others the hours it took me to find out why.

Am I to understand from your note that there is some policy against documenting TRex's build dependencies?

By the way, are you aware that Python 2 support has ended about 6 months ago?

**Comment by bdollma** [comment]
Hi @haggaie,
No we don't have any policy against documenting dependencies. We simply haven't requested a specific version hence it is legitimate to try and use both. 
We are aware that the support has ended for Python 2, however we have a lot of Python 2 code and our regression tests both.
Thanks,
