### ISSUE TITLE
[Issue] TRex does not work with Intel XXV710 25G NIC when used "--software -c 1" option with the latest F/W

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#496]
Hi,
TRex cannot receive any packets with Intel XXV710 25G NIC when used with "--software -c 1".
It's issue in the latest version of NIC F/W.
ARP fails at startup.
No issue without "--software" option. 
No issue with "-c 2" or more cores used.
No issue in old NIC F/Ws.

Here is not-working NIC F/W info
> ethtool -i eth0
driver: i40e
version: 2.10.19.82
firmware-version: 7.10 0x800051ac 19.0.12
expansion-rom-version:
bus-info: 0000:65:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes
> dmesg
[1594258.902616] i40e 0000:b3:00.1: fw 7.83.59945 api 1.9 nvm 7.10 0x800051ac 19.0.12
[1594259.136915] i40e 0000:b3:00.1: MAC address: 3c:fd:fe:d8:35:a1
[1594259.159085] i40e 0000:b3:00.1: PCI-Express: Speed 8.0GT/s Width x8
[1594259.168274] i40e 0000:b3:00.1: Features: PF-id[1] VFs: 64 VSIs: 66 QP: 28 RSS FD_ATR FD_SB NTUPLE CloudF VxLAN Geneve NVGRE PTP VEPA

Old working NIC F/W was
>ethtool -i eth4
driver: i40e
version: 2.7.29
firmware-version: 6.00 0x80003785 18.5.17
expansion-rom-version:
bus-info: 0000:3b:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

>dmesg
[    5.202608] i40e 0000:3b:00.1: fw 6.80.48950 api 1.7 nvm 6.00 0x80003785 18.5.17
[    5.446668] i40e 0000:3b:00.1: MAC address: 3c:fd:fe:c6:c6:71
[    5.474383] i40e 0000:3b:00.1: PCI-Express: Speed 8.0GT/s Width x8
[    5.487903] i40e 0000:3b:00.1: Features: PF-id[1] VFs: 64 VSIs: 66 QP: 56 RSS FD_ATR FD_SB NTUPLE CloudF DCB VxLAN Geneve NVGRE PTP VEPA

**Comment by hhaim** [comment]
@egwakim, it seems we started to get Cisco NICS with Cisco firmware 7.0.0 with the same issue 
workaround in v2.82 
see https://github.com/cisco-system-traffic-generator/trex-core/issues/508 
will close this issue for now track in #508
