### ISSUE TITLE
[Issue] "-nc" option does not stop in exact time in ASTF

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#500]
Hi,
If ASTF profile started with with "-nc 50 seconds", it stopped in 50 seconds in normal load situation.
But, in high load situation(4000 concurrent profiles running), stopping time increased up to 85 seconds.
Time difference was too high. Explicit stop command outside TRex can be considered, but, it's not the graceful way.
Is there any other ways to stop these profiles in wanted time in TRex side?

**Comment by hhaim** [comment]
It means that TRex CPU utilization is too high!! To solve this just reduce the multiplier or add more cores. It is a feature not a bug. See an explanation in our FAQ
