### ISSUE TITLE
Security alert on this binary file : wkhtmltopdf-amd64

### ISSUE THREAD

**Issue by rahendatri** [cisco-system-traffic-generator/trex-core#502]
Hello,
I got a security alert on a binary file named wkhtmltopdf-amd64 :
> "...File headers indicate anti-analysis techniques have been used to modify the file, which is used often by malware to avoid detection..."

Could somebody please confirm if this binary file came from the official repository of [wkhtmltopdf](https://wkhtmltopdf.org/downloads.html) ?

Regards,
rr

**Comment by hhaim** [comment]
@rahendatri thanks for reporting. It was used for generating NDR reports (HTML->PDF), but we moved to a new script and it is not used anymore.  it should be removed !

**Comment by rahendatri** [comment]
Hi @hhaim thank you for the fast response.
I understand now that the file is not used any more. But could you confirm if the file (that seems to be [wkhtmltopdf ](https://wkhtmltopdf.org/downloads.html)) came from the official repository ?

**Comment by hhaim** [comment]
@rahendatri I don't know, it was very long ago and I don't have the internal history before we published it to github.
I don't see a call to this exe anymore.

**Comment by bdollma** [comment]
Hello @rahendatri , the file was removed as you will see the next time we update the Github repo.
Thanks for reporting      ####👍.
Bes
