### ISSUE TITLE
Too long delay issue to reach maximum TCP throughput

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#512]
Hi,
During simulating FTP traffic, we found that current traffic behavior of TRex ASTF mode is quite differ from other real TCP stacks like Linux and BSD.
Other TCP stacks just took several seconds to reach the maximum throughput, but, TRex took at least 30 seconds(loop-back environment) ~ 60 seconds(Real environment).

It's quite different from real TCP behavior.
Setting tcp.no_delay=0x2(Force PUSH) can shorten time to several seconds, but, it generates too many Ack packets in reverse side. It's not suitable to simulate real traffic behavior like mobile network.
Is there any way to shorten this time to reach maximum TCP throughput without setting PUSH bit?

**Comment by hhaim** [comment]
@egwakim 
Are you using the ftp profile in the example folder?

**Comment by egwakim** [comment]
Modified, but, using similar example.

**Comment by hhaim** [comment]
There are a few issues with this profile:
1. You don’t have pipeline in the code, have a look in http_eflow2.py how to achieve this
2. Change initwnd to 10 or 20
2. There is a new mode of no_delay by amount of bytes, better to set it to 2mss (RFC)

**Comment by egwakim** [comment]
Thanks,
Much better now.

**Comment by hhaim** [comment]
@egwakim could you push the fix ftp profile

**Comment by egwakim** [comment]
Hi @hhaim 
The default value of tcp.no_delay_count is 0.
if (tcp.no_delay_counter = MSS*2) matches RFC5681, why it's not set to default?
Is there any special reason for it?

**Comment by hhaim** [comment]
@egwakim backward compatibility. We already published profile with different defaults
