### ISSUE TITLE
DPDK Command Not Found

### ISSUE THREAD

**Issue by bombblaster007** [cisco-system-traffic-generator/trex-core#514]
I am trying to install Trex on my Ubuntu 18.04 in a virtual machine on VMWare using the official manual https://trex-tgn.cisco.com/trex/doc/trex_manual.html

In the step 3.1.1 Identify the ports, I use the command sudo ./dpdk_setup_ports.py -s it gives me error that command not found. How can I resolve this?

I have tried installing sudo apt install dpdk but it still does not work.

**Comment by hhaim** [comment]
Please use our mailer for questions.
