### ISSUE TITLE
./b build failed

### ISSUE THREAD

**Issue by kruztw** [cisco-system-traffic-generator/trex-core#516]
error:
In file included from ../../src/dpdk/drivers/net/mlx5/mlx5.h:35:0,
                 from ../../src/dpdk/drivers/net/mlx5/mlx5_socket.c:19:
../../src/dpdk/drivers/common/mlx5/mlx5_glue.h:78:7: error: nested redefinition of ‘enum mlx5dv_dr_domain_type’
 enum  mlx5dv_dr_domain_type { unused, };
       ^~~~~~~~~~~~~~~~~~~~~
../../src/dpdk/drivers/common/mlx5/mlx5_glue.h:78:7: error: redeclaration of ‘enum mlx5dv_dr_domain_type’
In file included from ../../src/dpdk/drivers/common/mlx5/mlx5_prm.h:14:0,
                 from ../../src/dpdk/drivers/common/mlx5/mlx5_common.h:16,
                 from ../../src/dpdk/drivers/net/mlx5/mlx5_utils.h:15,
                 from ../../src/dpdk/drivers/net/mlx5/mlx5_socket.c:18:
/usr/include/infiniband/mlx5dv.h:1445:6: note: originally defined here
 enum mlx5dv_dr_domain_type {
      ^~~~~~~~~~~~~~~~~~~~~
In file included from ../../src/dpdk/drivers/net/mlx5/mlx5.h:35:0,
                 from ../../src/dpdk/drivers/net/mlx5/mlx5_socket.c:19:
../../src/dpdk/drivers/common/mlx5/mlx5_glue.h:91:8: error: redefinition of ‘struct mlx5dv_devx_event_channel’
 struct mlx5dv_devx_event_channel { int fd; };
        ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../src/dpdk/drivers/common/mlx5/mlx5_prm.h:14:0,
                 from ../../src/dpdk/drivers/common/mlx5/mlx5_common.h:16,
                 from ../../src/dpdk/drivers/net/mlx5/mlx5_utils.h:15,
                 from ../../src/dpdk/drivers/net/mlx5/mlx5_socket.c:18:
/usr/include/infiniband/mlx5dv.h:1353:8: note: originally defined here
 struct mlx5dv_devx_event_channel {
        ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../src/dpdk/drivers/net/mlx5/mlx5.h:35:0,
                 from ../../src/dpdk/drivers/net/mlx5/mlx5_socket.c:19:
../../src/dpdk/drivers/common/mlx5/mlx5_glue.h:93:0: warning: "MLX5DV_DEVX_CREATE_EVENT_CHANNEL_FLAGS_OMIT_EV_DATA" redefined
 #define MLX5DV_DEVX_CREATE_EVENT_CHANNEL_FLAGS_OMIT_EV_DATA 1
 
In file included from /usr/include/infiniband/mlx5dv.h:49:0,
                 from ../../src/dpdk/drivers/common/mlx5/mlx5_prm.h:14,
                 from ../../src/dpdk/drivers/common/mlx5/mlx5_common.h:16,
                 from ../../src/dpdk/drivers/net/mlx5/mlx5_utils.h:15,
                 from ../../src/dpdk/drivers/net/mlx5/mlx5_socket.c:18:
/usr/include/infiniband/mlx5_api.h:57:0: note: this is the location of the previous definition
 #define MLX5DV_DEVX_CREATE_EVENT_CHANNEL_FLAGS_OMIT_EV_DATA MLX5_IB_UAPI_DEVX_CR_EV_CH_FLAGS_OMIT_DATA
 
In file included from ../../src/dpdk/drivers/net/mlx5/mlx5.h:35:0,
                 from ../../src/dpdk/drivers/net/mlx5/mlx5_socket.c:19:
../../src/dpdk/drivers/common/mlx5/mlx5_glue.h:97:8: error: redefinition of ‘struct mlx5dv_var’
 struct mlx5dv_var { uint32_t page_id; uint32_t length; off_t mmap_off;
        ^~~~~~~~~~
In file included from ../../src/dpdk/drivers/common/mlx5/mlx5_prm.h:14:0,
                 from ../../src/dpdk/drivers/common/mlx5/mlx5_common.h:16,
                 from ../../src/dpdk/drivers/net/mlx5/mlx5_utils.h:15,
                 from ../../src/dpdk/drivers/net/mlx5/mlx5_socket.c:18:
/usr/include/infiniband/mlx5dv.h:1300:8: note: originally defined here
 struct mlx5dv_var {
        ^~~~~~~~~~

In file included from ../../src/dpdk/drivers/net/mlx5/mlx5.h:35:0,
                 from ../../src/dpdk/drivers/net/mlx5/mlx5_mp.c:13:
../../src/dpdk/drivers/common/mlx5/mlx5_glue.h:78:7: error: nested redefinition of ‘enum mlx5dv_dr_domain_type’
 enum  mlx5dv_dr_domain_type { unused, };
       ^~~~~~~~~~~~~~~~~~~~~
../../src/dpdk/drivers/common/mlx5/mlx5_glue.h:78:7: error: redeclaration of ‘enum mlx5dv_dr_domain_type’
In file included from ../../src/dpdk/drivers/common/mlx5/mlx5_glue.h:15:0,
                 from ../../src/dpdk/drivers/net/mlx5/mlx5.h:35,
                 from ../../src/dpdk/drivers/net/mlx5/mlx5_mp.c:13:
/usr/include/infiniband/mlx5dv.h:1445:6: note: originally defined here

I followed the website:
https://brezular.com/2019/08/01/cisco-trex-on-ubuntu-server-18-04/

and failed at ./b build

uname -a
Linux  5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hhaim** [comment]
Try with —no-mlx in the configuration stage

**Comment by kruztw** [comment]
not work.

first, I run:
./b --no-mlx configure
result:
The project was not configured: run "waf configure" first!

then, I run:
./b configure    # ok
./b --no-mlx configure 
result:
error as before   # error: nested redefinition of ‘enum mlx5dv_dr_domain_type’ ...

**Comment by kruztw** [comment]
./b configure:
Setting top to                           : /home/kruztw/trex-core
Setting out to                           : /home/kruztw/trex-core/linux_dpdk/build_dpdk
Checking for program 'strings'           : /usr/bin/strings
you have newer 3425 libstdc++.so remove the old one, do not commit this

mv: cannot stat '../scripts/so/x86_64/libstdc++.so.6': No such file or directory
Checking for program 'g++, c++'          : /usr/bin/g++
Checking for program 'ar'                : /usr/bin/ar
Checking for program 'gcc, cc'           : /usr/bin/gcc
Checking for program 'ar'                : /usr/bin/ar
Checking for program 'ldd'               : /usr/bin/ldd
Checking for library z                   : yes
Build sanitized images (GCC >= 4.9.0)    : no
Checking for OFED                        : Found version 5.0
Checking for library mnl                 : not found, will use internal version
Getting LD search path                   : ok
Checking for library ibverbs             : yes
Building bnxt PMD
'configure' finished successfully (0.243s)

/usr/bin/gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by hhaim** [comment]
./b distclean
./b configure —no-mlx
./b build

**Comment by kruztw** [comment]
./b distclean
Could not remove 'waf-2.0.18'
'distclean' finished successfully (0.002s)

./b configure --no-mlx
                        Destination filename for 'pkg' option.
  --publish-commit=PUBLISH_COMMIT, --publish_commit=PUBLISH_COMMIT
                        Specify commit id for 'publish_both' option (Please make sure it's good!)
  --no-bnxt             don't use bnxt dpdk driver. use with ./b configure --no-bnxt. no need to run build with it
  --no-mlx=NO_MLX       don't use mlx5 dpdk driver. use with ./b configure --no-mlx. no need to run build with it
  --with-ntacc          Use Napatech dpdk driver. Use with ./b configure --with-ntacc.
  --with-bird           Build Bird server. Use with ./b configure --with-bird.
  --no-ver              Don't update version file.
  --no-old              Don't build old targets.
  --private             private publish, do not replace latest/be_latest image with this image

  Configuration options:
    -o OUT, --out=OUT   build dir for the project
    -t TOP, --top=TOP   src dir for the project
    --prefix=PREFIX     installation prefix [default: '/usr/local/']
    --bindir=BINDIR     bindir
    --libdir=LIBDIR     libdir
    --check-cxx-compiler=CHECK_CXX_COMPILER
                        list of C++ compilers to try [g++ clang++ icpc]
    --check-c-compiler=CHECK_C_COMPILER
                        list of C compilers to try [gcc clang icc]
    --sanitized         for GCC 4.9.0+ use address sanitizer to catch memory errors
    --gcc6              use GCC 6.2 instead of the machine version
    --gcc7              use GCC 7.4 instead of the machine version
    --gcc8              use GCC 8.3 instead of the machine version

  Build and installation options:
    -p, --progress      -p: progress bar; -pp: ide output
    --targets=TARGETS   task generators, e.g. "target1,target2"

  Step options:
    --files=FILES       files to process, by regexp, e.g. "*/main.c,*/test/main.o"

  Installation and uninstallation options:
    --destdir=DESTDIR   installation root [default: '']
    -f, --force         force file installation
    --distcheck-args=ARGS
                        arguments to pass to distcheck
waf-2.0.18: error: --no-mlx option requires an argument                        Destination filename for 'pkg' option.
  --publish-commit=PUBLISH_COMMIT, --publish_commit=PUBLISH_COMMIT
                        Specify commit id for 'publish_both' option (Please make sure it's good!)
  --no-bnxt             don't use bnxt dpdk driver. use with ./b configure --no-bnxt. no need to run build with it
  --no-mlx=NO_MLX       don't use mlx5 dpdk driver. use with ./b configure --no-mlx. no need to run build with it
  --with-ntacc          Use Napatech dpdk driver. Use with ./b configure --with-ntacc.
  --with-bird           Build Bird server. Use with ./b configure --with-bird.
  --no-ver              Don't update version file.
  --no-old              Don't build old targets.
  --private             private publish, do not replace latest/be_latest image with this image

  Configuration options:
    -o OUT, --out=OUT   build dir for the project
    -t TOP, --top=TOP   src dir for the project
    --prefix=PREFIX     installation prefix [default: '/usr/local/']
    --bindir=BINDIR     bindir
    --libdir=LIBDIR     libdir
    --check-cxx-compiler=CHECK_CXX_COMPILER
                        list of C++ compilers to try [g++ clang++ icpc]
    --check-c-compiler=CHECK_C_COMPILER
                        list of C compilers to try [gcc clang icc]
    --sanitized         for GCC 4.9.0+ use address sanitizer to catch memory errors
    --gcc6              use GCC 6.2 instead of the machine version
    --gcc7              use GCC 7.4 instead of the machine version
    --gcc8              use GCC 8.3 instead of the machine version

  Build and installation options:
    -p, --progress      -p: progress bar; -pp: ide output
    --targets=TARGETS   task generators, e.g. "target1,target2"

  Step options:
    --files=FILES       files to process, by regexp, e.g. "*/main.c,*/test/main.o"

  Installation and uninstallation options:
    --destdir=DESTDIR   installation root [default: '']
    -f, --force         force file installation
    --distcheck-args=ARGS
                        arguments to pass to distcheck
waf-2.0.18: error: --no-mlx option requires an argument

**Comment by hhaim** [comment]
What is the distro, python version and gcc version?

**Comment by kruztw** [comment]
./b configure --no-mlx=mlx5   seems work

**Comment by kruztw** [comment]
uname -a
Linux paslab-System-Product-Name 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

python --version
Python 2.7.17

python3 --version
Python 3.6.9

gcc --version
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by kruztw** [comment]
./b configure --no-mlx=mlx5 
This command works fine.
