### ISSUE TITLE
Azure Wiki Instructions Seem to Skip a Step

### ISSUE THREAD

**Issue by MrPaulAR** [cisco-system-traffic-generator/trex-core#517]
Step: https://github.com/cisco-system-traffic-generator/trex-core/wiki/Build-For-Azure-Ubuntu-(mlx5)#follow-azure-dpdk-build---common

I don't have the folder structure listed in the diff command.  There is no "a" folder.

~/trex-core/linux_dpdk$ ls -1
BIRD_VERSION
b
bcov
build_dpdk
c_dumbpreproc.py
compile_bird.py
compile_bird.pyc
cov.py
d
version.c
version.h
waf-2.0.18
ws_main.py
ws_main.pyc
wscript

The diff command is failing.

~/trex-core/linux_dpdk$ diff --git a/linux_dpdk/ws_main.py b/linux_dpdk/ws_main.py
diff: unrecognized option '--git'
diff: Try 'diff --help' for more information.

**Comment by hhaim** [comment]
@MrPaulAR sorry for the complex wiki to make it work. We could make it simpler. 
Please try v2.79 tag as in latest DPDK things does not work

The instructions just show the diff, it does not mean you need to **run** it. 

you should open this file 
ws_main.py

and add return True in line 209. The same to the other change (- means remove the line)

```
 @@ -209,6 +209,7 @@ def check_ofed(ctx):
       ofed_ver= 42
       ofed_ver_show= '4.2'
  +    return True

```
