### ISSUE TITLE
Wrong Total-rx-pkt

### ISSUE THREAD

**Issue by karinlinux** [cisco-system-traffic-generator/trex-core#52]
Wrong Total-rx-pkt in trex version 2.28

**Comment by hhaim** [comment]
please provide more information

**Comment by karinlinux** [comment]
Trex always shows one more packets total_rx than total_tx
When I ran trex, I see that one packet (64 bytes) at the beginning of the test which considered at the total-rx statistics that make we always have one more packet rx than tx.
let me show a scenario:
i have ran the following command:
./t-rex-64 -c 1 -d 1 -m 1 -f cap2/dns_no_delay.yaml

the statistics that i see is:
 --------------
 Total-pkt-drop       : 0 pkts
 Warning : number of rx packets exceeds 101% of tx packets!
 Total-tx-bytes       : 170 bytes
 Total-tx-sw-bytes    : 0 bytes
 Total-rx-bytes       : 234 byte

 Total-tx-pkt         : 2 pkts
 Total-rx-pkt         : 3 pkts
 Total-sw-tx-pkt      : 0 pkts
 Total-sw-err         : 0 pkts
 Total ARP sent       : 2 pkts
 Total ARP received   : 0 pkts

I ran command in a back to back configuration

**Comment by hhaim** [comment]
"Trex always shows one more packets total_rx than total_tx
When I ran trex, I see that one packet (64 bytes) at the beginning of the test which considered at the total-rx statistics that make we always have one more packet rx than tx.
let me show a scenario:
i have ran the following command:
./t-rex-64 -c 1 -d 1 -m 1 -f cap2/dns_no_delay.yaml
the statistics that i see is:
Total-pkt-drop : 0 pkts
Warning : number of rx packets exceeds 101% of tx packets!
Total-tx-bytes : 170 bytes
Total-tx-sw-bytes : 0 bytes
Total-rx-bytes : 234 byte
Total-tx-pkt : 2 pkts
Total-rx-pkt : 3 pkts
Total-sw-tx-pkt : 0 pkts
Total-sw-err : 0 pkts
Total ARP sent : 2 pkts
Total ARP received : 0 pkts
I ran command in a back to back configuration
"

**Comment by ibarnea** [comment]
Hi,
When I run your command on ports connected in loopback, I see the counters as below (which is OK). Is it possible that you have some switch in the middle which issues the extra ARP packet?
--------------
 Total-pkt-drop       : 0 pkts
 Total-tx-bytes       : 170 bytes
 Total-tx-sw-bytes    : 0 bytes
 Total-rx-bytes       : 170 byte

 Total-tx-pkt         : 2 pkts
 Total-rx-pkt         : 2 pkts
 Total-sw-tx-pkt      : 0 pkts
 Total-sw-err         : 0 pkts
 Total ARP sent       : 2 pkts
 Total ARP received   : 0 pkts
