### ISSUE TITLE
Failed to start Trex with Intel 100G E810-CQDA2

### ISSUE THREAD

**Issue by selinaxue0** [cisco-system-traffic-generator/trex-core#520]
Test systems run Trex with Intel 100G E810-CQDA2 NIC card and met below error. 

I checked the trex-core/src/drivers/ and didn't find the ice driver which is for Intel 800 Serials NIC. 

[root@localhost ~]# ethtool -i enp75s0f0
driver: ice
version: 0.11.7
firmware-version: 0.50 0x800018f4 1.2233.0
expansion-rom-version:
bus-info: 0000:18:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

[root@localhost v2.82]# ./t-rex-64 -i -c 6 --cfg /etc/trex_cfg_cvl.yaml |tee trex_CVL_error.log
Starting Scapy server.... Scapy server is started
The ports are bound/configured.
Starting  TRex v2.82 please wait  ...
ERROR in DPDK map
Could not find requested interface 18:00.0
Killing Scapy server... Scapy server is killed

**Comment by hhaim** [comment]
It is not supported. Looked into the manual

**Comment by selinaxue0** [comment]
Thank you for the clarification, hhaim.  Could I know if there is a plan to support it recently?

**Comment by hhaim** [comment]
@selinaxue0 anyone with a NIC can add the support and pull request it.
