### ISSUE TITLE
[Suggestion] hugepage usage reduction

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#523]
Currently, 
TRex allocates hugepage for all NUMAs regardless it's usage.
But, in many cases, single NUMA used for the performance reason.
In the container based cloud solution, it's more critical issue because multiple containers need to utilize memory resource in efficient way.

The idea is simple,
Instead of allocating hugepages for all NUMAs, allocate hugepages for configured socket only.
In trex_cfg.yaml, we can configure CPU cores per socket,
Based on this configuration, we can configure hugepages.
For example,
in trex_cfg.yaml
if we set limit_memory to 1024, we can parse used socket numbers and allocate hugepages for it.
In dual NUMA case, we can reduce memory usage to 50%.
How about this improvement?

dual_if :
- socket : 0
    threads : [ 0, 2, 4 ]
- socket : 1 
    threads : [ 1, 3, 5 ]
All NUMA used : DPDK args = --socket-mem 1024,1024
                  
dual_if :
- socket : 0
    threads : [ 0, 2, 4 ]
Only NUMA0 used : DPDK args = --socket-mem 1024,0

dual_if :
- socket : 1 
    threads : [ 1, 3, 5 ]             
Only NUMA1 used : DPDK args = --socket-mem 0,1024

Best Regards
Gwangmoon

**Comment by hhaim** [comment]
@egwakim I think this is a good idea. There would be a need to optimized the dpdk_setup_ports to generate a configuration file that uses only NUMA>0. Today NUMA 0 is always used even if most cores are in NUMA>0
