### ISSUE TITLE
GTPU cleanup 

### ISSUE THREAD

**Issue by hhaim** [cisco-system-traffic-generator/trex-core#532]
1. remove the association between ```m_tuple_gen.has_active_client()``` to is_gtpu
```
    if (cur->check_limit() || !(cur->m_tuple_gen.has_active_clients() )){
        /* we can't generate a flow, there is a limit*/
        return;
    }
```

2. make the input support a mask ( for multi port support)

```if ( CGlobalInfo::m_options.m_enable_gtpu == i)
            {
              g_opts->m_ip_cfg[i].enable_gtp(1);
            }
```

3. 

void *tun_handle, instead of adding it do alloc_flow better to add a function to set it and only in case of tunnel to do so

```
CTcpFlow * alloc_flow(CPerProfileCtx * pctx,
                          uint32_t src,
                          uint32_t dst,
                          uint16_t src_port,
                          uint16_t dst_port,
                          uint16_t vlan,
                          bool is_ipv6,
                          void *tun_handle,
                          uint16_t tg_id=0,
                          uint16_t template_id=0);

    CUdpFlow * alloc_flow_udp(CPerProfileCtx * pctx,
                              uint32_t src,
                              uint32_t dst,
                              uint16_t src_port,
                              uint16_t dst_port,
                              uint16_t vlan,
                              bool is_ipv6,
                              void *tun_handle,
                              bool client,
                              uint16_t tg_id=0,
                              uint16_t template_id=0);
```
for example:

```
flow = alloc_flow(pctx,
                          src,
                          dst,
                          src_port,
                          dst_port,
                          vlan,
                          is_ipv6,
                          tg_id
                          template_id)
if (is_tunnel_aware()){
  flow->setTunnelData(tun_handle)
}
```

**Comment by jsmoon** [comment]
@hhaim I am interested in this feature also. Could you share the current status and future plan roughly?

**Comment by hhaim** [comment]
@jsmoon there is one commit that should be done in the client side, to make it work

The commit is about that:
1. API to turn off /turn on clients
2. Associate with client a general tunnel context for the tunnel creation 
3. Add documentation

The current code is GTP specific (in some places), I want to clean up the code in a way that all the tunnel code would be located in the same place (RPC,Client Conext, DP Add/Skip the tunnel) 
so it would be easy to add another tunnel (e.g. GRE tunnel)


One limitation is that each tunnel is associate with **one** core and it is **cannot** shared by number of cores

**Comment by jsmoon** [comment]
@hhaim thank you for your information!
> The current code is GTP specific (in some places), I want to clean up the code in a way that all the tunnel code would be located in the same place (RPC,Client Conext, DP Add/Skip the tunnel)

Would it be a big change from the initial code?

**Comment by hhaim** [comment]
@jsmoon, from the first place the original commit is not that big, so the cleanup should not be complex (most of the code is the add/skip gtpu)
The importance I saw from GTPU code is to have, first, a running code that work on a real scenario and then clean and make it more general (in the same model)
And I think they achieved that.

**Comment by jsmoon** [comment]
@hhaim, I got it. I'll wait until this feature is ready. Thanks.

**Comment by jsmoon** [comment]
@hhaim, according to my investigation, the current API("update_tunnel_client") is less useful for me.
It should be used after the client IP is registered.
Since the client IP is registered during BUILD, the first flow can be hardly adapted by "update_tunnel_client" API.
So, I think there is a way needed to set up the GTPU tunnel before the first flow generated.
@hhaim, please give me your opinion about this issue.

**Comment by hhaim** [comment]
@jsmoon there are two levels here. 
1. Working with API  - this is possible you ```load_profile```, call ```update_tunnel_client``` and then ```start```. 
2. Working with Console - This is not possible because start does both (load and start). 

due to 2, I've suggested to move the tunnel information to our client_cluster db. this will solve 2. it is not contradict the dynamic API to change tunnel information. 
we are planning to add this support

**Comment by jsmoon** [comment]
@hhaim `load_profile`, call `update_tunnel_client` and then `start` won't work.
This is the test result with API.
```
[verbose] Sending Request To Server:

{
    "id": "dhql01gy",
    "jsonrpc": "2.0",
    "method": "update_tunnel_client",
    "params": {
        "api_h": "0LwYhX6t",
        "attr": [
            {
                "client_ip": 268435457,
                "dip": "2.2.2.52",
                "sip": "1.1.1.51",
                "teid": 1,
                "version": 4
            }
        ],
        "tunnel_type": 1
    }
}



[verbose] Server Response:

{
    "id": "dhql01gy",
    "jsonrpc": "2.0",
    "result": {}
}



[verbose] Sending Request To Server:

{
    "id": "wwkmisnv",
    "jsonrpc": "2.0",
    "method": "get_clients_info",
    "params": {
        "api_h": "0LwYhX6t",
        "attr": [
            {
                "client_ip": 268435457
            }
        ],
        "is_range": false
    }
}



[verbose] Server Response:

{
    "id": "wwkmisnv",
    "jsonrpc": "2.0",
    "result": {
        "268435457": {
            "Found": 0
        }
    }
}

```

So I think I can make it work by the following change.
```
@@ -727,19 +728,23 @@ void TrexAstfDpCore::update_tunnel_for_client(CAstfDB* astf_db, std::vector<clie
 #endif
     for (auto elem : msg_data) {
         CIpInfoBase *ip_info = m_flow_gen->client_lookup(elem.client_ip);
-        if (ip_info) {
- 
 #ifndef TREX_SIM 
-           void *tunnel = ip_info->get_tunnel_info();
-           if (tunnel){
-               tfc.update_tunnel_object(elem, tunnel, tunnel_type);
-           } else {
-               void *tunnel = tfc.get_tunnel_object(elem, tunnel_type); 
-               ip_info->set_tunnel_info(tunnel);
-               ip_info->set_tunnel_type(tunnel_type);
-           }
-#endif
+        if (ip_info) {
+            void *tunnel = ip_info->get_tunnel_info();
+            if (tunnel){
+                tfc.update_tunnel_object(elem, tunnel, tunnel_type);
+                continue;
+            }
+            ip_info->inc_ref();
+        } else {
+            ip_info = new CSimpleClientInfo<CIpInfo>(elem.client_ip);             // <-- allocate new ip_info before profile started.
+            m_flow_gen->allocate_ip_info(ip_info);
         }
+
+        void *tunnel = tfc.get_tunnel_object(elem, tunnel_type);
+        ip_info->set_tunnel_info(tunnel);
+        ip_info->set_tunnel_type(tunnel_type);
+#endif
     }
 }
```
This concept can make the tunnel enable before a profile started.

**Comment by hhaim** [comment]
@jsmoon you are right, not sure how they work with that! ```load_profile``` in ASTF does not do anything, just move the json to all the cores. 
I think it is better to move the tunnel-json-info into the client-cluster DB as I suggested to them from the first place, this way it will be allocated with the right data in profile startup. 
The ```update_tunnel_for_client``` API is for advanced scenarios to change tunnel info in the middle of a session but it seems the basic does not work ... thanks for testing it.

**Comment by jsmoon** [comment]
@hhaim I think the client-cluster DB should be updated dynamically because my user does inform the client IP just before the additional profile loaded. If you make it a dynamic update possible, I'll wait for your change.

**Comment by hhaim** [comment]
@jsmoon I would like to achieve the following: 

from the console:
1) A simple way to load a profile with **static** tunnel info per client 
2) A simple way to change dynamically a client tunnel info per client 
3) The same from API

To achieve this I suggest to support both 
1) client-db info file, so user will add it before loading the profile-- this would be the default tunnel info  
2) A console command to change the tunnel info 

both 1,2 does not exits from the console today and we plan to add them

**Comment by jsmoon** [comment]
@hhaim thank you for your explanation. I'll wait for it.

**Comment by jsmoon** [comment]
@hhaim I found more issues in my perspective.
1. GTPU RX packet handled in the disabled port (when `--gtpu 0` used)
2. Inner packet header checksum could be invalid when the port has capable of header checksum offload.
Please consider them in your plan.

**Comment by hhaim** [comment]
@jsmoon thanks. @syaakov will look into this.

**Comment by jsmoon** [comment]
@hhaim @syaakov could I get the progress of this?
I can see the several GTPU issues are registered, but there is no update on them.

**Comment by hhaim** [comment]
@jsmoon you are right, @syaakov started to play with it and he found a number of issues that does not related to the **cleanup** task (it is another task). 
The main task right now is to move all the code to simulation in the same model we have today for other components as right now all the code is DPDK specific and is was not tested properly using valgrind in simulation. This is one of the reason of issues from the first place. 
@syaakov is a new developer in our team and work part time so it will take much longer to finish. 
If you have an urgency in some of the tasks (or all of them), you can choose to implement them,just let me know.  I can divert @syaakov to other tasks.

**Comment by jsmoon** [comment]
@hhaim I'd like to handle "gtpu mode: Inner packet header checksum could be invalid.".

**Comment by hhaim** [comment]
more cleanup issues. 

1. Add counters for tunnels (GTPU), errors etc
2. Add latency support 
3. Add read only cluster support so you can load the client tunnel info before the profile start 
4. Add support for DUT simulation in loopback --> remove/add tunnel to run GTPU in loopback ```--gtpu-debug```
5. Support more than 2 ports (today only 2 ports are supported)

**Comment by syaakov** [comment]
The above issues were fixed here:
1.  GTPU counters: https://github.com/cisco-system-traffic-generator/trex-core/commit/400f03c86c844a0096dff3f6b13e58a808aaefff
2.  Latency support: https://github.com/cisco-system-traffic-generator/trex-core/commit/a2d5c262485afba919dfa9ce65ab4c087926878b
3.  Read-only cluster: https://github.com/cisco-system-traffic-generator/trex-core/commit/0ccf1e99c1e41977668cc7d7580a95162203bb61
4. DUT simulation in loopback https://github.com/cisco-system-traffic-generator/trex-core/commit/46f66daee6d4ab0b8e7b63462547d6d3e6093f1f
5. Support more than 2 ports: https://github.com/cisco-system-traffic-generator/trex-core/commit/46f66daee6d4ab0b8e7b63462547d6d3e6093f1f
