### ISSUE TITLE
Traffic rate mismatch issue

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#538]
Hi,
In high loaded situation.
TRex traffic timing mismatch with actual time.
If temporary traffic burst exist during traffic generation, in spite of average load is not high, traffic will not be generated in wanted traffic ratio.
Virtual time in DP scheduler will be differ from real actual time.

It's quite crucial problem when user want to send traffic with exact speed.
User cannot send traffic with wanted traffic rate if eventual traffic burst exist during traffic generation.

There could be several solutions for it,
One solution would be recovering it when CPU is idle, process delayed packets and recover virtual time to actual time.
It'll be reasonable approach when the traffic burst is just temporary.

The disadvantage of this approach is,
In the long overloaded situation, such as high load with long duration time without idle time, we cannot recover it or it'll cause big time leap when CPU is idle again.

What do you think about this issue?
Do you have any suggestion about it?

Best Regards
Gwangmoon

**Comment by hhaim** [comment]
@egwakim you are right, In case the speed asked can't be provided there is no compensation and this is by design, it is not a bug. There is a conflict between the speed and total of bytes and we try to send the total bytes asked 
This happen in extrem cases that the user asked for more that it is possible.

Take this example 

* 10gbps port 
* 0..10sec  burst of 20gbps  (stream) total bytes 10*20g/8
* 10..20sec  : 0 gbps   total bytes 0 

In 0..10 seconds the time will be stretched to 20 seconds sending **only 10gbps**  because this is what it possible to do (the asked total bytes is OK (10*20g/8)
**then** there would be a wait for 10 seconds (it won't compensate for the burst in 0..10) 
The average speed would be 6gbps instead of 10gbps 

I don't see why we should conpensate as the user ask for a time with 0 gbps ..

**Comment by egwakim** [comment]
Hi @hhaim ,
I'm mentioning about the issue when 'short-term' burst case.
For example,
If we have 10 gbps port, sending traffic with average 1gbps and multiple traffic profiles runs up and down during transmission.
But, traffic rate burst in very short-term period like several mili-seconds(The worst case peak throughput 2gbps, CPU load 100%), this profile's time will be delayed in spite of average traffic ratio is under 10% and CPU is idle after burst.

In this case, user want to send traffic with exact traffic rate, but, user can not send traffic in spite of both port capacity and average CPU capacity is quite enough.

**Comment by hhaim** [comment]
@egwakim do you mean that you have **multiple** profiles each with 2gbps and the total of the all of them is a burst that is **much** more than 10gbps? for that we have a tx queue (~4000 pkts) that should absorb the burst, if the burst is higher than the queue then we are back to a *time streach* mode that I have described. 
If you don't like *time streach* mode, I think it possible to disable it in a global mode, I need to look into the code again but this was a feature not a bug ..

The 4000 pkts with 14MPPS (of 64B) could absorb a burst of ~300usec

**Comment by egwakim** [comment]
Hi @hhaim 
No, I meant the situation which total sum of throughput of multiple profiles is 2gbps.
Default tx/rx queue size is 512, we can increase it to 4096. 
The problem of time streach mode is that it does not go back to normal even though CPU and queue is quite idle enough.

**Comment by hhaim** [comment]
@egwakim it does not make sense that total of 2gbps with 10gbps ports creates a back-pressure (queue_full). 
Do you see queue full in this case? could you enlarge the tx queue size to 4096 to see if it helps?
In any case only in extreme cases, that you ask more that it could be supported, the scheduler is stretching the time and there is no compensation. 
I think it is possible to add another mode (to the scheduler) but it better to understand the issue first

**Comment by jsmoon** [comment]
@hhaim, the scheduler time stretching can be observed without tx queue full.
When I use an example that sends burst 1000 packets per flow, under my **net_i40e_vf** with **4096** rx_desc and tx_desc, I can see the time stretched.
The example snippet is
```
        total_pkts = 1000
        burst_pkts = 5
        # client commands
        prog_c = ASTFProgram(stream=False)
        prog_c.set_var("var1", total_pkts/burst_pkts)
        prog_c.set_label("c:")
        for _ in range(burst_pkts): # 1mpps
            prog_c.send_msg("x"*24)
        prog_c.delay(1)
        prog_c.jmp_nz("var1","c:")
```
The change to print out stretched time is
```
@@ -3562,6 +3562,7 @@ inline int CNodeGenerator::flush_file_realtime(dsec_t max_time,
 
     }/* while*/
 
+    std::cout << "stretched time: " << (offset - old_offset) << std::endl;
     return (teardown(thread,ON_TERIMATE,old_offset,offset));
 }
 
```
The observed time stretching is following:
```
stretched time: 0.00221832  <-- -d 10 -m 1
stretched time: 0.00859185  <-- -d 10 -m 10
stretched time: 0.0563978   <-- -d 10 -m 100
stretched time: 1.00236     <-- -d 10 -m 1000
```

According to my analysis, it depends on the total execution time of the scheduled nodes within EAT_WINDOW_DTIME(15usec). If the total time exceeds BURST_OFFSET_DTIME(100usec), the scheduler time is stretched.

I think the following options.
1. suppress scheduler time stretching by command line option or ASTFGlobalInfo
2. change time stretching condition to the extreme case only. (for instance, no scWAIT during several seconds)

I prefer option 1 by ASTFGlobalInfo.

**Comment by hhaim** [comment]
@jsmoon the problem is different the delay is in usec ```prog_c.delay(1)``` and EAT_WINDOW_DTIME is 15 usec 
so in your case you create a bursts of 1000 packets and **NOT** 5 as you might think and this is for every flow !! this is not normal. 

The scheduler works like this, it is trying to aggregate  up to 1000 packets and maximum window of 15usec for performance 
In you case every flow create burst of **full 1000** packets.
Could you change the delay to be 20-30 usec to corroborate it?
Again I want to understand the issue first

**Comment by hhaim** [comment]
@jsmoon 
one more thing

This is the feature that enable the time stench, try to disable it or enlarge BURST_OFFSET_DTIME to the queue size (~500usec) 
 
```
                if (dt > BURST_OFFSET_DTIME) {
                    state = scSTRECH;
```
You will get queue_full. Usually the profile are random and distribute,  If you create a very high bursts of 500usec this mechanism will get into work to slow you down

**Comment by jsmoon** [comment]
@hhaim, in my environment, receiving burst 1000 packets can be possible. The burst packets depends on the DUT behavior. My program is to simulate the situation. (I have been observed err_rx_throttled counter in my user's environment)

As I mentioned before, the burst RX packets is not the only reason to stretch the scheduler time. The sum of execution time for all the nodes within 15usec may exceed 100usec easily when multiple profiles are running dynamically.

As you suggested, increasing BURST_OFFSET_DTIME can be a candidate. It can reduce the occurrence of time stretching. But, under the environment of running multiple profiles with dynamic duration, I think disabling the time stretching is better option. What do you think about it?

**Comment by hhaim** [comment]
@jsmoon again, time stretch mechanism (TSM) was designed to do this:

1. Create micro bursts for better performance (up to 1000 pkts/15usec)
2. Avoid ```queue full``` by identify an issue ahead of time (~100usec) and try to stretch the time (throttle the tx)

BURST_OFFSET_DTIME should be lower than the tx queue size else you will experience "queue full" and we don't want this to happen 

If you want to simulate burst, your maximum burst is the size is the tx queue size which is ~4096 pkts which in maximum speed is ~200/400 usec, so I don't think you have a lot of freedom here 

Please enlarge the BURST_OFFSET_DTIME up to the point that you see queue full to verify how much freedom do we have. 

If it helps you have a way to mitigate this issue by enlarging the BURST_OFFSET_DTIME, I would add it to the RPC "setup_info"  and cache it in the scheduler. This way you would be able to *disable* it by setting the burst size higher than the queue size. 

I would not want to disable TSM globally for **all** use-cases, it helps for normal cases.

**Comment by hhaim** [comment]
@jsmoon setting BURST_OFFSET_DTIME to a very high value will create queue_full as I said but will have a **compensation** mechanism, meaning that very long burst will stall the cores but a bubbles of idle will be skipped.

back to my example

>>Take this example
   10gbps port
  0..10sec burst of 20gbps (stream) total bytes 10*20g/8
  10..20sec : 0 gbps total bytes 0

In this case the rate would be 10gbps over all the 20 sec time. After 4096 packets the queue full will be experienced

**Comment by jsmoon** [comment]
@hhaim, according to my analysis, TSM is affected by not only traffic behavior (TCP_RX_FLUSH, TCP_TX_FIF, TCP_TW) but also other behavior (FLOW_SYNC). If the lots of behaviors are running in the 15usec window, they affect TSM. My focusing point is this.

My simulation was to just show a sensitive case of TSM. It showed TSM could be performed under the quite low traffic and no tx queue full condition. That's it.

> If it helps you have a way to mitigate this issue by enlarging the BURST_OFFSET_DTIME, I would add it to the RPC "setup_info" and cache it in the scheduler. This way you would be able to disable it by setting the burst size higher than the queue size.
>
> I would not want to disable TSM globally for all use-cases, it helps for normal cases.

I want to disable TSM by request also. (not global)
Why don't you add it to the ASTFGlobalInfo.scheduler parameter?

**Comment by hhaim** [comment]
@jsmoon this is a scheduler configuration which is global to all profiles not just to **one** profile.  More other there should be a way to affect STL mode, not just ASTF.  (I think ```ASTFGlobalInfo``` includes global things already but better to find a better way)

**Comment by jsmoon** [comment]
@hhaim I understood.

**Comment by hhaim** [comment]
@jsmoon did you collaborate that enlarging BURST_OFFSET_DTIME value disable the TSM?

**Comment by jsmoon** [comment]
@hhaim, I did set the value to 500usec. It was better than before. But I observed it worked when the CPU load is high.

Basically, TSM is based on CPU load. Lots of scheduled non-traffic nodes may trigger it also.
Current TSM affects the traffic rate when the spot high CPU load observed.
I think this TSM should be affected by the traffic rate only.

Anyway, I need to suppress the TSM because my user wants to get an accurate average traffic rate.

**Comment by hhaim** [comment]
@jsmoon it is affected by BOTH CPU% and rate, if your CPU cannot handle the rate from any reason. 
let's me give an example, let's  say you 1tbps ports and you are trying to send 20gbps but your CPU can send only  10gbps (with the specific profile you have). TSM will be **activate**  because your requirement (**number of bytes to send in specific time) cannot be meet so the time is stretched! In this case there won't be a queue_full indication 

Again there are two a few constraint 

1. required throughput  
2. total number of bytes to send 
3. accuracy not to get to queue_full 

TSM try to solve 2,3 first. 

by setting BURST_OFFSET_DTIME  to very high value e.g. 1000,000usec you are effectivly disabling it

**Comment by egwakim** [comment]
Hi @hhaim ,
So, will you change it from your side?

**Comment by hhaim** [comment]
@egwakim we can, but I can't commit on ETA 
it should not be complex, just move the DEFINE to a variable that need to be change via RPC

**Comment by jsmoon** [comment]
@hhaim, I could change like as followed if you don't mind.
```
diff --git a/scripts/automation/trex_control_plane/interactive/trex/common/trex_client.py b/scripts/automation/trex_control_plane/interactive/trex/common/trex_client.py
index a54f630..eb9da03 100644
--- a/scripts/automation/trex_control_plane/interactive/trex/common/trex_client.py
+++ b/scripts/automation/trex_control_plane/interactive/trex/common/trex_client.py
@@ -1960,6 +1960,31 @@ class TRexClient(object):
 
 
     @client_api('command', True)
+    def set_dp_sched (self, stretch_time):
+        """
+            Change DP scheduler's parameters.
+
+            :parameters:
+                stretch_time: double
+                    Change minimum scheduler stretch time (seconds).
+                    Use large value to disable scheduler time stretch. Use 0 for reset changes.
+
+            :raises:
+                + :exc:`TRexError`
+
+        """
+
+        self.ctx.logger.pre_cmd("Changing DP scheduler's parameters")
+
+        rc = self._transmit("set_dp_sched", params = {'stretch_time': stretch_time})
+
+        self.ctx.logger.post_cmd(rc)
+
+        if not rc:
+            raise TRexError(rc)
+
+
+    @client_api('command', True)
     def push_packets (self, pkts, ports = None, force = False, ipg_usec = 0):
         """
             Pushes a list of packets to the server
diff --git a/src/bp_sim.cpp b/src/bp_sim.cpp
index 36b9a61..664f9f2 100755
--- a/src/bp_sim.cpp
+++ b/src/bp_sim.cpp
@@ -3608,9 +3608,11 @@ void CNodeGenerator::handle_time_strech(CGenNode * &node,
 
     /* fix the time offset */
     dsec_t dt = cur_time - n_time;
-    offset += dt;
-    /* set new offset */
-    m_scheduler_offset = offset;
+    if (!m_stretch_time || (dt > m_stretch_time)) {
+        offset += dt;
+        /* set new offset */
+        m_scheduler_offset = offset;
+    }
 
     /* check if flow sync message was delayed too much */
     if ( (cur_time - m_last_sync_time_sec) > SYNC_TIME_OUT ) {
diff --git a/src/bp_sim.h b/src/bp_sim.h
index 881f824..705f6bf 100755
--- a/src/bp_sim.h
+++ b/src/bp_sim.h
@@ -1346,6 +1346,11 @@ public:
 
     dsec_t                    m_last_sync_time_sec;
     dsec_t                    m_tw_level1_next_sec;
+
+    dsec_t                    m_stretch_time;
+
+public:
+    void set_stretch_time(dsec_t time) { m_stretch_time = time; }
 };
 
 
diff --git a/src/stx/common/trex_rpc_cmds_common.cpp b/src/stx/common/trex_rpc_cmds_common.cpp
index 1407297..70dff73 100644
--- a/src/stx/common/trex_rpc_cmds_common.cpp
+++ b/src/stx/common/trex_rpc_cmds_common.cpp
@@ -161,6 +161,11 @@ TREX_RPC_CMD(TrexRpcCmdGetRxQueuePkts, "get_rx_queue_pkts");
  */
 TREX_RPC_CMD(TrexRpcCmdTXPkts, "push_pkts");
 
+/**
+ * change DP scheduler parameter
+ */
+TREX_RPC_CMD(TrexRpcCmdSetDpSched, "set_dp_sched");
+
 /****************************** commands implementation ******************************/
 
 /**
@@ -1687,6 +1692,18 @@ TrexRpcCmdCancelAsyncTask::_run(const Json::Value &params, Json::Value &result)
     return (TREX_RPC_CMD_OK);
 }
 
+/**
+ * change DP scheduler parameters
+ */
+trex_rpc_cmd_rc_e
+TrexRpcCmdSetDpSched::_run(const Json::Value &params, Json::Value &result) {
+    double stretch_time = parse_double(params, "stretch_time", result);
+    auto fl = get_platform_api().get_fl();
+    for (auto thread: fl->m_threads_info) {
+        thread->m_node_gen.set_stretch_time(stretch_time);
+    }
+    return (TREX_RPC_CMD_OK);
+}
 
 /****************************** component implementation ******************************/
 
@@ -1732,6 +1749,7 @@ TrexRpcCmdsCommon::TrexRpcCmdsCommon() : TrexRpcComponent("common") {
     m_cmds.push_back(new TrexRpcCmdStopCapturePort(this));
     m_cmds.push_back(new TrexRpcCmdSetCapturePortBPF(this));
  
+    m_cmds.push_back(new TrexRpcCmdSetDpSched(this));
 }
 
 
```

**Comment by hhaim** [comment]
Hi, looks good in general, a few minor things 1) I've looked and there is
no get/set global configuration, better to rename to SetGlobalCfg
GetGlobalCfg And start with sched_max_stretch field This way it would be
easier to add a new field. BTW there is GetGlobalInfo RPC but this is read
only fields 2) better to change BURST_OFFSET_DTIME to be global variable in
CGlobal (which is likely to be in the cache) burst_size =
CGlobal::burst_offset_dtime
- if (dt > BURST_OFFSET_DTIME) { + if (dt > burst_size) { burst size will
be update when the first start will happen (it won't be possible to change
burst_offset when scheduler is working) Thanks Hanoh
