### ISSUE TITLE
Interface down-up during t-rex start

### ISSUE THREAD

**Issue by befarkas** [cisco-system-traffic-generator/trex-core#548]
Dear Team,

I am using the latest release, and I see that as soon as I start the trex, there is an interface down event happening on the interface which was up before. But only one interface of the pair, not both of them. The program recognizes it is a link-down, therefore sets 10mbps speed, and unable to resolve the destination MAC address. The interface is down for exactly 30 seconds, and then comes back, I could see it in the DUT router log. So when I try to start the stream, I must use the --force flag, and then it sends traffic, but because the dest mac was unknown, the reverse packets will not come back.

#######the wait which is triggered by the non-up interface, but the interface is down for 30 seconds instead of less than 10

wait 10 sec ..........
 WARNING : there is no link on one of the ports, interactive mode can continue
port : 0 

link         :  Link Down
promiscuous  : 0 

#######RESULT in console:

"ether": {
                    "dst": "00:ff:ff:ff:00:00",
                    "src": "d4:f5:ef:0c:e8:0e",
                    "state": "unconfigured"
                },
[trex-log.txt](https://github.com/cisco-system-traffic-generator/trex-core/files/5418829/trex-log.txt)
[trex-console.txt](https://github.com/cisco-system-traffic-generator/trex-core/files/5418831/trex-console.txt)

I attached in the file the debug logs, printouts, and everything.

Thank you for help!
BR: Bence

**Comment by hhaim** [comment]
@befarkas could you check with v2.79 which has an older DPDK version?

**Comment by befarkas** [comment]
Tested, issue is the same with same result.

In the router I see an exact 30 second down-up, any idea what process is making a 30 second up-down? it might would help to locate what call is triggering this.

*Oct 22 07:17:23.774: %LINK-3-UPDOWN: Interface GigabitEthernet2, changed state to down
*Oct 22 07:17:24.774: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet2, changed state to down
*Oct 22 07:17:53.774: %LINK-3-UPDOWN: Interface GigabitEthernet2, changed state to up
*Oct 22 07:17:54.774: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet2, changed state to up

**Comment by hhaim** [comment]
When you run trex server, the driver (DPDK) is initialized and it could take time to settled. 
Does the link stuck in down and the linux driver is up? if this is the case I would report it in DPDK mailer and would try to swap the cables
