### ISSUE TITLE
Enable trex for Intel I211 NIC

### ISSUE THREAD

**Issue by WqyJh** [cisco-system-traffic-generator/trex-core#550]
Intel I211 NIC has only two combined queues as shown below.
```bash
$ sudo ethtool -l enp1s0
Channel parameters for enp1s0:
Pre-set maximums:
RX:             0
TX:             0
Other:          1
Combined:       2
Current hardware settings:
RX:             0
TX:             0
Other:          1
Combined:       2
```

If you run trex on it you'd get the following error.

```bash
$ sudo ./t-rex-64 -f cap2/dns.yaml -d 10 -m 1000
The ports are bound/configured.
Starting  TRex v2.84 please wait  ...
 set driver name net_e1000_igb
 driver capability  : TCP_UDP_OFFLOAD  TSO
 set dpdk queues mode to DROP_QUE_FILTER
 Number of ports found: 2
zmq publisher at: tcp://*:4500
Ethdev port_id=0 nb_tx_queues=4 > 2
EAL: Error - exiting with code: 1
  Cause: Cannot configure device: err=-22, port=0
```

Which is caused by the following code.
```c++
    // One q for each core allowed to send on this port + 1 for latency q (Used in stateless) + 1 for RX core.
    m_max_queues_per_port = m_cores_to_dual_ports + 2;
```

However, if we don't need features like latency metric and arp refresh, the `m_max_queues_per_port` should be 1, and trex could run on I211.

**Comment by hhaim** [comment]
Just add —software to CLI

**Comment by WqyJh** [comment]
Thank you for your help, that works!

But there's two logical error in the codes I think need to be fixed.

First, there's no need to config latency queue and Rx queue when user doesn't specify options like `-l` or `--rx-check`.
```c++
    // One q for each core allowed to send on this port + 1 for latency q (Used in stateless) + 1 for RX core.
    m_max_queues_per_port  = m_cores_to_dual_ports + 2;
```

Therefore, conditions should be added like this.
```c++
    m_max_queues_per_port = m_cores_to_dual_ports;
    if ( CGlobalInfo::m_options.is_rx_enabled() ) { ++m_max_queues_per_port; }
    if ( CGlobalInfo::m_options.is_latency_enabled() ) { ++m_max_queues_per_port; }
```

Second, `get_dpdk_mode()` should not be called before `CGlobalInfo::m_dpdk_mode.choose_mode()`, otherwise it might encounter crash like #310 .
But there is an `get_dpdk_mode()` call by `parse_options()` which is called before `CGlobalInfo::m_dpdk_mode.choose_mode()`.

**Comment by hhaim** [comment]
No latency queue optimization is not supported anymore and won’t be supported. We have replaced it with software mode.
You can create PR that remove the CLI option

**Comment by zero-yx** [comment]
sorry，add what software to solve the problem?

**Comment by hhaim** [comment]
@zero-yx it should work in any version, just in software mode (--software)
