### ISSUE TITLE
issue with launching server in mode emu

### ISSUE THREAD

**Issue by daratitus** [cisco-system-traffic-generator/trex-core#557]
hello,

i have this error when i launch : ./t-rex-64 -i --astf --emu

root@t-rex1:/home/trex_repo/trex-core-2.84/scripts# cat /var/log/trex/emu_daemon_server.log
./trex-emu: line 12: ./trex_emu/trex-emu: No such file or directory

I think line 12 in trex-emu must be edited.

I have it like this now:

root@t-rex1:/home/trex_repo/trex-core-2.84/scripts# cat trex-emu
#! /bin/bash
INPUT_ARGS=${@//[��]/-} # replace bizarre minuses with normal one
EXTRA_INPUT_ARGS=""
TREX_LOGS_DIR="/var/log/trex"
EMU_LOG_PATH="$TREX_LOGS_DIR/emu_daemon_server.log"
ARCH=$(uname -m)
export LD_LIBRARY_PATH=$PWD/so/

if [[ "$ARCH" == "x86_64" ]] ; then
    mkdir -p $TREX_LOGS_DIR
    ./trex-emu $INPUT_ARGS &> $EMU_LOG_PATH
else
    echo "Default package support only x86_64. try compile trex-emu for your platform. "
    echo "https://github.com/cisco-system-traffic-generator/trex-emu "
fi
RESULT=$?

if [[ $RESULT != 0 ]]; then
    echo "trex-emu exit with a non zero code, check \"$EMU_LOG_PATH\" for more detalis"
fi

exit $RESULT
root@t-rex1:/home/trex_repo/trex-core-2.84/scripts#

But i have this error now when i launch t-rex in mode emu:

root@t-rex1:/home/trex_repo/trex-core-2.84/scripts# ./t-rex-64 -i -c 1 --software --emu
Starting Scapy server..... Scapy server is started
Starting Emu server......................................................................... Timeout
The ports are bound/configured.
Starting  TRex v2.84 please wait  ...
 set driver name net_ixgbe
 driver capability  : TCP_UDP_OFFLOAD  TSO
 set dpdk queues mode to ONE_QUE
 Number of ports found: 2
zmq publisher at: tcp://*:4500
 wait 1 sec .
port : 0
------------
link         :  link : Link Up - speed 10000 Mbps - full-duplex
promiscuous  : 0
port : 1
------------
link         :  link : Link Up - speed 10000 Mbps - full-duplex
promiscuous  : 0
 number of ports         : 2
 max cores for 2 ports   : 1
 tx queues per port      : 3
 -------------------------------
RX core uses TX queue number 65535 on all ports
 core, c-port, c-queue, s-port, s-queue, lat-queue
 ------------------------------------------
 1        0      0       1       0      0
 -------------------------------
Resource temporarily unavailable (src/thread.cpp:192)
./t-rex-64: line 100: 13904 Aborted                 (core dumped) ./_$(basename $0) $INPUT_ARGS $EXTRA_INPUT_ARGS
Traceback (most recent call last):
  File "general_daemon_server", line 233, in <module>
    action_funcs[args.action]()
  File "general_daemon_server", line 171, in kill_daemon
    run_command('kill %s' % pid) # usual kill
  File "general_daemon_server", line 70, in run_command
    close_fds = True, universal_newlines = True, preexec_fn = preexec_fn)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1295, in _execute_child
    restore_signals, start_new_session, preexec_fn)
BlockingIOError: [Errno 11] Resource temporarily unavailable
Could not stop scapy daemon server.
root@t-rex1:/home/trex_repo/trex-core-2.84/scripts#

Do you have any idea ?

Thanks

**Comment by hhaim** [comment]
It works with full package, In case you build it from scratch you should build and copy the exec
