### ISSUE TITLE
ASTF Tuneable issue

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#560]
@hhaim, according to my examination, some tuneable have issues.
1. mismatching between document and implementation: `ip.dont_use_inbound_mac` and `tcp.no_delay_counter` don't work for per-template. Please see CFlowTemplate::server_update_mac() and count_and_check_no_delay() each.
2. `tcp.no_delay_counter` does not reset by `reset_tuneables()`.
3. `scheduler.accurate = False` has the same effect on `scheduler.accurate = True`.

I'd like to discuss how they could be handled.

**Comment by hhaim** [comment]
@jsmoon thanks for looking into this. BTW who is doing this excellent QA?
1. Fix the doc or add the support 
2. Need to reset, it is a bug
3. Don't remember what I wanted to do there, I think there was two versions in my head (for ramp-up algo) and I ended up with one  (not accurate, update every 1 sec) , so better to remove this from doc and code as there was not a need for accurate (timer is working per 20usec, but rampup is updated every 1 sec)

**Comment by jsmoon** [comment]
@hhaim, I'd like to discuss one more thing.
As I added the document at #562, the current implementation is that only the first profile's global tuneable can be applied. But, the global IP tunable is available for each profile.
I think about making the TCP global tunable also available for each profile. It can run multiple clients and servers with different TCP parameters.
What do you think about it?

**Comment by hhaim** [comment]
@jsmoon I don't see a reason why not to do it. Multiple profile should behave as any profile.

**Comment by jsmoon** [comment]
@hhaim I found additional issues during source code analysis.

1. `tcp.keep*` tunable default values are not matched to implementation.
   for example, the `tcp_keepinit` variable has an initial value of 10. But it is the counter of TCP slow timeout (= 500ms). So, the default value of `tcp.keepinit` would be 5, but the document is 10.

2. `tcp.delay_ack_msec` will not update proper `tcp_slow_fast_ratio` value.
   `tcp_slow_fast_ratio` is calculated by `tcp_fast_ticks` timer tick counter instead of msec value.
   ```
        tcp_fast_ticks =  tw_time_msec_to_ticks(tune->m_tcp_delay_ack_msec);
        tcp_slow_fast_ratio = _update_slow_fast_ratio(tcp_fast_ticks);
   ```
   When `tcp.delay_ack_msec` is 20ms, `tcp_slow_fast_ratio` will be 1 and the TCP keepalive timer will expire in short time.

If I understood correctly, the TCP slow timeout should keep the value around 500ms.
I think the following code has a potential issue.
```
int CTcpPerThreadCtx::convert_slow_sec_to_ticks(uint16_t sec) {
    // tcp_slow_fast_ratio + 1 for the slow_tcp bug (tick starts at 0, ratio at 1)
    float sec_to_ticks = 1000.0f / ((tcp_slow_fast_ratio + 1) * TCP_TIMER_TICK_FAST_MS);
    return int(round(float(sec) * sec_to_ticks));
}
```
When the `tcp_slow_fast_ratio` is 9 (after issue 2 is fixed), `sec_to_ticks` will be 1. It means 1 sec converted to counter 1 and the TCP keepalive timer will expire earlier than expected.

What do you think about these issues?

**Comment by jsmoon** [comment]
@hhaim, I've tried to find a way to implement the per-profile global tunable.
Basically, I think I can move the tunable variables from CTcpPerThreadCtx to CPerProfileCtx.
But, when the `tcp.blackhole` tunable is different from other profiles, selecting the proper value is not easy.
For a simple solution, I can use FALLBACK_PROFILE_CTX for this.
If all the profiles have the same value, this approach will work as expected.

Could give me your opinion about this idea?

**Comment by hhaim** [comment]
@jsmoon moving the tunable per profile is a good idea. There would be always a tunables that would be global (like tcp.blackhole) but most of them could be local (per profile)

**Comment by jsmoon** [comment]
@hhaim I agree that tcp.blackhole would be global. But a user point of view, the tunable should be stated in a profile.
1. I think this type of tunable needs to be set by another method like set_global_cfg or others.
2. Or as I mentioned before, if the user could accept to have the restriction that all the profiles should have the same value, I can use any profile from FALLBACK_PROFILE_CTX.

**Comment by hhaim** [comment]
@jsmoon backward compatibility of one active profile is important. 
1. You could *add*  ```tcp.blackhole``` to  ```set_global_cfg``` but we can't remove it from tunable as old profile (single profile) will stop working. so my suggestion is to keep it per profile and update the global variable. new profile that would remove this could use the new way of ```set_global_cfg```

2. This could work along my suggestion with #1 as long as **one** profile works it is good.

**Comment by jsmoon** [comment]
@hhaim I agreed that backward compatibility is important.
With my PR #573, I've just raised. one profile works well with backward compatibility.
