### ISSUE TITLE
error while launching server in mode emu

### ISSUE THREAD

**Issue by daratitus** [cisco-system-traffic-generator/trex-core#566]
Hello,

I have this error : 
```
root@t-rex1:/home/trex_repo/trex-core-2.84/scripts# ./t-rex-64 -i -c 1 --software --emu
Starting Scapy server..... Scapy server is started
Starting Emu server......................................................................... Timeout
The ports are bound/configured.
Starting  TRex v2.84 please wait  ...
 set driver name net_ixgbe
 driver capability  : TCP_UDP_OFFLOAD  TSO
 set dpdk queues mode to ONE_QUE
 Number of ports found: 2
zmq publisher at: tcp://*:4500
 wait 1 sec .
port : 0
------------
link         :  link : Link Up - speed 10000 Mbps - full-duplex
promiscuous  : 0
port : 1
------------
link         :  link : Link Up - speed 10000 Mbps - full-duplex
promiscuous  : 0
 number of ports         : 2
 max cores for 2 ports   : 1
 tx queues per port      : 3
 -------------------------------
RX core uses TX queue number 65535 on all ports
 core, c-port, c-queue, s-port, s-queue, lat-queue
 ------------------------------------------
 1        0      0       1       0      0
 -------------------------------
Resource temporarily unavailable (src/thread.cpp:192)
./t-rex-64: line 100: 15901 Aborted                 (core dumped) ./_$(basename $0) $INPUT_ARGS $EXTRA_INPUT_ARGS
Killing Scapy server... Scapy server is killed
Emu server is NOT running
```
Do you have any idea ?

Thanks

**Comment by hhaim** [comment]
Try adding “low_end” to trex_cfg.yaml
You don’t enough resources on this VM

**Comment by daratitus** [comment]
Hi,

this is a big server with 4 10G ports, do I have to add "low_end" anyway ?

Thanks

**Comment by hhaim** [comment]
In that case there is need. Could you elaborate how do you get to this situation?
Could you put gdb? Is it with your own EMU server or with our package?

**Comment by daratitus** [comment]
I had this : 
```
root@t-rex1:/home/trex_repo/trex-core-2.84/scripts# cat /var/log/trex/emu_daemon_server.log
./trex-emu: line 12: ./trex_emu/trex-emu: No such file or directory
```
then i did : `cp trex-emu trex_emu/trex-emu`
to be noted that without emu mode, the server is working without any problems.

**Comment by daratitus** [comment]
I'm using your EMU server and your t-rex without any modifications

**Comment by hhaim** [comment]
@badr-bzh 
this 
>>I'm using your EMU server and your t-rex without any modifications

contradict this 

>> then i did : cp trex-emu trex_emu/trex-emu

Could you install a fresh latest package and test again? 
You should no copy anything with the package. If you build it from source, the issue could be explained as both the server and EMU should be build from the same tree

**Comment by badr-bzh** [comment]
I added the `low_end : true` and i still have the same error

**Comment by badr-bzh** [comment]
ok i will try with the latest package

**Comment by badr-bzh** [comment]
Hello, 
I tried with the latest package and i have this results:
`root@t-rex1:/home/trex2.86/scripts# ./t-rex-64 -i -c 1 --software --emu
Killing Scapy server... Scapy server is killed
Starting Scapy server..... Scapy server is started
Starting Emu server.... Emu server failed to run
Output: b'trex-emu exit with a non zero code, check "/var/log/trex/emu_daemon_server.log" for more detalis\n'
Could not start emu service
If you don't need it, don't use -emu flag.
ERROR encountered while configuring TRex system
`
and
`root@t-rex1:/home/trex2.86/scripts# cat /var/log/trex/emu_daemon_server.log
./trex-emu: line 12: ./trex_emu/trex-emu: No such file or directory
root@t-rex1:/home/trex2.86/scripts#
`
Do you have any idea ?
Thanks !

**Comment by badr-bzh** [comment]
Hello,
```
I tried with the latest package and i have this results:
root@t-rex1:/home/trex2.86/scripts# ./t-rex-64 -i -c 1 --software --emu 
Killing Scapy server... Scapy server is killed 
Starting Scapy server..... Scapy server is started 
Starting Emu server.... Emu server failed to run 
Output: b'trex-emu exit with a non zero code, check "/var/log/trex/emu_daemon_server.log" for more detalis\n' 
Could not start emu service 
If you don't need it, don't use -emu flag. 
ERROR encountered while configuring TRex system
```
and```

root@t-rex1:/home/trex2.86/scripts# cat /var/log/trex/emu_daemon_server.log
 ./trex-emu: line 12: ./trex_emu/trex-emu: No such file or directory 

```
Do you have any idea ?
Thanks !

**Comment by badr-bzh** [comment]
Hello,

I tried with the latest package and i have this results:
**_root@t-rex1:/home/trex2.86/scripts# ./t-rex-64 -i -c 1 --software --emu 
Killing Scapy server... Scapy server is killed 
Starting Scapy server..... Scapy server is started 
Starting Emu server.... Emu server failed to run 
Output: b'trex-emu exit with a non zero code, check "/var/log/trex/emu_daemon_server.log" for more detalis\n' 
Could not start emu service 
If you don't need it, don't use -emu flag. 
ERROR encountered while configuring TRex system_**
and

**_root@t-rex1:/home/trex2.86/scripts# cat /var/log/trex/emu_daemon_server.log
./trex-emu: line 12: ./trex_emu/trex-emu: No such file or directory_**

Do you have any idea ?
Thanks !

**Comment by bdollma** [comment]
Hello, 
Please upload here the **/var/log/trex/emu_daemon_server.log** file.
Also, please navigate to the **trex_emu/** directory and post here the output of **./trex-emu --version**
Thanks

**Comment by badr-bzh** [comment]
Here is the content of /var/log/trex/emu_daemon_server.log : 
`./trex-emu: line 12: ./trex_emu/trex-emu: No such file or directory`
`root@t-rex1:/home/trex2.86/scripts/trex_emu# ./trex-emu --version
-bash: ./trex-emu: No such file or directory
`
Do I have to download and build the trex-emu server independentally and then past it to /trex_emu/ ?
Thanks

**Comment by hhaim** [comment]
@badr-bzh I think I understand. When we say package we are referring to  this 
https://trex-tgn.cisco.com/trex/doc/trex_manual.html#_obtaining_the_trex_package

If you build from scratch, you need to follow the wiki

**Comment by bdollma** [comment]
Unless you have your own TRex code and changes please use the package provided by us which is already compiled.
Use the link Hanoch provided to download.

**Comment by badr-bzh** [comment]
yes i built from scratch, so i had to build the trex emu server too i guess.
i used the links https://trex-tgn.cisco.com/trex/release/
and problem solved !
Thank you @hhaim @bdollma
