### ISSUE TITLE
STL profile unexpected delayed start possibility

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#569]
@hhaim, my user observed a delayed start in STL mode.
He started a profile by start_traffic with 1-sec duration. But it seemed to start sending packets after several seconds. 
So, I checked the source and found a possibility.

This code is from DP start_traffic.
```
    /* update cur time */
    if ( CGlobalInfo::is_realtime() ){
        m_core->m_cur_time_sec = now_sec() + schd_offset;
    }
```
Since `CGlobalInfo::is_realtime()` is always true, these streams will be scheduled real-time(`now_sec()`) basis.
When DP scheduler time is stretched, the streams will be dispatched and performed after the stretched time passed.

```
DP scheduler dispatch time               now_sec()
                  | <-- stretched time --> |
                  v                        v
------------------*-------------------------*--------------------------
                                            ^
                                            |
                         new stream scheduled here
```

Do you have any idea to avoid this issue?

**Comment by hhaim** [comment]
@jsmoon what happen when you disable "stretched time "? does it solve the issue?

**Comment by jsmoon** [comment]
@hhaim definitely it could solve this issue. My user can avoid this issue by disabling it.
Since I found this possibility by source code analysis, I'd like to get a more nice solution.
 
Is there any reason to update `m_cur_time_sec` in here?

**Comment by hhaim** [comment]
In regards to this:
```   m_core->m_cur_time_sec = now_sec() + schd_offset;```
There is a reason. ```m_cur_time_sec``` is used to give an offset between DP cores (pipeline)
So when traffic is started it is possible to offset the timer in such way that it won't start at the same time on all the cores. 
It is not related to stretch time (BTW when this code have been written there was only **one** profile at a time so when we started the streams stretch was zero) 

In your case you see the issue when you have: 

1. one running profile that somehow stretch the time
2. start another profile

**Comment by jsmoon** [comment]
Yes, the possibility exists in multiple profiles.

But, I don't think this code gives the offset between DP cores due to the constant `schd_offset` value.
```
    double schd_offset = get_dpdk_mode()->dp_rx_queues()?
        SCHD_OFFSET_DTIME_RX_ENABLED:
        SCHD_OFFSET_DTIME;
```

As you mentioned, if it is not related to the stretch time, I think the stretch time effect needs to be removed.
In ASTF, there is no update of `m_cur_time_sec` while the new profile is added.

**Comment by hhaim** [comment]
@jsmoon the idea is to help not synchronizing all the cores, for example if you have 2 cores with total of 2 PPS. 
each core should have 1PPS but the there are two possibilities 

1.
```
    core1                *               *              *
    core2                *               *              *
           
```

or
2.  
```
    core1                *               *              *
    core2                        *               *              *
           
```

This mechanism try to do (2) and it was taken from STF (in STL it is less of an issue) and more in cases of low rates

**Comment by jsmoon** [comment]
@hhaim there is no core related factor in this code.
In STL, the mechanism trying to do (2) is accomplished by `m_mc_phase_pre_sec` during compile per core.
So I think the following code change can avoid the time stretch effect.
```
--- a/src/stx/stl/trex_stl_dp_core.cpp
+++ b/src/stx/stl/trex_stl_dp_core.cpp
@@ -1487,7 +1487,7 @@ TrexStatelessDpCore::start_traffic(TrexStreamsCompiledObj *obj,
 
     /* update cur time */
     if ( CGlobalInfo::is_realtime() ){
-        m_core->m_cur_time_sec = now_sec() + schd_offset;
+        if (m_state != TrexStatelessDpCore::STATE_TRANSMITTING) {
+            m_core->m_cur_time_sec = now_sec(); // because FLOW_SYNC is not running.
+        }
+        m_core->m_cur_time_sec += schd_offset;
     }
 
     /* no nodes in the list */
```
What do you think about this change?

**Comment by hhaim** [comment]
@jsmoon 
you mean this?
```
  m_core->m_cur_time_sec = now_sec()
  if (m_state != TrexStatelessDpCore::STATE_TRANSMITTING) {
     m_core->m_cur_time_sec += schd_offset;
   }
      
```

**Comment by jsmoon** [comment]
@hhaim
No, on STATE_TRANSMITTING state, updating `m_core->m_cur_time_sec` with `now_sec()` has race with `FLOW_SYNC`.
So, I thought it needs to be removed.
But, the first start_traffic is issued on a non-STATE_TRANSMITTING state. In this case, the `m_core->m_cur_time_sec` should be initialized and can be updated by `now_sec()` without race because FLOW_SYNC is not running.

**Comment by hhaim** [comment]
@jsmoon understood. 
I think we could remove this global ```m_core->m_cur_time_sec``` var
At startup code (start), it could be a var on the stack. 

so this 
```
...
    m_core->m_cur_time_sec =  0.01 + m_core->m_thread_id * m_core->m_flow_list->get_delta_flow_is_sec();

    if ( CGlobalInfo::is_realtime()  ) {
        if (m_core->m_cur_time_sec > 0.2 ) {
            m_core->m_cur_time_sec =  0.01 + m_core->m_thread_id*0.01;
        }
        m_core->m_cur_time_sec += now_sec() + 0.1 ;
    }

    dsec_t c_stop_sec = m_core->m_cur_time_sec + m_core->m_yaml_info.m_duration_sec;

```

to this ..


```
    cur_time_sec =  0.01 + m_core->m_thread_id * m_core->m_flow_list->get_delta_flow_is_sec();

    if ( CGlobalInfo::is_realtime()  ) {
        if (cur_time_sec > 0.2 ) {
            cur_time_sec =  0.01 + m_core->m_thread_id*0.01;
        }
        m_cur_time_sec += now_sec() + 0.1 ;
    }

    dsec_t c_stop_sec = cur_time_sec + m_core->m_yaml_info.m_duration_sec;
```

other places could be remove as nothing is done with this variable

**Comment by hhaim** [comment]
and places like this m_core->m_cur_time_sec could be replaced with now_sec() as it is not important to pipeline the stop 
```
        node->m_type = CGenNode::COMMAND;

        /* make sure it will be scheduled after the current node */
        node->m_time = m_core->m_cur_time_sec + duration ;
```

**Comment by jsmoon** [comment]
@hhaim, as far as I know, the deletion of the `m_core->m_cur_time_sec` variable is not easy.
There are many codes referring to the variables. This variable is used to get the current dispatching time.
In some cases, the current dispatching time is needed.

`CGenNode::COMMAND` case, in my memory, if `now_sec()` is used, the user cannot get an immediate response for the stop request due to the stretched time.

**Comment by hhaim** [comment]
@jsmoon I think it could be removed, but I agree that it could be not easy in current code base. 

My suggestion do minor change to what you suggested but do it for both STL and ASTF (both support multi-profile)

```
  if (m_state != TrexStatelessDpCore::STATE_TRANSMITTING) {
      m_core->m_cur_time_sec = schd_offset + now_sec() << set it once, we can touch it 
      cur_time = m_core->m_cur_time_sec
   }else {
    cur_time =  m_core->m_cur_time_sec + schd_offset  
    // we can't touch m_core->m_cur_time_sec
   }

   then use ```cur_time``` in the start nodes 
 
```

**Comment by jsmoon** [comment]
@hhaim O.K. I'll prepare a PR with the minor change.

**Comment by jsmoon** [comment]
@hhaim ASTF does not have this issue because `start_profile_ctx()` is called after the `start_scheduler()` is started.
So, I changed it for STL only.
