### ISSUE TITLE
trex client server profiles

### ISSUE THREAD

**Issue by SawsanY** [cisco-system-traffic-generator/trex-core#571]
Hi, please can I have help with this:
I am trying to launch a large scale IP prefix communication, the profile of client-server communication was working well, but the scenario was created only for duplicated src-dst, example
in the cap2/profile.yaml : client range is 10.0.0.1 , 10.0.0.10, server: 20.0.0.1 , 20.0.0.10
the result of traffic c which has been captured:
10.0.0.1 20.0.0.1
10.0.0.2 20.0.0.2
.
.
meanwhile, I need all the possible communication between these IP  ranges.
 can someone advise on this please?
Thank you

**Comment by hhaim** [comment]
@SawsanY you have a few options
1. choose random distribution 
2. choose seq but have a prime numbers in one of the ranges e.g. instead 10 and 10 have 13 and 10 or 10 and 13
