### ISSUE TITLE
ASTFProgram recv issues

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#572]
Hi,
my user wants to transfer TCP traffic more than 4Gbytes on a flow.
Since `recv` has the 32bit value limit, I made it called in the loop using by `jmp_nz`.
To make it work properly, `recv` should be used with `clear=True` due to the watermarking mechanism effect in the loop.

But, after the **non-block send** is used, another issue has been observed.
The **non-block send** triggers additionally received bytes when `recv` is called.
`clear=True` can remove them unexpectedly.
```
    inline void check_rx_condition(){
        if (m_cmd_rx_bytes>= m_cmd_rx_bytes_wm) {
            if (get_rx_clear()){
                m_cmd_rx_bytes=0;
                set_rx_clear(false);
            }
            EMUL_LOG(0, "ON_RX [%d]- NEXT \n",m_debug_id);
            next();
        }   
    }
```
The next `recv` cannot receive expected bytes. This makes user ASTF programming very tough.

@hhaim can you give me your opinion regarding this issue?

**Comment by hhaim** [comment]
@jsmoon have a look into the http_eflow3.py profile. 

```
 if r[1]==0:
          prog_c.recv(r[0])
        else:
            prog_c.set_var("var1",r[1]); # 
            prog_c.set_label("a:");
            prog_c.recv(r[0],True)
            prog_c.jmp_nz("var1","a:") # dec var "var2". in case it is *not* zero jump a: 
            if r[2]:
               prog_c.recv(bsize*r[2])
```

Maybe it would be better to change rx to 64bit

**Comment by jsmoon** [comment]
@hhaim I will change it to 64bit. Do I need to change the `recv_msg` also?

Anyway, I think the watermark mechanism issue in the loop needs to be solved also.
From the `recv` watermark mechanism and the loop, the user should fulfill the following restrictions.
```
    #prog_s.set_send_blocking(block=False)    # --  (1)
    prog_s.send('#'*first_size)
    prog_s.set_var("var1", loop)
    prog_s.set_label("a1:")
    prog_s.send('*'*size)                     # -- (2)
    prog_s.jmp_nz("var1", "a1:")
    prog_s.send('$'*last_size)

    prog_c.recv(first_size, clear=True)       # -- (3)
    prog_c.set_var("var1", loop)
    prog_c.set_label("a1:")
    prog_c.recv(size, clear=True)             # -- (4)
    prog_c.jmp_nz("var1", "a1:")
    prog_c.recv(last_size)
```
(1) the blocking send (default value) is mandatory to avoid unexpected receive buffer clear.
(2) syncing transfer size between send and receive is mandatory to avoid unexpected receive buffer clear.
(3) although this `recv` is out of the loop, clear=True is mandatory because the next `recv` is in the loop.
(4) clear=True is mandatory because size cannot represent the stacked watermark value in the loop.

I think (1) and (2) can be solved by the following change.
```
     inline void check_rx_condition(){
         if (m_cmd_rx_bytes>= m_cmd_rx_bytes_wm) {
             if (get_rx_clear()){
-                m_cmd_rx_bytes=0;
+                m_cmd_rx_bytes -= m_cmd_rx_bytes_wm;
                 set_rx_clear(false);
             }
             EMUL_LOG(0, "ON_RX [%d]- NEXT \n",m_debug_id);
```
What do you think about this suggestion?

Finally, what is your opinion for (3) and (4)?

**Comment by hhaim** [comment]
@jsmoon agreed. Need to do both. It is better to update the eflow_xx profiles but with your suggestion the old profiles, that we don't have control over, will continue to work too.

**Comment by jsmoon** [comment]
@hhaim I'll prepare a PR including **the 64bit support** and **the suggested change**.

**Comment by jsmoon** [comment]
@hhaim with my suggested change, I found the clear action will not work as documented.
![image](https://user-images.githubusercontent.com/4134762/99373049-4d64ed00-2904-11eb-9465-5e7eb0963613.png)
So, I'll find another solution.

**Comment by hhaim** [comment]
@jsmoon just changing it to 64bit will be backward compatible and will give the option to write cleaner programs
