### ISSUE TITLE
ASTFProgram wait_for_peer_close is not working properly

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#578]
Hi, I found that wait_for_peer_close is not working properly.

I changed `ftp_multiple_flows_sim.py` like the following.
```
        # server commands
        prog_s = ASTFProgram()
        prog_s.recv(len(self.ftp_get))
        prog_s.set_send_blocking (False) # Set to non-blocking to maximize thput in single flow
        prog_s.set_var("var2",loop); # set var 0 to loop
        prog_s.set_label("a:");
        prog_s.send('',size=self.max_buf_size,fill='*')
        prog_s.jmp_nz("var2","a:") # dec var "var2". in case it is *not* zero jump a:
        prog_s.wait_for_peer_close()
```
I think the server will wait for close from the client. But it does not work as I expected.
The connection is not closed properly.
![image](https://user-images.githubusercontent.com/4134762/99928916-8aaafe00-2d8e-11eb-93f1-f61afedb332f.png)

I captured the packets and I observed that the last packet was sent with the wrong sequence number.
![image](https://user-images.githubusercontent.com/4134762/99929019-f1301c00-2d8e-11eb-96fe-2bd7033b1fda.png)

@hhaim, Is it possible to send data with FIN?

Anyway I found that `CEmulApp::on_bh_tx_acked()` may call `next()` after the `wait_for_peer_close` is already called.
When I skipped calling the `next()`, `wait_for_peer_close` seems to work properly.

**Comment by hhaim** [comment]
@jsmoon 
You should set the last send to be blocking

**Comment by jsmoon** [comment]
@hhaim I know that. But I think that the `wait_for_peer_close` should make the same effect.

**Comment by hhaim** [comment]
@jsmoon understood now. So you want it to work the same when send non-blocking is done before wait_for_peer_close.
This feature **objective** is to send FIN-ACK-FIN-ACK without data. you need to change the state-machine to support this (non-blocking send and after that wait_for_peer_close().

**Comment by jsmoon** [comment]
@hhaim I have traced the `wait_for_peer_close()` effect.
It is converted to `tcDONT_CLOSE` and `process_cmd_one()` set `taDO_WAIT_FOR_CLOSE`.
I thought it intended to hold processing the next command to prevent close before send has been done.
But the next command is fetched at `on_bh_tx_acked()` actually and it triggered the FIN+data packet.
I don't know how I protect the unexpected FIN+data packet.

When I skipped the next command fetch, it performed as I expected.
```
--- a/src/44bsd/tcp_socket.cpp
+++ b/src/44bsd/tcp_socket.cpp
@@ -616,7 +616,7 @@ int CEmulApp::on_bh_tx_acked(uint32_t tx_bytes){
     if (add_to_queue) {
         m_api->tx_sbappend(m_flow,add_to_queue);
     }
-    if (is_next) {
+    if (!(m_flags&taDO_WAIT_FOR_CLOSE) && is_next) {
         EMUL_LOG(0, "ON_BH_TX [%d]-ACK \n",m_debug_id);
         next();
     }
```

**Comment by hhaim** [comment]
@jsmoon I don't remmeber the state-machine. try to run the unit-test and the new test you added. if all pass, and it has FIN without data, create a PR

**Comment by jsmoon** [comment]
@hhaim I think the changed `ftp_multiple_flows_sim.py` file is enough for the test.
What do you think about it?

**Comment by hhaim** [comment]
@jsmoon it is enough to test your new functionality, but the regression should work the same on old profile

**Comment by jsmoon** [comment]
@hhaim the regression `test_astf_prof_profiles` is running the `ftp_multiple_flows_sim.py`.
> but the regression should work the same on old profile

What do you mean? Don't touch the `ftp_multiple_flows_sim.py` and pass the regression with my change?

**Comment by hhaim** [comment]
@jsmoon what is the change for ```ftp_multiple_flows_sim.py``` ?

**Comment by jsmoon** [comment]
@hhaim it will be changed like this: remove blocking send + add wait_for_peer_close.
```
--- a/scripts/astf/ftp_multiple_flows_sim.py
+++ b/scripts/astf/ftp_multiple_flows_sim.py
@@ -33,25 +33,29 @@ class ftp_sim():
 
     def create_profile(self,fsize,nflows,tinc):
         self.tune_tcp(0)
-        loop = int(fsize*(1024*1024)/self.max_buf_size)
+        size_total = fsize*(1024*1024)
+        loop = int(size_total/self.max_buf_size)
+        remain = size_total%self.max_buf_size
 
         # client commands
         prog_c = ASTFProgram()
         if tinc != 0:
             prog_c.delay_rand(0,tinc*1000*1000)  # delay from 0 to random(tinc) seconds
         prog_c.send(self.ftp_get)
-        prog_c.recv(self.max_buf_size*loop)
+        prog_c.recv(size_total)
 
         # server commands
         prog_s = ASTFProgram()
         prog_s.recv(len(self.ftp_get))
-        prog_s.set_send_blocking (False) # Set to non-blocking to maximize thput in single flow
-        prog_s.set_var("var2",loop-1); # set var 0 to loop
-        prog_s.set_label("a:");
-        prog_s.send('',size=self.max_buf_size,fill='*')
-        prog_s.jmp_nz("var2","a:") # dec var "var2". in case it is *not* zero jump a:
-        prog_s.set_send_blocking (True) # back to blocking mode
-        prog_s.send('',size=self.max_buf_size,fill='*')
+        if loop:
+            prog_s.set_send_blocking (False) # Set to non-blocking to maximize thput in single flow
+            prog_s.set_var("var2",loop); # set var 0 to loop
+            prog_s.set_label("a:");
+            prog_s.send('',size=self.max_buf_size,fill='*')
+            prog_s.jmp_nz("var2","a:") # dec var "var2". in case it is *not* zero jump a:
+        if remain:
+            prog_s.send('',size=remain,fill='*')
+        prog_s.wait_for_peer_close()
 
         # ip generator
         ip_gen_c = ASTFIPGenDist(ip_range=["1.1.1.1", "1.1.1.100"], distribution="seq")
```

**Comment by hhaim** [comment]
@jsmoon understood. Yes, this is good to have to remove the complexity of the last send. 
Is the golden pcap exactly the same?

**Comment by jsmoon** [comment]
@hhaim where is the golden pcap? I can't find it for this profile.

**Comment by jsmoon** [comment]
@hhaim, is there anything else that I should do more?

**Comment by hhaim** [comment]
@jsmoon it's perfect. been busy.
