### ISSUE TITLE
dump abnormal packets

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#586]
Hi,
When I used the `FlowLatencyStats`, I can get the following error counters.
```JSON
"latency": {
                "324186556": {
                    "er": {
                        "drp": 2494,
                        "dup": 1,
                        "ooo": 12249674,
                        "sth": 3067419,
                        "stl": 12249675
                    },
"g": {
                    "bad_header": 84
                }
```
I'd like to get a dump of the abnormal ("dup" or "bad_header") packets with the counters for further analysis of DUT impact.
If I can get the "dup" packet on the fly, I can try the analysis of DUT impact without gathering whole packets by reproduction.
I think the current packet capturing by BPF filter is not appropriate for this requirement.

@hhaim what do you think about this requirement?

**Comment by hhaim** [comment]
@jsmoon I think this is a good idea, 
Usually capturing only *one* packet with the error won't give you much. 
For example, if you capture the "dup"  packet, for verifying it is really a "dup" you will need the history packets ..
The same for "drp" and "ooo". 
"bad_header" criteria is the only valid one that there is no need for history. 
I think it is better to have a ring of x packets (e.g. 5) and in case of an error, flush the ring, this will solve the "drp","ooo" and "dup"

**Comment by jsmoon** [comment]
@hhaim, I agree that the history packets will be a great help to inspect the "dup", "drp" and "ooo" issue.
Anyway, I have more questions for you.
1. Do you think the full packet dump is needed? I think the sequence numbers are enough for "drp" and "ooo" cases. 
2. "dup", "drp" and "ooo" are per-pgid counter. I think the history should be handled and dumped per pgid. What do you think about it?
3. How could I control the packet dump? always-on or user-specified? Do you have any idea about this?

**Comment by hhaim** [comment]
@jsmoon 
1. good idea, there is no need, we can copy only the last 12 bytes (out of 16 of metadata, MAGIC is not needed) and rebuild a default packets when saving to capture ring. Maybe we can use one of the default ip.value packet for the reason of the error (on all the ring packets)
2. yes, the ring of 12 bytes struct should per part of the pgid struct. I would put it as a pointer that would be allocated only when the feature is enabled on this pgid
3. In some cases we support 1024 PGID * 32 ports ~5MB of data. Better to enable it per pgid/all and only then to allocate the ring

**Comment by egwakim** [comment]
Hi @hhaim 
Regarding ooo(sth,stl), it's regarded as normal packets because it's counted as normal after all.
But, dup and bad_header is apparently abnormal case.

The purpose of this feature is providing 'light weight' simple method to trouble shoot abnormal packet issue.
It's not easy to analyze dup packet from captured packets and capturing also not easy job in high loaded situation.
In general, such abnormal packets found in high loaded situation, it's not easy to reproduce the issue if we enable the captures.

So, my suggestion is
It'll be better to dump abnormal packets(dup, bad_header) with very light weighted way if it's enabled.

BR
Gwangmoon

**Comment by hhaim** [comment]
@egwakim I agree, I just say that if we will add a ring of 12Byte * 5 (variable)  per pgid and only when enabled copy the header to the ring and flush when you get the packet with error ( dup, OOO .. ).
If your need is only for bad_header there is no need for a ring -- but do you get such issues ?

**Comment by jsmoon** [comment]
@hhaim, I'll prepare a PR to dump "bad_header" and "dup" packets for a simple approach.
