### ISSUE TITLE
Prevent TRex server abort from ASTF profile validation fail

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#597]
Hi,
Sometimes I've got the following message resulted to stop the TRex server.
```
terminate called after throwing an instance of 'Json::LogicError'
  what():  LargestUInt out of Int range
./t-rex-64: line 100: 26665 Aborted                 (core dumped) ./_$(basename $0) $INPUT_ARGS $EXTRA_INPUT_ARGS
```
Since I'm using multiple profiles, this causes unexpected results for other already running profiles.
So, I'd like to prevent the unexpected TRex server termination although the invalid ASTF profile is loaded.

According to my investigation, PARSE and BUILD operation in DP core could catch the Json::LogicError exception and handle it. But, the code location to catch the exception can be varied.

PARSE case
```
TrexAstfDpCore::::parse_astf_json())    ---- (1)
    +-- CAstfDB::set_profile_one_msg()    ---- (2)
    |   +-- CAstfDB::validate_profile()    ---- (2)
    +-- CAstfDB::verify_data()    ---- (2)
``` 

BUILD case
```
TrexAstfDpCore::create_tcp_batch())    ---- (1)
    +-- CFlowGenListPerThread::load_tcp_profile()
        +-- CAstfDB::get_db_ro()    ---- (2)
        +-- CAstfDB::get_db_template_rw()    ---- (2)
```

I think the catch code can be located at (1) or (2).
(1) can be a simple implementation at the top level.
(2) can handle the Json::LogicError where the JSON parser is used.

@hhaim which one do you prefer? (1) or (2)?
Do you have any suggestions to catch the Json::LogicError exception?

**Comment by bdollma** [comment]
@jsmoon 
Do you intend to add a new state in the handle?
Cause the user needs to understand that the profile is invalid.

**Comment by jsmoon** [comment]
@bdollma, no, there is no new state needed.
When the PARSE and BUILD operation failure will be ended to LOADED state.
And, as far as I know, when the PARSE and BUILD operation failed, the error message could be delivered to the client (user) by async message.

**Comment by bdollma** [comment]
@jsmoon 
So if you are sending him a failure message, why can't we discard the profile?

**Comment by jsmoon** [comment]
@bdollma, I think it is better to leave it to the user's choice.
Not all the PARSE and BUILD failures do not come from the invalid profile and JSON error.
For example, when a port collision between profiles is detected, the profile itself would be valid.

**Comment by bdollma** [comment]
@jsmoon 
I see what you mean but the difference between the two cases would be that a port collision can be resolved (the one profile using the ports finishes and now you can generate traffic) while a parsing error would require reloading the profile.

**Comment by jsmoon** [comment]
@bdollma
I agree that the PARSE failure case can be different from the BUILD failure case.
But I'm still thinking just the error information is enough.

The state machine by the user request is like this.
"profile_fragment" -> LOADED -> "start" -> (PARSE -> BUILD ->) TX -> "stop" -> (CLEANUP ->) LOADED -> "profile_clear" -> (DELETE) <removed>
In my opinion, after a user requests "start" at LOADED state,
the user would expect TX state if it is succeeded, LOADED state if it is failed.
After the user requests "start", if the profile disappeared, I think the user will be confused.

**Comment by jsmoon** [comment]
Hi,
According to my analysis, PARSE hardly raises the Json::LogicError exception with the normal client.
So I'll prepare a PR with a change for the BUILD case only at the location (1).

**Comment by hhaim** [comment]
@jsmoon agreed.
