### ISSUE TITLE
Incorrect handling of "split_mode" parameter of "load_pcap" method of STLProfile class

### ISSUE THREAD

**Issue by violenceway** [cisco-system-traffic-generator/trex-core#602]
While trying to replay a PCAP file, using "split_mode='IP'" parameter of "load_pcap" method of STLProfile class, following error occurs:

trex>start -f stl_pcap_replay.py --port 0 1 --force -t pcap=1mb.pcap,split='IP'

start -
Error loading profile 'stl_pcap_replay.py'

Python Traceback follows:

  File "stl_pcap_replay.py", line 28, in get_streams
    profile = STLProfile.load_pcap(pcap, ipg_usec=ipg, loop_count=loops, split_mode=split)
  File "/scratch/trex-core/scripts/automation/trex_control_plane/interactive/trex/stl/trex_stl_streams.py", line 1148, in load_pcap
    pkts_a, pkts_b = PCAPReader(pcap_file).read_all(ipg_usec, min_ipg_usec, speedup, split_mode = split_mode)
  File "/scratch/trex-core/scripts/automation/trex_control_plane/interactive/trex/stl/trex_stl_streams.py", line 1387, in read_all
    ts_usec = pkt.time * 1e6
TypeError: unsupported operand type(s) for *: 'Decimal' and 'float'

Seems like timestamp extracted from packet is of "decimal" type and can not participate in multiplication with data of type "float".
My custom script 'stl_pcap_replay.py' and pcap file '1mb.pcap' are provided in attachments.

[script_and_pcap.zip](https://github.com/cisco-system-traffic-generator/trex-core/files/5703477/script_and_pcap.zip)

**Comment by bdollma** [comment]
Hello,
Thanks for reporting this.
Scapy apparently changed the type of `pkt.time` to `Decimal` and we missed this in the last update.
We will fix it in the next release. 
For now, just convert `pkt.time` back to `float` as a temporary hack.
Thanks,
Bes

**Comment by violenceway** [comment]
Hi,

Thanks for clarification.
