### ISSUE TITLE
ASTF server send first issue

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#604]
Hi, this issue can be minor.
When I send first at the server-side, the first byte of the request would not be delivered.
```
           tcps_sndbyte |               128 |               249 | data bytes sent by application 
        tcps_sndbyte_ok |               128 |               248 | data bytes sent by tcp  
```
![image](https://user-images.githubusercontent.com/4134762/102458438-9933bf00-4087-11eb-9ea3-4d8f50375507.png)
![image](https://user-images.githubusercontent.com/4134762/102458669-eca60d00-4087-11eb-9a58-40b9cca76268.png)
As you can see in the picture, the first byte 'G' of "GET ..." was not included in the first data packet.

According to my investigation, during connection establishment (SYN -> SYN,ACK -> ACK), each ACK increases the acknowledge sequence number 1. If there is some data to send in the buffer where the last ACK received, the server treats the first byte already received by the client. (at src/44bsd/tcp_input.cpp)
```
1261         if (acked > so->so_snd.sb_cc) {
1262             INC_STAT_CNT(pctx, tg_id, tcps_rcvackbyte,so->so_snd.sb_cc);
1263             INC_STAT_CNT(pctx, tg_id, tcps_rcvackbyte_of,(acked-so->so_snd.sb_cc));
1264             tp->snd_wnd -= so->so_snd.sb_cc;
1265             so->so_snd.sbdrop_all(so);
1266             ourfinisacked = 1;
1267         } else {
1268             INC_STAT_CNT(pctx, tg_id, tcps_rcvackbyte,acked);
1269             so->so_snd.sbdrop(so,acked);  // <-- acked 1 byte here if there is some data (so->so_snd.sb_cc > 0)
1270             tp->snd_wnd -= acked;
1271             ourfinisacked = 0;
1272         }
```

I think this could happen because the `send()` from an application program is performed before the connection established. (at src/44bsd/flow_table.cpp)
```
 910     if (unlikely(temp->has_payload_params())) {
 911         lptflow->start_identifying_template(pctx, payload_info);
 912     } else {
 913         app->start(true); /* start the application */
 914     }       
 915 
 916     /* start listen */
 917     tcp_listen(lptflow->m_pctx,&lptflow->m_tcp);
```

@hhaim, do you know why the `app->start()` is called before `tcp_listen()`?

**Comment by hhaim** [comment]
@jsmoon can you provide the profile?  
```app->start(true)``` does not do much, it just enable the application and start the apps timer. The packet after ```tcp_listen``` is called is doing the job

**Comment by jsmoon** [comment]
```
--- a/scripts/astf/http_manual_commands.py
+++ b/scripts/astf/http_manual_commands.py
@@ -15,12 +15,12 @@ class Prof1():
      def create_profile(self):
         # client commands
         prog_c = ASTFProgram()
-        prog_c.send(http_req)
-        prog_c.recv(len(http_response))
+        prog_c.recv(len(http_req)-1)    # less 1 byte receive to continue
+        prog_c.send(http_response)
 
         prog_s = ASTFProgram()
-        prog_s.recv(len(http_req))
-        prog_s.send(http_response)
+        prog_s.send(http_req)
+        prog_s.recv(len(http_response))
 
         # ip generator
         ip_gen_c = ASTFIPGenDist(ip_range=["16.0.0.0", "16.0.0.255"], distribution="seq")
```

**Comment by hhaim** [comment]
Hi @jsmoon understood now (It was seems to me as a trivial case, only later saw that it is server->client)
The issue is that the buffer is added to the tx-queue **before** the flow was accepted by the server. 
adding ```accept()``` will solve this - it blocks the commands until the flow finish the state-machine 

for example:
```             
       prog_s = ASTFProgram()
        prog_s.accept()  <<<<<
        prog_s.send(http_req)
        prog_s.recv(len(http_response))

```
The solution is to add the ```connect``` command (```tcCONNECT_WAIT```) always as a first command in the server side.  (no matter if the first command is send or rcv). It could be done in client side (python) or server side (better)

**Comment by jsmoon** [comment]
Hi @hhaim, thanks for your good idea. The `accept()` works well.
And later I'll prepare a PR for the server-side solution.

**Comment by hhaim** [comment]
@jsmoon thanks for looking into it, I think the best way to solve it is just to add  CEmulAppCmd.tcCONNECT_WAIT (static) as a first command in case it is running in server mode. The issue is that the program is indirect and in cache in all other places and could be shared and used both by client and server so we **can't** change it in client side nor in the RPC side  

```
void CEmulApp::start(bool interrupt){
    /* there is at least one command */
    set_interrupt(interrupt);
    assert(m_program->get_size()>0);
    if (!is_udp_flow()) {
        m_q.set_window_size(m_api->get_tx_max_space(m_flow));
    }
    CEmulAppCmd * lpcmd=m_program->get_index(m_cmd_index); <<<<< here
    process_cmd(lpcmd);
    set_interrupt(false);
}
```
