### ISSUE TITLE
Example about "Simulate latency/jitter/drop in high rate" is missed in TRex ASTF documantation

### ISSUE THREAD

**Issue by Yurons** [cisco-system-traffic-generator/trex-core#605]
In TRex ASTF [documentation](https://trex-tgn.cisco.com/trex/doc/trex_astf.html) I found notes that we can simulate latency/jitter/drop in ASTF. Firstly in 2.1 Section #_feature_overview

> Performance and scale
> High bandwidth - ~200gb/sec with many realistic flows (not one elephant flow)
> High connection rate - order of MCPS
> Scale to millions of active established flows
> Simulate latency/jitter/drop in high rate
> Emulate L7 application, e.g. HTTP/HTTPS/Citrix- there is no need to implement the exact application.

  and in section [2.1.6. Simulation of latency/jitter/drop in high scale](https://trex-tgn.cisco.com/trex/doc/trex_astf.html#_simulation_of_latency_jitter_drop_in_high_scale)

Also I see mentions about drop and RTT in "2.3.10. Tutorial: Simple simulator" section.

So looks like TRex can do this in ASTF mode, but I couldn't find any example how to do this. And this is not clear for me.

**Comment by hhaim** [comment]
@Yurons this is part was written in the design phase. In the implementation phase this part wasn't implemented 
I will update the doc.

**Comment by hhaim** [comment]
see https://trex-tgn.cisco.com/trex/doc/trex_astf.html#_status (on radar)

**Comment by rashikrishna** [comment]
The documentation still mentions latency/jitter/packet drop simulation in ASTF. Is it supported now?

**Comment by rashikrishna** [comment]
@hhaim I still see documentation mentioning [simulation of latency/ jitter/ drop](https://trex-tgn.cisco.com/trex/doc/trex_astf.html#_simulation_of_latency_jitter_drop_in_high_scale). Is it supported now?
