### ISSUE TITLE
Hi, I want to  send 1M different tcp packets(vm is not suiteable),  what the bestest solution?

### ISSUE THREAD

**Issue by saimeny** [cisco-system-traffic-generator/trex-core#61]
I use the stateless trex client,  one transmission 5000 streams(because the limit is 20000) , find when stream's number exceed 400,  will drop 2 packet. The trex's version is v2.30.

**Comment by ybrustin** [comment]
Is it an option for you to put all the packets in pcap file, and then to use push_remote command?
(from trex-console: push -r)

**Comment by saimeny** [comment]
@ybrustin  I use like that ` c.connect()
    c.reset(ports = [0])

    # use an absolute path so the server can reach this
    pcap_file = os.path.abspath(pcap_file)

    c.push_remote(pcap_file = pcap_file,
                  ports = 0,
                  ipg_usec = 100,
                  count = 1)

    c.wait_on_traffic()`
in add_streams way, the server can receive the packets, but in this way does not, what's the difference between c.add_streams and the c.push_remote?  3q.

**Comment by ybrustin** [comment]
in push_remote, the file is opened at server side (path should be available at server)
