### ISSUE TITLE
mlx5 DPDK 21.02 with CX-4

### ISSUE THREAD

**Issue by hhaim** [cisco-system-traffic-generator/trex-core#626]
CX-4 and CX-4 VF are not stable with DPDK 21.02 there are spurious drops 
trex-23 is a CX-4 VF. for now this setup is going to be disabled 

![image](https://user-images.githubusercontent.com/13034429/107151027-336a0200-6969-11eb-93a1-36305a5e25f0.png)

**Comment by alialnu** [comment]
Hi @hhaim 
Can you please provide more information on how to reproduce this?

**Comment by hhaim** [comment]
@alialnu just run the **full** regression in the loop, there are many failures in various tests.  CX-5EN setup run without an issue.

**Comment by alialnu** [comment]
Hi @hhaim,
Do you still reproduce this issue with https://github.com/cisco-system-traffic-generator/trex-core/commit/aadd9abc7c7ea8eb1d937600a968dfc71e1b8393?

**Comment by hhaim** [comment]
v2.89 solves the issue
