### ISSUE TITLE
STLFlowLatencyStats does not work in MLX5 NIC

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#631]
Hi, my user wants to use MLX5 NIC in the SUT environment that the IP header can be changed.
There is no issue with Intel XL710 NIC VF in the same environment.
But, when MLX5 NIC used, the latency stats counter won't be updated. In this situation, there are packets on the receiver side actually.
```
   PG ID     |       0        |       1        
-------------+----------------+---------------
TX pkts      |             35 |             18 
RX pkts      |              0 |              0 
Max latency  |              0 |              0 
Min latency  |              0 |              0 
Avg latency  |              0 |              0 
-- Window -- |                |                
Last max     |              0 |              0 
Last-1       |                |                
Last-2       |                |                
Last-3       |                |                
Last-4       |                |                
Last-5       |                |                
Last-6       |                |                
Last-7       |                |                
Last-8       |                |                
Last-9       |                |                
Last-10      |                |                
Last-11      |                |                
Last-12      |                |                
Last-13      |                |                
---          |                |                
Jitter       |              0 |              0 
----         |                |                
Errors       |              0 |              0 

Port 1 (UL:tx, DL:rx) stats:
{
    "ibytes": 11956,
    "ierrors": 0,
    "ipackets": 98,  # <-- includes broadcast packet count (63)
    "obytes": 3924,
    "oerrors": 0,
    "opackets": 18,
    "rx_bps": 14939.1982421875,
    "rx_bps_L1": 17294.192443847656,
    "rx_pps": 14.718713760375977,
    "rx_util": 6.917676977539062e-05,
    "tx_bps": 5207.5166015625,
    "tx_bps_L1": 5685.270431518554,
    "tx_pps": 2.985961437225342,
    "tx_util": 2.2741081726074216e-05
}
Port 0 (DL:tx, UL:rx) stats:
{
    "ibytes": 7602,
    "ierrors": 0,
    "ipackets": 81,  # <-- includes broadcast packet count (63)
    "obytes": 6370,
    "oerrors": 0,
    "opackets": 35,
    "rx_bps": 9424.96484375,
    "rx_bps_L1": 11352.961212158203,
    "rx_pps": 12.04997730255127,
    "rx_util": 4.5411844848632814e-05,
    "tx_bps": 8233.240234375,
    "tx_bps_L1": 9137.991821289062,
    "tx_pps": 5.654697418212891,
    "tx_util": 3.655196728515625e-05
}
```

I had investigated this issue (packet received but does not update latency stats counter) and found the reason.

The difference between the two NICs is DPDK queue mode. MLX5 has **DROP_QUE_FILTER** compared to XL710 VF has **ONE_QUE**. 
In **DROP_QUE_FILTER** mode, `RXLatency::m_rcv_all` is not enabled and the received latency packet should keep the `FLOW_STAT_PAYLOAD_IP_ID` value in the IP header.
Otherwise, the received packets are not counted to the latency stats.

Although the `--software` may solve this issue, I'd like to solve this issue by supporting it with DROP_QUE_FILTER mode.
@hhaim, what do you think about my suggestion?

**Comment by hhaim** [comment]
@jsmoon your analysis is correct. The hardware filter is different betwean mlx5 and i40e driver due to the capabilities in the chip. 
In mlx5 the filter is based on the LSB bit of the TOS (ipv4 and ipv6). if the DUT changes this bit, it is not going to work and only software mode is the way to go. There is no other simple way to do hardware filter for this chip

**Comment by jsmoon** [comment]
@hhaim, in the DROP_QUE_FILTER mode, could I check the received packet's payload content if it is a latency packet?

**Comment by hhaim** [comment]
@jsmoon this is how the hardware works and it is documented. As you can see (ip.tos &0x01 ==0) so HW filter did not match. 
mlx5 driver does not have the capability to look into the end of the packet payload or to look into the ipv4.id. 
You can still work in software mode

**Comment by jsmoon** [comment]
@hhaim I understood that HW filter discards the packets (ip.tos & 0x01 == 0) in the DROP_QUE_FILTER mode.
The packets are definitely not counted to the latency stats.
But when the packet is captured (not discarded) in RX, it still won't be counted to the latency stats.
This mismatch made me confused.
