### ISSUE TITLE
T-Rex server time is going slightly faster than the host time.

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#634]
Hi, my colleague has been tried to convert captured packet timestamp to UTC.
He realized that T-Rex server time is slightly faster than host time.
I checked this issue and found the reason.

T-Rex server uses TSC(Timestamp Counter) from DPDK rte_rdtsc() for the elapsed time calculation.
And the frequency has been gotten from rte_get_tsc_hz(). Here is the frequency value.
```
(gdb) p timer_gd
$1 = {m_start_time = 752742161352728, m_1_div_freq = 4.1841004184100417e-10, m_freq = 2390000000} 
```

The m_freq is calibrated by CYC_PER_10MHZ in the following DPDK get_tsc_freq() routine.

```
uint64_t
get_tsc_freq(void)
{
#ifdef CLOCK_MONOTONIC_RAW
#define NS_PER_SEC 1E9
#define CYC_PER_10MHZ 1E7

        struct timespec sleeptime = {.tv_nsec = NS_PER_SEC / 10 }; /* 1/10 second */

        struct timespec t_start, t_end;
        uint64_t tsc_hz;

        if (clock_gettime(CLOCK_MONOTONIC_RAW, &t_start) == 0) {
                uint64_t ns, end, start = rte_rdtsc();
                nanosleep(&sleeptime,NULL);
                clock_gettime(CLOCK_MONOTONIC_RAW, &t_end);
                end = rte_rdtsc();
                ns = ((t_end.tv_sec - t_start.tv_sec) * NS_PER_SEC);
                ns += (t_end.tv_nsec - t_start.tv_nsec);

                double secs = (double)ns/NS_PER_SEC;
                tsc_hz = (uint64_t)((end - start)/secs);
                /* Round up to 10Mhz. 1E7 ~ 10Mhz */
                return RTE_ALIGN_MUL_NEAR(tsc_hz, CYC_PER_10MHZ);          // <-- here
        }
#endif
        return 0;
}
```

But, the Linux kernel message in the host shows that the TSC frequency is 2394.375 MHz.
```
# dmesg | grep TSC
[    0.068128] TSC deadline timer enabled
[    2.330124] tsc: Refined TSC clocksource calibration: 2394.375 MHz
```

The difference rate is 0.183%. ((2394.375-2390)/2394.375 = 0.001827199164709)
This means about a millisecond difference per 1 second.
I think it can be a quite large value.

@hhaim, what do you think about this?

**Comment by hhaim** [comment]
@jsmoon I agree, we can make the DPDK waits longer and make it more accurate.

**Comment by jsmoon** [comment]
@hhaim I found the regarding DPDK change(https://patches.dpdk.org/patch/51242/) and it seems to be coming from the ARM64 issue. So I think I should leave the change in the case of ARM64.

**Comment by hhaim** [comment]
@jsmoon ok
