### ISSUE TITLE
BIRD set_empty_config does not work

### ISSUE THREAD

**Issue by hhaim** [cisco-system-traffic-generator/trex-core#640]
It looks like there is a bug in PyBirdClient::set_empty_config()
If that function is called, subsequent calls to set_config() will fail even if the calling client is 
restarted, pybird must be killed to restore functionality.
A workaround is something like this:

``` 
defaultConfig = "router id 100.100.100.100;

  protocol device {

    scan time 1;
 
  }


  Pybird_c.set_config(new_cfg=defaultConfig)
```
  Right before ```pybird_c.release()```

 

  That way you have an empty config and you don’t have leftover mess in bird.conf when your 
  client exits.  A better solution would be when you PyBirdClient.disconnect() you should revert the 
  config if possible. The documentation does not address this.

**Comment by bdollma** [comment]
Solved in e22028de5c9cf936f825281116af725648a0151e.
