### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by fshahinfar1** [cisco-system-traffic-generator/trex-core#648]
Hi looks like there is a misspelling in `tui` reports. "statistics" was spelled as "statistitcs".
Just wanted to inform you.

I guess the issue is in the following line:

https://github.com/cisco-system-traffic-generator/trex-core/blob/2e497433ac6c888e735913d4d36b9add9db36b67/scripts/automation/trex_control_plane/interactive/trex/common/stats/trex_global_stats.py#L132

        stats_table = text_tables.TRexTextInfo('global statistitcs')

**Comment by fshahinfar1** [comment]
I could make a PR in order to close this issue. I am just not sure if it is something team wants to do.

**Comment by bdollma** [comment]
Hi, 
It is very minor but if you feel like it, you are welcome to make a PR.
Thanks for the catch.
