### ISSUE TITLE
Hi, can trex  just support one port?

### ISSUE THREAD

**Issue by saimeny** [cisco-system-traffic-generator/trex-core#65]
I use one port to send, do not care the recv ,but warning:

Configuration file /etc/trex_cfg.yaml should include even number of interfaces, got: 1
ERROR encountered while configuring trex system

**Comment by hhaim** [comment]
It is not possible in the current version

**Comment by saimeny** [comment]
OK, Thank you.

**Comment by fermulator** [comment]
Roadmap or other considerations/process to start thinking about it?
(who may I engage for such a discussion?)

**Comment by ybrustin** [comment]
It's in WIP state currently.

**Comment by hhaim** [comment]
released in v2.38

**Comment by qiaosiyi** [comment]
Hi, 
i am using TRex v2.61, and i just want to use one port in TRex,
this phy port can send and receive, so that i can test my outside loopback device.
i think dummy port setting may help.
my question is that is this requirement possible?
if possible, how can i set the  trex_cfg.yaml file.
