### ISSUE TITLE
Surplus packets issue on flow_latency_stat

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#650]
Hi,
Sometimes statistics counter of flow_latency_stats showed more Rx packets than Tx packets.
If ARP payload pattern matches with 16 bytes flow_latency_stats header, it can happen.
#define FLOW_STAT_PAYLOAD_MAGIC 0xAB
struct flow_stat_payload_header {
    uint8_t magic;               /* Always 0xAB */
    uint8_t flow_seq;
    uint16_t hw_id;           /*up to 1023(127) different streams */
    uint32_t seq;
    uint64_t time_stamp;  /* micro-seconds */
};

The last 16th ARP pattern starts with magic(0xab) and hw_id value is same as running traffic, it's counted as normal flow_latency packets.

To be able to avoid this issue,
One option would be isolating network except TRex, but, there are many equipments needed in the same network and isolation job is high costed job.

Another option would be preventing flow_latency counter increase for the broadcast packets because it's not the normal flow_latency packets.

How about dropping broadcast packets in flow_latency_stats ?

**Comment by hhaim** [comment]
@egwakim interesting. I think this is a good idea to keep only unicast packets. 
There is an effort to count multicast and broadcast

**Comment by jsmoon** [comment]
@hhaim I think the following change can be enough for this.
```
--- a/src/stx/common/trex_latency_counters.cpp
+++ b/src/stx/common/trex_latency_counters.cpp
@@ -211,7 +211,9 @@ void RXLatency::handle_pkt(const rte_mbuf_t *m, int port) {
           if (m_rcv_all && (!is_flow_stat_id(ip_id) ||
               (fsp_head->magic == FLOW_STAT_PAYLOAD_MAGIC &&
                fsp_head->hw_id < MAX_FLOW_STATS_PAYLOAD))) {
-            ip_id = FLOW_STAT_PAYLOAD_IP_ID;
+            if (rte_is_unicast_ether_addr(rte_pktmbuf_mtod(m, struct rte_ether_addr *))) {
+                ip_id = FLOW_STAT_PAYLOAD_IP_ID;
+            }
           }
           if (is_flow_stat_payload_id(ip_id)) {
             hr_time_t hr_time_now = os_get_hr_tick_64();
```

**Comment by hhaim** [comment]
@jsmoon correct

**Comment by jsmoon** [comment]
@hhaim should I add `rte_is_unicast_ether_addr` to the `src/pal/linux/mbuf.h`?
or should I block it using by `#ifndef TREX_SIM`?

**Comment by hhaim** [comment]
@jsmoon better to stub it and not to add ```#ifdef ```

**Comment by hhaim** [comment]
fixed https://github.com/cisco-system-traffic-generator/trex-core/commit/f2b10c6f0b689f638a9977832a0492af78098560
