### ISSUE TITLE
Add IPv6 support for ip_range

### ISSUE THREAD

**Issue by hesingh** [cisco-system-traffic-generator/trex-core#660]
Why doesn't trex support ip_range for IPv6 address?

**Comment by bdollma** [comment]
Hi, 
You need to be more specific. Why doesn't TRex support ranges for IPv6 where? In STL field engines?
If you mean why we don't have a IPv6 range like the [STLIPRange](https://github.com/cisco-system-traffic-generator/trex-core/blob/abbc1b790291f72fbcab94f416f851f15c89cfb6/scripts/automation/trex_control_plane/interactive/trex/stl/trex_stl_packet_builder_scapy.py#L2070) for field engines, the answer is that it is syntactic sugar. The field engine in TRex core works at byte level, hence it will work with IPv6 too. You are most welcome to implement it and open a PR.
Thanks

**Comment by hesingh** [comment]
It's terribly confusing to a new user of trex to see an[ imix_ipv6.py](https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/stl/imix_ipv6.py) and the first few lines of Python use IPv4 addresses.  The user think, is the script using IPv6 tunneled inside IPv4.  Only when one reads the whole script one sees trex has no support or ip6_range and instead hacks are being being used to create an IPv6 address range using IPv4 addresses.   When I get time, I will see what I can do to support IPv6 without using IPv4 address range.

**Comment by hesingh** [comment]
Using trex device engine API and without using any ip_range, I could develop a script for IPv6 source and destination address changing for 4096 stateless flows.
