### ISSUE TITLE
Tag to pull trex 2.86?

### ISSUE THREAD

**Issue by hesingh** [cisco-system-traffic-generator/trex-core#661]
How do I `git checkout` to a specific release tag for the trex repo?  I am interested in v2.86, but do not see a tag for this release.

```bash
~/trex-core/scripts/stl$ git tag
2.50
v.175
v.260
v.264
v1.74
v1.75
v1.76
v1.77
v1.78
v1.79
v1.80
v1.81
v1.82
v1.83
v1.84
v1.85
v1.86
v1.87
v1.88
v1.90
```

**Comment by bdollma** [comment]
Here:
https://github.com/cisco-system-traffic-generator/trex-core/releases/tag/v2.86

On the right side of the home page, click releases and you can find all the tagged versions.

**Comment by hesingh** [comment]
Thanks!
