### ISSUE TITLE
Can trex built on machine A be used on machine B? 

### ISSUE THREAD

**Issue by hesingh** [cisco-system-traffic-generator/trex-core#666]
I built my own trex build.  However, when I just copy all that exists in trex-core/scripts/ to a path, using trex 64bit binary invocation fails.

I could use a script or instructions for how to install software after building trex myself.  Right now, the only workaround I have is to copy the whole trex-core directory to path and then use trex binary apps.

**Comment by bdollma** [comment]
Actually, it does!
Here:
https://github.com/cisco-system-traffic-generator/trex-core/wiki

**Comment by hesingh** [comment]
I am aware of the wiki page but sorry, I don't see any install steps.

**Comment by bdollma** [comment]
What do you mean by install? This is not an executable file you need to run. It is a code base and you need to build it in order to run. 
It is clearly written in the wiki, that in order to build, you should do the following steps:
```
$cd linux_dpdk
$./b configure  (only once)
$./b build
```

**Comment by hesingh** [comment]
I have used the three steps above to build  and do understand trex is a codebase with many apps. However, I built trex-core on machine A.  If I need this built trex on machine B, is there a minimal set of directories in trex-core I copy to machine B or do I have to git clone trex again and build on machine B? Assume both machines are identical and run same OS and other software.

**Comment by bdollma** [comment]
Ok, this is another question totally from the title.
The whole repo is needed for TRex to work. So you need to copy the whole repo.
