### ISSUE TITLE
bp-sim-64-debug binary location?

### ISSUE THREAD

**Issue by davehouser1** [cisco-system-traffic-generator/trex-core#667]
Documentation [here ](https://trex-tgn.cisco.com/trex/doc/trex_manual.html#_basic_usage) shows examples of using "bp-sim-64-debug" binary. 

[This post](https://github.com/cisco-system-traffic-generator/trex-core/issues/100) mentions using this binary back in version 2.39, However I looked at 2.39 release and did not find the binary here either. 

Does this binary need to be compiled in some way? Where can I find this binary?

**Comment by hesingh** [comment]
The doc looks old.  You can use the following to run  the DNS test.

` sudo ./t-rex-64 -f cap2/dns.yaml -d 1 -l 1000`

**Comment by bdollma** [comment]
It is located in scripts folder if you are self compiled or in global scope if you download the client release.
Download the latest release and you will find it. https://trex-tgn.cisco.com/trex/release/
Also if you compile TRex it should be there, it simply is not part of the code base (in gitignore).
<img width="988" alt="Screen Shot 2021-03-20 at 9 26 41" src="https://user-images.githubusercontent.com/43345270/111862521-89659880-895e-11eb-8595-1f8140e3c734.png">
