### ISSUE TITLE
wait_on_traffic's rx_delay_ms doesn't seem to do anything

### ISSUE THREAD

**Issue by gabeblack** [cisco-system-traffic-generator/trex-core#668]
I setup a single stream in one direction (unidirectional) from port 0->DUT->port 1, pseudo code below:

```
all_ports = [0,1]
tx_port = [0]
c.reset(ports=all_ports)
c.add_streams(s1, ports=tx_port)
c.clear_stats()
c.start(ports=tx_port, duration=10)
# below call blocks
c.wait_on_traffic(ports=tx_port, rx_delay_ms=10000)
print("DONE!")
pprint.pprint(c.get_stats(sync_now=True))
```

The call to `c.wait_on_traffic()` only blocks the amount of `duration` in the call to `c.start()`. `rx_delay_ms` doesn't seem to have any effect at all. "DONE!" is always printed ~10 seconds after the call to `c.start()` no matter what `rx_delay_ms` is set to. Because my traffic is passing through a device that introduces latency and `rx_delay_ms` has no effect, my packet counts show will indicate dropped packets.

**Comment by bdollma** [comment]
Hi, 
What version are you using? We did some work on our async and that might have broken it.
Can you please try this on v2.87?
Thanks

**Comment by gabeblack** [comment]
Sorry for taking a while to respond. I am using 2.88. I installed 2.87 and the client to try it with that version. It seems like 2.87 works correctly. So this is introduced in v2.88

**Comment by bdollma** [comment]
Hi @gabeblack ,
I think the error might have been introduced at aa1b905a457e11736547816268ce569352ed4a52
If I recall correctly, **wait_on_traffic** uses the async functionality, and major changes were done in the aforementioned commit.
@hhaim would know best, he might take a look next week.
Thanks,

**Comment by hhaim** [comment]
@gabeblack I've looked into it on latest version and it works fine. 
the ```rx_delay``` is implemented in the python client side and it is applied only if **one** of the stream has a flow-stats/latency field.
You can add a delay yourself after the wait in case you want to read the counters without flow-stats/latency. 
```
c.wait_on_traffic(ports=tx_port, rx_delay_ms=10000)
delay_ms(10000)

```
The reason we added the ```rx_delay``` in the ```wait``` function is to remove the counters **rules** only after the in flight packets where counted
