### ISSUE TITLE
cache_size field question

### ISSUE THREAD

**Issue by DemyG** [cisco-system-traffic-generator/trex-core#67]
Hi all,

I am using Trex stl trafic profiles to test some VNFs' performace. In the following piece  of code ( part of scripts/stl/udp_1pkt_repeat_random.py), I don't really understand what cache_size actually is. It caches 255 packets or 255 bytes ? What is the maximum number it takes ?
```
 vm = STLScVmRaw( [   STLVmFlowVar ( "ip_src",
                                          min_value="10.0.0.1",
                                          max_value="10.0.0.255",
                                          size=4,
                                          step=1,
                                          op="inc"),
                           STLVmWrFlowVar (fv_name="ip_src",
                                           pkt_offset= "IP.src" ), # write ip to packet IP.src
                           STLVmFixIpv4(offset = "IP")                                # fix checksum
                         ],
                         split_by_field = "ip_src",
                         cache_size =255 # cache the packets, much better performance
                      ); 
```
Thank you in advance,
Dimitra

**Comment by hhaim** [comment]
Suggest to read the manual before asking questions.
https://trex-tgn.cisco.com/trex/doc/trex_stateless.html#_tutorial_field_engine_pre_caching_to_improve_performance

Hanoh
Sent from my iPhone

On 17 Nov 2017, at 11:11, DemyG <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi all,

I am using Trex stl trafic profiles to test some VNFs' performace. In the following piece of code ( part of scripts/stl/udp_1pkt_repeat_random.py), I don't really understand what cache_size actually is. It caches 255 packets or 255 bytes ? What is the maximum number it takes ?

 vm = STLScVmRaw( [   STLVmFlowVar ( "ip_src",
                                          min_value="10.0.0.1",
                                          max_value="10.0.0.255",
                                          size=4,
                                          step=1,
                                          op="inc"),
                           STLVmWrFlowVar (fv_name="ip_src",
                                           pkt_offset= "IP.src" ), # write ip to packet IP.src
                           STLVmFixIpv4(offset = "IP")                                # fix checksum
                         ],
                         split_by_field = "ip_src",
                         cache_size =255 # cache the packets, much better performance
                      );


Thank you in advance,
Dimitra

**Comment by DemyG** [comment]
ok, 

Thank you,
Dimitra
