### ISSUE TITLE
Stateless subscribers scale test script - is it correct?

### ISSUE THREAD

**Issue by hesingh** [cisco-system-traffic-generator/trex-core#670]
Please see the attached script.  The issue I see with this script at the DUT is "roughly 700 streams have packet counters increasing but rest of the 4094 streams have zero packet count".  The DUT is a VPP node which does not show any packets dropped.  Looks like trex is not sending traffic on all 4094 streams.  I suspect my script is not correct?

[stl-subs-py.txt](https://github.com/cisco-system-traffic-generator/trex-core/files/6176641/stl-subs-py.txt)

Is the issue on this line of the script?

`vm.var(name="mac_src", min_value=1, max_value=num_clients, size=2, op="inc")`

**Comment by hhaim** [comment]
@hesingh you can use the simulator to test the program. Replace ```fix_chksum_hw``` to software based checksum for the simulator. Another option is to capture the traffic in the rx side of the trex port

**Comment by hesingh** [comment]
@hhaim thanks.  Using trex capture monitor, I could verify the script is working fine with changing src-mac and IP src and dst.  With rx capture monitor, I see the packet have zero source IP which is not good.  It's an issue with my DUT, a VPP node.
