### ISSUE TITLE
Automatic ASTF profile stop when all flows are closed.

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#676]
This is a small improvement suggestion.

When there are limited long-lifetime flows in a profile, after the flows are closed, the profile would last to the profile duration time without traffic. If there is no profile duration specified, the profile status is TX but there is no traffic actually.
So, I'd like to improve this situation.
Especially in TCP flow, since the traffic duration will be varied by RTT in DUT, the appropriate profile duration is unpredictable.
I think this improvement would be helpful for this case.

Requirement:
For the limited flows profile, it should be stopped when there is no new traffic flow generation.

For example,
1. start a profile without duration, stop the profile automatically when all the limited flows are closed.
2. start a profile with duration and nc, before profile duration, stop the profile automatically without nc, after duration, stop the profile with nc.

If you agree to this improvement, I'll prepare a PR for this.
@hhain what do you think about this?

**Comment by jsmoon** [comment]
@hhaim could I get your opinion?

**Comment by hhaim** [comment]
@jsmoon I agree, it make sense
