### ISSUE TITLE
Mbuf_xx allocation with trex_cfg.yaml file

### ISSUE THREAD

**Issue by MD1614-TUD** [cisco-system-traffic-generator/trex-core#677]
This is a query regarding the understanding of the mbuf_xx allocation for different packet sizes. 

**Q1: Why do we have different mbuf_xx's allocated for two different servers having the same hardware?**

Description: I have two servers with the same hardware and hugepage configurations (Both have two 1G hugaepages). When I start the 'trex' on those two servers (with **default** config on both servers), the logs shows different values of allocated mbuf's. Any specific reasons would be a great help. Logs below:

**Server 1:**
```
Creating pool: small-pkt-const, count: 98280, size: 256, flags: 0
Creating pool: _128-pkt-const, count: 49140, size: 320, flags: 0
Creating pool: _256-pkt-const, count: 24570, size: 448, flags: 0
Creating pool: _512-pkt-const, count: 24570, size: 704, flags: 0
Creating pool: _1024-pkt-const, count: 24570, size: 1216, flags: 0
Creating pool: _2048-pkt-const, count: 57590, size: 2240, flags: 0
Creating pool: _4096-pkt-const, count: 14336, size: 4288, flags: 0
Creating pool: _9k-pkt-const, count: 14336, size: 9472, flags: 0
```
**Server 2:** 
```
Creating pool: small-pkt-const, count: 81900, size: 256, flags: 0
Creating pool: _128-pkt-const, count: 40950, size: 320, flags: 0
Creating pool: _256-pkt-const, count: 16380, size: 448, flags: 0
Creating pool: _512-pkt-const, count: 16380, size: 704, flags: 0
Creating pool: _1024-pkt-const, count: 16380, size: 1216, flags: 0
Creating pool: _2048-pkt-const, count: 45175, size: 2240, flags: 0
Creating pool: _4096-pkt-const, count: 7168, size: 4288, flags: 0
Creating pool: _9k-pkt-const, count: 7168, size: 9472, flags: 0
```
**Q2: When we assign the mbuf_xx values through the `trex_cfg.yaml` configuration file, what is the unit for those numbers? How do they map to the allocated mbuf number in the above logs?**

Example: By default `mbuf_256` has `8190` assigned. How this `8190` is mapped to the `_256-pkt-const, count: 24570` or `_256-pkt-const, count: 16380` ?

**Comment by hhaim** [comment]
@MD1614-TUD there is in the code a heuristic calculation that calculate a factor that is based on the number of ports and the speed of the ports.

**Comment by MD1614-TUD** [comment]
Thank you very much for the reply @hhaim. It will be a great help if you can point me to where in the code this calculation is done and which calculated factor shall I look into?

**Comment by hhaim** [comment]
```COLD_FUNC void update_memory_cfg() {
    CPlatformYamlInfo *cg=&global_platform_cfg_info;

    /* mul by interface type */
    float mul=1.0;
    if (cg->m_port_bandwidth_gb<10 || CGlobalInfo::m_options.m_is_lowend) {
        cg->m_port_bandwidth_gb=10.0;
    }

    mul = mul*(float)cg->m_port_bandwidth_gb/10.0;
    mul= mul * (float)CGlobalInfo::m_options.m_expected_portd/2.0;
    mul= mul * CGlobalInfo::m_options.m_mbuf_factor;
```

you can use the CLI option ```--mbuf-factor``` to change the factor (this is the ```CGlobalInfo::m_options.m_mbuf_factor```)

**Comment by MD1614-TUD** [comment]
Hi @hhaim, thank you for all the information provided. Now it is more clear to understand the mbuf_xx allocation. Closing the issue.

Recommendation: Adding some information in the documentation about the mempool configuration could be a good help.
