### ISSUE TITLE
Low TX rate with 512B frames

### ISSUE THREAD

**Issue by alialnu** [cisco-system-traffic-generator/trex-core#678]
Starting from TRex v2.80, there is a ~50% drop in TX rate with 512B frames.

The issue can be reproduced with `stl/bench.py`.

To reproduce, start TRex:
`$ ./t-rex-64 -i -c 14`

Then start traffic and monitor stats:
`> start -p 0 1 -m 100% -f stl/bench.py -t size=512,vm=cached`

This was caused by dbb64b2c, and the last good version is v2.79.

NIC: ConnectX-5.
Reproduces with multiple versions of MLNX_OFED (4.6-1.0.1.1, 5.2-2.2.0.0 and 5.3-1.0.0.1).

**Comment by hhaim** [comment]
@alialnu This is a mlx5 driver/ofed issue. trex code is the same. could you check with latest DPDK version v2.89 and latest ofed?

**Comment by alialnu** [comment]
> @alialnu This is a mlx5 driver/ofed issue. trex code is the same. could you check with latest DPDK version v2.89 and latest ofed?

I can also reproduce with v2.89.

**Comment by hhaim** [comment]
@alialnu it means that this is a dpdk mlx5 driver issue. try to figure out what was change betwean the DPDK. You can try to to git bisect to find the driver change that intruduce this.

**Comment by aleks-kozyrev** [comment]
@hhaim could you please try adding "dpdk_devargs : ['txq_inline_min=1','txq_inline_max=700']" to your trex_cfg.yaml file.
This should restore the performance for 512 bytes traffic generation.

**Comment by alialnu** [comment]
> 
> 
> @hhaim could you please try adding "dpdk_devargs : ['txq_inline_min=1','txq_inline_max=700']" to your trex_cfg.yaml file.
> This should restore the performance for 512 bytes traffic generation.

Thanks for the suggestion @aleks-kozyrev. Do you have an example of how to add this modification to the file?

**Comment by alialnu** [comment]
> 
> 
> > @hhaim could you please try adding "dpdk_devargs : ['txq_inline_min=1','txq_inline_max=700']" to your trex_cfg.yaml file.
> > This should restore the performance for 512 bytes traffic generation.
> 
> Thanks for the suggestion @aleks-kozyrev. I'll try it ~Do you have an example of how to add this modification to the file?~

Setting the devargs improves the rate with 512B frames, but degrades it with lower frame sizes.

**Comment by hhaim** [comment]
v2.91 solves this
