### ISSUE TITLE
Packet bit randomization support

### ISSUE THREAD

**Issue by sureshkvl** [cisco-system-traffic-generator/trex-core#68]
Does Trex support randomizing the bits in a packet.?

For example:
I want to randomize the UDP Source Port(0 to 65535) of my packet  when i run the throughput test.

Thanks
Suresh

**Comment by ybrustin** [comment]
You can do it in stateless mode.
https://trex-tgn.cisco.com/trex/doc/trex_stateless.html
Look for "field engine", "random"

**Comment by sureshkvl** [comment]
Thanks :)  I understand with this feature we can create millions of UDP  flows  by randomizing source/destination ports.
But how do i create Millions of TCP flows?

I see the mimic feature,(2.5.1. Using Stateless mode to mimic Stateful mode), can i create millions of tcp flows with  randomize the tcp ports(with full stream of packets - handshake, data and tear down)

Is it possible?

Thanks
Suresh

**Comment by ybrustin** [comment]
You can give same random_seed to streams of TCP flow converted from packets.
