### ISSUE TITLE
ASTF traffic duration with nc option

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#680]
Hi,

I have been used the ASTF profile of TCP traffic. The profile started with duration and nc.
But, when the `profile duration` is very short, sometimes the TCP flow cannot be connected within the duration.
Since the `m_traffic_duration` in the statistics is settled after the connection established, sometimes there is no traffic duration.
My user complaint about it. The delayed connection establishment can be natural when the DUT traffic path is in an idle state.

I understand that the `profile duration` is for the generation of new flows.
But when nc option is used, I think the `duration` would be traffic-related because it will stop the traffic.
So, I think that the profile duration could be synced with the traffic duration when both options(duration and nc) are specified.

![image](https://user-images.githubusercontent.com/4134762/114808054-7e2d4d80-9de2-11eb-9594-0c7b675b3eaf.png)

@hhaim what do you think about this?

**Comment by hhaim** [comment]
@jsmoon the all point of ``--nc`` mode is to stop the traffic just after the ```traffic_duration``` (stop new flow generation and stop **active flow** in the middle).  The reason for that is that you can't predict what would be a actual flow duration due to the drop rate, in some cases flow that has normally a duration of 1 sec without drop could take 100 sec to finish due to the drop. ``` --nc``` mode solves this by terminating just after the duration but the price is a statistic that is not accurate. 

I did not understand your suggestion but maybe the solution is to have a new mode that provides **two durations**. 

1. Duration for generating new flows 
2. Duration for waiting for active flows to terminate (in ``--nc`` mode this is zero while without it is unlimited)

**Comment by jsmoon** [comment]
@hhaim my suggestion is to separate the action of `duration` to `duration for new flow generation` and `duration for the traffic of active flows` when `--nc` is given.
The `--nc` mode will use the `duration` from the first connection establishment, not from the first flow generation.

**Comment by hhaim** [comment]
@jsmoon understood your suggestion now. I think it is not a good solution, what would happen if there is an issue with establishing the flows, how log would you wait? better to have two durations as I suggested earlier and just give enough time for at least one flow to be established

**Comment by jsmoon** [comment]
> what would happen if there is an issue with establishing the flows, how log would you wait?

My code will extend the duration during there are active flows. If there is no flow, the profile will be stopped immediately. i.e. maximum delay will be the first establishment time. In my investigation, it will be about **5 seconds** when all the establishments are failed. @hhaim, isn't it acceptable to you?

> better to have two durations as I suggested earlier and just give enough time for at least one flow to be established

My code has two durations internally. The one is `m_time_stop` for flow generation and another one is `m_traffic_duration` for active flow termination. The new `m_traffic_duration` is activated after the first establishment. Do you want it (the duration for the active flow termination) is explicitly assigned by a user?

**Comment by hhaim** [comment]
@jsmoon let's give an example to see that I understand

traffic_duration=1 sec
time to establish the first flow is 2 sec. 

The actual duration would be 2+1 = 3 sec. 
in case the first flow would take 6 sec to establish the test will stop after 5 sec with no active flows.

my question is why do we need this implictly?, either give enough time for the flow to be established in the duration of the test or provide explicitly the establish timeout. The main issue is more in the teardown when the time could be stretched to be very long due to drop and in this case better to have explicit timeout in case of ```--nc``` 

so my recommendation is to add 2 **explicit** timeouts (+ traffic_duration) 
1. Timeout for first establishment flow - today it is zero with ```--nc```
2. Timeout for tear-down - today it is zero ```--nc ```

**Comment by jsmoon** [comment]
> in case the first flow would take 6 sec to establish the test will stop after 5 sec with no active flows.

Yes, in this case, it will be the same result as without `--nc`. 

> my question is why do we need this implictly?

I thought this way could give less complicity for the user.

> either give enough time for the flow to be established in the duration of the test or provide explicitly the establish timeout. The main issue is more in the teardown when the time could be stretched to be very long due to drop and in this case better to have explicit timeout in case of `--nc`

To be stretched to a very long time, there should be no SYN+ACK for the stretched time at all. I thought it could be a kind of abnormal case on the DUT and would be no problem.


@hhaim I think you don't agree that `duration` is treated as `traffic duration` implicitly when `--nc` is given. I got it.
But I'm still not sure what you recommended.

> so my recommendation is to add 2 explicit timeouts (+ traffic_duration)

Do you mean that I should add two timeout parameters to the start command?

> 1. Timeout for first establishment flow - today it is zero with `--nc`
> 2. Timeout for tear-down - today it is zero `--nc`

I'm confusing how the timeout values should work with `--nc`.
Could you show examples of behavior for each case?

@hhaim please give your answer to my questions one by one for my clear understanding.

**Comment by hhaim** [comment]
>> Do you mean that I should add two timeout parameters to the start command? 

Yes, add two durations for advance users in the start command (on top of the traffic_duration), the default values of those durations are:
in case of ``--nc`` 0,0 and with normal operation it would be 0,infinit 

for example:

```start -f profile.py --e_duration 5 --t_duration 200 --nc --duration 100```

1. 5 sec to wait  for the first flow to be established 
2. 100 sec duration for new flows generation (**after** the first flow was established)
3. 200 sec maximum duration for tear-down (will exist in case active_flow=0)

The durations will work in both cases (``--nc`` and normal). It will override the default values in case of ``--nc`` (0,0) and in case of normal (0,infinit). 
With this proposal there is a backward comparability 
 
>>Could you show examples of behavior for each case?

see below

**Comment by jsmoon** [comment]
@hhaim I think the following comments need to be amended if I understood correctly.

> 2. 100 sec duration for new flows generation (after the first flow was established)

Do you mean that the **flow establishment** is the start point of the traffic duration? If `--duration` is working like this, after the first flow was established, I don't need to change anything.
(after the first flow was established) should be changed to (after the first flow generation is started)

> 3. 200 sec maximum duration for tear-down (will exist in case active_flow=0)

I think `exist` should be changed to `exit`.

Anyway, what is the base time for the `--t_duration`? I think it is the start point of the traffic duration, right?
If my understanding is correct, I'll update my PR as you suggested.

**Comment by hhaim** [comment]
>> Do you mean that the flow establishment is the start point of the traffic duration? If --duration were working like this, after the first flow was established, I wouldn't need to change anything.

Yes. if provided. by default it is zero in both cases (normal and nc)

>> I think exist should be changed to exit.

Correct. typo 


>> anyway, what is the base time for the --t_duration? I think it is the start point of the traffic duration, right?
  
Yes

**Comment by hhaim** [comment]
@jsmoon just to clear one more thing, 
```e_duration``` equal to zero is a special case. it means there is no need to wait  for a flow to be opened and the traffic duration starts immediately (as it is implemented currently), only time higher than zero waits for one flow to be established.

**Comment by jsmoon** [comment]
@hhaim, the current implementation is that the traffic duration (which is reported as statistics) starts when one connection is established.

**Comment by hhaim** [comment]
> @hhaim, the current implementation is that the traffic duration (which is reported as statistics) starts when one connection is established.

when you say ```the current implementation``` do you mean before your commit?

**Comment by jsmoon** [comment]
@hhaim yes.

**Comment by hhaim** [comment]
@jsmoon I don't think so, the timer of ```traffic_duration``` starts without any relation to the establishment of the flows

**Comment by jsmoon** [comment]
@hhaim but the `m_traffic_duration` in ASTF statistics have been calculated by the establishment time of the flows.

**Comment by hhaim** [comment]
@jsmoon understood now. there are two things, 
1. Statistic ```m_traffic_duration```
2. Traffic_duration for  new flow generation. I referred to this and not for how the statistic is collected 
I've talked about 2 and you about 1.  in our case we are not using ``m_traffic_duration``` so I don't care to change it
