### ISSUE TITLE
[New feature] LAG/LACP support in TRex

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#683]
Hi,
We need to use LAG/LACP with TRex.
Fortunately, LAG/LACP is supported in DPDK as bonding PMD.
See https://doc.dpdk.org/guides/prog_guide/link_bonding_poll_mode_drv_lib.html

Bonding device can be supported like memif case.
https://trex-tgn.cisco.com/trex/doc/trex_manual.html#_memif_interfaces

DPDK configuration change and additional changes for parsing .yaml file would be needed.

Will it be feasible in TRex?

Best Regards
Gwangmoon

**Comment by hhaim** [comment]
@egwakim I don't see an issue to add it. We have a full scalable software solution now for both ASTF and STL for redirecting flows, we did that for AWS and Azure. 
vdev is supported in ```trex_cfg`` file too see Azure example 
https://github.com/cisco-system-traffic-generator/trex-core/wiki/Azure-with-netvsc-DPDK-driver-(v2.89)

I would look into a referance commit that added the netvsc dpdk driver example and add the same for bonding interface.

**Comment by egwakim** [comment]
Thanks for comment,
Then, we'll try to contribute it.
