### ISSUE TITLE
ip4 length > l2 length with VPP + memif + TRex

### ISSUE THREAD

**Issue by ivan4th** [cisco-system-traffic-generator/trex-core#686]
When trying any of the ASTF TRex profiles with VPP, I get multiple errors in VPP: `ip4 length > l2 length`.

These don't happen with each packet but rather with some of them. It looks like the TCP payload is truncated down to 600 bytes for some reason, while looking at the TRex simulation, it should be 1448 bytes.  I have collected a snippet from dispatch trace dissected by Wireshark and other info here:
https://gist.github.com/ivan4th/e0130dac619f91a6bb8e7987550c2466

VPP version: 21.01.
I'm not really sure if this is a VPP or TRex problem (or both?), so I'm posting this to the vpp-dev mailing list too.
There was an old ticket related to a similar problem in VPP CSIT: https://jira.fd.io/browse/VPP-1676

Passing `--tso-disable --lro-disable --checksum-offload-disable` flags to TRex don't change anything.

vpp-dev mailing list post: https://lists.fd.io/g/vpp-dev/message/19267

The problem doesn't happen in STF or STL modes.

**Comment by hhaim** [comment]
@ivan4th it might be a memif (dpdk?) issue. trex is used with physical interfaces with loopback setup and we don't see such an issue. So, I assume this is the memif driver issue related to mbuf chain,
To debug it, you can convert the mbuf chain to one mbuf or to add sanity check on the tx mbuf before sending to verify the pkt.

**Comment by ivan4th** [comment]
@hhaim thanks for the tips, I've debugged the issue further and found a bug in DPDK memif driver: https://bugs.dpdk.org/show_bug.cgi?id=729
The fix is trivial but the process here is to wait for DPDK folks to fix it?

**Comment by hhaim** [comment]
@ivan4th thanks for looking into this, You can PR directly to this repo

**Comment by ivan4th** [comment]
Thanks, will do so
