### ISSUE TITLE
add descriptions of some words like 'flow'

### ISSUE THREAD

**Issue by zzsuki** [cisco-system-traffic-generator/trex-core#706]
i was going to use trex for firewall benchmark testing, stats wanted is recommanded in ietf rfc3511 which indicates max tcp connections and connections per second is wanted. i am not sure if  'flows' in trex means connection alive ? and is 'cps' means new connection per seconds . is it accurate?

**Comment by hhaim** [comment]
@zzsuki ```active-flows ``` means how many flows are active. ```CPS``` means **new** connection (flows) per second.

**Comment by zzsuki** [comment]
> @zzsuki `active-flows ` means how many flows are active. `CPS` means **new** connection (flows) per second.

thanks very much, is there any way to control the trraffic run with specific active-flows. i have tried cps and limit, these two args can not control the program keep active flows in specific number
