### ISSUE TITLE
Tracking ASTF profile state changes

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#708]
@hhaim, I'd like to get the ASTF profile state changes.
It is needed for a very short period of running due to an automatic profile stop from #679.
I think I can stack the state changes from the `get_async_events` messages.
But, while implementing this feature, I have found the following issues.

1. `get_async_events` and `sync`
After `get_async_events` was introduced, I think the `sync` is not required anymore after once performed at the `connect`.

2. `sync` and `epoch`
According to my investigation, by setting `self.epoch` as None, the async event messages won't update the profile state during `sync`. But, I need to stack all the event messages even though the `sync` is in progress.

3. `inc_epoch` in multi-threading
When I start a profile with blocking mode, `_transmit_async` triggers `inc_epoch` for the first profile. But, there is another thread that is starting another profile at that time, `inc_epoch` can be triggered also. I think this behavior is not thread-safe and unexpected.
In my thought, this action is not required. The T-Rex server is increasing the `epoch` internally. And, if I don't use blocking mode, there is no `inc_epoch` action.

@hhaim, what do you think about these issues?

**Comment by hhaim** [comment]
@jsmoon 

In case you stack it, you can get a burst of changes that only the last is relevant, is it what you want?
1. Yes
2. didn't understand this
3. Our API is not multi-threaded safe.  (we internally protect it)

**Comment by jsmoon** [comment]
@hhaim

Yes, I don't want to miss TX state while I'm waiting for it.

1. OK. But, I found an additional issue. When a profile is failed to load, the profile is STATE_IDLE in the T-Rex server. But the ASTFClient doesn't know it. Currently, only `sync` can get it.

2. Simply say, `get_async_events` messages are not updated during the `sync`  is in progress. If I remove the `sync` call, there is no issue anymore.

3. Understood. Anyway, I think the `inc_epoch` behavior is useless. What do you think about this?

**Comment by hhaim** [comment]
@jsmoon so what is suggestion to solve it? in once section you say that you don't need the ```sync``` and in another you need it

**Comment by jsmoon** [comment]
@hhaim, my suggestion for solving the issues is like the following:
1. I'll add publish the IDLE state and remove unnecessary `sync` calls.
2. If I removed the unnecessary `sync`, there is no other change for this issue.
3. I'd like to remove the unnecessary `inc_epoch` action.

**Comment by hhaim** [comment]
@jsmoon sound good. Removing the ```inc_epoch``` would work with the old and new server (that support the new API version change for ASYNC ZMQ), so there is no need to change API version again.
