### ISSUE TITLE
ASTF GTPU mode only works with --software RSS

### ISSUE THREAD

**Issue by ivan4th** [cisco-system-traffic-generator/trex-core#710]
The server part works just fine, but if `--software` is not set, the server responses never reach the client TCP stack (at least with > 1 cores).
Checked using an Intel XL710 card.
If this is the expected behavior, it's probably worth mentioning in the docs

**Comment by hhaim** [comment]
@ivan4th yes, you are right. we are doing some cleanups now

**Comment by syaakov** [comment]
We have changed the GTPU activation in version v2.93.
Now GTPU mode is enabled/disabled VIA RPC command,
And in case the software mode is off while trying to enable GTPU, TRex sends a message to use software mode.
You can find more information about it here:
https://trex-tgn.cisco.com/trex/doc/trex_astf.html#_gtpu_tutorials
