### ISSUE TITLE
I wrote an FTP yaml file and the program crashed

### ISSUE THREAD

**Issue by cuixun925** [cisco-system-traffic-generator/trex-core#711]
-- loading cap file ftp_zhudong.pcap 
Error: signal 11:

*** traceback follows ***

1       0x564ad5286ce4 ./_t-rex-64(+0x19ece4) [0x564ad5286ce4]
2       0x7f1c673a7390 /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390) [0x7f1c673a7390]
3       0x7f1c6645b2be /lib/x86_64-linux-gnu/libc.so.6(+0x14e2be) [0x7f1c6645b2be]
4       0x564ad526ef06 CMiniVM::mini_vm_replace_ip(CMiniVMReplaceIP*) + 134
5       0x564ad526f0f8 CMiniVM::mini_vm_run(CMiniVMCmdBase**) + 200
6       0x564ad527c12e CFlowPktInfo::do_generate_new_mbuf_ex_vm(CGenNode*, CFlowInfo*, short*) + 270
7       0x564ad5270099 CPluginCallbackSimple::rtsp_plugin(unsigned char, CGenNode*, CFlowPktInfo*) + 889
8       0x564ad526e6c7 on_node_generate_mbuf(unsigned char, CGenNode*, CFlowPktInfo*) + 39
9       0x564ad5229e43 CCoreEthIF::send_node(CGenNode*) + 899
10      0x564ad527f7f9 void CFlowGenListPerThread::on_flow_tick<false>(CGenNode*) + 25
11      0x564ad52eb7f5 CNATimerWheel::on_tick_level0(void*, void (*)(void*, CHTimerObj*)) + 117
12      0x564ad52262d9 int CNodeGenerator::flush_file_realtime<24, false>(double, double, CFlowGenListPerThread*, double&) + 697
13      0x564ad542d99b TrexDpCoreStf::start_stf() + 1083
14      0x564ad542e399 TrexDpCoreStf::start_scheduler() + 9
15      0x564ad53da4c9 TrexDpCore::start() + 89
16      0x564ad526c623 CFlowGenListPerThread::start(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, CPreviewMode&) + 115
17      0x564ad5206411 CGlobalTRex::run_in_core(unsigned char) + 487
18      0x564ad522a89d ./_t-rex-64(+0x14289d) [0x564ad522a89d]
19      0x564ad555a4b6 eal_thread_loop + 406
20      0x7f1c6739d6ba /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f1c6739d6ba]
21      0x7f1c6641451d clone + 109

**Comment by hhaim** [comment]
@cuixun925 this code is deprecated. the new code is ASTF but it does not support a field engine.
