### ISSUE TITLE
is there any way to set constant number of active flows in astf mode

### ISSUE THREAD

**Issue by zzsuki** [cisco-system-traffic-generator/trex-core#718]
i have set a profile with a pcap file like this:

`ASTFProfile(default_ip_gen=ip_gen,
                            cap_list=[
                                ASTFCapInfo(file="{}/pcaps_single_session/s7_single_session.pcap".format(PROJECT_ROOT), l7_percent=l7_percent)`

my purpose is to test thruput of s7comm and maximum tcp connections when l7 is s7comm; but i haven't found a way to set constant number of active flows(i have tried `l7_percent` and `mult` in function `start()` )

**Comment by bdollma** [comment]
Hi, 
There is a direct connection between `active_flows` and connections per second (`cps`). Let's say you generate at 1000 `cps` and each connections lasts 1 second, then you will have ~1000 active flows.
The complete answer is that you can't specify exactly the number of `active flows`, however using `cps` you can approximate that number. 
Thanks,

**Comment by hhaim** [comment]
@zzsuki this is from the manual,
![image](https://user-images.githubusercontent.com/13034429/120914589-cdd41b00-c6a7-11eb-8fd6-146c598973f1.png)

Controling the duration of the flow will change indirectly the active_flows. 
There is a way to do that in ASTF see emix2.py example

**Comment by zzsuki** [comment]
> Hi,
> There is a direct connection between `active_flows` and connections per second (`cps`). Let's say you generate at 1000 `cps` and each connections lasts 1 second, then you will have ~1000 active flows.
> The complete answer is that you can't specify exactly the number of `active flows`, however using `cps` you can approximate that number.
> Thanks,

Thanks very much ,that helps a lot. 
Besides, is there any way to find maximun tcp connectios of dut?

It needs to get attempt connection and connection successful.  I read the doc of trex and realized active_flows contains both established and non-established flows.
 
And the stats of astf contains client and server in traffic, should i try to verify tcps_connattempt in client side with tcps_accepts in server side? is it possible that trex itself cause the loss if it's different?

**Comment by hasantskn** [comment]
@hhaim  what is the relation between PPS and active flow?
