### ISSUE TITLE
Starting TRex fail due to EAL error

### ISSUE THREAD

**Issue by akram6wind** [cisco-system-traffic-generator/trex-core#72]
Hi,
I try to use TRex, but when I start the binary file "t-rex-64 -i". I have the following error:

EAL: Can only reserve 3850 pages from 4096 requested
Current CONFIG_RTE_MAX_MEMSEG=256 is not enough
Please either increase it or request less amount of memory.
EAL: FATAL: Cannot init memory

I attach the procedure used to build TRex and the output of "trex_cfg.yaml" generated by "dpdk_setup_ports.py -i" script, and the NIC used by TRex.
And, I would like if we can decrease the number of reserved page to start TRex and how ?

Thanks,

[trex-procedure.txt](https://github.com/cisco-system-traffic-generator/trex-core/files/1551403/trex-procedure.txt)

**Comment by hhaim** [comment]
Try to add it to grub kernel args
See here:
http://dpdk.org/doc/guides/linux_gsg/sys_reqs.html
