### ISSUE TITLE
tunnels reformat issues

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#725]
Hi, I've found some issues at the recently merged commit, `tunnels reformat`.

### 1. the outer IP header checksum is missing.

This is the receiver-side captured packet.
![image](https://user-images.githubusercontent.com/4134762/121638479-061f9300-cac6-11eb-8799-eecbf57e5f78.png)

Reason: HW checksum offloads are disabled by calling `tx_offload_csum`.
Additional issue: SW L4 checksum calculation will be performed 2 times, one for inner, one for outer.

### 2. "update_tunnel_client" doesn't work before the loaded profile started.

```
[verbose] Sending Request To Server:

{
    "id": "fwlahd7l",
    "jsonrpc": "2.0",
    "method": "update_tunnel_client",
    "params": {
        "api_h": "YBJUixXJ",
        "attr": [
            {
                "client_ip": 268435457,
                "dip": "2.2.2.52",
                "sip": "1.1.1.51",
                "teid": 1,
                "version": 4
            }
        ],
        "tunnel_type": 1
    }
}



[verbose] Server Response:

{
    "id": "fwlahd7l",
    "jsonrpc": "2.0",
    "result": {}
}



[verbose] Sending Request To Server:

{
    "id": "j4dhrphc",
    "jsonrpc": "2.0",
    "method": "get_async_events",
    "params": {
        "api_h": "YBJUixXJ",
        "session_id": 506399037,
        "user": "sub"
    }
}



[verbose] Server Response:

{
    "id": "j4dhrphc",
    "jsonrpc": "2.0",
    "result": {
        "data": []
    }
}

Start profile 'TEST.UDP' with duration 5

Starting traffic.                                           
[SUCCESS]

```

Suggestion: In addition, if the tunnel client information would be added to the client ASTFIPGenDist in the profile, users could use the tunnel more easy way.

### 3. packets without tunnel info are silently dropped.

```
 'total': {'ibytes': 0,
           'ierrors': 0,
           'ipackets': 0,
           'obytes': 0,
           'oerrors': 0,
           'opackets': 0,   <<<<< -- no packets out
           'rx_bps': 0.0,
           'rx_bps_L1': 0,
           'rx_pps': 0.0,
           'rx_util': 0.0,
           'tx_bps': 0.0,
           'tx_bps_L1': 0,
           'tx_pps': 0.0,
           'tx_util': 0.0},
 'traffic': {'client': {'m_active_flows': 0,
                        'm_avg_size': 39.99999898274742,
                        'm_est_flows': 0,
                        'm_rx_bw_l7_r': 0.0,
                        'm_rx_pps_r': 0.0,
                        'm_traffic_duration': 5.097898868152329,
                        'm_tx_bw_l7_r': 283.0188679245283,
                        'm_tx_bw_l7_total_r': 283.0188679245283,
                        'm_tx_pps_r': 0.8844339847564697,
                        'm_tx_ratio': 100.0,
                        'udps_closed': 5,
                        'udps_connects': 5,
                        'udps_keepdrops': 5,
                        'udps_sndbyte': 200,
                        'udps_sndpkt': 5},    <<<<< -- 5 packets sent
             'server': {'m_active_flows': 0,
                        'm_avg_size': 0.0,
                        'm_est_flows': 0,
                        'm_rx_bw_l7_r': 0.0,
                        'm_rx_pps_r': 0.0,
                        'm_tx_bw_l7_r': 0.0,
                        'm_tx_bw_l7_total_r': 0.0,
                        'm_tx_pps_r': 0.0,
                        'm_tx_ratio': 0.0}}}
```

Suggestion: the dropped packets counter needs to be collected in the traffic statistics.

@hhaim, what's your thought about these issues?

**Comment by hhaim** [comment]
1. The HW checksum is disabled in case of tunnels (and TSO and RSS) and it is calculated once! the outer is calculated based on the inner (payload is scanned once). @syaakov confirmed that he tested this, we will look into this 
2. It is not a new issue,we plan to fix this in a new commit
3. This is a feature, why would you want a non tunnel traffic on tunnel interface?
4. We plan to add counters to tunnels, so the drop will be reported

**Comment by jsmoon** [comment]
1. I think I misunderstood the checksum calculation mechanism. But, the outer IP checksum issue should be fixed.
2. o.k. I'll wait for it.
3. I don't want the non-tunnel traffic, it is just obseved result from issue 2. And I just want to sync the tunnel IP with the traffic profile easily. 
4. good.

**Comment by hhaim** [comment]
@jsmoon 
1. Agreed. it was tested maybe there is an issue on software driver. the point is that the payload is scanned once

**Comment by syaakov** [comment]
@jsmoon 
1. I uploaded a fix https://github.com/cisco-system-traffic-generator/trex-core/blob/master/src/tunnels/gtp_man.cpp#L293
2. we intend to load the tunnel context using DB before transmitting.
3. As Hanoch said, we are working on tunnel counters.
