### ISSUE TITLE
TRex is for website traffic generator or what?

### ISSUE THREAD

**Issue by TeckboyAj** [cisco-system-traffic-generator/trex-core#732]
firstly, I am sorry for asking you this question. but I am really confused because when I searched for an open-source traffic generator I got this code and read it for the last few days but till now I don't understand which traffic it will generate. is it for a website or router or for something else. please clear my doubt?

**Comment by hhaim** [comment]
@TeckboyAj it is for testing network gear at scale. You can create a website traffic but this is not the right tool for it.
