### ISSUE TITLE
GTP-U issue in Trex docker image in K8s Pod

### ISSUE THREAD

**Issue by subrnath** [cisco-system-traffic-generator/trex-core#744]
I am new in Trex. I am using the trex docker image https://hub.docker.com/r/trexcisco/trex and running as a K8s Pod. External connectivity provided via IPVLAN K8s CNI.

1) Can it work with the virtual interfaces in Pod  provided by IPVLAN CNI or DPDK is must? My requirement is to trigger single packet and hence i don't need DPDK. Inside the pod, i can see following two veth interfaces and packet is being sent via these. These interfaces are only recognized by trex and not the IPVLAN CNI provided interface.

5: veth1@veth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 92:87:5c:bd:28:bf brd ff:ff:ff:ff:ff:ff
    inet 2.2.2.2/24 brd 2.2.2.255 scope global veth1
       valid_lft forever preferred_lft forever
    inet6 fe80::9087:5cff:febd:28bf/64 scope link
       valid_lft forever preferred_lft forever
6: veth0@veth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 0a:03:f0:5c:3a:37 brd ff:ff:ff:ff:ff:ff
    inet 1.1.1.1/24 brd 1.1.1.255 scope global veth0
       valid_lft forever preferred_lft forever
    inet6 fe80::803:f0ff:fe5c:3a37/64 scope link
  
How to use the external IPVLAN interfaces so that trex recognizes this interface?

2) 

While sending GTP_U packet, getting the following error -

    from scapy.contrib.gtp import GTP_U_Header, TBCDByteField
ImportError: No module named gtp

In the file, it's imported as -
from scapy.contrib.gtp import GTP_U_Header, TBCDByteField

I can see python2 is used /usr/bin/python -> python2. But  scapy/contrib gtp module present inside the container -/var/trex/v2.41/external_libs/scapy-2.3.1/python3/scapy/contrib/gtp.py

Is the error due to python version related?

**Comment by hhaim** [comment]
@subrnath please use our mailer for questions. 
the docker in the hub is relatively old, please update to a newer version of the package (the hub is not updated regularly). 
In the new version we moved to python3 support only and newer scapy package and yes linux interfaces are supported (not in the same performance)
