### ISSUE TITLE
how to insert more different pcap files ?

### ISSUE THREAD

**Issue by utkarsh0902311047** [cisco-system-traffic-generator/trex-core#749]
I am running the command "start -f stl/bench.py -m 100% --port 0 -t size=1024,vm=cached".
How can I insert pcap files here?

**Comment by hhaim** [comment]
@utkarsh0902311047 please read the manual

**Comment by utkarsh0902311047** [comment]
> @utkarsh0902311047 please read the manual

I read the manual and it mentions that to include pcap files I have to run the yaml file. For that I have to run ./t-rex-64 command. But in this I am not able to set packet size. So how to include pcap files if I run this command start -f stl/bench.py -m 100% --port 0 -t size=1024,vm=cached
