### ISSUE TITLE
Unable to achieve 100Gbps and insert pcap files 

### ISSUE THREAD

**Issue by utkarsh0902311047** [cisco-system-traffic-generator/trex-core#750]
Hi,
I want to get Trex TX throughput of 100gbps and insert my own pcap files (of specific protocols like YOUTUBE, Facebook, etc).
If I try to run with python script stl/bench.py I can achieve 100gbps TX throughput but when I try to detect the protocol (using nDPI) in the data generated by trex it all shows Unknown. 
If I try to run ./t-rex-64 -f avl/sfr_delay_10_1g.yaml -c 4 -m 100 -d 10 -p --active-flows 52000, it says that I can only run on "-c 1" and the maximum TX throughput I can achieve is 8Gbps. But with yaml file I am able to put my own pcap files and able to detect the protocols (using nDPI).
I read the manual but couldn't find solution for this. 
Please help

**Comment by hhaim** [comment]
@utkarsh0902311047 please use the mailer for questions
