### ISSUE TITLE
trex astf could only scale to 26w of active established flows

### ISSUE THREAD

**Issue by UnknowSelf** [cisco-system-traffic-generator/trex-core#752]
when I use astf mode to test dut max connects. in my test environment, established flows only has 26W
my test script in below
![image](https://user-images.githubusercontent.com/11157598/129518418-40e05e83-1ff4-4904-b040-5b713cd7c548.png)

I execute the command
`> start -f test/conntest.py -d 30 -t --cps 10000 --payload-size 64`

The trex statistics
![image](https://user-images.githubusercontent.com/11157598/129517857-4f9341bb-da9e-4767-933b-310df658ffa4.png)

**Comment by UnknowSelf** [comment]
@ivan4th @drizzt @teknoraver @tbarbette

**Comment by hhaim** [comment]
@UnknowSelf 
1) The default active-flows is 1M, try to elarge it in trex_cfg.yaml to more  see in other thread how -- this is the reason for the "flow_overflow" error
2) The prog_c.delay() is in the wrong location. remove it and put it in the server side betwean the recv and send

**Comment by UnknowSelf** [comment]
Thanks for your reply @hhaim 
I modified the config file /etc/trex.yaml
`
memory:
    dp_flows: 200000
`
and then I tested the config is valid!
The problem is reloved.
