### ISSUE TITLE
undefined symbol: mlx5dv_dr_action_create_aso with MLNX OFED 5.4

### ISSUE THREAD

**Issue by bluecmd** [cisco-system-traffic-generator/trex-core#754]
Hello,

I am trying to set up TRex v2.91 on Ubuntu 20.04 with MLNX OFED version 5.4-1.0.3.0.

This is the result:
```
/opt/trex/v2.91# ./t-rex-64 -f cap2/dns.yaml -c 1 -m 1 -d 5
Error while determining OS type: module 'platform' has no attribute 'dist'
The ports are bound/configured.
Starting  TRex v2.91 please wait  ... 
EAL: so/x86_64/libmlx5-64.so: undefined symbol: mlx5dv_dr_action_create_aso, version MLX5_OFED
EAL: FATAL: Cannot init plugins
EAL: Cannot init plugins
 You might need to run ./trex-cfg  once  
EAL: Error - exiting with code: 1
  Cause: Invalid EAL arguments
```

Likely a version mismatch from what TRex's `so/x86_64/libmlx5-64.so` was compiled against I would guess.

EDIT: It seems this has been reported on the mailing list as well: https://groups.google.com/g/trex-tgn/c/-SR_RavGPAo/m/mvzMQg6vAAAJ

**Comment by hhaim** [comment]
@bluecmd see the manual, only 5.3 LTS is supported with this DPDK

**Comment by bluecmd** [comment]
Hi @hhaim - I did read the manual, but I failed to find where it says 5.3 is supported. I found that 5.2 is recommended in https://trex-tgn.cisco.com/trex/doc/trex_appendix_mellanox.html but I found no notice that things newer then 5.3 will not work.

Can you tell me where it says that? I can't find any reference to it in the installation guide (https://trex-tgn.cisco.com/trex/doc/trex_manual.html#_download_and_installation)

Regards,

**Comment by hhaim** [comment]
@bluecmd your link is right, see 
[this](https://trex-tgn.cisco.com/trex/doc/trex_appendix_mellanox.html#_upgrade_procedure )

OFED **only** GA 5.3 with v2.89+

**Comment by bluecmd** [comment]
Ah thanks. I didn't consider reading under "Upgrade" as this is a new install.

Very good, now I know where to look.
