### ISSUE TITLE
Https pcap file analyze faild

### ISSUE THREAD

**Issue by UnknowSelf** [cisco-system-traffic-generator/trex-core#755]
my test script in below
![image](https://user-images.githubusercontent.com/11157598/129878374-954f98b1-035f-45c0-b986-869a2d2f31ca.png)
The https pcap image
![image](https://user-images.githubusercontent.com/11157598/129878540-19f29361-d53c-4315-9ddf-281c7276e7c9.png)
The error info
![image](https://user-images.githubusercontent.com/11157598/129878661-aa56a98c-fde3-467a-b3fe-62ee50efe59f.png)
How to resolve the error?
@hhaim @ivan4th @drizzt @teknoraver @tbarbette

**Comment by hhaim** [comment]
@UnknowSelf please send email to our forum https://groups.google.com/forum/#!forum/trex-tgn before opening an issue here
