### ISSUE TITLE
EAL: Error enabling interrupts for fd 20 (Input/output error)，the drop rate equal tx rate

### ISSUE THREAD

**Issue by hx1260** [cisco-system-traffic-generator/trex-core#778]
This is my network topology and my trex_cfg.yaml
![Top](https://user-images.githubusercontent.com/67954978/144191391-25d1a4f4-00a5-4c1d-b7d8-c852c24789e0.png)
![TRex_cfg_yaml](https://user-images.githubusercontent.com/67954978/144191409-0f880e71-3022-4861-96ea-a553dbf8b030.png)
when i start ./t-rex-64 -i ,there is a error, its seem to be a dpdk error, how can i fix it?
![EAL_ERROR](https://user-images.githubusercontent.com/67954978/144191501-ca61aee5-2b6a-4ef8-8e1c-5544c001fcc2.png)
when i start trex>start -f stl/udp_1pkt_simple.py -m 10mbps on consle, the tx equal drop rate, no rx
![Trex_S](https://user-images.githubusercontent.com/67954978/144192107-920680ee-a2c8-439e-b448-86a919e0a9b9.png)
there are linux route and ip,mac 
![linux_route](https://user-images.githubusercontent.com/67954978/144192068-c34b9029-1b58-44f6-bbcb-2dd42e6df435.png)
![c6492f499de3efc0ca823c0614405d7](https://user-images.githubusercontent.com/67954978/144192212-9ccb0d05-6834-4ce3-a623-affd59bd962b.png)

but when i send arp on consle service mod,the mac is not right,what problem?
thanks very much!!!!!!!!!!!!This confused me for a week
![ARP](https://user-images.githubusercontent.com/67954978/144192358-3f9d00e8-f226-47aa-b77e-4b5dd56149a4.png)

**Comment by bdollma** [comment]
Hi, 
This is a bit confusing since you have merged a couple of problems.
1. Regarding the interrupts problem. It doesn't have to do anything with TRex. First thing that comes up in Google, seems to be a VMWare problem. Look [here](https://dannypsnl.github.io/blog/2019/10/18/cs/dpdk-input-output-error/)
2. TRex simply records the MAC address in by the ARP reply. Both of the GW interfaces are on the same Linux machine and hence, your machine is replying with the same MAC. You must configure this in your Linux if you want different MACs.
Thanks,

**Comment by hx1260** [comment]
> Hi, This is a bit confusing since you have merged a couple of problems.
> 
> 1. Regarding the interrupts problem. It doesn't have to do anything with TRex. First thing that comes up in Google, seems to be a VMWare problem. Look [here](https://dannypsnl.github.io/blog/2019/10/18/cs/dpdk-input-output-error/)
> 2. TRex simply records the MAC address in by the ARP reply. Both of the GW interfaces are on the same Linux machine and hence, your machine is replying with the same MAC. You must configure this in your Linux if you want different MACs.
>    Thanks,

Thank you very much for your answer. I’m sorry that I didn’t describe it clearly. I’m a trex novice. 
The problem I urgently want to solve is how to make the data packet depart from port0, reach port1 through the route, and be accepted. like this
![664f8ec113dc66721b1aeec68d08f50](https://user-images.githubusercontent.com/67954978/144204014-38e0060f-9c3d-41ca-b628-85ec88df7f79.png)

I configured routing on linux, but all the data packets were discarded<the tx rate equal drop rate,how can I solve this problem ？Thanks very much
I think the other problems are the cause of the above problem, so I describe it.

**Comment by hhaim** [comment]
@hx1260 suggest to take this thread to our mailer. 
the issue with interrupts is a DPDK issue,for 1gbps there is no need for DPDK, you can work with linux driver with PF packet. have a look into the manual

**Comment by hx1260** [comment]
Hello!
Thank you very much for your answer.
I follow trex doc.&nbsp; But it did not achieve the expected effect.
No packet accepted. The tx rate equal drop rate.&nbsp;What is the problem?&nbsp;


-----doc address----
You can follow&nbsp;this presentation&nbsp;for an example of how to configure the router as a DUT

----------------------




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cisco-system-traffic-generator/trex-core"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月1日(星期三) 晚上8:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cisco-system-traffic-generator/trex-core] EAL: Error enabling interrupts for fd 20 (Input/output error)，the drop rate equal tx rate (Issue #778)





 
@hx1260 suggest to take this thread to our mailer.
 the issue with interrupts is a DPDK issue,for 1gbps there is no need for DPDK, you can work with linux driver with PF packet. have a look into the manual
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
