### ISSUE TITLE
Testing multiple devices in parallel, segmented by VLAN

### ISSUE THREAD

**Issue by moffitj** [cisco-system-traffic-generator/trex-core#780]
I don't see what I would like to do is possible. If this is possible then I'd love to hear it.

I'd like to test a number of devices in parallel. Traffic for each device would be segmented by VLAN, with each DUT plugged into two ports on the same switch and trunked back to the TREX instance.

The only way I see of doing this is to open up multiple instances of trex and utilize linux dot1q interfaces, one pair for each instance of trex. The downside of this is increased memory usage from multiple trex instances, as well as all of the downsides of linux interfaces compared to the raw physical interfaces.

This almost seems to be possible, but not quite:

I see that the platform config file supports setting a VLAN, but that's for the entire trex instance. It also seems to only be a single tag for both ports in the platform, otherwise I might be able to get clever with SR-IOV.
I see that the traffic config files support VLANs, but it seems only for load balancing asymmetric traffic.

Ideally I'd like to set a client VLAN and server VLAN within the traffic profile so that I could set up a single trex instance on two physical interfaces for the most accuracy. Then I would start/stop the tagged traffic profiles as needed, for example, when an outside script detects that a device has been connected to specific ports on the switch.

If this is possible please let me know. If not, I hope the use-case is interesting enough that someone will pick this up as a future feature.

thanks,

**Comment by hhaim** [comment]
@moffitj it is possible. Stateless (STL) and Advanced Stateful (ASTF) should support that, but it would be a bit more complex to achieve this. 
Let's start with Stateless:
1. You can create stream with the right destination MAC/DOT1q 
2. If you like to have ARP/IPV6 ND for each client/server you can add software mode and EMU 

I suggest to close this issue and move this to our mailer with specific question (what the profile configuration you tried and what didn't work)

**Comment by moffitj** [comment]
Moved to google groups as suggested.
