### ISSUE TITLE
https://trex-tgn.cisco.com/trex/release/ is inaccessible

### ISSUE THREAD

**Issue by richmondstacey** [cisco-system-traffic-generator/trex-core#785]
Cannot download releases, documentation is not accessible, and several other links are broken on the main page.

e.g.

https://trex-tgn.cisco.com/trex/release/
https://trex-tgn.cisco.com/trex/doc/index.html

These give "ERR_FAILED".

**Comment by hhaim** [comment]
@richmondstacey we replaced the certificate. Please check with a different device. I’ve just checked and it works

**Comment by richmondstacey** [comment]
hmm you are correct. I got it to work by switching to a different browser...

Brave, Chrome didn't work, Safari did FYI (same device).

**Comment by bdollma** [comment]
Chrome has simply cached the SSL state. Just clear it. 
https://www.a2hosting.com/kb/getting-started-guide/internet-and-networking/clearing-a-web-browsers-ssl-state

**Comment by richmondstacey** [comment]
That did the trick, thanks all.

**Comment by J0eJ0h** [comment]
FYI, the revocation mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1749089 seems to have made it into Chrome and the site has stopped working again.
