### ISSUE TITLE
Issue on non-backward compatible change about no_delay=3

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#789]
Hi,
TRex prohibited to set no_delay=3 from following push.
https://github.com/cisco-system-traffic-generator/trex-core/commit/02bf4c680d80874406ac99b5a599f819e91d5dca

Some users have been used TCP parameter as no_delay=3.
We have been suffer from many throughput issues in the legacy usages.
It's not easy to resolve the all issues.
To mitigate the issue,
We tried "no_delay=0, no_delay_counter=mss*3", "no_delay=1,no_delay_counter=1" and "no_delay=1,no_delay_counter=mss*1"
But, all these TCP parameters could not passed all legacy test cases.
Only no_delay=3 could pass the all legacy test cases.

Will it possible to make it backward compatible?
My suggestion is
- No change on related documents and examples to make it recommended use for the new users
- Just allow no_delay=3

**Comment by bdollma** [comment]
Hi @egwakim , 
First, as you can see nothing is changed in the TCP code in the commit you mentioned. This commit fixes the profiles to support the changes made in previous commits.
From my understanding back when I implemented the fix, `no_delay` can't take a value of 3.
As documented:
`no_delay=0` - Enable Nagle Algorithm
`no_delay=1` - Disable Nagle Algorithm
`no_delay=2` - Force Push

This can be seen here in code:
https://github.com/cisco-system-traffic-generator/trex-core/blob/49a1381d2fdd81d446ab4d7be7122b2ab734f064/src/44bsd/tcp_input.cpp#L1708

The 2 bit mask works like this:
1. The least significant bit is responsible for enabling/disabling Nagle (1 - Means Enable, 0 Means disable)
2. The most significant bit is responsible for force push (1 - force push, 0 don't).

Now for the value 3, it would mean enabling force push and enabling Nagle. In my understanding this is contradictory. If force push is enabled, we can't wait and combine small size packets using Nagle.

Please provide us with a good use case of where the value 3 would make sense.
Thanks,

**Comment by egwakim** [comment]
Hi @bdollma 
Value 3 means enabling force push and disabling Nagle(1 means disable in Nagle bit).
Among hundreds of legacy use cases, some test cases running on the bad network(long delay, many packet loss).
Throughput would be better in such traffic path because ramp-up speed would be better after packet loss due to many frequent Ack packets.
It's non-backward compatible change in user point of view.
I tried to fix it by using existing TCP parameters, but, failed.

That's why I'm asking whether it's possible to make it backward compatible.

**Comment by bdollma** [comment]
@egwakim 
Sorry for the confusion, I edited my comment.
If force push is enabled, to the best of my understanding we send every packet immediately. 
So my questions is: If I am force pushing, why does the value of Nagle matter?
Thanks again.

**Comment by egwakim** [comment]
@bdollma 
Enabling Nagle would decrease throughput in long delayed network( 20 ms ~ 4000 ms ).
Some test cases failed due to low average throughput.
Average throughput of no_delay=2 was lower than no_delay=3 in long delayed traffic path.

**Comment by hhaim** [comment]
@egwakim thanks for reporting this !
agreed, we should revert this line and make it 0,3 again. 

```tunable_min_max_u32("no_delay", tune->m_tcp_no_delay, 0, 2);

==>
to this
tunable_min_max_u32("no_delay", tune->m_tcp_no_delay, 0, 3);

```
