### ISSUE TITLE
WATCHDOG: task 'Trex DP core 1' has not responded for more than 1.24736 seconds - timeout is 1 seconds

### ISSUE THREAD

**Issue by HouMinXi** [cisco-system-traffic-generator/trex-core#794]
Hello Hanoh

I try to use other trex_cfg.tamy configuration as below. I change the latency_thread_id to 12. And I catch how to reproduce this issue. once trex server start as well, I run pkill -9 t-rex to stop all t-rex process. After do pkill and re-lunch trex, trex will raise watchdog error. The t-rex version is 2.93

#cat /etc/trex_cfg.yaml 
### Config file generated by dpdk_setup_ports.py ###

- version: 2
  interfaces: ['13:00.0', '13:00.1']
  port_bandwidth_gb: 25
  port_info:
      - dest_mac: 40:a6:b7:3e:a5:61 # MAC OF LOOPBACK TO IT'S DUAL INTERFACE
        src_mac:  40:a6:b7:3e:a5:60
      - dest_mac: 40:a6:b7:3e:a5:60 # MAC OF LOOPBACK TO IT'S DUAL INTERFACE
        src_mac:  40:a6:b7:3e:a5:61

  platform:
      master_thread_id: 0
      latency_thread_id: 12
      dual_if:
        - socket: 0
          threads: [1,2,3,4,5,6,7,8,9,10,11]

  memory:
      mbuf_64     : 81920
      mbuf_128    : 51200
      mbuf_256    : 38400
      mbuf_512    : 38400
      mbuf_1024   : 38400
      mbuf_2048   : 38400
      mbuf_4096   : 38400
      mbuf_9k     : 38400
      global      : 5120
# ./t-rex-64 --no-ofed-check --no-scapy-server -i 1 -c 10
# pkill -9 t-rex
# ./t-rex-64 --no-ofed-check --no-scapy-server -i 1 -c 10
WATCHDOG: task 'Trex DP core 1' has not responded for more than 1.24734 seconds - timeout is 1 seconds

*** traceback follows ***

1       0x56030b360519 ./_t-rex-64(+0x1bf519) [0x56030b360519]
2       0x7fb067aeeb20 /lib64/libpthread.so.0(+0x12b20) [0x7fb067aeeb20]
3       0x7fb067aedfb0 nanosleep + 64
4       0x56030b4a6606 TrexDpCore::idle_state_loop() + 166
5       0x56030b4a66db TrexDpCore::start() + 59
6       0x56030b3394b3 CFlowGenListPerThread::start(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, CPreviewMode&) + 115
7       0x56030b2d00d9 CGlobalTRex::run_in_core(unsigned char) + 487
8       0x56030b2f399d ./_t-rex-64(+0x15299d) [0x56030b2f399d]
9       0x56030b6952b6 eal_thread_loop + 406
10      0x7fb067ae414a /lib64/libpthread.so.0(+0x814a) [0x7fb067ae414a]
11      0x7fb066adcdc3 clone + 67

*** addr2line information follows ***

??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0

Here is my kernel cmdline:
# cat /proc/cmdline 
BOOT_IMAGE=(hd0,msdos1)/vmlinuz-4.18.0-305.34.2.rt7.107.el8_4.x86_64 root=/dev/mapper/rhel_hp--dl388g10--02-root ro kpti resume=/dev/mapper/rhel_hp--dl388g10--02-swap rd.lvm.lv=rhel_hp-dl388g10-02/root rd.lvm.lv=rhel_hp-dl388g10-02/swap console=ttyS0,115200n81 skew_tick=1 isolcpus=managed_irq,domain,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 intel_pstate=disable nosoftlockup tsc=nowatchdog nohz_full=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 rcu_nocbs=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 crashkernel=1G-4G:384M,4G-16G:512M,16G-64G:1G,64G-128G:2G,128G-:4G mitigations=off nohz=on default_hugepagesz=1G hugepagesz=1G hugepages=24 intel_iommu=on iommu=pt modprobe.blacklist=qedi modprobe.blacklist=qedf modprobe.blacklist=qedr skew_tick=1 isolcpus=managed_irq,domain,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 intel_pstate=disable nosoftlockup tsc=nowatchdog nohz=on nohz_full=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 rcu_nocbs=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23

_Originally posted by @HouMinXi in https://github.com/cisco-system-traffic-generator/trex-core/issues/791#issuecomment-1020151460_

**Comment by hhaim** [comment]
@HouMinXi ```WATCHDOG ``` means that there is a interruption and the thread is starved for some reason. 
In case hypervisors it could happen, there is no relation to the ```kill``` command that you provided. it is an platform issue. 
BTW with mellanox cx-5 we didn't check it with RH8.3 see that manual how our regression works
