### ISSUE TITLE
https://trex-tgn.cisco.com is not accessible in Firefox due to certificate problems

### ISSUE THREAD

**Issue by J0eJ0h** [cisco-system-traffic-generator/trex-core#799]
The current certificate is one of the ones revoked per https://bugzilla.mozilla.org/show_bug.cgi?id=1749089

**Comment by bdollma** [comment]
@J0eJ0h I can now access the website through Firefox. Seems like the certificate issue is resolved. Can you please confirm? Thanks

**Comment by russianvoodoo** [comment]
Firefox works for now, but you can't open it from Chrome.

**Comment by bdollma** [comment]
@russianvoodoo It works in Chrome in my machine. Try to clear cache or force reload (`Ctrl/Cmd + Shift + R`).

**Comment by vincentbernat** [comment]
It may help to add the "IdenTrust Commercial Root CA 1" to the chain as it is quite recent (configuration to be done server-side). Browsers are OK with that, but servers may not have this intermediate certificate. For example, neither Ubuntu 22.04, nor Debian 11 (and currently 12) have the intermediate certificate. The certificate is not part of the [Mozilla bundle](https://ccadb-public.secure.force.com/mozilla/IncludedCACertificateReport) either (so, I don't know how it works with Firefox). However, "IdenTrust Commercial Root CA 1" is present in all of them.
