### ISSUE TITLE
goodbye all files like stl/udp_for_172.16.20.200.py

### ISSUE THREAD

**Issue by m0r1k** [cisco-system-traffic-generator/trex-core#805]
Can there be two or more dots in file names? Does it happen? :)

https://github.com/cisco-system-traffic-generator/trex-core/blob/400f03c86c844a0096dff3f6b13e58a808aaefff/scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_profile.py#L1995
![1](https://user-images.githubusercontent.com/30770134/154686385-9294115c-2dd8-49bc-9354-d2abd1c0ee7e.jpg)
![2](https://user-images.githubusercontent.com/30770134/154686392-ab02b998-3a8f-4e32-a3ee-e25a45d15971.jpg)

**Comment by m0r1k** [comment]
I don't know python, but maybe something like
https://docs.python.org/3/library/mimetypes.html
will be better

**Comment by bdollma** [comment]
You can't add `.` in the profile name. Just rename your profile to `udp_for_172_16_20_200.py` and it will work.
