### ISSUE TITLE
invalid config register when updating router image

### ISSUE THREAD

**Issue by bdollma** [cisco-system-traffic-generator/trex-core#808]
https://github.com/cisco-system-traffic-generator/trex-core/blob/400f03c86c844a0096dff3f6b13e58a808aaefff/scripts/automation/regression/CPlatform.py#L1015

`0x2021` is an invalid value for config register, it should probably be `0x2102`

https://www.cisco.com/c/en/us/support/docs/routers/10000-series-routers/50421-config-register-use.html

**Comment by jabir366** [comment]
I would like to take up this issue, is the solution simply  updating the config register value to `0x2102`

**Comment by bdollma** [comment]
Yes
