### ISSUE TITLE
Discussion about synchronous CP to DP messages.

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#812]
Hi, recently I've found the following code at [`src/stx/astf/trex_astf_rpc_cmds.cpp`](https://github.com/cisco-system-traffic-generator/trex-core/blob/d332833952f0014d0b91f47520b1b97de81e7f27/src/stx/astf/trex_astf_rpc_cmds.cpp#L849):
```
 819 trex_rpc_cmd_rc_e
 820 TrexRpcCmdGetClientsInfo::_run(const Json::Value &params, Json::Value &result) {
 821 
...
 849     uint8_t dp_core_count = get_astf_object()->get_dp_core_count();
 850     for (uint8_t core_id = 0; core_id < dp_core_count; core_id++) {
 851         static MsgReply<Json::Value> reply;
 852         reply.reset();
 853         TrexCpToDpMsgBase *msg = new TrexAstfDpGetClientStats(astf_db, msg_data, is_range, reply);
 854         get_astf_object()->send_msg_to_dp(core_id, msg);
 855         dps_results.push_back(reply.wait_for_reply());
 856     }
...
```
As far as I know, all the other CP to DP messages are asynchronous in ASTF mode.
But this routine uses CP to DP messages as synchronous.
Is it intended?

**Comment by hhaim** [comment]
@jsmoon there are more messages that are synchronous. if CP needs to read a state from DP you must have a synchronous call

**Comment by jsmoon** [comment]
@hhaim I know that several synchronous CP to RX messages, but I don't know any synchronous CP to DP messages before.
I am just concerned that CP may take time to get replies one by one from all DP cores. During waiting for replies, the "master" thread might be locked also.
I'm not sure that this synchronous message is enough fast.

**Comment by hhaim** [comment]
@jsmoon I missed the ASTF part. it is a good point.  You are right in case of ASTF there is no other example of ```synchronous CP to DP``` except of that, In case of STL there are a few examples. 
The **issue** with ASTF that state of **BUILD** could take a while (in the DP) so a sync command could fail in CP. 

so to overcome this, there is a need to either change this to async or to make sure the state of all profiles (e.g. IDLE or TX)
