### ISSUE TITLE
MAX_TCP_REASS_BLOCKS is too small for large OOO packets.

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#813]
Hi, I have been observed the following `tcps_rcvoopackdrop` counters when the traffic path has many nodes in its route.
```
  tcps_sndrexmitpack |               0                        10886             
  tcps_sndrexmitbyte |               0                      4198326             
     tcps_rcvduppack |             128                            0             
     tcps_rcvdupbyte |          107527                            0             
 tcps_rcvpartduppack |               5                            0             
 tcps_rcvpartdupbyte |          104332                            0             
  tcps_rcvoopackdrop |            2256                            0             
 tcps_rcvoobytesdrop |         3066356                            0             
      tcps_rcvoopack |            2507                            0             
      tcps_rcvoobyte |         3295510                            0             
      tcps_rcvdupack |               0                         2485             
```
Since some nodes do not guarantee packet ordering, the `tcps_rcvoopack` can be observed in general.
But, as you can see, lots of `tcps_rcvoopack` were dropped by `tcps_rcvoopackdrop`, about 90%.
I think it caused unexpected performance degradation.

As far as I know, `tcps_rcvoopackdrop` is increased when the reassembly block is full.
The maximum number of reassembly blocks is 4 which is defined by MAX_TCP_REASS_BLOCKS.
I think 4 is too small in this case.
@hhaim, what do you think about using a larger number of reassembly blocks?

**Comment by hhaim** [comment]
@jsmoon in any case the ```CTcpReass``` is  allocated dynamically only when there is an out of order (OOO) issue, so enlarging the **MAX_TCP_REASS_BLOCKS** will not have an impact when there is no OOO issue . However, at scale when **all** the flows have many OOO this could be a problem (of memory and performance in server side) and I think we should maybe limit the number of this objects ```CTcpReass``` instances. 

I would capture the OOO and learn if it is an inherent problem (the node OOO all the flows and it depends in the window size) or only part of the flow has this issue. 
Another question what would be the ideal value of MAX_TCP_REASS_BLOCKS in this case?

**Comment by hhaim** [comment]
@jsmoon another idea is to have a tunables for this. 
1. MAX_TCP_REASS_BLOCKS ==> max_tcp_reass_blocks_per_flow ==> by moving the object to the end of the struct and allocate the sizeof(CTcpReassBlock)* tuable
2. max_ooo_flows 


but first we need to understand the issue

**Comment by jsmoon** [comment]
@hhaim this issue happened with the 4M buffer and window size in 1 flow.
It means the flow sender can transmit about 3K packets at once.
When there is a packet dropped, all the following packets are counted as OOO packets until the dropped packet is received.
And there are more packet drops sparsely, after 5 packets are dropped, all the following received packets are dropped.

For example, let's assume the received 20 OOO packets are like these:
[ 1, 3, 5, 7, 9, 11, 13, 15, 17, 19,  2, 4, 6, 8, 10, 12, 14, 16, 18, 20 ]

At first, when the next packet is 1, 18 packets([ 3-8, 12-20 ]) will be counted as OOO packets.
And 6 packets([ 11-19, 20 ]) will be counted as dropped packets.
After all received 20 packets are processed, [ 12, 14, 16, 18 ] are in the reassembly queues and the next packet would be packet 11.
All the followed received packets will be dropped until packet 11 is retransmitted and received.
In this case, at least 9 reassembly queues are needed at least to avoid unexpected packet drops and retransmission.

Regarding the ideal value of MAX_TCP_REASS_BLOCKS, I prefer the dynamic size to the fixed value.
If there is no performance issue, I think std::vector or std::map can be used instead.
@hhaim, what do you think about my new suggestion?

**Comment by hhaim** [comment]
@jsmoon is the queue example you gave a real example base on pcap capture or just a theoretical one? 
Is it a drop or just an out of order? 
Did you verify that queue size of 9 solve the problem? 
Why there are so many drops in a lab environment?  Is it a DUT issue? 

The worst case of 3K packet window require 1.5K size to overcome the interleave drop (e.g. every odd number is drop or OOO in this order without drop), having 1.5K queue size (even dynamic) is not realistic as it not only consume memory, it will consume CPU. 

I think our main objective is to simulate a freeBSD stack (this was the main reason to upgrade the CC algo) from one hand but  not to get to memory exhaustion in case of many flows case (which is not common in freeBSD). We don't need to be better that freeBSD in case of drop. 

Looking into the latest freeBSD code there are a few main tunables 

1. tcp_reass_queue_guard (default 16) 
2. tcp_reass_maxqueuelen (default 100) in case we have a space

In any case we need to guard the global number of segments (in all the flows) 

I think that having dynamic vector is a good idea (std::vector) and I would add histogram statistic for the queue size (or at least a few counters 0-4, 4-8, 8-16, 16-32  

This is common from freeBSD
```
/*
	 * When we reach here we can't combine it
	 * with any existing segment.
	 *
	 * Limit the number of segments that can be queued to reduce the
	 * potential for mbuf exhaustion. For best performance, we want to be
	 * able to queue a full window's worth of segments. The size of the
	 * socket receive buffer determines our advertised window and grows
	 * automatically when socket buffer autotuning is enabled. Use it as the
	 * basis for our queue limit.
	 *
	 * However, allow the user to specify a ceiling for the number of
	 * segments in each queue.
	 *
	 * Always let the missing segment through which caused this queue.
	 * NB: Access to the socket buffer is left intentionally unlocked as we
	 * can tolerate stale information here.
	 *
	 * XXXLAS: Using sbspace(so->so_rcv) instead of so->so_rcv.sb_hiwat
	 * should work but causes packets to be dropped when they shouldn't.
	 * Investigate why and re-evaluate the below limit after the behaviour
	 * is understood.
	 */
```

**Comment by jsmoon** [comment]
@hhaim, I think I can add a new tunable `tcp_reass_maxqueuelen`, with a default value of 100 from FreeBSD.
tcp_reass also needs to be changed to reduce the performance degradation.

> is the queue example you gave a real example base on pcap capture or just a theoretical one?
Is it a drop or just an out of order?
Did you verify that queue size of 9 solve the problem?
Why there are so many drops in a lab environment? Is it a DUT issue?

It's a theoretical example.
I can't say it was a drop case without capturing packets which I failed to get it.
The drop counter happened instantly, but I'm not sure that it's due to a drop from DUT.
This is the reason why I thought OOO drop should be avoided as possible as it can be.

**Comment by jsmoon** [comment]
@hhaim I've prepared for the change: https://github.com/bidtt4/trex-core/commit/1243411f7d75142357530aa6e3785c087eec5a30. 
But, I have no idea to add histogram statistics for the queue size.
What do you need to know from it?

**Comment by hhaim** [comment]
@jsmoon the simplest is just to add a few static counters 
```
hist_4
hist_16
hist_100
hist_other
```

xx_4 would match to number of hits that the queue size is <4 _16 is less than 16 and more or eq to  4
