### ISSUE TITLE
E810: Packets bigger than 132B are resized to 64B

### ISSUE THREAD

**Issue by MaciejWachowski** [cisco-system-traffic-generator/trex-core#819]
**DESCRIPTION:**
Packets bigger than 132B are resized to 64B.

**REPRODUCTION STEPS:**
 - run t-rex server: **_sudo ./t-rex-64 -c 7 -i -v 1_**
 - open t-rex console
 - run command: _start -f stl/bench.py --force -m 1pps -t **size=132**,vm=cached_
 - check stats: **_stats -x_**:
 
```           Name:              |     Port 0:     |     Port 1:     
-------------------------------+-----------------+----------------
rx_good_packets                |               7 |               7 
tx_good_packets                |               7 |               7 
rx_good_bytes                  |             896 |             896 
tx_good_bytes                  |             896 |             896 
rx_unicast_packets             |               7 |               7 
tx_unicast_packets             |               7 |               7 
rx_size_128_to_255_packets     |               7 |               7 
tx_size_128_to_255_packets     |               7 |               7
```
 - run _**stop**_ and **_clear_** commands
 - run command: _start -f stl/bench.py --force -m 1pps -t **size=133**,vm=cached_
 - check stats: **_stats -x_**:
```
            Name:              |     Port 0:     |     Port 1:     
-------------------------------+-----------------+----------------
rx_good_packets                |               9 |               9 
tx_good_packets                |               9 |               9 
rx_good_bytes                  |             540 |             540 
tx_good_bytes                  |             540 |             540 
rx_unicast_packets             |               9 |               9 
tx_unicast_packets             |               9 |               9 
rx_size_64_packets             |               9 |               9 
tx_size_64_packets             |               9 |               9
```

**ENVIRONMENT:**
 - NIC: Intel E810 [E810-CQDA2]
 - TRex v2.96 (issue does not occure in v2.88, in v2.93 error occurs, in software mode error also occurs)
 - 2 interfaces in physical loopback (direct cable connection)
 - OS:
`Linux 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
`
 - Cores and NIC are in the same NUMA

```
Network devices using DPDK-compatible driver
============================================
0000:ca:00.0 'Ethernet Controller E810-C for QSFP 1592' drv=vfio-pci unused=ice,igb_uio
0000:ca:00.1 'Ethernet Controller E810-C for QSFP 1592' drv=vfio-pci unused=ice,igb_uio
```

**Trex config [/etc/trex_cfg.yaml]:** 
```
- version: 2
  interfaces: ['ca:00.0', 'ca:00.1']
  port_info:
      - ip: 1.1.1.1
        default_gw: 2.2.2.2
      - ip: 2.2.2.2
        default_gw: 1.1.1.1
  platform:
      master_thread_id: 32
      latency_thread_id: 33
      dual_if:
        - socket: 1
          threads: [34,35,36,37,38,39,40,41]
```
```
driver: ice
version: 5.13.0-30-generic
firmware-version: 3.10 0x8000ad67 1.3106.0
expansion-rom-version: 
bus-info: 0000:ca:00.1
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes
```

**Comment by hhaim** [comment]
@MaciejWachowski E810 support is very basic and wasn't tested. The driver is lack of feature that is not supported by DPDK.

**Comment by marcin-michalski** [comment]
@hhaim Is E810 support expected in predictable future?

**Comment by hhaim** [comment]
@marcin-michalski, I can't answer this, it depends on the DPDK driver support. We plan to upgrade to newer DPDK maybe it will help. Intel DPDK driver developers are involved, but I didn't see any meaningful progress for a long time, so I wouldn't put my money on this.

**Comment by leyirong** [comment]
@MaciejWachowski I reran the test by using the same command as you but with a good result.
![image](https://user-images.githubusercontent.com/96484620/159836800-efc3465d-b80c-452b-974d-00960841443d.png)

**Comment by MaciejWachowski** [comment]
@leyirong thank you for information!
Could you provide me your FW version on E810 and version of ice DDP package?
I am using `DDP package already present on device: ICE COMMS Package version 1.3.24.0`, `firmware-version: 3.10 0x8000ad67 1.3106.0`

**Comment by leyirong** [comment]
@MaciejWachowski FYI.
Comms Package: 1.3.16.0
firmware-version: 2.30 0x80005d1b 1.2877.0

**Comment by MaciejWachowski** [comment]
@leyirong thanks! I made a mistake in config, now it works and packets are not dropped, but I can observe that CPU util got worse:

trex v2.96:
```
trex>start -f stl/bench.py -m 30gbps --port 0 -t size=64,vm=cached
cpu_util.    : 33.23% @ 20 cores (20 per dual port)
```
trex with fix:
```
trex>start -f stl/bench.py -m 30gbps --port 0 -t size=64,vm=cached
cpu_util.    : 44.91% @ 20 cores (20 per dual port) 
```

**Comment by hhaim** [comment]
@marcin-michalski E810 works in software mode that cost ~300% more than the normal mode that is not supported by this driver
