### ISSUE TITLE
[Improvement suggestion] Get RTT, CWND info

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#834]
Hi,
User want to migrate existing verification tool(iperf) to TRex.
TCP throughput was not the issue with TRex, but, TRex lacks information about rtt(round trip time) and cwnd(congestion window).
In classic OS like Linux and FreeBSD,
iperf using getsockopt() API to get rtt and cwnd information per socket.
` tcp_info info = {};`
`  socklen_t len = sizeof(tcp_info);`
`  getsockopt(socket_fd, SOL_TCP, TCP_INFO, &info, &len);`
`  printf("RTT=%d, CWND=%d\n", info.tcpi_rtt, info.tcpi_snd_cwnd)`

But, there is no mapping API in TRex.
I assume that following 2 approaches would be possible, 
Hi @hhaim, how about your opinion?
Alternative#1. Adding new "TCP info" counter type and add them(rtt, cwnd) in "TCP info" counter. Currently,  4 types of counters('General','TCP','UDP','Flow table') available(see https://trex-tgn.cisco.com/trex/doc/trex_astf.html#_counters_reference). Adding them in 5th 'TCP info' type would be possible.
Alternative#2. Simply adding them(rtt,cwnd) in TCP counters(https://trex-tgn.cisco.com/trex/doc/trex_astf.html#_counters_reference) can be considered,

**Comment by hhaim** [comment]
@egwakim I think adding them to TCP section is better. The point about RTT/CWND that those counters should use the same infra of latency histogram (accurate). They are not a standard counters. 
I suggest to add this feature with a knob (disable by default) and only to sample of flows (e.g. 1-5%) because it could affect performance if you read the **accurate** high res counter. Another alternative is to use the 1msec resolution (the tick) with higher sample.

**Comment by egwakim** [comment]
Hi @hhaim 
I assume that you prefer following, is it correct?
Accuracy vs performance need to be discussed more in the implementation phase.
![image](https://user-images.githubusercontent.com/4927607/162149932-52a3706e-e4b7-4e8f-b0bd-33198d2696fb.png)

**Comment by hhaim** [comment]
@egwakim 
each "counter" should be an object with average/min/max and **histogram** (HDR) 
similar to latency object in STL/ASTF  
https://trex-tgn.cisco.com/trex/doc/cp_stl_docs/_modules/trex/stl/trex_stl_client.html#STLClient.get_pgid_stats

**Comment by egwakim** [comment]
Thanks for comment.
The purpose of getting rtt,cwnd is tracing TCP behavior to troubleshoot issues in the DUT.
Periodic real time statistics is more useful to visualize and understand it's trend.
Maybe new better idea would be needed.

**Comment by jsmoon** [comment]
I prefer the new RPC command like "get_flow_info".
The client could request it periodically with "profile_id" and "tg_ids".
```
{
    "method": "get_flow_info",
    "params": {
        "profile_id": "tg0",
        "tg_ids": [ 1 ]
    }
}
```
The server could respond with the information of selected flows.
```
{
    "result": {
        "1": [
            "<flow_id_1>": {
                "rtt" : 100,
                "cwnd" : 10
            },
            "<flow_id_n>": {
                "rtt" : 70,
                "cwnd" : 20
            }
        ]
    }
}
```
The flows selection could be activated by one of the following methods.
1. by the "start" RPC command parameters.
2. by the profile tunable.

Each method should have the select condition and the limit of flows.
The server could stack the flows to the limit which is matched to the condition.

@hhaim what do you think about my suggestion?

**Comment by hhaim** [comment]
@jsmoon the main use-case is scale of flows and scale of traffic, so I think the only option is a histogram for this kind of statistics. 
Even for one flow, the rtt and cwnd is not a changing over time and one counters can't say it all. 


What I ad in mind back then is to sample a few flows from each template in Rx core (to have the best latency) but I think doing sample of flows in the main DP cores would be fine too

**Comment by egwakim** [comment]
Hi @hhaim 
I need to get CWND/RTT info like well-known iperf case.
See example below, iperf shows changing Cwnd/RTT info at that moment.

# iperf -e -i 0.1 -t 180 -c 127.0.0.1
------------------------------------------------------------
Client connecting to 127.0.0.1, TCP port 5001 with pid 61264
Write buffer size:  128 KByte
TCP window size: 2.50 MByte (default)
------------------------------------------------------------
[  3] 2.30-2.40 sec   555 MBytes  46.5 Gbits/sec  4438/0          0     1023K/20 us
[ ID] Interval        Transfer    Bandwidth       Write/Err  Rtry    Cwnd/RTT
[  3] 2.40-2.50 sec   550 MBytes  46.1 Gbits/sec  4399/0          0     1023K/24 us
[ ID] Interval        Transfer    Bandwidth       Write/Err  Rtry    Cwnd/RTT
[  3] 2.50-2.60 sec   553 MBytes  46.4 Gbits/sec  4421/0          0     1023K/24 us
[ ID] Interval        Transfer    Bandwidth       Write/Err  Rtry    Cwnd/RTT
[  3] 2.60-2.70 sec   553 MBytes  46.4 Gbits/sec  4427/0          0     1023K/21 us
[ ID] Interval        Transfer    Bandwidth       Write/Err  Rtry    Cwnd/RTT
[  3] 2.70-2.80 sec   549 MBytes  46.1 Gbits/sec  4392/0          0     1023K/18 us
[ ID] Interval        Transfer    Bandwidth       Write/Err  Rtry    Cwnd/RTT
[  3] 2.80-2.90 sec   550 MBytes  46.1 Gbits/sec  4400/0          0     1023K/24 us
[ ID] Interval        Transfer    Bandwidth       Write/Err  Rtry    Cwnd/RTT
[  3] 2.90-3.00 sec   518 MBytes  43.4 Gbits/sec  4141/0          0     1023K/20 us
[ ID] Interval        Transfer    Bandwidth       Write/Err  Rtry    Cwnd/RTT
[  3] 3.00-3.10 sec   544 MBytes  45.6 Gbits/sec  4349/0          0     1023K/20 us
[ ID] Interval        Transfer    Bandwidth       Write/Err  Rtry    Cwnd/RTT
[  3] 3.10-3.20 sec   542 MBytes  45.5 Gbits/sec  4339/0          0     1023K/19 us

**Comment by hhaim** [comment]
@egwakim iperf by default work with one flow with ```-c ``` you can add a few flows. TRex use-case is a different, it is more for scale of flows, so it better to save statistic on all/sample of flows. Now **even** for one flow use-case I would prefer statistic (min/max/average/histogram etc.) as a user so I wouldn't need to collect the statistic in real time. 

If the raw information is so important for your user, I would add on top of the statistic a way to choose specific flow (using some sort of filter) so the data will be collected into a buffer so the client API will collect this buffer (not in realtime). But this is another **advance** feature on top of the default statistic, and this feature can't be scale to M of flows.

The statistic object I'm talking about was implemented already in the latency use-case so you don't need to re-invent it.

**Comment by egwakim** [comment]
Hi, @hhaim 
The purpose of tracing real-time rtt/cwnd is for tuning of DUT equipment to maximize TCP performance.
Additional histogram info also good, but, visualizing trend of rtt/cwnd change with small number of flows is what we need to do

**Comment by hhaim** [comment]
@egwakim what is your proposal to choose the "flows" you want to inspect? let's say you have a profile with 1M active flows?

**Comment by egwakim** [comment]
As jsmoon suggested. It would be disabled by default.
flows would be selected by profile_id + tg_id.
User would not activate this feature for 1M active flows.

**Comment by hhaim** [comment]
@egwakim in that case I think there is a need to **limit** the stats in case of a profile with a miss configuration that create more than x flows (e.g. 10) and take only the first. 

I do think that the global statistic is important too to measure latency at scale (the main purpose)

**Comment by jsmoon** [comment]
@hhaim, I'd like to focus on how to expose the information of flow to the user.
The statistics (min/max/average/histogram, etc) in T-Rex would be another story.
I think we can discuss that after the request from my user has been resolved.

My users have their own usage of the information. (history, histogram, statistics, etc.)
I think the following implementation will be enough in my case.

1. DP core saves the created flow pointers (limited by 1, 5, or 10, a small fixed number is enough) per template.
2. user requests the information on the template flow by ZMQ RPC.
3. CP core refers to the template flows, collects the required information, and responds to the user.
4. 2 to 3 would be performed by user pace. 10 requests/sec will be used.

In my opinion,  the saving overhead of the flow pointer will be very tiny especially when the limit number is 1,
If the limit number is 1, and I think 1 flow per template is probably enough for most cases,
on the new flow creation,
```
if (!pctx->tg_flows[tg_id]) {
    pctx->tg_flows[tg_id] = flow;
    flow->is_saved = true;
}
```
on the flow closing,
```
if (flow->is_saved && pctx->tg_flows[tg_id] == flow) {
    pctx->tg_flows[tg_id] = nullptr;
}
```
they will be all the code running in DP cores.
It's no wonder that the CP core can handle the request without disturbing DP cores as statistics do.

If you agree with this suggestion, I'll prepare a PR for it.

**Comment by hhaim** [comment]
@jsmoon @egwakim understood. will review the code
