### ISSUE TITLE
ERROR: Failure: ImportError (cannot import name 'CAPWAP_PKTS')

### ISSUE THREAD

**Issue by wittling** [cisco-system-traffic-generator/trex-core#836]
Hopefully someone can help me out with this error I am getting.

I have just cloned and built trex-core, which was successful.  When I run the ./scripts/run_regression --func, all of the tests run, and I get a "Happy Cat".

But when I run the ./scripts/run_functional_tests, while a lot of the output looks positive and favorable, I get ten errors related to an inability to import CAPWAP_PKTS. I can tell that this is related to Wireless, which I actually don't need for the tests I need to be running, so maybe I can just ignore this. But I wanted to post here and inquire about the error, and see if there is something I should have or could have done to suppress this issue during my build.

   ImportError: cannot import name 'CAPWAP_PKTS'
-----------------------------------------------------------------------------
9) ERROR: Failure: ImportError (cannot import name 'CAPWAP_PKTS')

Here is the bottom of the output:
10) ERROR: Failure: ImportError (cannot import name 'CAPWAP_PKTS')

   Traceback (most recent call last):
    /opt/github/trex-core/scripts/external_libs/nose-1.3.4/python3/nose/failure.py line 39 in runTest
      raise self.exc_val.with_traceback(self.tb)
    /opt/github/trex-core/scripts/external_libs/nose-1.3.4/python3/nose/loader.py line 414 in loadTestsFromName
      addr.filename, addr.module)
    /opt/github/trex-core/scripts/external_libs/nose-1.3.4/python3/nose/importer.py line 47 in importFromPath
      return self.importFromDir(dir_path, fqname)
    /opt/github/trex-core/scripts/external_libs/nose-1.3.4/python3/nose/importer.py line 94 in importFromDir
      mod = load_module(part_fqname, fh, filename, desc)
    /usr/lib64/python3.6/imp.py line 235 in load_module
      return load_source(name, filename, file)
    /usr/lib64/python3.6/imp.py line 172 in load_source
      module = _load(spec)
    <frozen importlib._bootstrap> line 684 in _load

    <frozen importlib._bootstrap> line 665 in _load_unlocked

    <frozen importlib._bootstrap_external> line 678 in exec_module

    <frozen importlib._bootstrap> line 219 in _call_with_frames_removed

    /opt/github/trex-core/scripts/automation/trex_control_plane/interactive/trex/wireless/unit_tests/trex_wireless_worker_test.py line 9 in <module>
      from wireless.trex_wireless_ap import AP
    /opt/github/trex-core/scripts/automation/trex_control_plane/interactive/trex/wireless/trex_wireless_ap.py line 11 in <module>
      from scapy.contrib.capwap import CAPWAP_PKTS, CAPWAP_DATA, CAPWAP_Header, CAPWAP_Wireless_Specific_Information_IEEE802_11, CAPWAP_Radio_MAC
   ImportError: cannot import name 'CAPWAP_PKTS'

-----------------------------------------------------------------------------
148 tests run in 46.8 seconds.
10 errors (138 tests passed)

           /\_/\
          ( o.o )
           > ^ <

This cat is sad, test failed.

*** python3 test failed

**Comment by hhaim** [comment]
@wittling best workaround is to filter those tests.

**Comment by wittling** [comment]
Okay so this is just noise, if I am not doing any wireless testing. I just wanted to check to make sure I could just ignore that.
