### ISSUE TITLE
Information Needed on Maximum Active Connection

### ISSUE THREAD

**Issue by ashiksl** [cisco-system-traffic-generator/trex-core#844]
Hi All,

I am new to T-rex.
My query is how  T-rex creates an active connection of more than 65k with one client and one server.
In my understanding, If one client uses all the available ports ( 65 K), it can create a maximum of 65000 active connections.

I would like to know how t-rex creates more than 65k active connections with one client and server.

Thanks,
Lokesh

**Comment by hhaim** [comment]
@ashiksl maximum active flows with one client-server is less than 65K (we don't use all the ports). 
TRex can't breach the theoretical value
