### ISSUE TITLE
Dockerfile fails to build based on 16.10

### ISSUE THREAD

**Issue by michaelhans** [cisco-system-traffic-generator/trex-core#85]
Attempting to build with the `ubuntu/16.10/Dockerfile` fails with issues finding yakkety repository files. Ubuntu 16.10 is EOL and I believe (though i haven't confirmed) they pull EOL docker tags, their hub page doesn't show any EOL tags. 

```
W: The repository 'http://security.ubuntu.com/ubuntu yakkety-security Release' does not have a Release file.
...
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/yakkety/universe/source/Sources  404  Not Found [IP: 91.189.88.162 80]
...
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update' returned a non-zero code: 100
```

I copied that directory and based on 16.04 LTS which works (builds trex and simulator) at #84 . I didn't update the original/docs in that PR as I was unsure if others existing build systems would fail though anyone who hasn't pulled that image prior to it's tag disappearing is also in a bad state.

**Comment by hhaim** [comment]
rebased
