### ISSUE TITLE
clear_profile() may get stuck

### ISSUE THREAD

**Issue by bdollma** [cisco-system-traffic-generator/trex-core#850]
The ASTF function:

https://github.com/cisco-system-traffic-generator/trex-core/blob/8a2002b6a0c5a4a8db997aa1da1b7bdbc2fd5aa7/scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py#L658

may (need to run multiple times) get stuck in a loop.

Minimal reproducible example:

```python

    try:
        # take all the ports
        c.reset()

        # load ASTF profile
        if not profile_path:
            profile_path = os.path.join(astf_path.get_profiles_path(), 'http_simple.py')

        c.load_profile(profile_path)

        print(c.get_profiles())

        c.clear_profile()

        print(c.get_profiles())
```

Just by starting at the function, the following code does not make sense:

```python
                if block:
                    rc = self._transmit_async('profile_clear', params = params, ok_states = self.STATE_IDLE)
                else:
                    rc = self._transmit('profile_clear', params = params)
```

The async should be the non blocking one.

Originally described here: https://groups.google.com/g/trex-tgn/c/1Ivfqn3Bfao

**Comment by jsmoon** [comment]
@bdollma, I think the following code could solve this issue.

```python
                if block and profile_state is self.STATE_ASTF_LOADED:
                    rc = self._transmit_async('profile_clear', params = params, ok_states = self.STATE_IDLE)
                else:
                    rc = self._transmit('profile_clear', params = params)
```

**Comment by bdollma** [comment]
Hi @jsmoon ,
This doesn't solve the problem, `clear_profile` still gets stuck.
It doesn't make sense that if the `block` parameter is set to `True`, we send an async command. It should be the other way around.

**Comment by jsmoon** [comment]
@bdollma
> This doesn't solve the problem, clear_profile still gets stuck.

I have failed to reproduce the stuck in clear_profile with your example.
So I checked the original thread, in that case, clear_profile is called without a profile loaded.
The suck is reproduced with it well. My suggestion works well for this stuck case.

> It doesn't make sense that if the block parameter is set to True, we send an async command. It should be the other way around.

I cannot agree with this. The block parameter is meaningful only when we need to get the result asynchronous way.
When the profile_state is self.STATE_IDLE, there is no result reported asynchronously.

**Comment by bdollma** [comment]
@jsmoon,
Ok, this is very confusing but I think I am starting to understand what happens here.

The `profile_clear` RPC itself is async ( message is sent from CP to DP and not waited for response). The `_transmit_async` blocks in order to receive the event about the change from the server. I think a better name for `block` would be `wait`.

However I still don't understand why we need to wait for the event only in case of LOADED.

In case of IDLE the server calls immediately the `delete_profile` function which publishes the event: `    profile->publish_astf_profile_clear();`

**Comment by jsmoon** [comment]
@bdollma, the `delete_profile` in STATE_IDLE is for the special case.
When the 'profile_fragment' is failed, the profile is left in STATE_IDLE. In this case, the profile on the server will be left also.
So the 'profile_clear' in STATE_IDLE is to clean up the fragmented profile.
From the implementation point of view, the `_transmit_async` is implemented for the STEADY -> TRANSIENT -> STEADY state change, not for STEADY -> STEADY change. There is no TRANSIENT state from STATE_IDLE to STATE_ASTF_LOADED.

For the change of the `_transmit_async` name, @ybrustin is the original author. So, I think we need an agreement from him at first.

**Comment by jsmoon** [comment]
@bdollma, @ybrustin what do you think about changing `_transmit_async` to `_transmit_sync`?

**Comment by bdollma** [comment]
@jsmoon ,
So the problem lies in the fact that clearing a profile in `IDLE` doesn't create a change in the state from `STEADY->TRANSIENT` and the `_transmit_async` doesn't support this?

**Comment by bdollma** [comment]
@jsmoon 
I see. In this case I think that your solution is probably the best approach to this at the moment since `_transmit_async` is used by `start` and `stop` and we would not want to interfere with that.

As I suggested before, I would rename `block` to `wait`.

**Comment by jsmoon** [comment]
@bdollma 
> As I suggested before, I would rename `block` to `wait`.

Do you prefer `_transmit_wait`?

**Comment by jsmoon** [comment]
@bdollma Do you mean the parameter `block`?
Then we need to consider that the parameter is a part of API because Python users may call `clear_profile()` with a keyword argument.
And for consistency, the `block` parameters of `start` and `stop` should also be changed.

**Comment by bdollma** [comment]
@jsmoon You make a good point. Since it is an Api call we could break user code.

`_transmit_wait` is a better name that `_transmit_async`, I would even be more verbose and have `_transmit_wait_on_state` since we are waiting for the state to be updated.
