### ISSUE TITLE
get_profiles doesn't return profiles

### ISSUE THREAD

**Issue by bdollma** [cisco-system-traffic-generator/trex-core#851]
The following ASTF function:

https://github.com/cisco-system-traffic-generator/trex-core/blob/8a2002b6a0c5a4a8db997aa1da1b7bdbc2fd5aa7/scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py#L856

```python
    def get_profiles(self):
        """
            Get profile list from Server.
        """
        params = {
            'handler': self.handler,
            }
        self.ctx.logger.pre_cmd('Getting profile list.')
        rc = self._transmit('get_profile_list', params = params)
        self.ctx.logger.post_cmd(rc)
        if not rc:
            raise TRexError(rc.err())
```

forgets to return anything.

We should add:
```python
return rc.data()
```

Also, this is not a command, it is a getter, as such this decorator:
```python
@client_api('command', True)
```

should be changed to:

```python
@client_api('getter', True)
```

**Comment by jsmoon** [comment]
@bdollma, I agree that the current `get_profiles()' is weird.
I think it can be removed because the similar getter 'get_profiles_state()' also returns the list of profiles with the current state.
But 'get_profiles_state()' does not use 'get_profile_list' ZMQ RPC command. It uses the updated list of profiles in the ASTFClinet instance by async events.
Do you need to make it a getter using the ZMQ RPC command?

**Comment by bdollma** [comment]
I think it makes sense to have a sync command for `get_profiles`. 
The idea is that users make decisions on loading/unloading profiles based on the actual state, as such we should always provide a correct and updated state of the profiles. The async command doesn't necessarily provide the updated version.

**Comment by jsmoon** [comment]
@bdollma
> The idea is that users make decisions on loading/unloading profiles based on the actual state, as such we should always provide a correct and updated state of the profiles.

The `get_profiles` and 'get_profile_list' sync command does not provide the state; it is just providing profile names only.
I can make it as you suggested, but the functionality won't be expected.

> The async command doesn't necessarily provide the updated version.

The async events are updated by 'get_async_events' ZMQ RPC command. I think this provides the correct and updated state of the profiles.

**Comment by bdollma** [comment]
Hi @jsmoon,
The `get_profile` function uses the `get_profile_list` RPC which is sync, and returns the actual list of profiles in the server at the moment of the call. It is a simple RPC who is meant to provide the actual state of the server.

The async commands invoke `_on_astf_profile_state_chg` which eventually updates the `astf_profile_state` dictionary which in turn is used by `get_profile_states`. This whole thing can take a few msec.

I think we should have both (especially considering that the infra for both exists).

I will provide a simple example for the sync case. Let us suppose I want to remove a profile. I want to verify right now that the profile was removed. It will take a few msec to get the event that the profile was removed in async mode, so using the `get_profile_state` is not an option.

I hope this was clear.

**Comment by jsmoon** [comment]
@bdollma I understood.

But you need to consider the following case.

>  Let us suppose I want to remove a profile. I want to verify right now that the profile was removed.

The default profile exists always even though it is the IDLE state unlikely to the other profiles.
I think you cannot verify it for the default profile.
