### ISSUE TITLE
Huge memory consumption from a large amount of event log messages

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#853]
Hi, my colleague observed a huge memory usage and high CPU load after massive profiles are loaded/started/stopped.
He observed it after he ran millions of profiles.

He found that the EventHandlers saves the event log messages **implicitly** after handling events from 'get_async_events'.
Since the size of event log messages is unlimited, the memory size of log messages may reach giga-bytes from a few million profiles.
And it takes time to append new log messages because list type is used for saving.

To avoid this situation, the TRex client user should clear the event log messages **explicitly** from time to time.
But the user cannot recognize it easily because it is unknown behavior.
So I think the number of the event log messages should be limited to a certain number, e.g. 1000.

@hhaim, @bdollma, what do you think about this issue?

**Comment by hhaim** [comment]
@jsmoon it sounds like a bug. It you point to the unlimited queue? is it python side or server side?

**Comment by hhaim** [comment]
```
    def on_event (self, event_name, *args, **kwargs):
        """
            trigger an event

            if a handler is registered for 'event_name' it will be called
            and be passed with *args and **kwargs
        """
        if event_name not in self.events_handlers:
            raise TRexError("TRex Events: unhandled event '{0}'".format(event_name))


        event = self.events_handlers[event_name](*args, **kwargs)
        if event:  
            self.events.append(event)   <<<<<

```

are you talking about this?

**Comment by jsmoon** [comment]
@hhaim yes, right.

**Comment by bdollma** [comment]
@jsmoon , I agree that we should limit it. I can see in the code that there are calls to `pop_event` or `get_events` expect for in the client Api. Actually, the optimal data structure for this use case would be a `Queue` (FIFO) so you could `pop` elements very easily. (If we reach the limit, we will have to `pop` for each `append` and that would be nasty on a list).

**Comment by jsmoon** [comment]
@bdollma, `Queue` is a good suggestion. I'll prepare a PR for this issue.
