### ISSUE TITLE
How to simulate video streaming in an ASTF profile.

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#866]
Hi,
I need to make multiple flows serialized from the different templates in an ASTF profile.
```
<flow1 of template1>, <flow2 of template2>, ... <flowN of templateN>
```
For more complex usage, I need to select the next template and insert some idle time dynamically; they should be responsive to the traffic status.
```
<flow1 of template1>, <idle_time1>, <flow2 of template2>, <flow3 of template1>, <idle_time2>, ...
```
But I think this could be quite a large change.
So I'd like to focus on the simple serialization feature at first.

My basic idea is the following:
- make an initial template and generate flows from the initial template only.
- add a program command to select the next template. e.g. `set_next_template(tg_name)`

@hhain what do you think about this? do you have any other suggestions?

**Comment by hhaim** [comment]
@jsmoon could you say a bit more why it is needed and is the use-case that it simulate?

The first issue in this mode that each thread has its own template CPS, I would start with one thread (the first) that simulate the program (all the other will get zero work to do)

next I would create an object like Ramup that has two commands: start template x, delay.

**Comment by jsmoon** [comment]
@hhaim I should simulate a video streaming (DASH algorithm) in a profile.

> The first issue in this mode that each thread has its own template CPS, I would start with one thread (the first) that simulate the program (all the other will get zero work to do)

If the thread means the series of flows from templates, basically I agree with you.
I think I could make the other templates 0 CPS.

> next I would create an object like Ramup that has two commands: start template x, delay.

Creating an object is a good suggestion.
And I need to select the `x` and `delay` dynamically reflecting the traffic status.
Could I make it work in the object?

**Comment by jsmoon** [comment]
@hhaim I prefer implementing the following pseudo-code for the simulation.
```
fetch_chunks = video_time/chunk_time
saved_chunks = 0
buffer_level = buffer_time/chunk_time

# statistics counters
stall_cnt = 0
fetch_time = 0

base_time = <current_time>
while fetch_chunks > 0 or saved_chunks > 0

    if saved_chunks < buffer_level and fetch_chunks > 0
        fetch_base = <current_time>
        <fetching a chunk by new flow>

        saved_chunks += 1
        fetch_chunks -= 1
        fetch_time += elapsed_time(fetch_base)
    else
        sleep(play_time)

    while elapsed_time(base_time) > chunk_time
        if saved_chunks > 0
            base_time += chunk_time
            saved_chunks -= 1
        else
            if fetch_chunks > 0
                base_time = <current_time> # stall
                stall_cnt += 1
            break
```
The implemented ASTF program will be like this:
```Python
    def _create_scheduler_program(self, video_time, chunk_time, buffer_time, tg_name):
        prog = ASTFProgram()

        # setup initial values
        prog.set_var("fetch_chunks", video_time/chunk_time)
        prog.set_var("saved_chunks", 0)
        prog.set_next_template(tg_name)
        play_time = chunk_time / 5  # playing resolution

        prog.set_tick_var('base_time')
        prog.jmp('L_main_cond:')
        prog.set_label("L_main_loop:")
        if True:
            # fetch a chunk by the control of saved chunks level
            prog.jmp_ge('saved_chunks', 'L_play:', buffer_time/chunk_time)
            prog.jmp_le('fetch_chunks', 'L_play:', 0) # whole chunks are fetched
            if True:
                prog.set_tick_var('fetch_base')
                prog.exec_template()

                prog.add_var('saved_chunks', 1)
                prog.add_var('fetch_chunks', -1)
                prog.add_tick_stats('user_counter_B', 'fetch_base')
                prog.jmp('L_fetch_end:')

            # simulate playing only
            prog.set_label('L_play:')
            if True:
                prog.delay(int(play_time * 1000000))
                prog.jmp('L_fetch_end:')

            prog.set_label('L_fetch_end:')

            # update played time
            prog.set_label('L_update_loop:')
            prog.jmp_dp('base_time', 'L_played_end:', chunk_time)
            if True:
                prog.jmp_le('saved_chunks', 'L_stall:', 0)
                if True:
                    prog.add_tick_var('base_time', chunk_time)
                    prog.add_var('saved_chunks', -1)
                    prog.jmp('L_update_loop:')

                prog.set_label('L_stall:')
                prog.jmp_le('fetch_chunks', 'L_played_end:', 0) # exit loop if no fetch
                if True:
                    prog.add_stats('user_counter_A', 1) # stall count
                    prog.set_tick_var('base_time')
                    prog.jmp('L_played_end:')

            prog.set_label('L_played_end:')

        prog.set_label("L_main_cond:")
        prog.jmp_gt('fetch_chunks', 'L_main_loop:', 0)
        prog.jmp_gt('saved_chunks', 'L_main_loop:', 0)
```
For this implementation, I should add the following commands:
- branch operations
  - conditional jump commands: `jmp_lt`, `jmp_gt`, `jmp_eq`, `jmp_le`, `jmp_ge`, `jmp_ne`
  - unconditional jump command: `jmp`
- arithmetic operations
  - add value to the variable: `add_var`
  - add value to the tick variable: `add_tick_var`
- user defined counters: `user_counter_A`, `user_counter_B`, ...
  - add value to the user counter: `add_stats`
  - add elapsed time to the user counter: `add_tick_stats`
- execution control of template flow
  - select a template for new flow execution: `set_next_template`
  - execute a flow from selected template: `exec_template`

@hhiam please give me your thought about this way.

**Comment by hhaim** [comment]
@jsmoon sorry for the late response. It looks good in general.
Don't you want to simulate a different delay per template?

**Comment by jsmoon** [comment]
@hhaim
> Don't you want to simulate a different delay per template?

Yes, I did. I can roughly implement it using constant `delay` and `jmp_dp`.

**Comment by hhaim** [comment]
@jsmoon understood.
