### ISSUE TITLE
Can't run trex (version 2.98) with 4 x Intel 2.5GbE I225-V LAN 

### ISSUE THREAD

**Issue by dk1312** [cisco-system-traffic-generator/trex-core#870]
Hi all, 

When I try to run the command "sudo ./t-rex-64 -f cap2/dns.yaml -m 1 -d 1", the below error happen. 
```
 ERROR in DPDK map
Could not find requested interface 01:00.0
```
Could you please show me how can I fix this? 

Thank you so much.

**Comment by dk1312** [comment]
I found the root cause.

**Comment by Oosl** [comment]
can you tell me what`s the root cause of this issue? I have the same issue now. Thanks very much!

**Comment by dk1312** [comment]
Hi Oosl, 

`Could not find requested interface 01:00.0`

I used the PCI id (01:00.0 and 02:00.0) to configure trex_cfg.yaml. But it seems that the default DPDK driver is not compatible with Intel 2.5GbE I225-V. I don't know which one is right for this NIC. So I switched to using the Linux interface (enp1s0 and enp2s0)  instead of the PCI id for the trex_cfg.yaml file. Then it works again.

**Comment by Oosl** [comment]
thanks very much!
Following what you said, it works!
but for this:

> "But it seems that the default DPDK driver is not compatible with Intel 2.5GbE I225-V. I don't know which one is right for this NIC."  

I don`t  agree with you and I think this issue is bug of trex. Because Pktgen-DPDK can work fine with the default DPDK driver (vfio-pci).

**Comment by dk1312** [comment]
Yeah, I read the DPDK document. I saw it is also supported Intel 2.5GbE I225-V with the driver as you mentioned. But I don't know why it doesn't work with TREX. So I tried to find another way that I showed you.

Hoping TREX team could look into this.

**Comment by Snailfl** [comment]
Hi all,

Excuse me, has this problem been solved yet? I found that I loaded this driver, and the same problem still occurs.

Network devices using DPDK-compatible driver
============================================
0000:02:00.0 'Ethernet Controller I225-V' drv=igb_uio unused=igc,vfio-pci,uio_pci_generic
