### ISSUE TITLE
./t-rex-64: line 94: ./_t-rex-64: No such file or directory

### ISSUE THREAD

**Issue by digger-yu** [cisco-system-traffic-generator/trex-core#871]
hi

when i run the script
I encountered the following error. is this have more detailed information to view,
did i messing something 

`root@dperf:~/trex-core/scripts# cat ../VERSION
v2.98r

root@dperf:~/trex-core/scripts# ./t-rex-64 -i
WARNING: tried to configure 2 hugepages for socket 0, but result is: 1
Starting Scapy server.... Scapy server is started
The ports are bound/configured.
**./t-rex-64: line 94: ./_t-rex-64: No such file or directory**
Killing Scapy server... Scapy server is killed
root@dperf:~/trex-core/scripts#`

**Comment by malanmoon** [comment]
How did you fixed it?
