### ISSUE TITLE
ASTF : Is there a way to manage flows duration

### ISSUE THREAD

**Issue by warrensonn** [cisco-system-traffic-generator/trex-core#883]
Hello,
I'm using ASTF Trex to reach maximum concurrent connections and maximum CPS  of the DUT (2 separated tests).
I've been facing issues to get the maximum out of it because I cannot find a way to keep the flows active longer, no matter what Trex pcap file I use.
The only thing I found is to add a server delay and it does not look good.
Is there a better way to manage flows duration so that I can, for CC test make them longer, and for CPS test very short in time ? 
Thanks a lot.

**Comment by hhaim** [comment]
Hi Warren,

Have a look into this profile,
https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/astf/http_high_active_flows.py

You will need to change the trex_cfg.yaml to set the DP_FLOWS to more that
the default (1M flows)

With this profile we change the duration of the flow and by having more
long flows (which are slow) we can have for the same bandwidth more
active-flows

Thanks
Hanoh
