### ISSUE TITLE
STL get_pgid_stats takes long response time

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#885]
Hi, recently I found that STL `get_pgid_stats`'s response time is relatively high; 20 msec when the i40evf driver is used.
It updates port stats counters by calling `g_trex.sync_threads_stats()`.
```C++
COLD_FUNC int TrexDpdkPlatformApi::get_pgid_stats(Json::Value &json, std::vector<uint32_t> pgids) const {
    g_trex.sync_threads_stats();  // <-- why this has been called?
    CFlowStatRuleMgr::instance()->dump_json(json, pgids);
    return 0;
}
```
To get the port stats counters, the i40evf driver asks them to the PF driver, which takes most of the response time.
But, AFAIK, the PGID stats do not need to collect the port stats counters.
Why this has been called?

I think it can be removed without side effects and the response time can be improved.
@hhaim, what do you think of it?

**Comment by hhaim** [comment]
@jsmoon sorry of the late response, I think that in both cases ( software mode and hardware mode) this is not needed. 
as in hardware mode there is a direct API to read the counters and sync them and in software this sync is not needed.
