### ISSUE TITLE
how to improve port rate?

### ISSUE THREAD

**Issue by lawrenceywr** [cisco-system-traffic-generator/trex-core#891]
i use `./_t-rex-64 -i --software` to start trex server
then `./trex-console` to start client
like this 
![image](https://user-images.githubusercontent.com/25687903/179702770-7786b6f8-d68c-406e-a540-879b2f859cb9.png)
however ,when i use `start -m 100% -d 120 -f stl/multi_udp.py` to start generate stream,the bandwidth is only 699Mbps
![image](https://user-images.githubusercontent.com/25687903/179703082-2f91888f-9ad0-4157-aeb1-82cdbdde08dc.png)
how to improve the trex bandwidth,
thanks a lot

**Comment by hhaim** [comment]
@lawrenceywr please send an email to the group.
