### ISSUE TITLE
version `MLX5_OFED' not found (required by so/x86_64/libmlx5-64.so)

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#894]
Hi, recently, my colleague observed the following error in the Ubuntu 20.04 machine.
```
EAL: /lib/x86_64-linux-gnu/libmlx5.so.1: version `MLX5_OFED' not found (required by so/x86_64/libmlx5-64.so)
EAL: FATAL: Cannot init plugins
```
There is no issue with the Ubuntu 18.04 machine.
He found that MLNX_OFED_LINUX-5.4-2.4.1.3 is the last release that has the `MLX5_OFED` version.

According to my investigation, this happens when I build with the internal version of ibverbs.
My building host does not have installed OFED and it drives to use the internal ibverbs library.
```
Checking for OFED                        : not found 
Checking for library mnl                 : not found, will use internal version 
Configuring dummy MLX5 autoconf          : done 
Warning: will use internal version of ibverbs. If you need to use Mellanox NICs, install OFED:
https://trex-tgn.cisco.com/trex/doc/trex_manual.html#_mellanox_connectx_4_support 
Building mlx5 PMD 
```
This building with this configuration links the `libibverbs.so` and `libmlx5.so` in the `external_libs/ibverbs/x86_64/`.
The `libmlx5.so` file has the `MLX5_OFED` version. 
But the package does not include these files.
So, in the target host (Ubuntu machine), _t-rex-64 loads the installed `libmlx5.so` and there is no issue in the Ubuntu 18.04 machine.

I'd like to run T-Rex on Ubuntu 18.04 and 20.04 machines with a single binary package.
In my thought, when a binary is built with the internal library, the library should be packaged with the binary also.

@hhaim, what do you think about this?

**Comment by hhaim** [comment]
@jsmoon I'm not sure it is possible! each distro could have a different version of verb and you need to compile with the right FLAGS on each one of them . 
The external/libverbs **match** the version that we report that we support (with a single distro rel7. 9) -- this way we can compile on a build server without the need of the OFED installed.

the simplest solution is to build for each [distro,ofed-version]
