### ISSUE TITLE
Improve ASTF IP distribution for flow generation.

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#896]
Hi, recently I've found an issue on split_ips.

This is a typical IPGen for flow generation in the ASTF profile.
```
            ip_gen_c = ASTFIPGenDist(ip_range=["16.0.0.0", "16.0.0.255"], distribution="seq")
            ip_gen_s = ASTFIPGenDist(ip_range=["48.0.0.0", "48.0.255.255"], distribution="seq")
            ip_gen = ASTFIPGen(glob=ASTFIPGenGlobal(ip_offset="1.0.0.0"),
                               dist_client=ip_gen_c,
                               dist_server=ip_gen_s)
```

In my analysis, with 2 dual ports and 3 cores for a dual port, client IP distribution will be shown as follows.
split_ips() with total_threads=6 and poolinfo={.ip_start="16.0.0.1", .ip_end="16.0.0.255"}
thread_id | dual_port_id | client IPs | # of IPs
---------- | -------------- | ---------- | ----
0 | 0 | 16.0.0.1-16.0.0.42 | (42)
1 | 1 | 17.0.0.43-17.0.0.84 | (42)
2 | 0 | 16.0.0.85-16.0.0.126 | (42)
3 | 1 | 17.0.0.127-17.0.0.168 | (42)
4 | 0 | 16.0.0.169-16.0.0.210 | (42)
5 | 1 | 17.0.0.211-17.0.0.255 | (45)

As you can see,
- due to the `ip_offset`, there are missing client IPs from the given IP range: 16.0.0.43-16.0.0.84, ...
- last core's `# of IPs` will be quite large when the client IP range is small: 6 over 11 total IPs, others are 1.

@hhaim what do you think about this issue?

**Comment by hhaim** [comment]
@jsmoon this is expected. "16.0.0.1", "16.0.0.255" means that you want 255 clients total in any setup ( with 1 dual ports or 10 dual ports) the number of clients is an important factor and we don't want to change it. 

there is another field in the  ```ASTFIPGenDist```  ```per_core_distribution``` that gives each dual ports all the clients 

```def __init__(self, ip_range, distribution="seq",per_core_distribution=None):```


>>>last core's # of IPs will be quite large when the client IP range is small: 6 over 11 total IPs, others are 1.

this is the residue, there is a way to split the residue in a better way (1 to each)

**Comment by jsmoon** [comment]
@hhaim now I understand that keeping the number of clients matters.

But, when `per_core_distribution` is used, `split_ips_v2()` will distribute IPs and the result will be as follows.
thread_id | dual_port_id | client IPs | # of IPs
-- | -- | -- | --
0 | 0 | 16.0.0.1-16.0.0.42 | (42)
1 | 1 | 17.0.0.127-17.0.0.168 | (42)
2 | 0 | 16.0.0.43-16.0.0.84 | (42)
3 | 1 | 17.0.0.169-17.0.0.210 | (42)
4 | 0 | 16.0.0.85-16.0.0.129 | (45)
5 | 1 | 17.0.0.211-17.0.0.255 | (45)

In this case, we will have 3 surplus clients. I think we need to fix it also.
If you agree, I'll prepare a PR for this issue including the residue.

**Comment by jsmoon** [comment]
@hhaim, for ip_range=["16.0.0.1", "16.0.0.11"], I'll make the IP distribution as follows.
Please give me your opinion about it.

## split_ips()

thread_id | dual_port_id | client IPs | # of IPs
-- | -- | -- | --
0 | 0 | 16.0.0.1-16.0.0.1 | (1)
1 | 1 | 17.0.0.2-17.0.0.3 | (2)
2 | 0 | 16.0.0.4-16.0.0.5 | (2)
3 | 1 | 17.0.0.6-17.0.0.7 | (2)
4 | 0 | 16.0.0.8-16.0.0.9 | (2)
5 | 1 | 17.0.0.10-17.0.0.11 | (2)

total clients = 11

## split_ips_v2() (when `per_core_distribution` is used) 

thread_id | dual_port_id | client IPs | # of IPs
-- | -- | -- | --
0 | 0 | 16.0.0.1-16.0.0.3 | (3)
1 | 1 | 17.0.0.1-17.0.0.3 | (3)
2 | 0 | 16.0.0.4-16.0.0.7 | (4)
3 | 1 | 17.0.0.4-17.0.0.7 | (4)
4 | 0 | 16.0.0.8-16.0.0.11 | (4)
5 | 1 | 17.0.0.8-17.0.0.11 | (4)

total clients = 11 * 2

**Comment by jsmoon** [comment]
@hhaim should I allow `ip_offset` = '0.0.0.0' with `per_core_distribution`?
I think the same IP can be used in the same dual_port_id, but cannot be used in the other dual_port_id.
To my thought, we need to prohibit this usage, `ip_offset` = '0.0.0.0' with `per_core_distribution`.
Please confirm your thought including my previous comment.

**Comment by hhaim** [comment]
@jsmoon 

> @hhaim, for ip_range=["16.0.0.1", "16.0.0.11"], I'll make the IP distribution as follows. Please give me your opinion about it.
> 
> ## `ip_offset` = '1.0.0.0' only
> thread_id	dual_port_id	client IPs	# of IPs
> 0	0	16.0.0.1-16.0.0.1	(1)
> 1	1	17.0.0.2-17.0.0.3	(2)
> 2	0	16.0.0.4-16.0.0.5	(2)
> 3	1	17.0.0.6-17.0.0.7	(2)
> 4	0	16.0.0.8-16.0.0.9	(2)
> 5	1	17.0.0.10-17.0.0.11	(2)
> total clients = 11
> 
> ## `ip_offset` = '1.0.0.0' with `per_core_distribution`
> thread_id	dual_port_id	client IPs	# of IPs
> 0	0	16.0.0.1-16.0.0.3	(3)
> 1	1	17.0.0.1-17.0.0.3	(3)
> 2	0	16.0.0.4-16.0.0.7	(4)
> 3	1	17.0.0.4-17.0.0.7	(4)
> 4	0	16.0.0.8-16.0.0.11	(4)
> 5	1	17.0.0.8-17.0.0.11	(4)
> total clients = 11 * 2

@jsmoon looks good. it seems v2 version has a bug and v1 could be improved with the residue

**Comment by hhaim** [comment]
> @hhaim should I allow `ip_offset` = '0.0.0.0' with `per_core_distribution`? I think the same IP can be used in the same dual_port_id, but cannot be used in the other dual_port_id. To my thought, we need to prohibit this usage, `ip_offset` = '0.0.0.0' with `per_core_distribution`. Please confirm your thought including my previous comment.

@jsmoon you are correct. With per_core_disto ip_offset can't be 0.0.0.0
