### ISSUE TITLE
Cannot change hash functions or use static not random keys on E810

### ISSUE THREAD

**Issue by MaciejWachowski** [cisco-system-traffic-generator/trex-core#898]
I am not able to change hash function on E810 card:
```
RSS hash function:
    toeplitz: on
    xor: off
    crc32: off

root@my_server:~# ethtool -X ens802f0 hfunc xor
Cannot set RX flow hash configuration: Operation not supported
```
I also tried with newest ethtool (5.18) and newest ice driver (1.9.11) but with no success.
Do you have any information how to change hash func or if is able to do it using TRex?

**Comment by hhaim** [comment]
@MaciejWachowski this is an issue to DPDK driver maintainers
