### ISSUE TITLE
how to make tx L2 line rate ? like 10G port tx 10Gbps

### ISSUE THREAD

**Issue by 119064273** [cisco-system-traffic-generator/trex-core#905]
current test,  L1 could do 10Gbps, but L2 only 7.6Gbps, so the port tx rate only 7.6Gbps,  is this current limited?

**Comment by bdollma** [comment]
use bigger packets, the overhead of preamble is limiting you. https://support.spirent.com/SC_KnowledgeView?Id=FAQ10739

**Comment by 119064273** [comment]
@bdollma  thanks
