### ISSUE TITLE
(ASTF mode) Testing through firewall does not work properly with random source ports

### ISSUE THREAD

**Issue by debanjana-in-tech** [cisco-system-traffic-generator/trex-core#915]
Trex in ASTF mode allocates random source ports for each flow. With random ports on each flow (even for same source IP), the testing through firewall does not work. Random port numbers cause the Firewall to treat each packet as a separate session, preventing the session from being offloaded to a dedicated network processor. It has a very negative effect on the performance - all traffic generated by trex is handled by CPU which is heavily loaded instead of offloading it.

<img width="848" alt="diff_source_port" src="https://user-images.githubusercontent.com/11670646/189283836-ffe082c2-6309-4ef1-b450-5daf38f30739.png">

Questions:
1. Is there any way to set all source ports the same for all flows and all clients ?
2. If no, can we have the same source port for all flows for each client ? 
3. Do you have any suggestion/workaround on how we can make it work with firewalls?

We checked this using Trex version 2.91 and 2.99, both have same issue.

Thanks in advance.

**Comment by hhaim** [comment]
@debanjana-in-tech it is not a random source port. What  each flow has different source port. 
trex allocate source port (distinct) for each flow. You can limit the number of flows and make them very long, this way you will have less source ports and less flows.  (see limit and eflow example)
