### ISSUE TITLE
'list' type support in flow_var

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#92]
Hi,
Many other commercial tool supports 'list' type in flow.
http://trex-tgn.cisco.com/trex/doc/trex_rpc_server_spec.html#_flow_var.
In TRex side, flow selected with inc/dec/random from {init_value,min_value,max_value} set.

Can I add 'list' type in this rpc command?
If I add 'list' type, which option will be natural and preferred approach in your current TRex design?

Option#1. add 'list' which is same as set of {init_value,min_value,max_value}.
User can use 'op' inc/dec/random from this 'list' set.

Option#2. add 'list' op and list set
User can use this 'list' as fixed order from specified 'list' set

**Comment by hhaim** [comment]
@egwakim could you provide an example of a profile with this new primitive? I would like to understand what is the scale of the list. Is it a big or small list?

**Comment by egwakim** [comment]
Some guys asked me to support several UDP port number list like {4001,4005,7003}.
It'll not big.I assume that 128 will be enough, but, bigger will be better. IXIA have such feature. Is there any limitation on json rpc length?

**Comment by hhaim** [comment]
See here https://github.com/cisco-system-traffic-generator/trex-core/pull/111
