### ISSUE TITLE
Field Engine caching breaks equal packet distribution

### ISSUE THREAD

**Issue by GrzegorzKania-lime** [cisco-system-traffic-generator/trex-core#939]
Hey,
I've stumbled across strange behaviour, when using STL UDP examples on Intel E810(2x100G) NIC.
Accordingly to the docs, to increase TRex performance for small packets (like 64B), user should provide the cache to store X number of packets inside it - before traffic starts.

So I wanted to test this for the STL script:
[stl/udp_1pkt_src_ip_split.py](https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/stl/udp_1pkt_src_ip_split.py)

I've made the experiment and indeed, the bandwidth increased - but the packet distribution across the flows seems to be distorted.
I've switched the caching off, and then distribution came back to "inc" expected values.

In the attachment, there is XLS file with amount of bandwidth for particular flow. (On the left cache ON, on the right cache OFF)

```
...
10.0.0.50.1025 > 48.0.0.1.12                        3.50 MB        2m23s  205.13 Kbps || 10.0.0.235.1025 > 48.0.0.1.12                       3.37 MB        2m30s  188.23 Kbps
10.0.0.51.1025 > 48.0.0.1.12                        3.50 MB        2m23s  205.13 Kbps || 10.0.0.236.1025 > 48.0.0.1.12                       3.37 MB        2m30s  188.23 Kbps
10.0.0.75.1025 > 48.0.0.1.12                        3.50 MB        2m23s  205.13 Kbps || 10.0.0.237.1025 > 48.0.0.1.12                       3.37 MB        2m30s  188.23 Kbps
10.0.0.76.1025 > 48.0.0.1.12                        3.50 MB        2m23s  205.13 Kbps || 10.0.0.238.1025 > 48.0.0.1.12                       3.37 MB        2m30s  188.23 Kbps
10.0.0.77.1025 > 48.0.0.1.12                        3.50 MB        2m23s  205.13 Kbps || 10.0.0.239.1025 > 48.0.0.1.12                       3.37 MB        2m30s  188.23 Kbps 
10.0.0.1.1025 > 48.0.0.1.12                         3.15 MB        2m23s  184.61 Kbps || 10.0.0.24.1025 > 48.0.0.1.12                        3.37 MB        2m30s  188.23 Kbps
10.0.0.10.1025 > 48.0.0.1.12                        3.15 MB        2m23s  184.61 Kbps || 10.0.0.240.1025 > 48.0.0.1.12                       3.37 MB        2m30s  188.23 Kbps 
10.0.0.106.1025 > 48.0.0.1.12                       3.15 MB        2m23s  184.61 Kbps || 10.0.0.241.1025 > 48.0.0.1.12                       3.37 MB        2m30s  188.23 Kbps
10.0.0.107.1025 > 48.0.0.1.12                       3.15 MB        2m23s  184.61 Kbps || 10.0.0.242.1025 > 48.0.0.1.12                       3.37 MB        2m30s  188.23 Kbps
10.0.0.108.1025 > 48.0.0.1.12                       3.15 MB        2m23s  184.61 Kbps || 10.0.0.243.1025 > 48.0.0.1.12                       3.37 MB        2m30s  188.23 Kbps 
10.0.0.11.1025 > 48.0.0.1.12                        3.15 MB        2m23s  184.61 Kbps || 10.0.0.244.1025 > 48.0.0.1.12                       3.37 MB        2m30s  188.23 Kbps
...
```

Expected behaviour:
Enabling cache in FE, should not affect "inc" packet distribution.
[Inequal_dist.xlsx](https://github.com/cisco-system-traffic-generator/trex-core/files/9943619/Inequal_dist.xlsx)
[Script for processing large pcaps easily](https://www.zenetys.com/wp-content/uploads/2020/06/tcpdump-stats)
This stats were gathered from 15M packets sample, while small amount of traffic was send (100kpps).

**Comment by hhaim** [comment]
@GrzegorzKania-lime this is expected. The cache has a limited size per core! it is not the same output as without cache.

**Comment by MaciejWachowski** [comment]
@hhaim What do you mean by: _The cache has a limited size per core_? If I have 10 cores and cache size 255 should I expected 2550 flows?

**Comment by hhaim** [comment]
@MaciejWachowski yes, a cache of 255 means that each core has a 255 packets to save (after FE) . Total flows for all the cores would be 2550. There is no magic 
see here:
https://trex-tgn.cisco.com/trex/doc/trex_stateless.html#_tutorial_field_engine_pre_caching_to_improve_performance
