### ISSUE TITLE
Confirming Packet loss across 2 Azure VMs ASTF

### ISSUE THREAD

**Issue by yusefMS06** [cisco-system-traffic-generator/trex-core#974]
Hi @hhaim 

I have a 2 VM setup in azure. Goal is to conduct CPS testing on this Client -> Server VM scenario. 
Run the following command on the client VM after navigating to folder ~/trex-core/scripts
`sudo ./t-rex-64 -i -c 16 --no-ofed-check --cfg /etc/trex_cfg_client.yaml -v 7 --astf --astf-client-mask 0x1`
Run the following command on the server VM after navigating to folder ~/trex-core/scripts
`sudo ./t-rex-64 -i -c 16 --no-ofed-check --cfg /etc/trex_cfg_server.yaml -v 7 --astf --astf-server-only --no-key`

Starting Traffic:
On server, in your trex-console:
`start -f ./astf/http_manual_commands.py`
On client:
`start -f ./astf/http_manual_commands.py -m 100000`

Traffic is transmitting across VMs opackets on client are similar to the ipackets on the server side, but in the response direction (server->client) opackets on server are much less than ipackets on the server. Even though this is the case the server opackets do indeed match the client ipackets. Not sure if this loss is significant or if this is caused by some of the packets being syn, syn|ack, or FIN/RST packets. 

Any clarification on this?

Example Image:
Left Console is Client.  Right Console is Server
![image](https://user-images.githubusercontent.com/112422069/217621507-ce7c438d-5689-4236-b5c2-dc169d4d0a1a.png)

Additionally, I looked at the stats using tui then switching to the ASTF screen. Client connections initiated = server connection accepted = client connections established & server connection established. Not sure if this should be true because on client side there are a number of tcps_badsyn and on server side there are a number of  tcps_rcvdupack. 

Can we confirm this is proper logically?

Example Image:
![image](https://user-images.githubusercontent.com/112422069/217623681-b335cf89-8889-4e29-9390-78ccdefb3109.png)

**Comment by hhaim** [comment]
@yusefMS06 please use our mailers for questions. the counters looks good.

**Comment by yusefMS06** [comment]
Thank you @hhaim 

What email should I use or is there a link to the "mailers"?
