### ISSUE TITLE
I cannot access https://trex-tgn.cisco.com/youtrack/issue/trex-537

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#979]
Hi, the comment in commit 48a4cc736a tells me to see https://trex-tgn.cisco.com/youtrack/issue/trex-537, but I cannot access the page. How could I get the content?

I'm trying to use the mbuf-const to reduce the usage of mbuf. But I get an error when the mbuf-const is freed and then used again.
If I don't free the mbuf-const, can I use it safely? Why the mbuf-const is disabled for ASTF interactive mode?

**Comment by jsmoon** [comment]
@hhaim, thank you for your quick response.
If I understand it correctly, I can use the const-mbuf for my change.

**Comment by hhaim** [comment]
@jsmoon you **can't** use the const-mbuf if you are not syncing with the driver tx- queue (there is no simple way to do this). 
I looked into the PR, not sure I understand how it solves the issue or what is the issue?
In the old ASTF **none-interactive** there was no need to sync with a new profile (all the mbuf would return after program exist).

The performance penalty is low so I still do not understand what you are trying to solve?

**Comment by jsmoon** [comment]
@hhaim from your e-mail,
> To implement that we can add a cache for const mbuf that won't return to the main pool.

I implemented a cache `mbufs_cached` and the const-mbuf in `mbufs_cached` will never return to the main pool. 

As you know that my colleague runs lots of profiles, and lots of 2K mbufs are consumed by redundant ones.
I would like to reduce 2K mbuf consumption by minimizing the redundant mbufs.

**Comment by hhaim** [comment]
@jsmoon I've answered this in the PR
