### ISSUE TITLE
Link error of document reference2.22.3.

### ISSUE THREAD

**Issue by digger-yu** [cisco-system-traffic-generator/trex-core#988]
https://trex-tgn.cisco.com/trex/doc/trex_stateless.html#_fd_io_open_source_project_using_trex

2.22.3. FD.IO open source project using TRex
[here](https://gerrit.fd.io/r/gitweb?p=csit.git;a=tree;f=resources/tools/t-rex)

![image](https://user-images.githubusercontent.com/55081697/223371045-79840ee8-98c8-40ea-b6a9-f65e6767ba9c.png)

**Comment by hhaim** [comment]
same as  #996
