### ISSUE TITLE
The document maybe have a description error

### ISSUE THREAD

**Issue by digger-yu** [cisco-system-traffic-generator/trex-core#989]
https://github.com/cisco-system-traffic-generator/trex-core/blob/master/doc/trex_ndr_bench_doc.asciidoc#16-optimized-binary-search

in this document  part 1.6.1 
```
Figure 7. Last Iteration, IMIX Traffic, Optimized Algorithm
After 4 iterations, we conclude that P-Drop Rate (PDR is 0.1% in our case and queue full is 2%) is 87.66 Gbps.

Discussion
The simple binary search took 7 iterations. The optimized binary search took 7 iterations (including checking the upper bound). Hence in this case, (as in most cases) the optimized binary search is faster.
```
question 1  the 87.66 and figure 7 It doesn't match the number in the picture
question 2  "The optimized binary search took 7 iterations " is should "7" or "4"

**Comment by hhaim** [comment]
same as  #996
