### ISSUE TITLE
There is a link error in this document

### ISSUE THREAD

**Issue by digger-yu** [cisco-system-traffic-generator/trex-core#993]
https://github.com/cisco-system-traffic-generator/trex-core/blob/master/doc/draft_trex_stateless_moved1.asciidoc

![image](https://user-images.githubusercontent.com/55081697/223635211-7c3f17f0-6f5d-4b7e-945b-0d07532c2e81.png)
![image](https://user-images.githubusercontent.com/55081697/223635357-8aafdd5c-0a84-45b8-b431-7296ab6affad.png)

**Comment by hhaim** [comment]
same as  #996
