### ISSUE TITLE
Many images in the document are not displayed and links are wrong

### ISSUE THREAD

**Issue by digger-yu** [cisco-system-traffic-generator/trex-core#994]
https://github.com/cisco-system-traffic-generator/trex-core/blob/master/doc/trex_analytics.asciidoc

like 
![image](https://user-images.githubusercontent.com/55081697/223643202-73a2dedf-bbee-41de-a6d4-df4265229cc0.png)
![image](https://user-images.githubusercontent.com/55081697/223643258-5a445b98-ba25-4ef8-8d51-9685dbe96e3d.png)
![image](https://user-images.githubusercontent.com/55081697/223643300-ef668632-82ca-4ab4-b2a8-e768520c8ee5.png)
![image](https://user-images.githubusercontent.com/55081697/223643427-5f35865d-2709-4ffa-83f2-e20a289d3dab.png)

**Comment by hhaim** [comment]
same as  #996
