### ISSUE TITLE
link error in document

### ISSUE THREAD

**Issue by digger-yu** [cisco-system-traffic-generator/trex-core#996]
https://github.com/cisco-system-traffic-generator/trex-core/blob/master/doc/draft_trex_stateless_moved1.asciidoc

![image](https://user-images.githubusercontent.com/55081697/223646812-b7fbf11b-07dc-4fb4-bed8-f2d3fc4a97ed.png)
![image](https://user-images.githubusercontent.com/55081697/223646835-b0b01d5d-6328-4fca-b205-2eb441dbd6c5.png)

**Comment by hhaim** [comment]
The code is compiled and showed in this server. 
please have a look into this:

https://trex-tgn.cisco.com/trex/doc/trex_stateless.html
